-- The Dual Order. Civilization V: Brave New World + Community Patch.
-- Scalar game objects are cloned so columns added by the Community Patch are retained.

UPDATE CustomModOptions SET Value = 1 WHERE Name IN
('EVENTS_BATTLES', 'EVENTS_CITY', 'EVENTS_PLAYER_TURN', 'EVENTS_RELIGION',
 'EVENTS_FOUND_RELIGION', 'EVENTS_GOLDEN_AGE',
 'EVENTS_UNIT_CONVERTS', 'EVENTS_UNIT_CREATED', 'EVENTS_UNIT_PREKILL',
 'EVENTS_WAR_AND_PEACE');

INSERT INTO Colors(Type,Red,Green,Blue,Alpha) VALUES
('COLOR_DUAL_ORDER_PRIMARY',0.90,0.88,0.82,1),
('COLOR_DUAL_ORDER_SECONDARY',0.055,0.050,0.045,1);
INSERT INTO PlayerColors(Type,PrimaryColor,SecondaryColor,TextColor) VALUES
('PLAYERCOLOR_DUAL_ORDER','COLOR_DUAL_ORDER_PRIMARY','COLOR_DUAL_ORDER_SECONDARY','COLOR_PLAYER_BLACK_TEXT');

INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES
('DUAL_ORDER_ICON_ATLAS',256,'DualOrderIcon256.dds',1,1),
('DUAL_ORDER_ICON_ATLAS',128,'DualOrderIcon128.dds',1,1),
('DUAL_ORDER_ICON_ATLAS',80,'DualOrderIcon80.dds',1,1),
('DUAL_ORDER_ICON_ATLAS',64,'DualOrderIcon64.dds',1,1),
('DUAL_ORDER_ICON_ATLAS',48,'DualOrderIcon48.dds',1,1),
('DUAL_ORDER_ICON_ATLAS',45,'DualOrderIcon45.dds',1,1),
('DUAL_ORDER_ICON_ATLAS',32,'DualOrderIcon32.dds',1,1),
('DUAL_ORDER_ICON_ATLAS',24,'DualOrderIcon24.dds',1,1),
('DUAL_ORDER_ICON_ATLAS',16,'DualOrderIcon16.dds',1,1),
('DUAL_ORDER_ALPHA_ATLAS',256,'DualOrderAlpha256.dds',1,1),
('DUAL_ORDER_ALPHA_ATLAS',128,'DualOrderAlpha128.dds',1,1),
('DUAL_ORDER_ALPHA_ATLAS',80,'DualOrderAlpha80.dds',1,1),
('DUAL_ORDER_ALPHA_ATLAS',64,'DualOrderAlpha64.dds',1,1),
('DUAL_ORDER_ALPHA_ATLAS',48,'DualOrderAlpha48.dds',1,1),
('DUAL_ORDER_ALPHA_ATLAS',45,'DualOrderAlpha45.dds',1,1),
('DUAL_ORDER_ALPHA_ATLAS',32,'DualOrderAlpha32.dds',1,1),
('DUAL_ORDER_ALPHA_ATLAS',24,'DualOrderAlpha24.dds',1,1),
('DUAL_ORDER_ALPHA_ATLAS',16,'DualOrderAlpha16.dds',1,1),
('DUAL_ORDER_LEADER_ATLAS',256,'DualOrderLeader256.dds',1,1),
('DUAL_ORDER_LEADER_ATLAS',128,'DualOrderLeader128.dds',1,1),
('DUAL_ORDER_LEADER_ATLAS',64,'DualOrderLeader64.dds',1,1),
('DUAL_ORDER_OBJECT_ATLAS',256,'DualOrderObjects256.dds',5,1),
('DUAL_ORDER_OBJECT_ATLAS',128,'DualOrderObjects128.dds',5,1),
('DUAL_ORDER_OBJECT_ATLAS',80,'DualOrderObjects80.dds',5,1),
('DUAL_ORDER_OBJECT_ATLAS',64,'DualOrderObjects64.dds',5,1),
('DUAL_ORDER_OBJECT_ATLAS',45,'DualOrderObjects45.dds',5,1),
('DUAL_ORDER_OBJECT_ATLAS',32,'DualOrderObjects32.dds',5,1),
('DUAL_ORDER_OBJECT_ATLAS',16,'DualOrderObjects16.dds',5,1),
('DUAL_ORDER_UNIT_FLAG_ATLAS',32,'DualOrderUnitFlag32.dds',1,1);

INSERT INTO Traits(Type,Description,ShortDescription) VALUES
('TRAIT_DUAL_ORDER_TWIN_MANDATES','TXT_KEY_TRAIT_DUAL_ORDER_HELP','TXT_KEY_TRAIT_DUAL_ORDER_SHORT');

CREATE TEMP TABLE DualOrderLeaderClone AS SELECT * FROM Leaders WHERE Type='LEADER_WASHINGTON';
UPDATE DualOrderLeaderClone SET ID=NULL,Type='LEADER_GRANDMASTER_SEVERIN',
 Description='TXT_KEY_LEADER_GRANDMASTER_SEVERIN',Civilopedia='TXT_KEY_LEADER_GRANDMASTER_SEVERIN_PEDIA',
 CivilopediaTag='TXT_KEY_CIVILOPEDIA_LEADERS_GRANDMASTER_SEVERIN',ArtDefineTag='DualOrderLeaderScene.xml',
 PortraitIndex=0,IconAtlas='DUAL_ORDER_LEADER_ATLAS',PackageID=NULL,
 VictoryCompetitiveness=8,WonderCompetitiveness=4,MinorCivCompetitiveness=6,
 Boldness=7,DiploBalance=7,WarmongerHate=5,WorkAgainstWillingness=6,WorkWithWillingness=6,
 DenounceWillingness=5,DoFWillingness=5,Loyalty=8,Neediness=4,Forgiveness=4,Chattiness=4,Meanness=5;
INSERT INTO Leaders SELECT * FROM DualOrderLeaderClone;
DROP TABLE DualOrderLeaderClone;
INSERT INTO Leader_Traits VALUES ('LEADER_GRANDMASTER_SEVERIN','TRAIT_DUAL_ORDER_TWIN_MANDATES');

CREATE TEMP TABLE DualOrderCivClone AS SELECT * FROM Civilizations WHERE Type='CIVILIZATION_AMERICA';
UPDATE DualOrderCivClone SET ID=NULL,Type='CIVILIZATION_DUAL_ORDER',
 Description='TXT_KEY_CIV_DUAL_ORDER_DESC',ShortDescription='TXT_KEY_CIV_DUAL_ORDER_SHORT_DESC',
 Adjective='TXT_KEY_CIV_DUAL_ORDER_ADJECTIVE',Civilopedia='TXT_KEY_CIV_DUAL_ORDER_PEDIA',
 CivilopediaTag='TXT_KEY_CIV5_DUAL_ORDER',Strategy='TXT_KEY_CIV_DUAL_ORDER_STRATEGY',
 DefaultPlayerColor='PLAYERCOLOR_DUAL_ORDER',Playable=1,AIPlayable=1,PackageID=NULL,
 PortraitIndex=0,IconAtlas='DUAL_ORDER_ICON_ATLAS',AlphaIconAtlas='DUAL_ORDER_ALPHA_ATLAS',
 MapImage='DualOrderMap.dds',DawnOfManImage='DualOrderDawn.dds',
 DawnOfManQuote='TXT_KEY_DUAL_ORDER_DAWN_OF_MAN',DawnOfManAudio='',SoundtrackTag='GERMANY',
 ArtDefineTag='ART_DEF_CIVILIZATION_GERMANY',ArtStyleType='ARTSTYLE_EUROPEAN',
 ArtStyleSuffix='_EURO',ArtStylePrefix='EUROPEAN ';
INSERT INTO Civilizations SELECT * FROM DualOrderCivClone;
DROP TABLE DualOrderCivClone;

INSERT INTO Civilization_Leaders VALUES ('CIVILIZATION_DUAL_ORDER','LEADER_GRANDMASTER_SEVERIN');
INSERT INTO Civilization_FreeBuildingClasses SELECT 'CIVILIZATION_DUAL_ORDER',BuildingClassType
 FROM Civilization_FreeBuildingClasses WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_FreeTechs SELECT 'CIVILIZATION_DUAL_ORDER',TechType
 FROM Civilization_FreeTechs WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_FreeUnits(CivilizationType,UnitClassType,UnitAIType,Count)
 SELECT 'CIVILIZATION_DUAL_ORDER',UnitClassType,UnitAIType,Count
 FROM Civilization_FreeUnits WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_Start_Region_Priority VALUES ('CIVILIZATION_DUAL_ORDER','REGION_HILLS');

CREATE TEMP TABLE DualOrderUnitClone AS SELECT * FROM Units WHERE Type='UNIT_LONGSWORDSMAN';
UPDATE DualOrderUnitClone SET ID=NULL,Type='UNIT_DUAL_ORDER_DIVIDED_TEMPLAR',
 Description='TXT_KEY_UNIT_DUAL_ORDER_DIVIDED_TEMPLAR',
 Civilopedia='TXT_KEY_UNIT_DUAL_ORDER_DIVIDED_TEMPLAR_PEDIA',
 Strategy='TXT_KEY_UNIT_DUAL_ORDER_DIVIDED_TEMPLAR_STRATEGY',
 Help='TXT_KEY_UNIT_DUAL_ORDER_DIVIDED_TEMPLAR_HELP',Combat=23,
 Cost=(Cost*110+99)/100,PortraitIndex=0,IconAtlas='DUAL_ORDER_OBJECT_ATLAS',
 UnitFlagIconOffset=0,UnitFlagAtlas='DUAL_ORDER_UNIT_FLAG_ATLAS';
INSERT INTO Units SELECT * FROM DualOrderUnitClone;
DROP TABLE DualOrderUnitClone;
INSERT INTO Civilization_UnitClassOverrides VALUES
('CIVILIZATION_DUAL_ORDER','UNITCLASS_LONGSWORDSMAN','UNIT_DUAL_ORDER_DIVIDED_TEMPLAR');

CREATE TEMP TABLE DualOrderBuildingClone AS SELECT * FROM Buildings WHERE Type='BUILDING_ARMORY';
UPDATE DualOrderBuildingClone SET ID=NULL,Type='BUILDING_DUAL_ORDER_HALL_CONCORDANCE',
 Description='TXT_KEY_BUILDING_DUAL_ORDER_HALL_CONCORDANCE',
 Civilopedia='TXT_KEY_BUILDING_DUAL_ORDER_HALL_CONCORDANCE_PEDIA',
 Strategy='TXT_KEY_BUILDING_DUAL_ORDER_HALL_CONCORDANCE_STRATEGY',
 Help='TXT_KEY_BUILDING_DUAL_ORDER_HALL_CONCORDANCE_HELP',
 PortraitIndex=1,IconAtlas='DUAL_ORDER_OBJECT_ATLAS';
INSERT INTO Buildings SELECT * FROM DualOrderBuildingClone;
DROP TABLE DualOrderBuildingClone;
INSERT INTO Civilization_BuildingClassOverrides VALUES
('CIVILIZATION_DUAL_ORDER','BUILDINGCLASS_ARMORY','BUILDING_DUAL_ORDER_HALL_CONCORDANCE');

INSERT INTO UnitPromotions
(Type,Description,Help,CannotBeChosen,LostWithUpgrade,PortraitIndex,IconAtlas,PediaType,PediaEntry) VALUES
('PROMOTION_DUAL_ORDER_ZEAL','TXT_KEY_PROMOTION_DUAL_ORDER_ZEAL','TXT_KEY_PROMOTION_DUAL_ORDER_ZEAL_HELP',1,0,2,'DUAL_ORDER_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_DUAL_ORDER_ZEAL'),
('PROMOTION_DUAL_ORDER_ZEAL_ACTIVE','TXT_KEY_PROMOTION_DUAL_ORDER_ZEAL_ACTIVE','TXT_KEY_PROMOTION_DUAL_ORDER_ZEAL_ACTIVE_HELP',1,1,2,'DUAL_ORDER_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_DUAL_ORDER_ZEAL_ACTIVE'),
('PROMOTION_DUAL_ORDER_BALANCE_1','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE_HELP',1,1,3,'DUAL_ORDER_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE'),
('PROMOTION_DUAL_ORDER_BALANCE_2','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE_HELP',1,1,3,'DUAL_ORDER_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE'),
('PROMOTION_DUAL_ORDER_BALANCE_3','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE_HELP',1,1,3,'DUAL_ORDER_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE'),
('PROMOTION_DUAL_ORDER_BALANCE_4','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE_HELP',1,1,3,'DUAL_ORDER_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE'),
('PROMOTION_DUAL_ORDER_BALANCE_5','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE_HELP',1,1,3,'DUAL_ORDER_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_DUAL_ORDER_BALANCE'),
('PROMOTION_DUAL_ORDER_SCHISM_STRIKE','TXT_KEY_PROMOTION_DUAL_ORDER_SCHISM_STRIKE','TXT_KEY_PROMOTION_DUAL_ORDER_SCHISM_STRIKE_HELP',1,0,4,'DUAL_ORDER_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_DUAL_ORDER_SCHISM_STRIKE'),
('PROMOTION_DUAL_ORDER_SCHISM_WOUNDED','TXT_KEY_PROMOTION_DUAL_ORDER_SCHISM_WOUNDED','TXT_KEY_PROMOTION_DUAL_ORDER_SCHISM_WOUNDED_HELP',1,1,4,'DUAL_ORDER_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_DUAL_ORDER_SCHISM_WOUNDED'),
('PROMOTION_DUAL_ORDER_HOLY_SUPPORT','TXT_KEY_PROMOTION_DUAL_ORDER_HOLY_SUPPORT','TXT_KEY_PROMOTION_DUAL_ORDER_HOLY_SUPPORT_HELP',1,1,4,'DUAL_ORDER_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_DUAL_ORDER_HOLY_SUPPORT');

UPDATE UnitPromotions SET CombatPercent=10 WHERE Type IN
('PROMOTION_DUAL_ORDER_ZEAL_ACTIVE','PROMOTION_DUAL_ORDER_HOLY_SUPPORT');
UPDATE UnitPromotions SET CombatPercent=2 WHERE Type='PROMOTION_DUAL_ORDER_BALANCE_1';
UPDATE UnitPromotions SET CombatPercent=4 WHERE Type='PROMOTION_DUAL_ORDER_BALANCE_2';
UPDATE UnitPromotions SET CombatPercent=6 WHERE Type='PROMOTION_DUAL_ORDER_BALANCE_3';
UPDATE UnitPromotions SET CombatPercent=8 WHERE Type='PROMOTION_DUAL_ORDER_BALANCE_4';
UPDATE UnitPromotions SET CombatPercent=10 WHERE Type='PROMOTION_DUAL_ORDER_BALANCE_5';
UPDATE UnitPromotions SET AttackMod=20 WHERE Type='PROMOTION_DUAL_ORDER_SCHISM_WOUNDED';

INSERT INTO Unit_FreePromotions(UnitType,PromotionType) VALUES
('UNIT_DUAL_ORDER_DIVIDED_TEMPLAR','PROMOTION_COVER_1'),
('UNIT_DUAL_ORDER_DIVIDED_TEMPLAR','PROMOTION_DUAL_ORDER_SCHISM_STRIKE');

-- Runtime classification by building class automatically includes every civilization's replacement building.
CREATE TABLE DualOrderBuildingRoles
(ID INTEGER PRIMARY KEY AUTOINCREMENT, BuildingClassType TEXT NOT NULL, RoleType TEXT NOT NULL);
INSERT INTO DualOrderBuildingRoles(BuildingClassType,RoleType) VALUES
('BUILDINGCLASS_BARRACKS','MANDATE'),('BUILDINGCLASS_ARMORY','MANDATE'),('BUILDINGCLASS_TEMPLE','MANDATE'),
('BUILDINGCLASS_BARRACKS','MILITARY'),('BUILDINGCLASS_ARMORY','MILITARY'),('BUILDINGCLASS_MILITARY_ACADEMY','MILITARY'),
('BUILDINGCLASS_SHRINE','RELIGIOUS'),('BUILDINGCLASS_TEMPLE','RELIGIOUS'),('BUILDINGCLASS_GRAND_TEMPLE','RELIGIOUS'),
('BUILDINGCLASS_MONASTERY','RELIGIOUS'),('BUILDINGCLASS_CATHEDRAL','RELIGIOUS'),('BUILDINGCLASS_MOSQUE','RELIGIOUS'),
('BUILDINGCLASS_PAGODA','RELIGIOUS'),('BUILDINGCLASS_CHURCH','RELIGIOUS'),('BUILDINGCLASS_MANDIR','RELIGIOUS'),
('BUILDINGCLASS_SYNAGOGUE','RELIGIOUS'),('BUILDINGCLASS_STUPA','RELIGIOUS'),('BUILDINGCLASS_ORDER','RELIGIOUS');
