-- Twin Mandates, Balance Pressure, Hall bonuses, AI priorities and civilization lists.

INSERT INTO BuildingClasses(Type,DefaultBuilding,Description) VALUES
('BUILDINGCLASS_DUAL_ORDER_MANDATE_YIELDS','BUILDING_DUAL_ORDER_MANDATE_YIELDS','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY'),
('BUILDINGCLASS_DUAL_ORDER_BALANCE_1','BUILDING_DUAL_ORDER_BALANCE_1','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY'),
('BUILDINGCLASS_DUAL_ORDER_BALANCE_2','BUILDING_DUAL_ORDER_BALANCE_2','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY'),
('BUILDINGCLASS_DUAL_ORDER_BALANCE_3','BUILDING_DUAL_ORDER_BALANCE_3','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY'),
('BUILDINGCLASS_DUAL_ORDER_BALANCE_4','BUILDING_DUAL_ORDER_BALANCE_4','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY'),
('BUILDINGCLASS_DUAL_ORDER_BALANCE_5','BUILDING_DUAL_ORDER_BALANCE_5','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY'),
('BUILDINGCLASS_DUAL_ORDER_GOLDEN_ARMAMENT','BUILDING_DUAL_ORDER_GOLDEN_ARMAMENT','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY'),
('BUILDINGCLASS_DUAL_ORDER_HALL_HAPPINESS','BUILDING_DUAL_ORDER_HALL_HAPPINESS','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY');

INSERT INTO Buildings
(Type,BuildingClass,Description,Cost,FaithCost,GreatWorkCount,NeverCapture,NukeImmune,ConquestProb,IsDummy,ShowInPedia) VALUES
('BUILDING_DUAL_ORDER_MANDATE_YIELDS','BUILDINGCLASS_DUAL_ORDER_MANDATE_YIELDS','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_DUAL_ORDER_BALANCE_1','BUILDINGCLASS_DUAL_ORDER_BALANCE_1','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_DUAL_ORDER_BALANCE_2','BUILDINGCLASS_DUAL_ORDER_BALANCE_2','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_DUAL_ORDER_BALANCE_3','BUILDINGCLASS_DUAL_ORDER_BALANCE_3','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_DUAL_ORDER_BALANCE_4','BUILDINGCLASS_DUAL_ORDER_BALANCE_4','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_DUAL_ORDER_BALANCE_5','BUILDINGCLASS_DUAL_ORDER_BALANCE_5','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_DUAL_ORDER_GOLDEN_ARMAMENT','BUILDINGCLASS_DUAL_ORDER_GOLDEN_ARMAMENT','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_DUAL_ORDER_HALL_HAPPINESS','BUILDINGCLASS_DUAL_ORDER_HALL_HAPPINESS','TXT_KEY_BUILDING_DUAL_ORDER_DUMMY',-1,-1,-1,1,1,0,1,0);

INSERT INTO Building_YieldChanges(BuildingType,YieldType,Yield) VALUES
('BUILDING_DUAL_ORDER_MANDATE_YIELDS','YIELD_PRODUCTION',1),
('BUILDING_DUAL_ORDER_MANDATE_YIELDS','YIELD_FAITH',1),
('BUILDING_DUAL_ORDER_HALL_CONCORDANCE','YIELD_PRODUCTION',2),
('BUILDING_DUAL_ORDER_HALL_CONCORDANCE','YIELD_FAITH',3);
INSERT INTO Building_YieldModifiers(BuildingType,YieldType,Yield) VALUES
('BUILDING_DUAL_ORDER_BALANCE_1','YIELD_PRODUCTION',1),
('BUILDING_DUAL_ORDER_BALANCE_2','YIELD_PRODUCTION',2),
('BUILDING_DUAL_ORDER_BALANCE_3','YIELD_PRODUCTION',3),
('BUILDING_DUAL_ORDER_BALANCE_4','YIELD_PRODUCTION',4),
('BUILDING_DUAL_ORDER_BALANCE_5','YIELD_PRODUCTION',5);
UPDATE Buildings SET MilitaryProductionModifier=25
 WHERE Type='BUILDING_DUAL_ORDER_GOLDEN_ARMAMENT';
UPDATE Buildings SET Happiness=1
 WHERE Type='BUILDING_DUAL_ORDER_HALL_HAPPINESS';
UPDATE Building_DomainFreeExperiences SET Experience=Experience+5
 WHERE BuildingType='BUILDING_DUAL_ORDER_HALL_CONCORDANCE';

-- The Armory flavor row is inherited; replace its value instead of creating a duplicate.
UPDATE Building_Flavors SET Flavor=40
 WHERE BuildingType='BUILDING_DUAL_ORDER_HALL_CONCORDANCE'
 AND FlavorType='FLAVOR_MILITARY_TRAINING';
INSERT INTO Building_Flavors(BuildingType,FlavorType,Flavor) VALUES
('BUILDING_DUAL_ORDER_HALL_CONCORDANCE','FLAVOR_RELIGION',35),
('BUILDING_DUAL_ORDER_HALL_CONCORDANCE','FLAVOR_PRODUCTION',20),
('BUILDING_DUAL_ORDER_HALL_CONCORDANCE','FLAVOR_HAPPINESS',15),
('BUILDING_DUAL_ORDER_HALL_CONCORDANCE','FLAVOR_GREAT_PEOPLE',12);

INSERT INTO Leader_Flavors(LeaderType,FlavorType,Flavor)
SELECT 'LEADER_GRANDMASTER_SEVERIN',Type,CASE Type
 WHEN 'FLAVOR_RELIGION' THEN 9 WHEN 'FLAVOR_OFFENSE' THEN 8
 WHEN 'FLAVOR_DEFENSE' THEN 8 WHEN 'FLAVOR_MILITARY_TRAINING' THEN 9
 WHEN 'FLAVOR_PRODUCTION' THEN 8 WHEN 'FLAVOR_EXPANSION' THEN 6
 WHEN 'FLAVOR_CULTURE' THEN 5 WHEN 'FLAVOR_SCIENCE' THEN 5
 WHEN 'FLAVOR_DIPLOMACY' THEN 3 WHEN 'FLAVOR_WONDER' THEN 4
 ELSE 5 END FROM Flavors;
INSERT INTO Leader_MajorCivApproachBiases(LeaderType,MajorCivApproachType,Bias)
SELECT 'LEADER_GRANDMASTER_SEVERIN',MajorCivApproachType,CASE MajorCivApproachType
 WHEN 'MAJOR_CIV_APPROACH_WAR' THEN 7 WHEN 'MAJOR_CIV_APPROACH_HOSTILE' THEN 5
 WHEN 'MAJOR_CIV_APPROACH_DECEPTIVE' THEN 3 WHEN 'MAJOR_CIV_APPROACH_GUARDED' THEN 7
 WHEN 'MAJOR_CIV_APPROACH_AFRAID' THEN 2 WHEN 'MAJOR_CIV_APPROACH_FRIENDLY' THEN 5
 ELSE 5 END FROM Leader_MajorCivApproachBiases WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Leader_MinorCivApproachBiases(LeaderType,MinorCivApproachType,Bias)
SELECT 'LEADER_GRANDMASTER_SEVERIN',MinorCivApproachType,Bias
 FROM Leader_MinorCivApproachBiases WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Diplomacy_Responses(LeaderType,ResponseType,Response,Bias)
SELECT 'LEADER_GRANDMASTER_SEVERIN',ResponseType,Response,Bias
 FROM Diplomacy_Responses WHERE LeaderType='LEADER_WASHINGTON';

INSERT INTO Civilization_CityNames(CivilizationType,CityName) VALUES
('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_1'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_2'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_3'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_4'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_5'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_6'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_7'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_8'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_9'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_10'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_11'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_12'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_13'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_14'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_15'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_16'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_17'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_18'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_19'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_20'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_21'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_22'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_23'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_CITY_DUAL_ORDER_24');
INSERT INTO Civilization_SpyNames(CivilizationType,SpyName) VALUES
('CIVILIZATION_DUAL_ORDER','TXT_KEY_SPY_DUAL_ORDER_1'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_SPY_DUAL_ORDER_2'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_SPY_DUAL_ORDER_3'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_SPY_DUAL_ORDER_4'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_SPY_DUAL_ORDER_5'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_SPY_DUAL_ORDER_6'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_SPY_DUAL_ORDER_7'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_SPY_DUAL_ORDER_8'),
('CIVILIZATION_DUAL_ORDER','TXT_KEY_SPY_DUAL_ORDER_9'),('CIVILIZATION_DUAL_ORDER','TXT_KEY_SPY_DUAL_ORDER_10');
