-- Population yields, reputation bands, timed server states, AI priorities, and name lists.

INSERT INTO BuildingClasses(Type,DefaultBuilding,Description) VALUES
('BUILDINGCLASS_ROMAN_GLADIUS_PLAYER_GOLD','BUILDING_ROMAN_GLADIUS_PLAYER_GOLD','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY'),
('BUILDINGCLASS_ROMAN_GLADIUS_PLAYER_SCIENCE','BUILDING_ROMAN_GLADIUS_PLAYER_SCIENCE','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY'),
('BUILDINGCLASS_ROMAN_GLADIUS_PLAYER_CULTURE','BUILDING_ROMAN_GLADIUS_PLAYER_CULTURE','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY'),
('BUILDINGCLASS_ROMAN_GLADIUS_MODERATOR','BUILDING_ROMAN_GLADIUS_MODERATOR','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY'),
('BUILDINGCLASS_ROMAN_GLADIUS_LEGENDARY','BUILDING_ROMAN_GLADIUS_LEGENDARY','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY'),
('BUILDINGCLASS_ROMAN_GLADIUS_THRIVING','BUILDING_ROMAN_GLADIUS_THRIVING','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY'),
('BUILDINGCLASS_ROMAN_GLADIUS_TROUBLED','BUILDING_ROMAN_GLADIUS_TROUBLED','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY'),
('BUILDINGCLASS_ROMAN_GLADIUS_TOXIC','BUILDING_ROMAN_GLADIUS_TOXIC','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY'),
('BUILDINGCLASS_ROMAN_GLADIUS_DEAD','BUILDING_ROMAN_GLADIUS_DEAD','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY'),
('BUILDINGCLASS_ROMAN_GLADIUS_OWNER_ONLINE','BUILDING_ROMAN_GLADIUS_OWNER_ONLINE','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY'),
('BUILDINGCLASS_ROMAN_GLADIUS_GRAND_OPENING','BUILDING_ROMAN_GLADIUS_GRAND_OPENING','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY'),
('BUILDINGCLASS_ROMAN_GLADIUS_PEAK_HOURS','BUILDING_ROMAN_GLADIUS_PEAK_HOURS','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY'),
('BUILDINGCLASS_ROMAN_GLADIUS_MILESTONE_HAPPINESS','BUILDING_ROMAN_GLADIUS_MILESTONE_HAPPINESS','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY'),
('BUILDINGCLASS_ROMAN_GLADIUS_SUCCESSFUL_NETWORK','BUILDING_ROMAN_GLADIUS_SUCCESSFUL_NETWORK','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY');

INSERT INTO Buildings
(Type,BuildingClass,Description,Cost,FaithCost,GreatWorkCount,NeverCapture,NukeImmune,ConquestProb,IsDummy,ShowInPedia) VALUES
('BUILDING_ROMAN_GLADIUS_PLAYER_GOLD','BUILDINGCLASS_ROMAN_GLADIUS_PLAYER_GOLD','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_ROMAN_GLADIUS_PLAYER_SCIENCE','BUILDINGCLASS_ROMAN_GLADIUS_PLAYER_SCIENCE','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_ROMAN_GLADIUS_PLAYER_CULTURE','BUILDINGCLASS_ROMAN_GLADIUS_PLAYER_CULTURE','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_ROMAN_GLADIUS_MODERATOR','BUILDINGCLASS_ROMAN_GLADIUS_MODERATOR','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_ROMAN_GLADIUS_LEGENDARY','BUILDINGCLASS_ROMAN_GLADIUS_LEGENDARY','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_ROMAN_GLADIUS_THRIVING','BUILDINGCLASS_ROMAN_GLADIUS_THRIVING','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_ROMAN_GLADIUS_TROUBLED','BUILDINGCLASS_ROMAN_GLADIUS_TROUBLED','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_ROMAN_GLADIUS_TOXIC','BUILDINGCLASS_ROMAN_GLADIUS_TOXIC','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_ROMAN_GLADIUS_DEAD','BUILDINGCLASS_ROMAN_GLADIUS_DEAD','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_ROMAN_GLADIUS_OWNER_ONLINE','BUILDINGCLASS_ROMAN_GLADIUS_OWNER_ONLINE','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_ROMAN_GLADIUS_GRAND_OPENING','BUILDINGCLASS_ROMAN_GLADIUS_GRAND_OPENING','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_ROMAN_GLADIUS_PEAK_HOURS','BUILDINGCLASS_ROMAN_GLADIUS_PEAK_HOURS','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_ROMAN_GLADIUS_MILESTONE_HAPPINESS','BUILDINGCLASS_ROMAN_GLADIUS_MILESTONE_HAPPINESS','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_ROMAN_GLADIUS_SUCCESSFUL_NETWORK','BUILDINGCLASS_ROMAN_GLADIUS_SUCCESSFUL_NETWORK','TXT_KEY_BUILDING_ROMAN_GLADIUS_DUMMY',-1,-1,-1,1,1,0,1,0);

INSERT INTO Building_YieldChanges(BuildingType,YieldType,Yield) VALUES
('BUILDING_ROMAN_GLADIUS_PLAYER_GOLD','YIELD_GOLD',1),
('BUILDING_ROMAN_GLADIUS_PLAYER_SCIENCE','YIELD_SCIENCE',1),
('BUILDING_ROMAN_GLADIUS_PLAYER_CULTURE','YIELD_CULTURE',1),
('BUILDING_ROMAN_GLADIUS_MODERATOR','YIELD_CULTURE',1);
INSERT INTO Building_YieldModifiers(BuildingType,YieldType,Yield) VALUES
('BUILDING_ROMAN_GLADIUS_LEGENDARY','YIELD_GOLD',15),
('BUILDING_ROMAN_GLADIUS_LEGENDARY','YIELD_CULTURE',10),
('BUILDING_ROMAN_GLADIUS_THRIVING','YIELD_GOLD',10),
('BUILDING_ROMAN_GLADIUS_TOXIC','YIELD_GOLD',-10),
('BUILDING_ROMAN_GLADIUS_OWNER_ONLINE','YIELD_PRODUCTION',10),
('BUILDING_ROMAN_GLADIUS_OWNER_ONLINE','YIELD_GOLD',10),
('BUILDING_ROMAN_GLADIUS_PEAK_HOURS','YIELD_GOLD',15),
('BUILDING_ROMAN_GLADIUS_PEAK_HOURS','YIELD_PRODUCTION',10),
('BUILDING_ROMAN_GLADIUS_SUCCESSFUL_NETWORK','YIELD_GOLD',10),
('BUILDING_ROMAN_GLADIUS_SUCCESSFUL_NETWORK','YIELD_CULTURE',10);
INSERT INTO Building_YieldModifiers(BuildingType,YieldType,Yield) VALUES
('BUILDING_ROMAN_GLADIUS_LEGENDARY','YIELD_FOOD',20),
('BUILDING_ROMAN_GLADIUS_THRIVING','YIELD_FOOD',10),
('BUILDING_ROMAN_GLADIUS_TROUBLED','YIELD_FOOD',-10),
('BUILDING_ROMAN_GLADIUS_TOXIC','YIELD_FOOD',-20),
('BUILDING_ROMAN_GLADIUS_DEAD','YIELD_FOOD',-50),
('BUILDING_ROMAN_GLADIUS_GRAND_OPENING','YIELD_FOOD',50),
('BUILDING_ROMAN_GLADIUS_PEAK_HOURS','YIELD_FOOD',10);
UPDATE Buildings SET Happiness=1 WHERE Type='BUILDING_ROMAN_GLADIUS_MILESTONE_HAPPINESS';

-- The Console has exactly the design's +2 Culture and +1 Gold, independent of CP Monument tuning.
DELETE FROM Building_YieldChanges WHERE BuildingType='BUILDING_ROMAN_GLADIUS_SERVER_CONSOLE';
INSERT INTO Building_YieldChanges(BuildingType,YieldType,Yield) VALUES
('BUILDING_ROMAN_GLADIUS_SERVER_CONSOLE','YIELD_CULTURE',2),
('BUILDING_ROMAN_GLADIUS_SERVER_CONSOLE','YIELD_GOLD',1);

UPDATE Building_Flavors SET Flavor=35
 WHERE BuildingType='BUILDING_ROMAN_GLADIUS_SERVER_CONSOLE' AND FlavorType='FLAVOR_CULTURE';
INSERT INTO Building_Flavors(BuildingType,FlavorType,Flavor) VALUES
('BUILDING_ROMAN_GLADIUS_SERVER_CONSOLE','FLAVOR_GOLD',25),
('BUILDING_ROMAN_GLADIUS_SERVER_CONSOLE','FLAVOR_GROWTH',25);

INSERT INTO Leader_Flavors(LeaderType,FlavorType,Flavor)
SELECT 'LEADER_ROMAN_GLADIUS',Type,CASE Type
 WHEN 'FLAVOR_GROWTH' THEN 10 WHEN 'FLAVOR_GOLD' THEN 9 WHEN 'FLAVOR_SCIENCE' THEN 8
 WHEN 'FLAVOR_CULTURE' THEN 8 WHEN 'FLAVOR_DIPLOMACY' THEN 8 WHEN 'FLAVOR_HAPPINESS' THEN 8
 WHEN 'FLAVOR_EXPANSION' THEN 3 WHEN 'FLAVOR_OFFENSE' THEN 3 WHEN 'FLAVOR_DEFENSE' THEN 7
 WHEN 'FLAVOR_PRODUCTION' THEN 7 WHEN 'FLAVOR_WONDER' THEN 5 ELSE 5 END FROM Flavors;
INSERT INTO Leader_MajorCivApproachBiases(LeaderType,MajorCivApproachType,Bias)
SELECT 'LEADER_ROMAN_GLADIUS',MajorCivApproachType,CASE MajorCivApproachType
 WHEN 'MAJOR_CIV_APPROACH_WAR' THEN 3 WHEN 'MAJOR_CIV_APPROACH_HOSTILE' THEN 3
 WHEN 'MAJOR_CIV_APPROACH_DECEPTIVE' THEN 2 WHEN 'MAJOR_CIV_APPROACH_GUARDED' THEN 5
 WHEN 'MAJOR_CIV_APPROACH_AFRAID' THEN 4 WHEN 'MAJOR_CIV_APPROACH_FRIENDLY' THEN 9 ELSE 8 END
 FROM Leader_MajorCivApproachBiases WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Leader_MinorCivApproachBiases(LeaderType,MinorCivApproachType,Bias)
SELECT 'LEADER_ROMAN_GLADIUS',MinorCivApproachType,Bias
 FROM Leader_MinorCivApproachBiases WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Diplomacy_Responses(LeaderType,ResponseType,Response,Bias)
SELECT 'LEADER_ROMAN_GLADIUS',ResponseType,Response,Bias
 FROM Diplomacy_Responses WHERE LeaderType='LEADER_WASHINGTON';

INSERT INTO Civilization_CityNames(CivilizationType,CityName) VALUES
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_1'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_2'),
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_3'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_4'),
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_5'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_6'),
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_7'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_8'),
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_9'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_10'),
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_11'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_12'),
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_13'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_14'),
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_15'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_16'),
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_17'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_18'),
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_19'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_CITY_ROMAN_GLADIUS_20');
INSERT INTO Civilization_SpyNames(CivilizationType,SpyName) VALUES
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_SPY_ROMAN_GLADIUS_1'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_SPY_ROMAN_GLADIUS_2'),
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_SPY_ROMAN_GLADIUS_3'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_SPY_ROMAN_GLADIUS_4'),
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_SPY_ROMAN_GLADIUS_5'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_SPY_ROMAN_GLADIUS_6'),
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_SPY_ROMAN_GLADIUS_7'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_SPY_ROMAN_GLADIUS_8'),
('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_SPY_ROMAN_GLADIUS_9'),('CIVILIZATION_ROMAN_GLADIUS_NETWORK','TXT_KEY_SPY_ROMAN_GLADIUS_10');
