-- Brave New World + installed Community Patch v151 (5.4.6).
UPDATE CustomModOptions SET Value=1 WHERE Name IN
('EVENTS_BATTLES','EVENTS_RED_COMBAT','EVENTS_RED_COMBAT_RESULT','EVENTS_CITY','EVENTS_GOLDEN_AGE','EVENTS_UNIT_CREATED',
 'EVENTS_UNIT_PREKILL','EVENTS_UNIT_CONVERTS','EVENTS_UNIT_UPGRADES','EVENTS_WAR_AND_PEACE');
INSERT INTO Colors(Type,Red,Green,Blue,Alpha) VALUES
('COLOR_CR7_RED',0.48,0.025,0.065,1),('COLOR_CR7_GOLD',0.94,0.74,0.24,1);
INSERT INTO PlayerColors(Type,PrimaryColor,SecondaryColor,TextColor) VALUES('PLAYERCOLOR_CR7','COLOR_CR7_RED','COLOR_CR7_GOLD','COLOR_PLAYER_WHITE_TEXT');
INSERT INTO Traits(Type,Description,ShortDescription) VALUES
('TRAIT_CR7_HABIT','TXT_KEY_CR7_TRAIT_HELP','TXT_KEY_CR7_TRAIT');
CREATE TEMP TABLE CR7Clone AS SELECT * FROM Leaders WHERE Type='LEADER_WASHINGTON';
UPDATE CR7Clone SET ID=NULL,Type='LEADER_CRISTIANO_RONALDO',Description='TXT_KEY_CR7_LEADER',Civilopedia='TXT_KEY_CR7_LEADER_PEDIA',CivilopediaTag='TXT_KEY_CIVILOPEDIA_LEADERS_CR7',ArtDefineTag='CR7LeaderScene.xml',PortraitIndex=0,IconAtlas='CR7_LEADER_ATLAS',PackageID=NULL,VictoryCompetitiveness=10,WonderCompetitiveness=6,MinorCivCompetitiveness=5,Boldness=8,DiploBalance=6,WarmongerHate=4,WorkAgainstWillingness=4,WorkWithWillingness=7,DenounceWillingness=4,DoFWillingness=7,Loyalty=7,Neediness=3,Forgiveness=4,Chattiness=5,Meanness=4;
INSERT INTO Leaders SELECT * FROM CR7Clone;
DROP TABLE CR7Clone;
INSERT INTO Leader_Traits VALUES('LEADER_CRISTIANO_RONALDO','TRAIT_CR7_HABIT');
CREATE TEMP TABLE CR7Clone AS SELECT * FROM Civilizations WHERE Type='CIVILIZATION_PORTUGAL';
UPDATE CR7Clone SET ID=NULL,Type='CIVILIZATION_RELENTLESS_SEVEN',Description='TXT_KEY_CR7_CIV',ShortDescription='TXT_KEY_CR7_CIV',Adjective='TXT_KEY_CR7_ADJECTIVE',Civilopedia='TXT_KEY_CR7_CIV_PEDIA',CivilopediaTag='TXT_KEY_CIV5_CR7',Strategy='TXT_KEY_CR7_STRATEGY',DefaultPlayerColor='PLAYERCOLOR_CR7',Playable=1,AIPlayable=0,PackageID=NULL,PortraitIndex=0,IconAtlas='CR7_ICON_ATLAS',AlphaIconAtlas='CR7_ALPHA_ATLAS',MapImage='CR7Map.dds',DawnOfManImage='CR7Dawn.dds',DawnOfManQuote='TXT_KEY_CR7_DAWN',DawnOfManAudio='',SoundtrackTag='PORTUGAL';
INSERT INTO Civilizations SELECT * FROM CR7Clone;
DROP TABLE CR7Clone;
INSERT INTO Civilization_Leaders VALUES('CIVILIZATION_RELENTLESS_SEVEN','LEADER_CRISTIANO_RONALDO');
INSERT INTO Civilization_FreeBuildingClasses(CivilizationType,BuildingClassType) SELECT 'CIVILIZATION_RELENTLESS_SEVEN',BuildingClassType FROM Civilization_FreeBuildingClasses WHERE CivilizationType='CIVILIZATION_PORTUGAL';
INSERT INTO Civilization_FreeTechs(CivilizationType,TechType) SELECT 'CIVILIZATION_RELENTLESS_SEVEN',TechType FROM Civilization_FreeTechs WHERE CivilizationType='CIVILIZATION_PORTUGAL';
INSERT INTO Civilization_FreeUnits(CivilizationType,UnitClassType,UnitAIType,Count) SELECT 'CIVILIZATION_RELENTLESS_SEVEN',UnitClassType,UnitAIType,Count FROM Civilization_FreeUnits WHERE CivilizationType='CIVILIZATION_PORTUGAL';
CREATE TEMP TABLE CR7Clone AS SELECT * FROM Units WHERE Type='UNIT_CAVALRY';
UPDATE CR7Clone SET ID=NULL,Type='UNIT_CR7_COMPLETE_FORWARD',Description='TXT_KEY_CR7_UNIT',Civilopedia='TXT_KEY_CR7_UNIT_PEDIA',Strategy='TXT_KEY_CR7_UNIT_STRATEGY',Help='TXT_KEY_CR7_UNIT_HELP',Cost=(Cost*120+99)/100,Moves=Moves+1,PortraitIndex=0,IconAtlas='CR7_OBJECT_ATLAS',UnitFlagIconOffset=0,UnitFlagAtlas='CR7_FLAG_ATLAS';
INSERT INTO Units SELECT * FROM CR7Clone;
DROP TABLE CR7Clone;
CREATE TEMP TABLE CR7Clone AS SELECT * FROM Buildings WHERE Type='BUILDING_BARRACKS';
UPDATE CR7Clone SET ID=NULL,Type='BUILDING_CR7_SPORTING_ACADEMY',Description='TXT_KEY_CR7_ACADEMY',Civilopedia='TXT_KEY_CR7_ACADEMY_PEDIA',Strategy='TXT_KEY_CR7_ACADEMY_STRATEGY',Help='TXT_KEY_CR7_ACADEMY_HELP',PortraitIndex=1,IconAtlas='CR7_OBJECT_ATLAS';
INSERT INTO Buildings SELECT * FROM CR7Clone;
DROP TABLE CR7Clone;
INSERT INTO Civilization_UnitClassOverrides VALUES('CIVILIZATION_RELENTLESS_SEVEN','UNITCLASS_CAVALRY','UNIT_CR7_COMPLETE_FORWARD');
INSERT INTO Civilization_BuildingClassOverrides VALUES('CIVILIZATION_RELENTLESS_SEVEN','BUILDINGCLASS_BARRACKS','BUILDING_CR7_SPORTING_ACADEMY');
