INSERT OR REPLACE INTO Language_en_US(Tag,Text) VALUES
('TXT_KEY_CR7_CIV','The Relentless Seven'),
('TXT_KEY_CR7_ADJECTIVE','Relentless'),
('TXT_KEY_CR7_LEADER','Cristiano Ronaldo'),
('TXT_KEY_CIVILOPEDIA_LEADERS_CR7','Cristiano Ronaldo'),
('TXT_KEY_CIV5_CR7','The Relentless Seven'),
('TXT_KEY_CR7_TITLE','The Boy from Madeira Who Refused to Be Ordinary'),
('TXT_KEY_CR7_TRAIT','Work Until Greatness Becomes Habit'),
('TXT_KEY_CR7_TRAIT_HELP','+15% Combat Experience for military units. Each genuine upgrade grants a permanent Reinvention tier: +2% strength and 3 HP healing per kill per tier (maximum III, IV after Chapter VI). Earn Ambition through development and victories to unlock seven permanent Career Chapters. Click CR7 to view your career.'),
('TXT_KEY_CR7_CIV_PEDIA','A civilization inspired by Cristiano Ronaldo: Madeira, Sporting, Manchester, Madrid, Portugal, Juventus and Al-Nassr. Preserve veterans and pursue ambition across generations.'),
('TXT_KEY_CR7_LEADER_PEDIA','Cristiano Ronaldo rose from Funchal through disciplined development, adapting across clubs and eras while captaining Portugal. This civilization celebrates training, longevity and continuing ambition; it assumes no future achievements.'),
('TXT_KEY_CR7_STRATEGY','Train at Sporting Academies, preserve high-level units, and upgrade them through successive eras. Earn Ambition from worthy victories and civic achievements. Freedom, Domination and Culture suit a veteran-led empire; Diplomacy is a secondary path.'),
('TXT_KEY_CR7_UNIT','Complete Forward'),
('TXT_KEY_CR7_UNIT_HELP','Cavalry replacement: active CP baseline, +20% Production cost, +1 Movement, move after attacking. Relentless Finisher: +15% vs wounded, ignore rivers, heal 8 HP on kills, restore 1 Movement after first kill each turn. After upgrade: +8% vs wounded, heal 5 HP on kills.'),
('TXT_KEY_CR7_UNIT_PEDIA','An adaptable veteran whose explosive attack becomes a decisive finish. Uses standard Cavalry world art with a custom flag and portrait.'),
('TXT_KEY_CR7_UNIT_STRATEGY','Finish wounded opponents; keep the Forward alive to preserve its reduced veteran promotion through upgrades.'),
('TXT_KEY_CR7_ACADEMY','Sporting Academy'),
('TXT_KEY_CR7_ACADEMY_HELP','Barracks replacement. Retains all active CP Barracks effects; +1 Production, +1 Culture. Produced military units gain +5% Combat Experience and First In, Last Out. At Level 4: 15 Production and 10 Culture in their original training city, +1 Ambition; one rewarded unit per training city per era.'),
('TXT_KEY_CR7_ACADEMY_PEDIA','Inspired by the lonely but formative years of training in Lisbon. Purchased units do not receive its training bonuses.'),
('TXT_KEY_CR7_ACADEMY_STRATEGY','Build early, then protect and promote its graduates. Each training city can celebrate one Level 4 graduate per era.'),
('TXT_KEY_CR7_DUMMY','Career bonus'),
('TXT_KEY_CR7_LEGACY','The Story Is Still Being Written'),
('TXT_KEY_CR7_DIPLO_FIRST_GREETING','I came from a small island with a dream larger than the horizon. Tell me—what are you prepared to sacrifice for yours?'),
('TXT_KEY_CR7_DIPLO_DECLARE_WAR','You have chosen the greatest test. I will meet it at my highest level.'),
('TXT_KEY_CR7_DIPLO_ATTACKED','Pressure does not change the standard. It reveals who was prepared.'),
('TXT_KEY_CR7_DIPLO_DEFEATED','You have won today. Tomorrow, the work begins again.'),
('TXT_KEY_CR7_DIPLO_VICTORY','Greatness was never one moment. It was every day that came before it.'),
('TXT_KEY_CR7_DAWN','From the island of Madeira came a child unwilling to accept the limits placed before him. He left home while still young, carrying neither wealth nor certainty—only a conviction that talent must be sharpened until no weakness remained.[NEWLINE][NEWLINE]In Manchester, he transformed spectacle into purpose. In Madrid, goals became records and records became expectation. Across Europe and beyond it, new leagues brought new demands, yet the standard never fell. For Portugal, years of disappointment ended beneath the leadership of its eternal captain.[NEWLINE][NEWLINE]Cristiano Ronaldo, Boy from Madeira Who Refused to Be Ordinary, your people now inherit that relentless ambition. Train them until exhaustion becomes discipline. Preserve those who have survived the hardest trials. Strike when your opponents weaken, and let every age witness your reinvention.[NEWLINE][NEWLINE]Will your greatness fade with the passage of time—or will history discover that you have only just begun?'),
('TXT_KEY_CR7_CHAPTER_1_TITLE','The Island Boy'),
('TXT_KEY_CR7_CHAPTER_1_STORY','On the steep streets of Funchal, talent appeared before opportunity. The dream was enormous, but its beginnings were small.'),
('TXT_KEY_CR7_CHAPTER_1_EFFECTS','Capital: +1 Food and +1 Production; one free Sporting Academy once its requirements are met. First military unit trained in the capital each era: +5 XP. Workers trained there: +1 Sight.'),
('TXT_KEY_CR7_CHAPTER_2_TITLE','Alone in Lisbon'),
('TXT_KEY_CR7_CHAPTER_2_STORY','The child leaves his island, his family and everything familiar. Talent has opened the door; discipline must now keep it open.'),
('TXT_KEY_CR7_CHAPTER_2_EFFECTS','Newly trained military units: +5 XP. Earned promotions heal 10 HP, once per unit per turn. Sporting Academies: +1 additional Production.'),
('TXT_KEY_CR7_CHAPTER_3_TITLE','The Theatre of Dreams'),
('TXT_KEY_CR7_CHAPTER_3_STORY','The tricks become purpose. The boy becomes an athlete, the winger becomes a match-winner, and potential becomes expectation.'),
('TXT_KEY_CR7_CHAPTER_3_EFFECTS','Level 4+ military units: Explosive Athlete (+1 Movement on turns begun above 90 HP; ignore rivers; +5% strength attacking from open terrain). Military Gold purchases: 5% rebate. Great Generals: +10% generation.'),
('TXT_KEY_CR7_CHAPTER_4_TITLE','The Standard of Madrid'),
('TXT_KEY_CR7_CHAPTER_4_STORY','Records cease to be distant targets. Every season begins with the expectation that yesterday''s impossible number will be surpassed.'),
('TXT_KEY_CR7_CHAPTER_4_EFFECTS','Level 4+ units: +5% strength against wounded units and cities; +15% General points fighting major-civ units. Veteran city captures: Culture and Golden Age Points equal to 3 x population, heal captor 15 HP (25-turn civ cooldown). Each distinct original capital: 2-turn Golden Age and +3 XP to surviving war participants.'),
('TXT_KEY_CR7_CHAPTER_5_TITLE','The Captain''s Crown'),
('TXT_KEY_CR7_CHAPTER_5_STORY','Individual brilliance brought admiration. Leadership brings something greater: the belief that an entire nation can finally cross the line together.'),
('TXT_KEY_CR7_CHAPTER_5_EFFECTS','Ordinary General aura: +3 percentage points. Military units within 2 tiles: +5% defense, +5% ranged defense, heal 3 HP at turn start. An enemy declaration of war grants 50 Golden Age Points and heals friendly-territory military units 5 HP (30-turn cooldown).'),
('TXT_KEY_CR7_CHAPTER_6_TITLE','Different League, Same Standard'),
('TXT_KEY_CR7_CHAPTER_6_STORY','The shirt changes. The country changes. The role changes. The demand placed upon himself does not.'),
('TXT_KEY_CR7_CHAPTER_6_EFFECTS','Military upgrades: -15% Gold; retain all XP; Reinvention IV available; upgrades below 35% HP heal 15 HP. First 3 currently eligible overseas cities: +1 Gold, +1 Culture, +1 Tourism after Flight, +3% military production.'),
('TXT_KEY_CR7_CHAPTER_7_TITLE','Beyond Time'),
('TXT_KEY_CR7_CHAPTER_7_STORY','Opponents change, generations change, and football itself changes. The number seven remains, still measuring himself against tomorrow.'),
('TXT_KEY_CR7_CHAPTER_7_EFFECTS','Immediately: 6-turn Golden Age, free Social Policy, +8 XP to all military units, full healing, 2 turns of We Love the King Day in all cities. During Golden Ages: +5% military production, Culture and Tourism; veterans heal 3 HP each turn. Every further 60 Ambition: 1-turn Golden Age, 15 x era Culture, +1% permanent military production AND Tourism (each capped at +5%; rewards continue).'),
('TXT_KEY_PROMOTION_CR7_HABIT','Relentless Training'),
('TXT_KEY_PROMOTION_CR7_HABIT_HELP','+15% Combat Experience.'),
('TXT_KEY_PROMOTION_CR7_ACADEMY_TRAINING','Sporting Graduate'),
('TXT_KEY_PROMOTION_CR7_ACADEMY_TRAINING_HELP','+5% Combat Experience.'),
('TXT_KEY_PROMOTION_CR7_FINISHER','Relentless Finisher'),
('TXT_KEY_PROMOTION_CR7_FINISHER_HELP','+15% vs wounded; ignore rivers; heal 8 HP on kills; first kill each turn restores 1 Movement, without an additional attack.'),
('TXT_KEY_PROMOTION_CR7_FINISHER_VETERAN','Veteran Finisher'),
('TXT_KEY_PROMOTION_CR7_FINISHER_VETERAN_HELP','+8% vs wounded; heal 5 HP on kills. Retained through upgrades.'),
('TXT_KEY_PROMOTION_CR7_EXPLOSIVE','Explosive Athlete'),
('TXT_KEY_PROMOTION_CR7_EXPLOSIVE_HELP','Ignore rivers; +5% strength attacking FROM open terrain; gain 1 Movement on turns begun above 90 HP.'),
('TXT_KEY_PROMOTION_CR7_EXPLOSIVE_OPEN','Explosive Athlete: open ground'),
('TXT_KEY_PROMOTION_CR7_EXPLOSIVE_OPEN_HELP','+5% attacking strength while standing on open ground.'),
('TXT_KEY_PROMOTION_CR7_EXPLOSIVE_MOVE','Explosive Athlete: fresh legs'),
('TXT_KEY_PROMOTION_CR7_EXPLOSIVE_MOVE_HELP','+1 Movement for this turn, qualified at its beginning above 90 HP.'),
('TXT_KEY_PROMOTION_CR7_MADRID_GG','Madrid: major opponent'),
('TXT_KEY_PROMOTION_CR7_MADRID_GG_HELP','+15% Great General points in the current combat against a major-civilization unit.'),
('TXT_KEY_PROMOTION_CR7_MADRID','The Standard of Madrid'),
('TXT_KEY_PROMOTION_CR7_MADRID_HELP','+5% vs wounded; +5% vs cities; +15% General points against major-civ units.'),
('TXT_KEY_PROMOTION_CR7_CAPTAIN','Captain''s Standard'),
('TXT_KEY_PROMOTION_CR7_CAPTAIN_HELP','+5% defense; +5% ranged defense; heal 3 HP at turn start within 2 tiles of a friendly Great General.'),
('TXT_KEY_PROMOTION_CR7_FIRST_IN','First In, Last Out'),
('TXT_KEY_PROMOTION_CR7_FIRST_IN_HELP','First time at Level 4: original training city gains 15 Production, 10 Culture; +1 Ambition. One rewarded graduate per city per era.'),
('TXT_KEY_PROMOTION_CR7_WORKER_SIGHT','Madeiran Horizons'),
('TXT_KEY_PROMOTION_CR7_WORKER_SIGHT_HELP','+1 Sight.'),
('TXT_KEY_PROMOTION_CR7_FORWARD_MOBILITY','Complete Forward'),
('TXT_KEY_PROMOTION_CR7_FORWARD_MOBILITY_HELP','Can move after attacking; does not grant additional attacks.'),
('TXT_KEY_PROMOTION_CR7_REINVENTION_1','Reinvention I'),
('TXT_KEY_PROMOTION_CR7_REINVENTION_1_HELP','+2% strength; heal 3 HP after a kill. This is one total tier, not stacking tiers.'),
('TXT_KEY_PROMOTION_CR7_REINVENTION_2','Reinvention II'),
('TXT_KEY_PROMOTION_CR7_REINVENTION_2_HELP','+4% strength; heal 6 HP after a kill. This is one total tier, not stacking tiers.'),
('TXT_KEY_PROMOTION_CR7_REINVENTION_3','Reinvention III'),
('TXT_KEY_PROMOTION_CR7_REINVENTION_3_HELP','+6% strength; heal 9 HP after a kill. This is one total tier, not stacking tiers.'),
('TXT_KEY_PROMOTION_CR7_REINVENTION_4','Reinvention IV'),
('TXT_KEY_PROMOTION_CR7_REINVENTION_4_HELP','+8% strength; heal 12 HP after a kill. This is one total tier, not stacking tiers.'),
('TXT_KEY_CITY_CR7_1','Funchal'),
('TXT_KEY_CITY_CR7_2','Lisbon'),
('TXT_KEY_CITY_CR7_3','Manchester'),
('TXT_KEY_CITY_CR7_4','Madrid'),
('TXT_KEY_CITY_CR7_5','Turin'),
('TXT_KEY_CITY_CR7_6','Riyadh'),
('TXT_KEY_CITY_CR7_7','Porto'),
('TXT_KEY_CITY_CR7_8','Braga'),
('TXT_KEY_CITY_CR7_9','Aveiro'),
('TXT_KEY_CITY_CR7_10','Coimbra'),
('TXT_KEY_CITY_CR7_11','Faro'),
('TXT_KEY_CITY_CR7_12','Setúbal'),
('TXT_KEY_CITY_CR7_13','Guimarães'),
('TXT_KEY_CITY_CR7_14','Leiria'),
('TXT_KEY_CITY_CR7_15','Viseu'),
('TXT_KEY_CITY_CR7_16','Moscow'),
('TXT_KEY_CITY_CR7_17','Cardiff'),
('TXT_KEY_CITY_CR7_18','Paris'),
('TXT_KEY_CITY_CR7_19','Doha'),
('TXT_KEY_CITY_CR7_20','Jeddah');
