INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CIV','The Shattered Empire');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_SHORT','Shattered Empire');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_ADJECTIVE','Imperial');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_LEADER','The Last Emperor');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_TRAIT','The Weight of an Empire');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_TRAIT_HELP','Begin with 82 Imperial Authority, a population-2 capital and two provinces (or Settlers where safe founding is unavailable). Every province has a persistent Governor. Govern Loyalty, military Oaths, reforms and succession to avert civil wars. Survive collapse and restore unity to earn +10% Production and Culture while stable. Open Imperial Administration near the top panel.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CIV_PEDIA','Conquering the world was never the difficult part. Keeping it was.[NEWLINE][NEWLINE]Aeternum once ruled a world of marble avenues, provincial palaces and legions sworn to the Eternal Throne. Victory brought distant lands into the imperial order, but each Governor acquired estates, clients and soldiers. The Last Emperor inherits the symbols of eternity and the practical burden of persuading powerful people to keep their promises.[NEWLINE][NEWLINE]This fictional civilization tells its history through the Governors appointed, soldiers lost, Emperors chosen, and provinces restored in each campaign. Collapse is avoidable: a loyal, ambitious Governor can remain an invaluable ally.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_LEADER_PEDIA','The Last Emperor is the permanent diplomatic face of the Eternal Throne. Individual rulers succeed one another inside Imperial Administration, where their reigns, relationships and achievements survive saving and loading. The monarch must balance the hereditary court, the armies, and the provincial council.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_STRATEGY','Three early cities and strong Imperial Legions reward expansion, but sustained growth strains administration. Garrison provinces, connect them to Aeternum and construct Governor Palaces. Complete demands before deadlines and manage ambitious Governors before they organize a civil war. Choose reforms and successors that address your weakest institution. Military suppression, autonomy and reconciliation can all end rebellions.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DAWN','Last Emperor, the Eternal Throne is yours. Aeternum and two provinces await your command. Your Legions can conquer kingdoms; your Governors can keep them prosperous or tear them apart. Rule wisely, listen before resentment hardens, and make the shattered crown whole again.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_LEGION','Imperial Legion');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_LEGION_HELP','Replaces the Warrior. Strength 10; costs 15% more (rounded up). Imperial Discipline grants +15% Combat Strength in friendly territory while Authority is at least 60. Discipline survives upgrades. Participates in provincial Oaths and bounded crisis defections.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_LEGION_PEDIA','The Imperial Legion carries the eagle of Aeternum and an oath to the Eternal Throne. Training binds the cohort to its recruiting province; service and victory strengthen its allegiance, while a rebellious home Governor may threaten it. Its inherited discipline endures when its weapons change.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_LEGION_STRATEGY','Use the Legion to defend exposed early provinces. Maintain Authority above 60 for its friendly territory bonus. A veteran with a weak Oath and a rebellious home province may defect; keep provincial loyalty high.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_PALACE','Provincial Governor''s Palace');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_PALACE_HELP','Replaces the Monument, retaining all normal costs and effects. +1 Gold. In provinces: +2 Loyalty each political interval and permits autonomy charters. In the capital: +1 Authority every ten Standard-speed turns. Effects scale in timing with game speed.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_PALACE_PEDIA','The Palace combines the public monuments of imperial memory with the offices of provincial rule. Tax accounts, petitions and military rolls pass through its halls. Its strength rests in trusted administration, not merely marble walls.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_PALACE_STRATEGY','Build early in provinces to support Loyalty and unlock autonomy. The capital Palace provides measured Authority recovery. Provincial administration costs 1 Gold per city regardless of the Palace.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DUMMY','Imperial administration effect');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_GOLDEN','Golden Empire');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_STABLE','Stable Empire');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_STRAINED','Strained Empire');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_FRACTURED','Fractured Empire');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_COLLAPSE','Imperial Collapse');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_LOYALIST','Loyalist');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_MILITARIST','Militarist');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_MERCHANT','Merchant');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_POPULIST','Populist');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_AMBITIOUS','Ambitious');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_NONE','Unreformed court');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_MONARCHY','Absolute Monarchy');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_FEDERATION','Imperial Federation');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DICTATORSHIP','Military Dictatorship');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_PROVINCE_I','Province I');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_PROVINCE_II','Province II');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_STAGE_0','Loyal administration');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_STAGE_1','Discontent');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_STAGE_2','Defiance');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_STAGE_3','Armed revolt');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_STAGE_4','Secession crisis');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_FOUNDING','Aeternum was founded as {1_Name}, seat of the Eternal Throne.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_APPOINTED','{1_Name} was appointed Governor of {2_City}, serving as a {3_Type}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_REPLACED','The Emperor dismissed {1_Old} and appointed {2_New}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_REBEL','Governor {1_Name} betrayed the Throne and raised a rebellion in {2_City}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_REBEL_END','The faction of {1_Name} ended its rebellion: {2_Result}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_WAR','{1_War} began when {2_Leader} claimed the Throne, supported by {3_Count} provinces.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_WAR_END','{1_War} ended: {2_Result}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_DEFECTION','A regiment associated with {1_Name} defected ({2_Unit}).');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_DEMAND_MET','The court fulfilled the demand of {1_Name}: {2_Demand}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_DEMAND_FAILED','The court refused or failed the demand of {1_Name}: {2_Demand}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_REFORM','The Emperor adopted {1_Reform}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_CHARTER','{1_Name} received a provincial autonomy charter.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_PAYMENT','Received {1_Cost} Gold from the court.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_PAID','The court granted {1_Name} {2_Cost} Gold.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_COUNCIL','The reign of {1_Name} approached its end; the Council presented three successors.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_SUCCESSOR','{1_Name} took the Eternal Throne as {2_Heir}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_SUCCESSION_CRISIS','A disputed succession cost the Empire legitimacy.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_COLLAPSE','Imperial Authority fell into collapse. The provinces awaited a restoration.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_RESTORED','The Empire Reborn: authority and provincial loyalty endured, restoring imperial unity.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_LOST','The Empire lost {1_City}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_CONQUEST','The Legions conquered {1_City} during the reign of {2_Emperor}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_TITLE','Provincial petition');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_NOTICE','{1_Name}, Governor of {2_City}, requests: {3_Demand}. Deadline: turn {4_Turn}. Review Imperial Administration.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_GARRISON','Maintain a military garrison');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_CONNECTION','Connect the province to the capital');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_WALLS','Build Walls');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_GROWTH','Increase provincial population');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_PEACE','Maintain five Standard-speed turns of peace');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_FARMS','Construct two additional Farms');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_RESOURCE','Improve the indicated strategic resource');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_CAMP','Eliminate the nearby Barbarian camp');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_FUNDS','Provide financial assistance');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_AUTONOMY','Grant military autonomy');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_MET','Demand fulfilled: {1_Demand}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_FAILED','Demand refused or expired: {1_Demand}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_UNREST_TITLE','Provincial unrest');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_UNREST_NOTICE','{1_Name} in {2_City} has entered {3_Stage}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REVOLT_TITLE','Provincial rebellion');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REVOLT_NOTICE','{1_Name} has raised a rebel army near {2_City}. Suppress the tracked forces or negotiate in Imperial Administration.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_WAR_NAME','The War of {1_Count} Crowns');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_WAR_NOTICE','{1_Name} claims the Eternal Throne; {2_Count} provinces are involved. The civil war ends when every participating faction is resolved.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REBEL_UNIT','Rebels of {1_Name}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_RESULT_SUPPRESSED','military suppression');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_RESULT_AUTONOMY','negotiated autonomy');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_RESULT_CONCESSION','financial concessions');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_RESULT_RECONCILED','political reconciliation');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_RESULT_EXHAUSTED','exhaustion and autonomy');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_RESULT_LOST','territorial loss');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_RESULT_RESTORED','imperial unity restored');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_SUCCESSION_TITLE','The Imperial Council');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_SUCCESSION_NOTICE','Three persistent candidates seek the Eternal Throne. Choose in the Dynasty tab before the deadline; otherwise the Council selects an appropriate heir.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HEIR_BLOOD','Heir of Blood');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HEIR_STEEL','Heir of Steel');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HEIR_COUNCIL','Council''s Choice');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HEIR_COUNCIL_RELATION','Provincial council');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HEIR_HELP_BLOOD','+15 Authority. Ambitious Governors lose 10 Loyalty. Peaceful succession adds another +5 Authority.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HEIR_HELP_STEEL','+15 military Oath. Merchant and Populist Governors lose 10 Loyalty. Peaceful succession adds +5 Authority.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HEIR_HELP_COUNCIL','+10 provincial Loyalty, -15 Authority, and -10% city Production for ten Standard-speed turns. Peaceful succession adds +5 Authority.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HEIR_TRAIT_BLOOD','Hereditary legitimacy');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HEIR_TRAIT_STEEL','Veteran commander');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HEIR_TRAIT_COUNCIL','Consensus builder');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HEIR_TRAIT_FOUNDER','Keeper of the fractured crown');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REFORM_HELP_MONARCHY','+10% military Production in the capital. Suppression yields +7 Authority instead of +5. Distant provinces lose another 2 Loyalty per interval. Rebel recruitment budgets increase by 1.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REFORM_HELP_FEDERATION','+3 Loyalty per interval in chartered provinces and fewer demands. Chartered provinces lose 10% Production. Administrative capacity increases by three cities.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REFORM_HELP_DICTATORSHIP','+15 effective Oath to disciplined Legion lineages while active. +10% Combat Strength against barbarian units, including rebels. Militarist Governor Ambition grows faster.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REFORM_COST','Costs 10 Authority; changes have a 30 Standard-speed turn cooldown. Unlocks in the Classical Era.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REPLACE_COST','Costs 8 Authority. Replacement creates one turn of resistance and reduces local military Oaths by 5.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CHARTER_COST','Peacetime: 50% provincial Gold cost and 5 Authority; +15 Loyalty, +12 Ambition and permanent autonomy. Requires a Palace and loyal or discontented administration.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_SETTLEMENT_COST','Wartime: 200% provincial Gold cost and 10 Authority. Ends this faction only, guarantees at least 70 Loyalty, adds 20 Ambition and permanent autonomy. Hereditary privileges add 0.5 Ambition each political interval, including after Governor replacement.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_AUTHORITY_LABEL','Authority');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_ACTION_SETTLEMENT','Negotiate wartime autonomy');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_HISTORY_DEMAND_CANCELLED','The petition of {1_Name} was withdrawn because it was no longer feasible: {2_Demand}. No political penalty applied.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_RECONCILE_COST','Costs 15 Authority; ends the local revolt and rebuilds loyalty.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REBELLION_REQUIRED','An active provincial rebellion is required.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_AUTHORITY_REQUIRED','Insufficient Imperial Authority.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_GOLD_REQUIRED','Insufficient Gold.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_ERA_REQUIRED','Reforms unlock in the Classical Era.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_COOLDOWN','This decision is on cooldown.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_PALACE_REQUIRED','A Palace and an unchartered province are required.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_INVALID','This decision is no longer available.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_READY','Decision available.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_ACTION_DONE','The court has enacted the decision.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REPLACED','Dismissed from office.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_ACTION_BRIBE','Compensate Governor: +12 Loyalty');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_ACTION_CHARTER','Grant peacetime autonomy');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_ACTION_REPLACE','Replace Governor: 8 Authority');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_ACTION_FUND','Fund the petition: fulfill demand');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_ACTION_REFUSE','Refuse the petition: -12 Loyalty');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_ACTION_CONCESSION','Negotiate financial concessions');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_ACTION_RECONCILE','Political reconciliation: 15 Authority');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_PROMO_DISCIPLINE','Imperial Discipline');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_PROMO_HELP_DISCIPLINE','Persistent Legion lineage. +15% friendly territory strength while Authority is at least 60.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_PROMO_DISCIPLINE_ACTIVE','Imperial Discipline: active');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_PROMO_HELP_DISCIPLINE_ACTIVE','+15% Combat Strength in friendly territory.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_PROMO_REBEL_COMBAT','Imperial counterinsurgency');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_PROMO_HELP_REBEL_COMBAT','+10% Combat Strength against barbarians, including political rebel armies.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_RESTORED_TITLE','The Empire Reborn');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_RESTORED_NOTICE','+10% Production and Culture in all imperial cities while stable. Renewed political crisis makes these effects dormant.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_TITLE','Imperial Administration');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_LAUNCHER','Imperial Authority: {1_Authority} - {2_State}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_SUMMARY','Emperor {1_Name} | Authority {2_Authority}: {3_State}[NEWLINE]Government: {4_Reform}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_TAB_OVERVIEW','Overview');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_TAB_GOVERNORS','Governors');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_TAB_DECISIONS','Decisions');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_TAB_MILITARY','Military Oaths');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_TAB_REFORMS','Reforms');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_TAB_DYNASTY','Dynasty');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_TAB_CHRONICLE','Chronicle');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_GOVERNOR_DETAIL','{1_City}[NEWLINE]{2_Name}, {3_Archetype}[NEWLINE]Loyalty {4_Loyalty} | Ambition {5_Ambition} | Prestige {6_Prestige}[NEWLINE]{7_Stage}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_GOVERNOR_DATES','Governor #{1_ID}; appointed turn {2_Turn}; relationship {3_Relationship}; autonomy: {4_Charter}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_LOYALTY_CHANGE','Last interval Loyalty change: {1_Amount} (routine movement capped at +/-8)');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_DETAIL','Petition: {1_Demand}[NEWLINE]Deadline: turn {2_Turn}; financial compensation: {3_Cost} Gold');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_TARGET','Target total: {1_Target}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DEMAND_LOCATION','Target plot: {1_X}, {2_Y}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DECISION_HELP','Only currently valid actions are shown. Replacements cost Authority; payments scale with population, income and speed. Decisions have cooldowns. Ambition and Prestige alone never cause rebellion.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_OVERVIEW_DETAIL','Loyal provinces: {1_Loyal} | Discontented: {2_Unrest} | Rebel: {3_Rebels}[NEWLINE]Administrative strain: {4_Strain} | Average Loyalty: {5_Loyalty}[NEWLINE]War duration pressure: {6_Turns} turns');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_OVERVIEW_HELP','Loyalty below 45 causes discontent; below 25 causes defiance. Two critical political checks can trigger revolt. Authority below 30 and three nearby severe provinces with an ambitious claimant can produce a War of the Crowns. Administration capacity is 5 + twice your era, with three extra under Federation.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_WAR_DETAIL','{1_War}[NEWLINE]Claimant: {2_Leader}; began turn {3_Turn}[NEWLINE]Provinces: {4_Count}; rebel troops raised: {5_Troops}; defections: {6_Defections}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_WAR_RECORD','{1_War}: claimant {2_Leader}[NEWLINE]Turns {3_Start}-{4_End}: {5_Result}[NEWLINE]Provinces restored {6_Count}; troops raised {7_Troops}; Authority lost {8_Lost}, recovered {9_Recovered}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_RESTORATION_DETAIL','Restoration: {1_State}[NEWLINE]Qualifying stability: {2_Progress}/{3_Required} turns. Requires a resolved collapse, Authority 75, average Loyalty 80, no revolt or pending succession.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_SUCCESSION_PENDING','The Council awaits a successor. Decision deadline: turn {1_Turn}.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_MILITARY_OVERVIEW','Tracked land regiments: {1_Count}; average Oath: {2_Oath}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_MILITARY_HELP','Oaths follow home-province Loyalty and Authority. Defections require a political rebellion and Oath below 40, are limited to two per faction, and exclude foreign mod uniques, civilians, cargo, embarked troops and units in cities. An equivalent rebel is created safely before a defector is removed.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CAPITAL_ARMY','Central imperial army');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_UNIT_DETAIL','{1_Name} (lineage #{2_ID})[NEWLINE]Oath {3_Oath}: {4_Status} | Battles {5_Battles}; kills {6_Kills}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_OATH_FANATIC','Fanatically loyal');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_OATH_RELIABLE','Reliable');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_OATH_QUESTIONABLE','Questionable');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_OATH_MUTINY','Mutiny risk');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_OATH_DEFECTION','Defection candidate');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DYNASTY_RECORD','Emperor {1_Name}[NEWLINE]Reign {2_Start}-{3_End} ({4_Length} turns)[NEWLINE]Civil wars {5_Wars}; revolts {6_Revolts}; provinces acquired {7_Acquired}; lost {8_Lost}; reforms {9_Reforms}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REFORM_OVERVIEW','Active government: {1_Reform}[NEWLINE]Next change available in {2_Turns} turns. Reforms unlock after the Ancient Era and cost 10 Authority.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_ADOPT_REFORM','Adopt {1_Reform}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_SELECT_HEIR','Crown {1_Name}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_TURN','Turn {1_Turn}');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_UI_HINT','Decisions are validated by the gameplay manager. Escape closes administration.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_YES','Yes');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_NO','No');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_ACTIVE','Active');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DORMANT','Dormant');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_LOCKED','Not yet restored');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_UNKNOWN_CITY','an imperial city');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_GARRISON','Military garrison');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_UNGARRISONED','No military garrison');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_CONNECTION','Capital connection');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_PALACE','Governor''s Palace');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_AUTONOMY','Autonomy charter');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_FEDERATION','Federation charter');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_DISTANCE','Distance from capital');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_MONARCHY','Centralized government');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_AMBITION','Ambition above 70');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_UNHAPPINESS','Negative imperial Happiness');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_WAR','Prolonged warfare');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_STRAIN','Administrative overextension');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_AUTHORITY','Imperial Authority');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_LOYALIST','Loyalist administration');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_MERCHANT','Economic restrictions');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_POPULIST','Prosperous population');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_RELATIONSHIP','Relationship with Emperor');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_REASON_NEARBY_REVOLT','Nearby rebel support');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_0','Aeternum');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_1','Valoria');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_2','Vespera');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_3','Aquila');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_4','Corvinum');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_5','Solaria');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_6','Marcellia');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_7','Dravena');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_8','Elyria');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_9','Carinum');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_10','Caelestis');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_11','Nova Aeternum');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_12','Vallum');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_13','Severia');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_14','Flavium');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_15','Portus Aureus');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_16','Vindex');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_17','Altoria');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_18','Valentia');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_19','Lucania');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_20','Magnara');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_21','Neravum');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_22','Tiberia');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_CITY_23','Justinia');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DIPLO_FIRST_GREETING','Behold the Eternal Throne. Kingdoms rise and fall, but our Empire shall endure. Do you come as a friend, or as another enemy seeking our ruins?');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DIPLO_DEFEATED','The banners have fallen. The Legions have scattered. Yet remember this, conqueror: even shattered empires leave shadows upon the earth.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DIPLO_DECLAREWAR','Our Legions will settle what your envoys could not. Let the imperial eagles advance.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DIPLO_ATTACKED','You strike at the Throne while our provinces watch. You shall learn what still binds this Empire.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DIPLO_PEACE_MADE_BY_HUMAN_GRACIOUS','Let our peoples rest. Even an Emperor must know when to sheathe the sword.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DIPLO_TRADE_ACCEPT_ACCEPTABLE','The imperial treasury accepts these terms.');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_IMPERIAL_DIPLO_TRADE_REJECT_UNACCEPTABLE','Such terms would make every Governor laugh at the Throne. Present a fairer offer.');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_0');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_1');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_2');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_3');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_4');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_5');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_6');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_7');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_8');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_9');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_10');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_11');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_12');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_13');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_14');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_15');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_16');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_17');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_18');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_19');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_20');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_21');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_22');
INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_SHATTERED_EMPIRE','TXT_KEY_IMPERIAL_CITY_23');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_CIVILOPEDIA_LEADERS_IMPERIAL_HEADING_1','The Last Emperor');
INSERT INTO Language_en_US(Tag,Text) VALUES ('TXT_KEY_CIVILOPEDIA_LEADERS_IMPERIAL_TEXT_1','The Last Emperor is the permanent diplomatic face of the Eternal Throne. Individual rulers succeed one another inside Imperial Administration, where their reigns, relationships and achievements survive saving and loading. The monarch must balance the hereditary court, the armies, and the provincial council.');
INSERT INTO Diplomacy_Responses SELECT 'LEADER_LAST_EMPEROR',ResponseType,Response,Bias FROM Diplomacy_Responses WHERE LeaderType='LEADER_AUGUSTUS';
DELETE FROM Diplomacy_Responses WHERE LeaderType='LEADER_LAST_EMPEROR' AND ResponseType='RESPONSE_FIRST_GREETING';
INSERT INTO Diplomacy_Responses VALUES ('LEADER_LAST_EMPEROR','RESPONSE_FIRST_GREETING','TXT_KEY_IMPERIAL_DIPLO_FIRST_GREETING',1);
DELETE FROM Diplomacy_Responses WHERE LeaderType='LEADER_LAST_EMPEROR' AND ResponseType='RESPONSE_DEFEATED';
INSERT INTO Diplomacy_Responses VALUES ('LEADER_LAST_EMPEROR','RESPONSE_DEFEATED','TXT_KEY_IMPERIAL_DIPLO_DEFEATED',1);
DELETE FROM Diplomacy_Responses WHERE LeaderType='LEADER_LAST_EMPEROR' AND ResponseType='RESPONSE_DECLAREWAR';
INSERT INTO Diplomacy_Responses VALUES ('LEADER_LAST_EMPEROR','RESPONSE_DECLAREWAR','TXT_KEY_IMPERIAL_DIPLO_DECLAREWAR',1);
DELETE FROM Diplomacy_Responses WHERE LeaderType='LEADER_LAST_EMPEROR' AND ResponseType='RESPONSE_ATTACKED';
INSERT INTO Diplomacy_Responses VALUES ('LEADER_LAST_EMPEROR','RESPONSE_ATTACKED','TXT_KEY_IMPERIAL_DIPLO_ATTACKED',1);
DELETE FROM Diplomacy_Responses WHERE LeaderType='LEADER_LAST_EMPEROR' AND ResponseType='RESPONSE_PEACE_MADE_BY_HUMAN_GRACIOUS';
INSERT INTO Diplomacy_Responses VALUES ('LEADER_LAST_EMPEROR','RESPONSE_PEACE_MADE_BY_HUMAN_GRACIOUS','TXT_KEY_IMPERIAL_DIPLO_PEACE_MADE_BY_HUMAN_GRACIOUS',1);
DELETE FROM Diplomacy_Responses WHERE LeaderType='LEADER_LAST_EMPEROR' AND ResponseType='RESPONSE_TRADE_ACCEPT_ACCEPTABLE';
INSERT INTO Diplomacy_Responses VALUES ('LEADER_LAST_EMPEROR','RESPONSE_TRADE_ACCEPT_ACCEPTABLE','TXT_KEY_IMPERIAL_DIPLO_TRADE_ACCEPT_ACCEPTABLE',1);
DELETE FROM Diplomacy_Responses WHERE LeaderType='LEADER_LAST_EMPEROR' AND ResponseType='RESPONSE_TRADE_REJECT_UNACCEPTABLE';
INSERT INTO Diplomacy_Responses VALUES ('LEADER_LAST_EMPEROR','RESPONSE_TRADE_REJECT_UNACCEPTABLE','TXT_KEY_IMPERIAL_DIPLO_TRADE_REJECT_UNACCEPTABLE',1);
