-- Original generated art; DDS files are imported into the VFS.
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ICON_ATLAS',256,'LastCityIcon256.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ICON_ATLAS',128,'LastCityIcon128.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ICON_ATLAS',80,'LastCityIcon80.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ICON_ATLAS',64,'LastCityIcon64.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ICON_ATLAS',48,'LastCityIcon48.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ICON_ATLAS',45,'LastCityIcon45.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ICON_ATLAS',32,'LastCityIcon32.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ICON_ATLAS',24,'LastCityIcon24.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ICON_ATLAS',16,'LastCityIcon16.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ALPHA_ATLAS',256,'LastCityAlpha256.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ALPHA_ATLAS',128,'LastCityAlpha128.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ALPHA_ATLAS',80,'LastCityAlpha80.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ALPHA_ATLAS',64,'LastCityAlpha64.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ALPHA_ATLAS',48,'LastCityAlpha48.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ALPHA_ATLAS',45,'LastCityAlpha45.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ALPHA_ATLAS',32,'LastCityAlpha32.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ALPHA_ATLAS',24,'LastCityAlpha24.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_ALPHA_ATLAS',16,'LastCityAlpha16.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_LEADER_ATLAS',256,'WardenPortrait256.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_LEADER_ATLAS',128,'WardenPortrait128.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_LEADER_ATLAS',64,'WardenPortrait64.dds',1,1);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_OBJECT_ATLAS',256,'LastCityObjects256.dds',4,3);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_OBJECT_ATLAS',128,'LastCityObjects128.dds',4,3);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_OBJECT_ATLAS',80,'LastCityObjects80.dds',4,3);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_OBJECT_ATLAS',64,'LastCityObjects64.dds',4,3);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_OBJECT_ATLAS',48,'LastCityObjects48.dds',4,3);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_OBJECT_ATLAS',45,'LastCityObjects45.dds',4,3);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_OBJECT_ATLAS',32,'LastCityObjects32.dds',4,3);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_OBJECT_ATLAS',24,'LastCityObjects24.dds',4,3);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_OBJECT_ATLAS',16,'LastCityObjects16.dds',4,3);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_PROMOTION_ATLAS',256,'LastCityPromotions256.dds',4,6);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_PROMOTION_ATLAS',128,'LastCityPromotions128.dds',4,6);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_PROMOTION_ATLAS',80,'LastCityPromotions80.dds',4,6);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_PROMOTION_ATLAS',64,'LastCityPromotions64.dds',4,6);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_PROMOTION_ATLAS',48,'LastCityPromotions48.dds',4,6);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_PROMOTION_ATLAS',45,'LastCityPromotions45.dds',4,6);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_PROMOTION_ATLAS',32,'LastCityPromotions32.dds',4,6);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_PROMOTION_ATLAS',24,'LastCityPromotions24.dds',4,6);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_PROMOTION_ATLAS',16,'LastCityPromotions16.dds',4,6);
INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES ('LC_UNIT_FLAG_ATLAS',32,'LastCityUnitFlag32.dds',1,1);
UPDATE Civilizations SET PortraitIndex=0,IconAtlas='LC_ICON_ATLAS',AlphaIconAtlas='LC_ALPHA_ATLAS',MapImage='LastLightMap.dds',DawnOfManImage='LastLight.dds' WHERE Type='CIVILIZATION_LAST_CITY';
UPDATE Leaders SET PortraitIndex=0,IconAtlas='LC_LEADER_ATLAS',ArtDefineTag='WardenLeaderScene.xml' WHERE Type='LEADER_LC_WARDEN';
UPDATE Units SET PortraitIndex=0,IconAtlas='LC_OBJECT_ATLAS',UnitFlagAtlas='LC_UNIT_FLAG_ATLAS',UnitFlagIconOffset=0 WHERE Type='UNIT_LC_LAST_WATCH';
UPDATE Buildings SET PortraitIndex=1,IconAtlas='LC_OBJECT_ATLAS' WHERE Type='BUILDING_LC_DISTRICT';
UPDATE Buildings SET PortraitIndex=2,IconAtlas='LC_OBJECT_ATLAS' WHERE Type='BUILDING_LC_BARRACKS';
UPDATE Buildings SET PortraitIndex=3,IconAtlas='LC_OBJECT_ATLAS' WHERE Type='BUILDING_LC_RESIDENTIAL';
UPDATE Buildings SET PortraitIndex=4,IconAtlas='LC_OBJECT_ATLAS' WHERE Type='BUILDING_LC_SHELTER';
UPDATE Buildings SET PortraitIndex=5,IconAtlas='LC_OBJECT_ATLAS' WHERE Type='BUILDING_LC_HOSPITAL';
UPDATE Buildings SET PortraitIndex=6,IconAtlas='LC_OBJECT_ATLAS' WHERE Type='BUILDING_LC_STORAGE';
UPDATE Buildings SET PortraitIndex=7,IconAtlas='LC_OBJECT_ATLAS' WHERE Type='BUILDING_LC_DEPOT';
UPDATE Buildings SET PortraitIndex=8,IconAtlas='LC_OBJECT_ATLAS' WHERE Type='BUILDING_LC_WATER';
UPDATE Buildings SET PortraitIndex=9,IconAtlas='LC_OBJECT_ATLAS' WHERE Type='BUILDING_LC_DAWN';
UPDATE UnitPromotions SET PortraitIndex=0,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_SANCTUARY';
UPDATE UnitPromotions SET PortraitIndex=1,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_NO_CONQUEST';
UPDATE UnitPromotions SET PortraitIndex=2,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_WATCH';
UPDATE UnitPromotions SET PortraitIndex=3,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_RESOLVE';
UPDATE UnitPromotions SET PortraitIndex=4,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_INVADER';
UPDATE UnitPromotions SET PortraitIndex=5,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_BOSS';
UPDATE UnitPromotions SET PortraitIndex=6,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_COMMAND';
UPDATE UnitPromotions SET PortraitIndex=7,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_PLAGUE';
UPDATE UnitPromotions SET PortraitIndex=8,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_ELITE';
UPDATE UnitPromotions SET PortraitIndex=9,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_VETERAN_1';
UPDATE UnitPromotions SET PortraitIndex=10,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_VETERAN_ACTIVE_1';
UPDATE UnitPromotions SET PortraitIndex=11,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_TRAINING_1';
UPDATE UnitPromotions SET PortraitIndex=12,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_VETERAN_2';
UPDATE UnitPromotions SET PortraitIndex=13,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_VETERAN_ACTIVE_2';
UPDATE UnitPromotions SET PortraitIndex=14,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_TRAINING_2';
UPDATE UnitPromotions SET PortraitIndex=15,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_VETERAN_3';
UPDATE UnitPromotions SET PortraitIndex=16,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_VETERAN_ACTIVE_3';
UPDATE UnitPromotions SET PortraitIndex=17,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_TRAINING_3';
UPDATE UnitPromotions SET PortraitIndex=18,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_VETERAN_4';
UPDATE UnitPromotions SET PortraitIndex=19,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_VETERAN_ACTIVE_4';
UPDATE UnitPromotions SET PortraitIndex=20,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_TRAINING_4';
UPDATE UnitPromotions SET PortraitIndex=21,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_VETERAN_5';
UPDATE UnitPromotions SET PortraitIndex=22,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_VETERAN_ACTIVE_5';
UPDATE UnitPromotions SET PortraitIndex=23,IconAtlas='LC_PROMOTION_ATLAS' WHERE Type='PROMOTION_LC_TRAINING_5';
