assert(loadstring(UISource))()
local K=MapModData.TheKingdoms
assert(not Controls.RealmLauncher.hidden and Controls.RealmPanel.hidden)
Controls.RealmStatus.click();assert(not Controls.RealmPanel.hidden and #Instances.RealmTabs==5)
Instances.RealmTabs[2].TabChoice.click();assert(#Instances.RealmList>=1 and #Instances.RealmActions>=2)
Instances.RealmActions[1].ActionChoice.click();assert(Controls.RealmDetailText.text:find('HOUSE'))
local before=Players[0].gold;local button=Instances.RealmActions[1].ActionChoice;assert(not button.disabled);button.click();assert(Players[0].gold<before)
Controls.RealmClose.click();assert(Controls.RealmPanel.hidden)
Events.SerialEventEnterCityScreen.Fire();assert(Controls.RealmLauncher.hidden and Controls.RealmPanel.hidden)
Events.SerialEventExitCityScreen.Fire();assert(not Controls.RealmLauncher.hidden)
Events.AILeaderMessage.Fire();assert(Controls.RealmLauncher.hidden);Events.LeavingLeaderViewMode.Fire();assert(not Controls.RealmLauncher.hidden)
Events.SerialEventGameMessagePopupShown.Fire({Type=99});assert(Controls.RealmLauncher.hidden)
Events.SerialEventGameMessagePopupProcessed.Fire(99);assert(not Controls.RealmLauncher.hidden)
createGuard(10);assert(not Controls.RealmPanel.hidden and #Instances.RealmActions==2)
-- Separate candidate callbacks must each appoint their displayed character.
local s=K.State(0);local expected=s.pending[10].candidates[2]
Instances.RealmActions[2].ActionChoice.click();assert(s.guards[expected] and not s.pending[10])
Controls.RealmClose.click();assert(Controls.RealmPanel.hidden)
Active=1;Events.GameplaySetActivePlayer.Fire();assert(Controls.RealmLauncher.hidden,'AI-only views must not show human controls')
Active=2;Events.GameplaySetActivePlayer.Fire();assert(Controls.RealmLauncher.hidden,'foreign civ must not show controls')
Active=0;Events.GameplaySetActivePlayer.Fire();Controls.RealmStatus.click();assert(not Controls.RealmPanel.hidden)
assert(Escape(KeyEvents.KeyDown,Keys.VK_ESCAPE) and Controls.RealmPanel.hidden)
-- Succession renders true neutrality, then updates backing through actual button callbacks.
K.BeginCivilWar(s);assert(s.war.supported==nil);K.Commit(0)
Controls.RealmStatus.click();Instances.RealmTabs[3].TabChoice.click()
local neutral=K.Text('PLAYER_SUPPORT_NEUTRAL',K.Text('NEUTRAL'))
assert(Controls.RealmDetailText.text:find(neutral,1,true) and #Instances.RealmActions==7)
Instances.RealmList[2].RowChoice.click()
assert(Controls.RealmDetailText.text:find(neutral,1,true),'selecting a faction row does not commit backing')
Instances.RealmActions[1].ActionChoice.click();assert(s.war.supported==2)
local backed=K.Text('PLAYER_SUPPORT',s.houses[s.war.factions[2].house].name)
assert(Controls.RealmDetailText.text:find(backed,1,true))
assert(Instances.RealmActions[7].ActionChoice.disabled,'Neutral shares the existing action cooldown')
Turn=s.war.actionNext;LuaEvents.KingdomsChanged.Fire(0)
assert(not Instances.RealmActions[7].ActionChoice.disabled)
Instances.RealmActions[7].ActionChoice.click()
assert(s.war.supported==nil and Controls.RealmDetailText.text:find(neutral,1,true))
assert(K.HistoryText(s.history[#s.history])==K.Text('WAR_NEUTRAL'))
-- Both nil and an invalid saved backing ID render safely. Fresh UI contexts preserve Neutral.
s.war.supported=999;LuaEvents.KingdomsChanged.Fire(0)
assert(Controls.RealmDetailText.text:find(neutral,1,true));s.war.supported=nil
K.Save(0);reload();K=MapModData.TheKingdoms;s=K.State(0)
assert(s.war and s.war.supported==nil);assert(loadstring(UISource))()
Controls.RealmStatus.click();Instances.RealmTabs[3].TabChoice.click()
assert(Controls.RealmDetailText.text:find(neutral,1,true),'neutral war rendering survives a fresh context')
