function saved(pid,k) return Saved['PSJ_V1_P'..pid..'_'..k] end
local c=newCity(P,0,0)
GameEvents.PlayerCityFounded.Fire(2,0,0)
local u=newUnit(P,17)
GameEvents.UnitCreated.Fire(2,17)
assert(u.script:find('%[OTHER:keep%]'),'foreign script data lost')
T=1;GameEvents.PlayerDoTurn.Fire(2)
assert(P.culture==5 and P.science==5 and saved(2,'MEM_FIRST_NIGHT')==0)
GameEvents.PlayerDoTurn.Fire(2)
assert(P.culture==5,'duplicate turn duplicated First Night')
c.buildings[300]=1
GameEvents.CityConstructed.Fire(2,1,300)
GameEvents.CityConstructed.Fire(2,1,300)
assert(P.culture==15 and saved(2,'HOME_ERA')==0)
GameEvents.UnitPrekill.Fire(4,9,1,0,0,true,2)
GameEvents.UnitPrekill.Fire(4,9,1,0,0,false,2)
assert(P.culture==25 and saved(2,'MEM_FIRST_DANGER')==0)
local mine=plot(1,0,2);mine.improvement=500
GameEvents.PlayerBuilt.Fire(2,20,1,0,1)
GameEvents.PlayerBuilt.Fire(2,20,1,0,1)
assert(P.science==15 and saved(2,'MEM_FIRST_MINE')==0)
mine.resource=600
GameEvents.PlayerBuilt.Fire(2,20,1,0,1)
assert(not saved(2,'MEM_FIRST_HARVEST'),'invalid improvement harvested resource')
mine.improvement=501;GameEvents.PlayerBuilt.Fire(2,20,1,0,2)
GameEvents.PlayerBuilt.Fire(2,20,1,0,2)
assert(c.food==5 and P.culture==30 and saved(2,'MEM_FIRST_HARVEST')==0)
Teams[2].met[0]=true;GameEvents.TeamMeet.Fire(2,0);GameEvents.TeamMeet.Fire(2,0)
assert(P.culture==40 and saved(2,'MEM_FIRST_FRIEND')==0)
u.x=10;plot(10,0,-1);GameEvents.UnitSetXY.Fire(2,17,10,0)
assert(P.culture==50 and P.science==25 and u.xp==15 and saved(2,'MEM_FIRST_JOURNEY')==0)
GameEvents.NaturalWonderDiscovered.Fire(2,1,12,0,true)
assert(P.culture==65 and P.science==35 and u.xp==15,'unattributed wonder XP')
GameEvents.NaturalWonderDiscovered.Fire(2,1,12,0,true,2,17)
GameEvents.NaturalWonderDiscovered.Fire(2,1,12,0,true,2,17)
assert(u.xp==25,'wonder XP duplicated')
GameEvents.GoodyHutReceivedBonus.Fire(2,17,1,10,0)
GameEvents.GoodyHutReceivedBonus.Fire(2,17,2,10,0)
assert(u.xp==30,'ruin XP duplicated')
Plots['10:0'].area=2;GameEvents.UnitSetXY.Fire(2,17,10,0)
Plots['10:0'].area=1;GameEvents.UnitSetXY.Fire(2,17,10,0)
Plots['10:0'].area=2;GameEvents.UnitSetXY.Fire(2,17,10,0)
assert(u.xp==40,'landmass XP farmed')
local second=newCity(P,3,0);GameEvents.PlayerCityFounded.Fire(2,3,0)
assert(P.culture==80 and saved(2,'MEM_BEYOND_HOME')==0)
for _,k in ipairs({'FIRST_SHELTER','FIRST_NIGHT','FIRST_DANGER','FIRST_MINE','FIRST_HARVEST',
    'FIRST_JOURNEY','FIRST_FRIEND','FIRST_WONDER','BEYOND_HOME'}) do assert(saved(2,'MEM_'..k)==0,k) end
local beforeC,beforeS=P.culture,P.science
P.era=1;GameEvents.TeamSetEra.Fire(2,1,false)
assert(P.culture-beforeC==37 and P.science-beforeS==37,'Classical recall plus Something New wrong')
assert(saved(2,'MEM_SOMETHING_NEW')==1)
local afterC,afterS=P.culture,P.science
GameEvents.TeamSetEra.Fire(2,1,true)
assert(P.culture==afterC and P.science==afterS,'duplicate era reward')
P.era=2;GameEvents.TeamSetEra.Fire(2,2,true)
assert(P.culture-afterC==57 and P.science-afterS==57,'memory ages wrong')
assert(c.buildings[301]==1 and c.buildings[302]==0 and c.buildings[303]==0,'Home tier stacking')
c.owner=0;GameEvents.CityCaptureComplete.Fire(2,true,0,0,0)
assert(c.buildings[301]==0,'captured Home retained bonuses')
c.owner=2;GameEvents.CityCaptureComplete.Fire(0,true,0,0,2)
assert(c.buildings[301]==1,'regained Home age lost')
P.capital=second;T=2;GameEvents.PlayerDoTurn.Fire(2)
assert(c.buildings[301]==1 and not second.buildings[301],'Home moved with Palace')
-- Rebuilding retains construction era, but a new foundation at this tile does not.
c.buildings[300]=0;T=3;GameEvents.PlayerDoTurn.Fire(2);assert(c.buildings[301]==0)
c.buildings[300]=1;GameEvents.CityConstructed.Fire(2,1,300);assert(c.buildings[301]==1)
-- A Survivor born in Medieval never qualifies for the Ancient veteran award.
local young=newUnit(P,18);GameEvents.UnitCreated.Fire(2,18)
local upgraded=newUnit(P,19,201)
GameEvents.UnitUpgraded.Fire(2,17,19)
GameEvents.UnitConverted.Fire(2,2,17,19,true)
assert(upgraded.script:find('%[PSJ1:') and upgraded.script:find('%[OTHER:keep%]'))
P.units={upgraded,young};u=upgraded;u.x=10
-- Ten distinct owner turns outside, then return; upgrades retain the lifetime.
for t=4,13 do T=t;GameEvents.PlayerDoTurn.Fire(2) end
local culture=P.culture
u.x=3;GameEvents.PlayerDoTurn.Fire(2);assert(P.culture==culture,'same-turn return counted twice')
T=14;GameEvents.PlayerDoTurn.Fire(2);assert(P.culture==culture+15,'Home Again absent')
T=15;GameEvents.PlayerDoTurn.Fire(2);assert(P.culture==culture+15,'Home Again repeated')
P.era=5;GameEvents.TeamSetEra.Fire(2,5,true)
assert(u.promotions[401] and not young.promotions[401],'Ancient qualification lost/faked')
assert(c.buildings[302]==1 and c.buildings[301]==0 and c.buildings[303]==0)
P.era=7;local notes=#P.notifications;GameEvents.TeamSetEra.Fire(2,7,true)
assert(#P.notifications==notes+2 and saved(2,'NARRATIVE_7')==1,'Information finale/consolidation')
assert(c.buildings[303]==1 and c.buildings[301]==0 and c.buildings[302]==0)
-- Transfer to a different Paul does not transfer personal history or rewards.
local captive=newUnit(AI,22,201)
GameEvents.UnitConverted.Fire(2,1,19,22,false)
assert(not captive.promotions[400] and not captive.promotions[401] and not captive.script:find('%[PSJ1:'),'capture leaked identity')
local aiCity=newCity(AI,20,0);GameEvents.PlayerCityFounded.Fire(1,20,0)
T=16;GameEvents.PlayerDoTurn.Fire(1)
assert(AI.culture==15 and AI.science==15 and #AI.notifications==0,'AI First Night/Journey rewards or privacy failed')
assert(Foreign.culture==0 and Foreign.science==0,'foreign civ got rewards')
-- Nil unit, foreign owner and invalid build inputs are harmless.
GameEvents.UnitSetXY.Fire(99,99)
GameEvents.PlayerBuilt.Fire(2,20,0,0,999)
GameEvents.UnitConverted.Fire(2,99,123,456,true)
ReloadC,ReloadS=P.culture,P.science
ReloadNotes=#P.notifications
print('PASS PSJ runtime: all ten Memories, aging, Home capture/Palace, XP, upgrades, return, AI and finale')
