-- The Filthy Realm. Civilization V: Brave New World + Community Patch.
-- Scalar game objects are cloned so columns added by the Community Patch are retained.

UPDATE CustomModOptions SET Value = 1 WHERE Name IN
('EVENTS_BATTLES', 'EVENTS_CITY', 'EVENTS_DIPLO_MODIFIERS', 'EVENTS_PLAYER_TURN',
 'EVENTS_MINORS_INTERACTION', 'EVENTS_RESOLUTIONS', 'EVENTS_TILE_IMPROVEMENTS', 'EVENTS_TRADE_ROUTES',
 'EVENTS_UNIT_ACTIONS', 'EVENTS_UNIT_CONVERTS', 'EVENTS_UNIT_CREATED', 'EVENTS_UNIT_PREKILL',
 'EVENTS_WAR_AND_PEACE');

INSERT INTO Colors(Type,Red,Green,Blue,Alpha) VALUES
('COLOR_FILTHY_PRIMARY',0.94,0.16,0.43,1),
('COLOR_FILTHY_SECONDARY',0.075,0.055,0.070,1);
INSERT INTO PlayerColors(Type,PrimaryColor,SecondaryColor,TextColor) VALUES
('PLAYERCOLOR_FILTHY','COLOR_FILTHY_PRIMARY','COLOR_FILTHY_SECONDARY','COLOR_PLAYER_WHITE_TEXT');

INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES
('FILTHY_ICON_ATLAS',256,'FilthyIcon256.dds',2,1),
('FILTHY_ICON_ATLAS',128,'FilthyIcon128.dds',2,1),
('FILTHY_ICON_ATLAS',80,'FilthyIcon80.dds',2,1),
('FILTHY_ICON_ATLAS',64,'FilthyIcon64.dds',2,1),
('FILTHY_ICON_ATLAS',48,'FilthyIcon48.dds',2,1),
('FILTHY_ICON_ATLAS',45,'FilthyIcon45.dds',2,1),
('FILTHY_ICON_ATLAS',32,'FilthyIcon32.dds',2,1),
('FILTHY_ICON_ATLAS',24,'FilthyIcon24.dds',2,1),
('FILTHY_ICON_ATLAS',16,'FilthyIcon16.dds',2,1),
('FILTHY_ALPHA_ATLAS',256,'FilthyAlpha256.dds',1,1),
('FILTHY_ALPHA_ATLAS',128,'FilthyAlpha128.dds',1,1),
('FILTHY_ALPHA_ATLAS',80,'FilthyAlpha80.dds',1,1),
('FILTHY_ALPHA_ATLAS',64,'FilthyAlpha64.dds',1,1),
('FILTHY_ALPHA_ATLAS',48,'FilthyAlpha48.dds',1,1),
('FILTHY_ALPHA_ATLAS',45,'FilthyAlpha45.dds',1,1),
('FILTHY_ALPHA_ATLAS',32,'FilthyAlpha32.dds',1,1),
('FILTHY_ALPHA_ATLAS',24,'FilthyAlpha24.dds',1,1),
('FILTHY_ALPHA_ATLAS',16,'FilthyAlpha16.dds',1,1),
('FILTHY_OBJECT_ATLAS',256,'FilthyObjects256.dds',9,1),
('FILTHY_OBJECT_ATLAS',128,'FilthyObjects128.dds',9,1),
('FILTHY_OBJECT_ATLAS',80,'FilthyObjects80.dds',9,1),
('FILTHY_OBJECT_ATLAS',64,'FilthyObjects64.dds',9,1),
('FILTHY_OBJECT_ATLAS',45,'FilthyObjects45.dds',9,1),
('FILTHY_OBJECT_ATLAS',32,'FilthyObjects32.dds',9,1),
('FILTHY_OBJECT_ATLAS',16,'FilthyObjects16.dds',9,1),
('FILTHY_UNIT_FLAG_ATLAS',32,'FilthyUnitFlag32.dds',1,1);

INSERT INTO Traits(Type,Description,ShortDescription) VALUES
('TRAIT_FILTHY_WELCOME','TXT_KEY_TRAIT_FILTHY_HELP','TXT_KEY_TRAIT_FILTHY_SHORT');

CREATE TEMP TABLE FilthyLeaderClone AS SELECT * FROM Leaders WHERE Type='LEADER_WASHINGTON';
UPDATE FilthyLeaderClone SET ID=NULL,Type='LEADER_FILTHY_FRANK',
 Description='TXT_KEY_LEADER_FILTHY_FRANK',Civilopedia='TXT_KEY_LEADER_FILTHY_FRANK_PEDIA',
 CivilopediaTag='TXT_KEY_CIVILOPEDIA_LEADERS_FILTHY_FRANK',ArtDefineTag='FilthyLeaderScene.xml',
 PortraitIndex=1,IconAtlas='FILTHY_ICON_ATLAS',PackageID=NULL,
 VictoryCompetitiveness=8,WonderCompetitiveness=2,MinorCivCompetitiveness=6,
 Boldness=9,DiploBalance=3,WarmongerHate=2,WorkAgainstWillingness=9,WorkWithWillingness=5,
 DenounceWillingness=8,DoFWillingness=4,Loyalty=4,Neediness=4,Forgiveness=2,Chattiness=8,Meanness=8;
INSERT INTO Leaders SELECT * FROM FilthyLeaderClone;
DROP TABLE FilthyLeaderClone;
INSERT INTO Leader_Traits VALUES ('LEADER_FILTHY_FRANK','TRAIT_FILTHY_WELCOME');

CREATE TEMP TABLE FilthyCivClone AS SELECT * FROM Civilizations WHERE Type='CIVILIZATION_AMERICA';
UPDATE FilthyCivClone SET ID=NULL,Type='CIVILIZATION_FILTHY_REALM',
 Description='TXT_KEY_CIV_FILTHY_DESC',ShortDescription='TXT_KEY_CIV_FILTHY_SHORT_DESC',
 Adjective='TXT_KEY_CIV_FILTHY_ADJECTIVE',Civilopedia='TXT_KEY_CIV_FILTHY_PEDIA',
 CivilopediaTag='TXT_KEY_CIV5_FILTHY',Strategy='TXT_KEY_CIV_FILTHY_STRATEGY',
 DefaultPlayerColor='PLAYERCOLOR_FILTHY',Playable=1,AIPlayable=1,PackageID=NULL,
 PortraitIndex=0,IconAtlas='FILTHY_ICON_ATLAS',AlphaIconAtlas='FILTHY_ALPHA_ATLAS',
 MapImage='FilthyMap.dds',DawnOfManImage='FilthyDawn.dds',
 DawnOfManQuote='TXT_KEY_FILTHY_DAWN_OF_MAN',DawnOfManAudio='',SoundtrackTag='JAPAN',
 ArtDefineTag='ART_DEF_CIVILIZATION_JAPAN',ArtStyleType='ARTSTYLE_ASIAN',
 ArtStyleSuffix='_ASIA',ArtStylePrefix='ASIAN ';
INSERT INTO Civilizations SELECT * FROM FilthyCivClone;
DROP TABLE FilthyCivClone;

INSERT INTO Civilization_Leaders VALUES ('CIVILIZATION_FILTHY_REALM','LEADER_FILTHY_FRANK');
INSERT INTO Civilization_FreeBuildingClasses SELECT 'CIVILIZATION_FILTHY_REALM',BuildingClassType
 FROM Civilization_FreeBuildingClasses WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_FreeTechs SELECT 'CIVILIZATION_FILTHY_REALM',TechType
 FROM Civilization_FreeTechs WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_FreeUnits(CivilizationType,UnitClassType,UnitAIType,Count)
 SELECT 'CIVILIZATION_FILTHY_REALM',UnitClassType,UnitAIType,Count
 FROM Civilization_FreeUnits WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_Start_Region_Priority VALUES ('CIVILIZATION_FILTHY_REALM','REGION_GRASS');

CREATE TEMP TABLE FilthyUnitClone AS SELECT * FROM Units WHERE Type='UNIT_GREAT_WAR_INFANTRY';
UPDATE FilthyUnitClone SET ID=NULL,Type='UNIT_FILTHY_PEACE_LORD',
 Description='TXT_KEY_UNIT_FILTHY_PEACE_LORD',Civilopedia='TXT_KEY_UNIT_FILTHY_PEACE_LORD_PEDIA',
 Strategy='TXT_KEY_UNIT_FILTHY_PEACE_LORD_STRATEGY',Help='TXT_KEY_UNIT_FILTHY_PEACE_LORD_HELP',
 Combat=52,PortraitIndex=0,IconAtlas='FILTHY_OBJECT_ATLAS',
 UnitFlagIconOffset=0,UnitFlagAtlas='FILTHY_UNIT_FLAG_ATLAS';
INSERT INTO Units SELECT * FROM FilthyUnitClone;
DROP TABLE FilthyUnitClone;
INSERT INTO Civilization_UnitClassOverrides VALUES
('CIVILIZATION_FILTHY_REALM','UNITCLASS_GREAT_WAR_INFANTRY','UNIT_FILTHY_PEACE_LORD');

INSERT INTO UnitClasses(Type,Description,DefaultUnit) VALUES
('UNITCLASS_FILTHY_SALAMANDER_MAN','TXT_KEY_UNIT_FILTHY_SALAMANDER_MAN','UNIT_FILTHY_SALAMANDER_MAN');
CREATE TEMP TABLE FilthySalamanderClone AS SELECT * FROM Units WHERE Type='UNIT_SCOUT';
UPDATE FilthySalamanderClone SET ID=NULL,Type='UNIT_FILTHY_SALAMANDER_MAN',
 Class='UNITCLASS_FILTHY_SALAMANDER_MAN',Description='TXT_KEY_UNIT_FILTHY_SALAMANDER_MAN',
 Civilopedia='TXT_KEY_UNIT_FILTHY_SALAMANDER_MAN_PEDIA',Strategy='TXT_KEY_UNIT_FILTHY_SALAMANDER_MAN_STRATEGY',
 Help='TXT_KEY_UNIT_FILTHY_SALAMANDER_MAN_HELP',Combat=0,RangedCombat=0,Cost=-1,FaithCost=-1,
 PrereqTech=NULL,Moves=5,ShowInPedia=0,PortraitIndex=2,IconAtlas='FILTHY_OBJECT_ATLAS',
 UnitFlagIconOffset=0,UnitFlagAtlas='FILTHY_UNIT_FLAG_ATLAS';
INSERT INTO Units SELECT * FROM FilthySalamanderClone;
DROP TABLE FilthySalamanderClone;

CREATE TEMP TABLE FilthyBuildingClone AS SELECT * FROM Buildings WHERE Type='BUILDING_BROADCAST_TOWER';
UPDATE FilthyBuildingClone SET ID=NULL,Type='BUILDING_FILTHY_KITCHEN',
 Description='TXT_KEY_BUILDING_FILTHY_KITCHEN',Civilopedia='TXT_KEY_BUILDING_FILTHY_KITCHEN_PEDIA',
 Strategy='TXT_KEY_BUILDING_FILTHY_KITCHEN_STRATEGY',Help='TXT_KEY_BUILDING_FILTHY_KITCHEN_HELP',
 PortraitIndex=1,IconAtlas='FILTHY_OBJECT_ATLAS';
INSERT INTO Buildings SELECT * FROM FilthyBuildingClone;
DROP TABLE FilthyBuildingClone;
INSERT INTO Civilization_BuildingClassOverrides VALUES
('CIVILIZATION_FILTHY_REALM','BUILDINGCLASS_BROADCAST_TOWER','BUILDING_FILTHY_KITCHEN');

INSERT INTO UnitPromotions
(Type,Description,Help,CannotBeChosen,LostWithUpgrade,PortraitIndex,IconAtlas,PediaType,PediaEntry) VALUES
('PROMOTION_FILTHY_KNOW_YOUR_PLACE','TXT_KEY_PROMOTION_FILTHY_KNOW_YOUR_PLACE','TXT_KEY_PROMOTION_FILTHY_KNOW_YOUR_PLACE_HELP',1,0,0,'FILTHY_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_FILTHY_KNOW_YOUR_PLACE'),
('PROMOTION_FILTHY_CITY_STRENGTH_10','TXT_KEY_PROMOTION_FILTHY_CITY_STRENGTH_10','TXT_KEY_PROMOTION_FILTHY_CITY_STRENGTH_10_HELP',1,1,4,'FILTHY_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_FILTHY_CITY_STRENGTH_10'),
('PROMOTION_FILTHY_CITY_STRENGTH_15','TXT_KEY_PROMOTION_FILTHY_CITY_STRENGTH_15','TXT_KEY_PROMOTION_FILTHY_CITY_STRENGTH_15_HELP',1,1,4,'FILTHY_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_FILTHY_CITY_STRENGTH_15'),
('PROMOTION_FILTHY_HUMILIATED','TXT_KEY_PROMOTION_FILTHY_HUMILIATED','TXT_KEY_PROMOTION_FILTHY_HUMILIATED_HELP',1,1,0,'FILTHY_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_FILTHY_HUMILIATED'),
('PROMOTION_FILTHY_SALAMANDER_ENEMY','TXT_KEY_PROMOTION_FILTHY_SALAMANDER_ENEMY','TXT_KEY_PROMOTION_FILTHY_SALAMANDER_ENEMY_HELP',1,1,2,'FILTHY_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_FILTHY_SALAMANDER_ENEMY'),
('PROMOTION_FILTHY_SALAMANDER_FRIEND','TXT_KEY_PROMOTION_FILTHY_SALAMANDER_FRIEND','TXT_KEY_PROMOTION_FILTHY_SALAMANDER_FRIEND_HELP',1,1,2,'FILTHY_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_FILTHY_SALAMANDER_FRIEND'),
('PROMOTION_FILTHY_DISTORTION_ZOC','TXT_KEY_PROMOTION_FILTHY_DISTORTION_ZOC','TXT_KEY_PROMOTION_FILTHY_DISTORTION_ZOC_HELP',1,1,4,'FILTHY_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_FILTHY_DISTORTION_ZOC'),
('PROMOTION_FILTHY_STOPPED','TXT_KEY_PROMOTION_FILTHY_STOPPED','TXT_KEY_PROMOTION_FILTHY_STOPPED_HELP',1,1,6,'FILTHY_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_FILTHY_STOPPED');

UPDATE UnitPromotions SET CombatPercent=10 WHERE Type='PROMOTION_FILTHY_CITY_STRENGTH_10';
UPDATE UnitPromotions SET CombatPercent=15 WHERE Type='PROMOTION_FILTHY_CITY_STRENGTH_15';
UPDATE UnitPromotions SET CombatPercent=-10 WHERE Type IN
('PROMOTION_FILTHY_HUMILIATED','PROMOTION_FILTHY_SALAMANDER_ENEMY');
UPDATE UnitPromotions SET MovesChange=-1 WHERE Type='PROMOTION_FILTHY_SALAMANDER_ENEMY';
UPDATE UnitPromotions SET MovesChange=1 WHERE Type='PROMOTION_FILTHY_SALAMANDER_FRIEND';
UPDATE UnitPromotions SET IgnoreZOC=1 WHERE Type='PROMOTION_FILTHY_DISTORTION_ZOC';
UPDATE UnitPromotions SET OnlyDefensive=1,RangeChange=-100 WHERE Type='PROMOTION_FILTHY_STOPPED';

INSERT INTO Unit_FreePromotions VALUES
('UNIT_FILTHY_PEACE_LORD','PROMOTION_FILTHY_KNOW_YOUR_PLACE');
