-- Filth dummy buildings, unique-object bonuses, AI and civilization lists.

INSERT INTO BuildingClasses(Type,Description,DefaultBuilding) VALUES
('BUILDINGCLASS_FILTHY_LEVEL_1','TXT_KEY_BUILDING_FILTHY_LEVEL_1','BUILDING_FILTHY_LEVEL_1'),
('BUILDINGCLASS_FILTHY_LEVEL_2','TXT_KEY_BUILDING_FILTHY_LEVEL_2','BUILDING_FILTHY_LEVEL_2'),
('BUILDINGCLASS_FILTHY_LEVEL_3','TXT_KEY_BUILDING_FILTHY_LEVEL_3','BUILDING_FILTHY_LEVEL_3'),
('BUILDINGCLASS_FILTHY_LEVEL_4','TXT_KEY_BUILDING_FILTHY_LEVEL_4','BUILDING_FILTHY_LEVEL_4'),
('BUILDINGCLASS_FILTHY_LEVEL_5','TXT_KEY_BUILDING_FILTHY_LEVEL_5','BUILDING_FILTHY_LEVEL_5'),
('BUILDINGCLASS_FILTHY_DISTORTED_1','TXT_KEY_BUILDING_FILTHY_DISTORTED_1','BUILDING_FILTHY_DISTORTED_1'),
('BUILDINGCLASS_FILTHY_DISTORTED_2','TXT_KEY_BUILDING_FILTHY_DISTORTED_2','BUILDING_FILTHY_DISTORTED_2'),
('BUILDINGCLASS_FILTHY_DISTORTED_3','TXT_KEY_BUILDING_FILTHY_DISTORTED_3','BUILDING_FILTHY_DISTORTED_3'),
('BUILDINGCLASS_FILTHY_DISTORTED_4','TXT_KEY_BUILDING_FILTHY_DISTORTED_4','BUILDING_FILTHY_DISTORTED_4'),
('BUILDINGCLASS_FILTHY_DISTORTED_5','TXT_KEY_BUILDING_FILTHY_DISTORTED_5','BUILDING_FILTHY_DISTORTED_5');

INSERT INTO Buildings
(Type,BuildingClass,Cost,FaithCost,PrereqTech,Description,Civilopedia,Strategy,Help,
 ArtDefineTag,MinAreaSize,NeverCapture,NukeImmune,ConquestProb,ShowInPedia,PortraitIndex,IconAtlas) VALUES
('BUILDING_FILTHY_LEVEL_1','BUILDINGCLASS_FILTHY_LEVEL_1',-1,-1,NULL,'TXT_KEY_BUILDING_FILTHY_LEVEL_1','TXT_KEY_BUILDING_FILTHY_LEVEL_PEDIA','','TXT_KEY_BUILDING_FILTHY_LEVEL_1_HELP','',-1,1,1,0,0,3,'FILTHY_OBJECT_ATLAS'),
('BUILDING_FILTHY_LEVEL_2','BUILDINGCLASS_FILTHY_LEVEL_2',-1,-1,NULL,'TXT_KEY_BUILDING_FILTHY_LEVEL_2','TXT_KEY_BUILDING_FILTHY_LEVEL_PEDIA','','TXT_KEY_BUILDING_FILTHY_LEVEL_2_HELP','',-1,1,1,0,0,3,'FILTHY_OBJECT_ATLAS'),
('BUILDING_FILTHY_LEVEL_3','BUILDINGCLASS_FILTHY_LEVEL_3',-1,-1,NULL,'TXT_KEY_BUILDING_FILTHY_LEVEL_3','TXT_KEY_BUILDING_FILTHY_LEVEL_PEDIA','','TXT_KEY_BUILDING_FILTHY_LEVEL_3_HELP','',-1,1,1,0,0,3,'FILTHY_OBJECT_ATLAS'),
('BUILDING_FILTHY_LEVEL_4','BUILDINGCLASS_FILTHY_LEVEL_4',-1,-1,NULL,'TXT_KEY_BUILDING_FILTHY_LEVEL_4','TXT_KEY_BUILDING_FILTHY_LEVEL_PEDIA','','TXT_KEY_BUILDING_FILTHY_LEVEL_4_HELP','',-1,1,1,0,0,3,'FILTHY_OBJECT_ATLAS'),
('BUILDING_FILTHY_LEVEL_5','BUILDINGCLASS_FILTHY_LEVEL_5',-1,-1,NULL,'TXT_KEY_BUILDING_FILTHY_LEVEL_5','TXT_KEY_BUILDING_FILTHY_LEVEL_PEDIA','','TXT_KEY_BUILDING_FILTHY_LEVEL_5_HELP','',-1,1,1,0,0,3,'FILTHY_OBJECT_ATLAS'),
('BUILDING_FILTHY_DISTORTED_1','BUILDINGCLASS_FILTHY_DISTORTED_1',-1,-1,NULL,'TXT_KEY_BUILDING_FILTHY_DISTORTED_1','TXT_KEY_BUILDING_FILTHY_LEVEL_PEDIA','','TXT_KEY_BUILDING_FILTHY_DISTORTED_HELP','',-1,1,1,0,0,4,'FILTHY_OBJECT_ATLAS'),
('BUILDING_FILTHY_DISTORTED_2','BUILDINGCLASS_FILTHY_DISTORTED_2',-1,-1,NULL,'TXT_KEY_BUILDING_FILTHY_DISTORTED_2','TXT_KEY_BUILDING_FILTHY_LEVEL_PEDIA','','TXT_KEY_BUILDING_FILTHY_DISTORTED_HELP','',-1,1,1,0,0,4,'FILTHY_OBJECT_ATLAS'),
('BUILDING_FILTHY_DISTORTED_3','BUILDINGCLASS_FILTHY_DISTORTED_3',-1,-1,NULL,'TXT_KEY_BUILDING_FILTHY_DISTORTED_3','TXT_KEY_BUILDING_FILTHY_LEVEL_PEDIA','','TXT_KEY_BUILDING_FILTHY_DISTORTED_HELP','',-1,1,1,0,0,4,'FILTHY_OBJECT_ATLAS'),
('BUILDING_FILTHY_DISTORTED_4','BUILDINGCLASS_FILTHY_DISTORTED_4',-1,-1,NULL,'TXT_KEY_BUILDING_FILTHY_DISTORTED_4','TXT_KEY_BUILDING_FILTHY_LEVEL_PEDIA','','TXT_KEY_BUILDING_FILTHY_DISTORTED_HELP','',-1,1,1,0,0,4,'FILTHY_OBJECT_ATLAS'),
('BUILDING_FILTHY_DISTORTED_5','BUILDINGCLASS_FILTHY_DISTORTED_5',-1,-1,NULL,'TXT_KEY_BUILDING_FILTHY_DISTORTED_5','TXT_KEY_BUILDING_FILTHY_LEVEL_PEDIA','','TXT_KEY_BUILDING_FILTHY_DISTORTED_HELP','',-1,1,1,0,0,4,'FILTHY_OBJECT_ATLAS');

INSERT INTO Building_YieldModifiers(BuildingType,YieldType,Yield) VALUES
('BUILDING_FILTHY_LEVEL_1','YIELD_CULTURE',-2),
('BUILDING_FILTHY_LEVEL_2','YIELD_CULTURE',-3),('BUILDING_FILTHY_LEVEL_2','YIELD_GOLD',-3),
('BUILDING_FILTHY_LEVEL_3','YIELD_CULTURE',-5),('BUILDING_FILTHY_LEVEL_3','YIELD_GOLD',-5),('BUILDING_FILTHY_LEVEL_3','YIELD_PRODUCTION',-5),
('BUILDING_FILTHY_LEVEL_4','YIELD_CULTURE',-7),('BUILDING_FILTHY_LEVEL_4','YIELD_GOLD',-7),('BUILDING_FILTHY_LEVEL_4','YIELD_PRODUCTION',-7),
('BUILDING_FILTHY_LEVEL_5','YIELD_CULTURE',-10),('BUILDING_FILTHY_LEVEL_5','YIELD_GOLD',-10),('BUILDING_FILTHY_LEVEL_5','YIELD_PRODUCTION',-10),
('BUILDING_FILTHY_DISTORTED_1','YIELD_CULTURE',-3),
('BUILDING_FILTHY_DISTORTED_2','YIELD_CULTURE',-5),('BUILDING_FILTHY_DISTORTED_2','YIELD_GOLD',-5),
('BUILDING_FILTHY_DISTORTED_3','YIELD_CULTURE',-8),('BUILDING_FILTHY_DISTORTED_3','YIELD_GOLD',-8),('BUILDING_FILTHY_DISTORTED_3','YIELD_PRODUCTION',-8),
('BUILDING_FILTHY_DISTORTED_4','YIELD_CULTURE',-11),('BUILDING_FILTHY_DISTORTED_4','YIELD_GOLD',-11),('BUILDING_FILTHY_DISTORTED_4','YIELD_PRODUCTION',-11),
('BUILDING_FILTHY_DISTORTED_5','YIELD_CULTURE',-15),('BUILDING_FILTHY_DISTORTED_5','YIELD_GOLD',-15),('BUILDING_FILTHY_DISTORTED_5','YIELD_PRODUCTION',-15);
UPDATE Buildings SET Happiness=-1 WHERE Type IN ('BUILDING_FILTHY_LEVEL_5','BUILDING_FILTHY_DISTORTED_5');

INSERT INTO Building_YieldChanges(BuildingType,YieldType,Yield)
 SELECT 'BUILDING_FILTHY_KITCHEN','YIELD_TOURISM',2
 WHERE NOT EXISTS(SELECT 1 FROM Building_YieldChanges
  WHERE BuildingType='BUILDING_FILTHY_KITCHEN' AND YieldType='YIELD_TOURISM');
INSERT INTO Building_Flavors(BuildingType,FlavorType,Flavor) VALUES
('BUILDING_FILTHY_KITCHEN','FLAVOR_CULTURE',30),
('BUILDING_FILTHY_KITCHEN','FLAVOR_GREAT_PEOPLE',20),
('BUILDING_FILTHY_KITCHEN','FLAVOR_OFFENSE',12);

INSERT INTO Leader_Flavors(LeaderType,FlavorType,Flavor)
SELECT 'LEADER_FILTHY_FRANK',Type,CASE Type
 WHEN 'FLAVOR_CULTURE' THEN 10 WHEN 'FLAVOR_OFFENSE' THEN 9
 WHEN 'FLAVOR_MILITARY_TRAINING' THEN 8 WHEN 'FLAVOR_DIPLOMACY' THEN 8
 WHEN 'FLAVOR_GOLD' THEN 7 WHEN 'FLAVOR_ESPIONAGE' THEN 9
 WHEN 'FLAVOR_I_TRADE_ORIGIN' THEN 10 WHEN 'FLAVOR_I_TRADE_DESTINATION' THEN 7
 WHEN 'FLAVOR_PILLAGE' THEN 10 WHEN 'FLAVOR_EXPANSION' THEN 5
 WHEN 'FLAVOR_SCIENCE' THEN 5 WHEN 'FLAVOR_WONDER' THEN 2
 WHEN 'FLAVOR_DEFENSE' THEN 3 ELSE 5 END FROM Flavors;
INSERT INTO Leader_MajorCivApproachBiases(LeaderType,MajorCivApproachType,Bias)
SELECT 'LEADER_FILTHY_FRANK',MajorCivApproachType,CASE MajorCivApproachType
 WHEN 'MAJOR_CIV_APPROACH_WAR' THEN 8 WHEN 'MAJOR_CIV_APPROACH_HOSTILE' THEN 8
 WHEN 'MAJOR_CIV_APPROACH_DECEPTIVE' THEN 7 WHEN 'MAJOR_CIV_APPROACH_GUARDED' THEN 3
 WHEN 'MAJOR_CIV_APPROACH_AFRAID' THEN 1 WHEN 'MAJOR_CIV_APPROACH_FRIENDLY' THEN 5
 ELSE 6 END FROM Leader_MajorCivApproachBiases WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Leader_MinorCivApproachBiases(LeaderType,MinorCivApproachType,Bias)
SELECT 'LEADER_FILTHY_FRANK',MinorCivApproachType,Bias
FROM Leader_MinorCivApproachBiases WHERE LeaderType='LEADER_WASHINGTON';

INSERT INTO Diplomacy_Responses(LeaderType,ResponseType,Response,Bias)
SELECT 'LEADER_FILTHY_FRANK',ResponseType,Response,Bias
FROM Diplomacy_Responses WHERE LeaderType='LEADER_WASHINGTON';

INSERT INTO Civilization_CityNames(CivilizationType,CityName) VALUES
('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_1'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_2'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_3'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_4'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_5'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_6'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_7'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_8'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_9'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_10'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_11'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_12'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_13'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_14'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_15'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_16'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_17'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_18'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_19'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_20'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_21'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_22'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_23'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_CITY_FILTHY_24');
INSERT INTO Civilization_SpyNames(CivilizationType,SpyName) VALUES
('CIVILIZATION_FILTHY_REALM','TXT_KEY_SPY_FILTHY_1'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_SPY_FILTHY_2'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_SPY_FILTHY_3'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_SPY_FILTHY_4'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_SPY_FILTHY_5'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_SPY_FILTHY_6'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_SPY_FILTHY_7'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_SPY_FILTHY_8'),
('CIVILIZATION_FILTHY_REALM','TXT_KEY_SPY_FILTHY_9'),('CIVILIZATION_FILTHY_REALM','TXT_KEY_SPY_FILTHY_10');
