-- English localization for The Filthy Realm.
INSERT INTO Language_en_US(Tag,Text) VALUES
('TXT_KEY_CIV_FILTHY_DESC','The Filthy Realm'),
('TXT_KEY_CIV_FILTHY_SHORT_DESC','The Filthy Realm'),
('TXT_KEY_CIV_FILTHY_ADJECTIVE','Filthy'),
('TXT_KEY_CIV_FILTHY_PEDIA','The Filthy Realm'),
('TXT_KEY_CIV_FILTHY_STRATEGY','[COLOR_POSITIVE_TEXT]The Filthy Realm[ENDCOLOR] is a Culture/Domination civilization that contaminates foreign Cities through Trade Routes, Tourism, pillaging, and fighting near enemy population centres. Disruption earns Filthy Points for four active Realm abilities. Keep contact with rivals, then attack their most contaminated Cities with Peace Lords.'),
('TXT_KEY_CIV5_FILTHY','The Filthy Realm'),
('TXT_KEY_CIV5_FILTHY_TITLE','The Filthy Realm'),
('TXT_KEY_CIV5_FILTHY_HEADING_1','A Higher Form of Civilization'),
('TXT_KEY_CIV5_FILTHY_TEXT_1','The Realm does not isolate itself from the world. It trades with it, offends it, contaminates it, and turns every public reaction into fuel for stranger ambitions.'),
('TXT_KEY_CIV5_FILTHY_HEADING_2','Welcome to the Rice Fields'),
('TXT_KEY_CIV5_FILTHY_TEXT_2','Foreign Cities exposed to Filthy trade, cultural influence, pillaging, and violence accumulate up to five levels of Filth. Neglect allows contamination to decay, but sustained contact makes an economy increasingly vulnerable.'),
('TXT_KEY_CIV5_FILTHY_HEADING_3','The Filthy Realm'),
('TXT_KEY_CIV5_FILTHY_TEXT_3','Filthy Points are a persistent resource spent through an active command panel. The Realm can summon Salamander Man, distort a contaminated City, steal a chosen yield, or simply force nearby enemies to stop.'),

('TXT_KEY_LEADER_FILTHY_FRANK','Filthy Frank'),
('TXT_KEY_LEADER_FILTHY_FRANK_PEDIA','Filthy Frank leads a deliberately chaotic realm whose cultural reach and military provocation turn foreign attention into power. This fictional strategy-game portrayal translates the supplied design into a Culture/Domination ruleset.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_FILTHY_FRANK','Filthy Frank'),
('TXT_KEY_CIVILOPEDIA_LEADERS_FILTHY_FRANK_NAME','Filthy Frank'),
('TXT_KEY_CIVILOPEDIA_LEADERS_FILTHY_FRANK_SUBTITLE','Lord of the Rice Fields'),
('TXT_KEY_CIVILOPEDIA_LEADERS_FILTHY_FRANK_LIVED','The Contemporary Era'),
('TXT_KEY_CIVILOPEDIA_LEADERS_FILTHY_FRANK_TITLES_1','Leader of the Filthy Realm'),
('TXT_KEY_CIVILOPEDIA_LEADERS_FILTHY_FRANK_HEADING_1','Negative Attention Is Still Attention'),
('TXT_KEY_CIVILOPEDIA_LEADERS_FILTHY_FRANK_TEXT_1','Frank prospers by remaining entangled with everyone else. Trade Routes and cultural influence spread Filth peacefully; pillaging, battles, denunciations, and declarations of war generate the Filthy Points used by his active abilities.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_FILTHY_FRANK_HEADING_2','Temperament'),
('TXT_KEY_CIVILOPEDIA_LEADERS_FILTHY_FRANK_TEXT_2','Frank favours Culture, offense, pillaging, international Trade Routes, espionage, bold diplomacy, and constant contact. He has little patience for passive defense or Wonder obsession.'),

('TXT_KEY_TRAIT_FILTHY_SHORT','Welcome to the Rice Fields'),
('TXT_KEY_TRAIT_FILTHY_HELP','Foreign Cities exposed to your international [ICON_INTERNATIONAL_TRADE] Trade Routes, Tourism, pillaging, and nearby combat gain up to 5 levels of [COLOR_MAGENTA]Filth[ENDCOLOR], reducing Culture, Gold, and Production by up to 10%. At levels 4 and 5, your nearby military units gain +10% or +15% Combat Strength. Earn [COLOR_MAGENTA]Filthy Points[ENDCOLOR] from disruption and spend them through ENTER THE FILTHY REALM.'),

('TXT_KEY_UNIT_FILTHY_PEACE_LORD','Peace Lord'),
('TXT_KEY_UNIT_FILTHY_PEACE_LORD_HELP','Replaces Great War Infantry. 52 Combat Strength. Kills grant +5 additional Filthy Points and humiliate adjacent enemy military units for one turn. Once per Peace Lord, Filthy Intervention can force an adjacent enemy below 30 HP to retreat and grants +10 Filthy Points.'),
('TXT_KEY_UNIT_FILTHY_PEACE_LORD_STRATEGY','Finish weakened enemies near contaminated Cities, then use Filthy Intervention through the Realm panel to displace another badly wounded adjacent unit.'),
('TXT_KEY_UNIT_FILTHY_PEACE_LORD_PEDIA','The Peace Lord turns battlefield humiliation into a resource. Its active intervention does not destroy its target: it forces the victim to retreat to the nearest valid tile away from the Peace Lord.'),
('TXT_KEY_UNIT_FILTHY_SALAMANDER_MAN','Salamander Man'),
('TXT_KEY_UNIT_FILTHY_SALAMANDER_MAN_HELP','Temporary non-combat unit with 5 Movement. Adjacent enemies suffer -10% Combat Strength and -1 Movement; adjacent friendly military units gain +1 Movement. Expires after 5 turns.'),
('TXT_KEY_UNIT_FILTHY_SALAMANDER_MAN_STRATEGY','Keep Salamander Man just behind the front line. His aura disrupts adjacent enemies and accelerates friendly military units.'),
('TXT_KEY_UNIT_FILTHY_SALAMANDER_MAN_PEDIA','Summoned for 25 Filthy Points, Salamander Man is a temporary aura unit that cannot attack, capture Cities, upgrade, or be gifted.'),

('TXT_KEY_BUILDING_FILTHY_KITCHEN','Filthy Kitchen'),
('TXT_KEY_BUILDING_FILTHY_KITCHEN_HELP','Replaces the Broadcast Tower and retains its normal effects. +2 Tourism. Great Works generate Food and Filthy Points when created, and up to 3 passive Filthy Points per City every 5 turns. International Trade Routes from this City spread Filth faster.'),
('TXT_KEY_BUILDING_FILTHY_KITCHEN_STRATEGY','Concentrate Great Works in Filthy Kitchens and use those Cities as international Trade Route origins.'),
('TXT_KEY_BUILDING_FILTHY_KITCHEN_PEDIA','A Filthy Kitchen turns creative production into food, provocation, and wider contamination.'),
('TXT_KEY_BUILDING_FILTHY_LEVEL_PEDIA','A hidden marker used by the Filthy Realm runtime. Only one Filth-level building can exist in a City at once.'),
('TXT_KEY_BUILDING_FILTHY_LEVEL_1','Filth I'),('TXT_KEY_BUILDING_FILTHY_LEVEL_1_HELP','-2% Culture.'),
('TXT_KEY_BUILDING_FILTHY_LEVEL_2','Filth II'),('TXT_KEY_BUILDING_FILTHY_LEVEL_2_HELP','-3% Culture and Gold.'),
('TXT_KEY_BUILDING_FILTHY_LEVEL_3','Filth III'),('TXT_KEY_BUILDING_FILTHY_LEVEL_3_HELP','-5% Culture, Gold, and Production.'),
('TXT_KEY_BUILDING_FILTHY_LEVEL_4','Filth IV'),('TXT_KEY_BUILDING_FILTHY_LEVEL_4_HELP','-7% Culture, Gold, and Production. Nearby Filthy military units gain +10% Combat Strength.'),
('TXT_KEY_BUILDING_FILTHY_LEVEL_5','Absolutely Disgusting'),('TXT_KEY_BUILDING_FILTHY_LEVEL_5_HELP','-10% Culture, Gold, and Production; -1 Local Happiness. Nearby Filthy military units gain +15% Combat Strength.'),
('TXT_KEY_BUILDING_FILTHY_DISTORTED_1','Distorted Filth I'),('TXT_KEY_BUILDING_FILTHY_DISTORTED_2','Distorted Filth II'),
('TXT_KEY_BUILDING_FILTHY_DISTORTED_3','Distorted Filth III'),('TXT_KEY_BUILDING_FILTHY_DISTORTED_4','Distorted Filth IV'),
('TXT_KEY_BUILDING_FILTHY_DISTORTED_5','Distorted Filth V'),('TXT_KEY_BUILDING_FILTHY_DISTORTED_HELP','Realm Distortion increases this City''s current Filth penalties by 50%.'),

('TXT_KEY_PROMOTION_FILTHY_KNOW_YOUR_PLACE','Know Your Place'),
('TXT_KEY_PROMOTION_FILTHY_KNOW_YOUR_PLACE_HELP','Kills grant +5 Filthy Points and adjacent enemies receive -10% Combat Strength for 1 turn. Grants one use of Filthy Intervention against an adjacent enemy military unit below 30 HP.'),
('TXT_KEY_PROMOTION_FILTHY_CITY_STRENGTH_10','Filthy Territory: +10%'),('TXT_KEY_PROMOTION_FILTHY_CITY_STRENGTH_10_HELP','+10% Combat Strength near a foreign City at Filth IV.'),
('TXT_KEY_PROMOTION_FILTHY_CITY_STRENGTH_15','Filthy Territory: +15%'),('TXT_KEY_PROMOTION_FILTHY_CITY_STRENGTH_15_HELP','+15% Combat Strength near a foreign City at Filth V. This replaces the level IV bonus.'),
('TXT_KEY_PROMOTION_FILTHY_HUMILIATED','Know Your Place'),('TXT_KEY_PROMOTION_FILTHY_HUMILIATED_HELP','-10% Combat Strength until the beginning of the next turn.'),
('TXT_KEY_PROMOTION_FILTHY_SALAMANDER_ENEMY','Salamander Aura'),('TXT_KEY_PROMOTION_FILTHY_SALAMANDER_ENEMY_HELP','-10% Combat Strength and -1 Movement while adjacent to Salamander Man.'),
('TXT_KEY_PROMOTION_FILTHY_SALAMANDER_FRIEND','Salamander Guidance'),('TXT_KEY_PROMOTION_FILTHY_SALAMANDER_FRIEND_HELP','+1 Movement while adjacent to Salamander Man.'),
('TXT_KEY_PROMOTION_FILTHY_DISTORTION_ZOC','Distorted Passage'),('TXT_KEY_PROMOTION_FILTHY_DISTORTION_ZOC_HELP','Ignores enemy Zone of Control within 2 tiles of the distorted City.'),
('TXT_KEY_PROMOTION_FILTHY_STOPPED','It''s Time to Stop'),('TXT_KEY_PROMOTION_FILTHY_STOPPED_HELP','This unit has no Movement and cannot attack for the remainder of the current turn.'),

('TXT_KEY_FILTHY_DAWN_OF_MAN','Filthy Frank, ruler of the Rice Fields, the world has mistaken disgust for distance. You know better. Every complaint is contact, every denunciation is attention, and every open route is another road by which the Realm may spread.[NEWLINE][NEWLINE]Send your traders beyond the paddies. Fill foreign streets with Filth, turn their outrage into Filthy Points, and make their most contaminated Cities welcome your Peace Lords. When subtlety fails, open the Filthy Realm and command reality itself to stop.[NEWLINE][NEWLINE]Frank, will you build a higher form of civilization?'),
('TXT_KEY_FILTHY_FILTH_GAINED','{1_CityName} has reached Filth level {2_Level}.'),
('TXT_KEY_FILTHY_INTERVENTION_NOTIFICATION','{1_UnitName} forced {2_TargetName} to retreat: +10 Filthy Points.'),
('TXT_KEY_FILTHY_SALAMANDER_NOTIFICATION','Salamander Man has entered the Realm for 5 turns.'),

('TXT_KEY_CITY_FILTHY_1','The Rice Fields'),('TXT_KEY_CITY_FILTHY_2','Chin Chin'),
('TXT_KEY_CITY_FILTHY_3','Pink Season'),('TXT_KEY_CITY_FILTHY_4','Harlem'),
('TXT_KEY_CITY_FILTHY_5','Ravioli Ridge'),('TXT_KEY_CITY_FILTHY_6','Salamander Vale'),
('TXT_KEY_CITY_FILTHY_7','Human Cake'),('TXT_KEY_CITY_FILTHY_8','Hair Cake'),
('TXT_KEY_CITY_FILTHY_9','Weeaboo Ward'),('TXT_KEY_CITY_FILTHY_10','Dizasta'),
('TXT_KEY_CITY_FILTHY_11','Francis'),('TXT_KEY_CITY_FILTHY_12','The Dark Lord'),
('TXT_KEY_CITY_FILTHY_13','Green Echo'),('TXT_KEY_CITY_FILTHY_14','Safari Sector'),
('TXT_KEY_CITY_FILTHY_15','Kitchen District'),('TXT_KEY_CITY_FILTHY_16','Pocketoli'),
('TXT_KEY_CITY_FILTHY_17','Filth Harbor'),('TXT_KEY_CITY_FILTHY_18','Pink Plateau'),
('TXT_KEY_CITY_FILTHY_19','Cake Province'),('TXT_KEY_CITY_FILTHY_20','Realm''s Edge'),
('TXT_KEY_CITY_FILTHY_21','Stop Station'),('TXT_KEY_CITY_FILTHY_22','Peace Lord Post'),
('TXT_KEY_CITY_FILTHY_23','The Eyebrows'),('TXT_KEY_CITY_FILTHY_24','Bogerbo'),
('TXT_KEY_SPY_FILTHY_1','Pink Guy'),('TXT_KEY_SPY_FILTHY_2','Salamander'),
('TXT_KEY_SPY_FILTHY_3','Chin Chin'),('TXT_KEY_SPY_FILTHY_4','Safari Man'),
('TXT_KEY_SPY_FILTHY_5','Lemon'),('TXT_KEY_SPY_FILTHY_6','Ravioli'),
('TXT_KEY_SPY_FILTHY_7','Boger'),('TXT_KEY_SPY_FILTHY_8','Green Echo'),
('TXT_KEY_SPY_FILTHY_9','Peace Lord'),('TXT_KEY_SPY_FILTHY_10','Dark Lord');

DELETE FROM Diplomacy_Responses WHERE LeaderType='LEADER_FILTHY_FRANK' AND ResponseType IN
('RESPONSE_FIRST_GREETING','RESPONSE_GREETING_NEUTRAL_HELLO','RESPONSE_GREETING_HOSTILE_HELLO',
 'RESPONSE_DOW_GENERIC','RESPONSE_ATTACKED_HOSTILE','RESPONSE_DEFEATED','RESPONSE_PEACE_OFFER',
 'RESPONSE_TRADE_ACCEPT_ACCEPTABLE','RESPONSE_TRADE_REJECT_UNACCEPTABLE','RESPONSE_RESPONSE_TO_BEING_DENOUNCED');
INSERT INTO Language_en_US(Tag,Text) VALUES
('TXT_KEY_LEADER_FILTHY_FIRSTGREETING_1','Welcome to the Rice Fields. Try not to touch anything.'),
('TXT_KEY_LEADER_FILTHY_GREETING_NEUTRAL_1','What brings you back to the Realm?'),
('TXT_KEY_LEADER_FILTHY_GREETING_HOSTILE_1','Your disgust only proves you are paying attention.'),
('TXT_KEY_LEADER_FILTHY_DOW_1','It is time for a higher form of diplomacy.'),
('TXT_KEY_LEADER_FILTHY_ATTACKED_1','You have entered the Realm willingly. Absolutely disgusting.'),
('TXT_KEY_LEADER_FILTHY_DEFEATED_1','It''s time to stop.'),
('TXT_KEY_LEADER_FILTHY_PEACE_1','Enough filth for one war. For now.'),
('TXT_KEY_LEADER_FILTHY_TRADE_ACCEPT_1','The route is open. Excellent.'),
('TXT_KEY_LEADER_FILTHY_TRADE_REJECT_1','Not filthy enough.'),
('TXT_KEY_LEADER_FILTHY_DENOUNCED_1','Negative attention is still attention.');
INSERT INTO Diplomacy_Responses(LeaderType,ResponseType,Response,Bias) VALUES
('LEADER_FILTHY_FRANK','RESPONSE_FIRST_GREETING','TXT_KEY_LEADER_FILTHY_FIRSTGREETING%',1),
('LEADER_FILTHY_FRANK','RESPONSE_GREETING_NEUTRAL_HELLO','TXT_KEY_LEADER_FILTHY_GREETING_NEUTRAL%',1),
('LEADER_FILTHY_FRANK','RESPONSE_GREETING_HOSTILE_HELLO','TXT_KEY_LEADER_FILTHY_GREETING_HOSTILE%',1),
('LEADER_FILTHY_FRANK','RESPONSE_DOW_GENERIC','TXT_KEY_LEADER_FILTHY_DOW%',1),
('LEADER_FILTHY_FRANK','RESPONSE_ATTACKED_HOSTILE','TXT_KEY_LEADER_FILTHY_ATTACKED%',1),
('LEADER_FILTHY_FRANK','RESPONSE_DEFEATED','TXT_KEY_LEADER_FILTHY_DEFEATED%',1),
('LEADER_FILTHY_FRANK','RESPONSE_PEACE_OFFER','TXT_KEY_LEADER_FILTHY_PEACE%',1),
('LEADER_FILTHY_FRANK','RESPONSE_TRADE_ACCEPT_ACCEPTABLE','TXT_KEY_LEADER_FILTHY_TRADE_ACCEPT%',1),
('LEADER_FILTHY_FRANK','RESPONSE_TRADE_REJECT_UNACCEPTABLE','TXT_KEY_LEADER_FILTHY_TRADE_REJECT%',1),
('LEADER_FILTHY_FRANK','RESPONSE_RESPONSE_TO_BEING_DENOUNCED','TXT_KEY_LEADER_FILTHY_DENOUNCED%',1);
