-- Run after companion-table inheritance.
INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_LUNA_CACHE_NODE', 'YIELD_PRODUCTION', 0
WHERE NOT EXISTS (SELECT 1 FROM Building_YieldChanges
 WHERE BuildingType = 'BUILDING_LUNA_CACHE_NODE' AND YieldType = 'YIELD_PRODUCTION');
UPDATE Building_YieldChanges SET Yield = Yield + 1
WHERE BuildingType = 'BUILDING_LUNA_CACHE_NODE' AND YieldType = 'YIELD_PRODUCTION';

INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
SELECT 'BUILDING_LUNA_CACHE_NODE', 'FLAVOR_PRODUCTION', 15
WHERE NOT EXISTS (SELECT 1 FROM Building_Flavors
 WHERE BuildingType = 'BUILDING_LUNA_CACHE_NODE' AND FlavorType = 'FLAVOR_PRODUCTION');

INSERT INTO Leader_Flavors (LeaderType, FlavorType, Flavor)
SELECT 'LEADER_GPT_LUNA', Type,
 CASE Type
 WHEN 'FLAVOR_OFFENSE' THEN 7 WHEN 'FLAVOR_DEFENSE' THEN 6
 WHEN 'FLAVOR_CITY_DEFENSE' THEN 5 WHEN 'FLAVOR_MILITARY_TRAINING' THEN 8
 WHEN 'FLAVOR_GROWTH' THEN 5 WHEN 'FLAVOR_PRODUCTION' THEN 9
 WHEN 'FLAVOR_EXPANSION' THEN 9 WHEN 'FLAVOR_GOLD' THEN 6
 WHEN 'FLAVOR_SCIENCE' THEN 6 WHEN 'FLAVOR_DIPLOMACY' THEN 7
 WHEN 'FLAVOR_RECON' THEN 8 WHEN 'FLAVOR_NAVAL_RECON' THEN 8
 WHEN 'FLAVOR_NAVAL_GROWTH' THEN 6 WHEN 'FLAVOR_TILE_IMPROVEMENT' THEN 7
 WHEN 'FLAVOR_WONDER' THEN 2 WHEN 'FLAVOR_RELIGION' THEN 3
 WHEN 'FLAVOR_CULTURE' THEN 4 ELSE 5 END
FROM Flavors;
INSERT INTO Leader_MajorCivApproachBiases (LeaderType, MajorCivApproachType, Bias)
SELECT 'LEADER_GPT_LUNA', MajorCivApproachType,
 CASE MajorCivApproachType
 WHEN 'MAJOR_CIV_APPROACH_WAR' THEN 6 WHEN 'MAJOR_CIV_APPROACH_HOSTILE' THEN 5
 WHEN 'MAJOR_CIV_APPROACH_DECEPTIVE' THEN 4 WHEN 'MAJOR_CIV_APPROACH_GUARDED' THEN 5
 WHEN 'MAJOR_CIV_APPROACH_AFRAID' THEN 2 WHEN 'MAJOR_CIV_APPROACH_FRIENDLY' THEN 6
 WHEN 'MAJOR_CIV_APPROACH_NEUTRAL' THEN 5 ELSE Bias END
FROM Leader_MajorCivApproachBiases WHERE LeaderType = 'LEADER_WASHINGTON';
INSERT INTO Leader_MinorCivApproachBiases (LeaderType, MinorCivApproachType, Bias)
SELECT 'LEADER_GPT_LUNA', MinorCivApproachType, Bias
FROM Leader_MinorCivApproachBiases WHERE LeaderType = 'LEADER_WASHINGTON';

-- Generic coverage prevents missing diplomacy responses; Luna-specific lines replace key cases below.
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias)
SELECT 'LEADER_GPT_LUNA', ResponseType, Response, Bias
FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_WASHINGTON';

INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_1'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_2'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_3'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_4'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_5'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_6'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_7'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_8'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_9'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_10'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_11'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_12'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_13'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_14'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_15'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_16'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_17'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_18'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_19'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_20'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_21'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_22'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_23'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_24'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_25'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_26'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_27'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_28'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_29'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_30'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_31'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_32'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_33'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_34'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_CITY_LUNA_35');
INSERT INTO Civilization_SpyNames (CivilizationType, SpyName) VALUES
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_SPY_LUNA_1'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_SPY_LUNA_2'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_SPY_LUNA_3'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_SPY_LUNA_4'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_SPY_LUNA_5'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_SPY_LUNA_6'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_SPY_LUNA_7'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_SPY_LUNA_8'),
('CIVILIZATION_GPT_LUNA', 'TXT_KEY_SPY_LUNA_9'), ('CIVILIZATION_GPT_LUNA', 'TXT_KEY_SPY_LUNA_10');

DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_GPT_LUNA' AND ResponseType IN
('RESPONSE_FIRST_GREETING', 'RESPONSE_GREETING_NEUTRAL_HELLO', 'RESPONSE_GREETING_POLITE_HELLO',
 'RESPONSE_GREETING_HOSTILE_HELLO', 'RESPONSE_GREETING_AT_WAR_HOSTILE', 'RESPONSE_DECLAREWAR',
 'RESPONSE_DOW_GENERIC', 'RESPONSE_ATTACKED', 'RESPONSE_DEFEATED', 'RESPONSE_PEACE_OFFER',
 'RESPONSE_NO_PEACE', 'RESPONSE_AGREE_SHORT', 'RESPONSE_DISAGREE_SHORT', 'RESPONSE_LETS_HEAR_IT',
 'RESPONSE_LETSHEARIT', 'RESPONSE_GOODBYE', 'RESPONSE_TRADE_ACCEPT_GENEROUS',
 'RESPONSE_TRADE_ACCEPT_ACCEPTABLE', 'RESPONSE_TRADE_REJECT_INSULTING',
 'RESPONSE_TRADE_REJECT_UNACCEPTABLE', 'RESPONSE_WORK_WITH_US', 'RESPONSE_WORK_WITH_US_YES',
 'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 'RESPONSE_THANKFUL');
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES
('LEADER_GPT_LUNA', 'RESPONSE_FIRST_GREETING', 'TXT_KEY_LUNA_DIPLO_FIRST_GREETING_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_GREETING_NEUTRAL_HELLO', 'TXT_KEY_LUNA_DIPLO_NEUTRAL_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_GREETING_POLITE_HELLO', 'TXT_KEY_LUNA_DIPLO_FRIENDLY_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_GREETING_HOSTILE_HELLO', 'TXT_KEY_LUNA_DIPLO_HOSTILE_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_GREETING_AT_WAR_HOSTILE', 'TXT_KEY_LUNA_DIPLO_AT_WAR_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_DECLAREWAR', 'TXT_KEY_LUNA_DIPLO_DECLAREWAR_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_DOW_GENERIC', 'TXT_KEY_LUNA_DIPLO_DECLAREWAR_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_ATTACKED', 'TXT_KEY_LUNA_DIPLO_ATTACKED_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_DEFEATED', 'TXT_KEY_LUNA_DIPLO_DEFEATED_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_PEACE_OFFER', 'TXT_KEY_LUNA_DIPLO_PEACE_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_NO_PEACE', 'TXT_KEY_LUNA_DIPLO_NO_PEACE_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_AGREE_SHORT', 'TXT_KEY_LUNA_DIPLO_AGREE_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_DISAGREE_SHORT', 'TXT_KEY_LUNA_DIPLO_DISAGREE_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_LETS_HEAR_IT', 'TXT_KEY_LUNA_DIPLO_PROPOSAL_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_LETSHEARIT', 'TXT_KEY_LUNA_DIPLO_PROPOSAL_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_GOODBYE', 'TXT_KEY_LUNA_DIPLO_GOODBYE_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_TRADE_ACCEPT_GENEROUS', 'TXT_KEY_LUNA_DIPLO_AGREE_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_TRADE_ACCEPT_ACCEPTABLE', 'TXT_KEY_LUNA_DIPLO_AGREE_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_TRADE_REJECT_INSULTING', 'TXT_KEY_LUNA_DIPLO_DISAGREE_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_TRADE_REJECT_UNACCEPTABLE', 'TXT_KEY_LUNA_DIPLO_DISAGREE_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_WORK_WITH_US', 'TXT_KEY_LUNA_DIPLO_FRIENDSHIP_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_WORK_WITH_US_YES', 'TXT_KEY_LUNA_DIPLO_FRIENDSHIP_ACCEPT_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 'TXT_KEY_LUNA_DIPLO_DENOUNCED_1', 1),
('LEADER_GPT_LUNA', 'RESPONSE_THANKFUL', 'TXT_KEY_LUNA_DIPLO_THANKFUL_1', 1);
