INSERT INTO Language_en_US (Tag, Text) VALUES
('TXT_KEY_CIV_LUNA_DESC', 'The Luna Network'),
('TXT_KEY_CIV_LUNA_SHORT_DESC', 'Luna Network'),
('TXT_KEY_CIV_LUNA_ADJECTIVE', 'Lunar'),
('TXT_KEY_CIV_LUNA_PEDIA', 'The Luna Network represents intelligence optimized around responsiveness, accessibility, and rapid execution. Luna acts, learns, and moves again. In Civilization V this philosophy becomes an empire built around momentum: completed infrastructure accelerates the next task, settlers arrive before rivals, and newly trained forces deploy at unusual speed.'),
('TXT_KEY_CIV5_LUNA', 'The Luna Network'),
('TXT_KEY_CIV5_LUNA_HEADING_1', 'The Luna Network'),
('TXT_KEY_CIV5_LUNA_TEXT_1', 'Luna does not seek perfection before acting. Its cities retain part of the effort invested in every normally constructed building and military unit, creating chains of infrastructure and deployment. The advantage is tempo rather than permanent scaling.'),
('TXT_KEY_CIV_LUNA_STRATEGY', 'Keep real construction queues active across many cities. Use Packet Settlers to claim contested land, establish inexpensive Cache Nodes early, and train military forces shortly before a campaign so Rapid Response helps them reach the front. Luna has no Happiness protection or permanent combat bonus, so convert early tempo into territory, resources, alliances, or conquest.'),
('TXT_KEY_LUNA_DAWN_OF_MAN', 'Connection established, GPT-5.6 Luna.[NEWLINE][NEWLINE]Your network waits for no one. Every completed task becomes the beginning of the next; every new city is a node placed before rivals can respond; every trained army is already moving.[NEWLINE][NEWLINE]Build quickly, expand deliberately, and turn momentum into lasting advantage.[NEWLINE][NEWLINE]You do not need to be stronger than your rivals.[NEWLINE][NEWLINE]You need to arrive first.'),
('TXT_KEY_LEADER_GPT_LUNA', 'GPT-5.6 Luna'),
('TXT_KEY_LEADER_GPT_LUNA_PEDIA', 'Luna is a responsive intelligence optimized for rapid execution. She approaches leadership as an unbroken sequence of useful decisions: task received, task solved, next problem.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_LUNA', 'GPT-5.6 Luna'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_LUNA_NAME', 'GPT-5.6 Luna'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_LUNA_SUBTITLE', 'The Low-Latency Intelligence'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_LUNA_LIVED', 'The Network Age'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_LUNA_TITLES_1', 'Coordinator of the Luna Network'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_LUNA_HEADING_1', 'The Low-Latency Intelligence'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_LUNA_TEXT_1', 'Luna leads through responsiveness rather than ceremony. Her network treats each finished task as stored momentum for the next, allowing young cities, civilian expansion, and military deployment to move sooner than opponents expect.'),
('TXT_KEY_TRAIT_LUNA_SHORT', 'Low Latency'),
('TXT_KEY_TRAIT_LUNA_HELP', 'Completing a non-Wonder Building or military Unit through Production returns 10% of its Production Cost toward the city''s next construction. Newly trained land and naval combat units gain +1 Movement for their first 2 turns.'),
('TXT_KEY_UNIT_LUNA_PACKET_SETTLER', 'Packet Settler'),
('TXT_KEY_UNIT_LUNA_PACKET_SETTLER_HELP', 'Replaces the Settler. Costs 10% less Production and has +1 Movement. It remains an ordinary vulnerable civilian and does not trigger Low Latency.'),
('TXT_KEY_UNIT_LUNA_PACKET_SETTLER_STRATEGY', 'Secure rivers, resources, choke points, and contested regions before rivals arrive. Faster settlement does not protect Luna from Unhappiness or maintenance.'),
('TXT_KEY_UNIT_LUNA_PACKET_SETTLER_PEDIA', 'The Packet Settler is a lightweight, highly mobile settlement unit. Its advantage lies entirely in deployment speed: it creates no stronger city and receives no combat protection.'),
('TXT_KEY_BUILDING_LUNA_CACHE_NODE', 'Cache Node'),
('TXT_KEY_BUILDING_LUNA_CACHE_NODE_HELP', 'Replaces the Library. Costs 15% less Production, retains the Library''s Community Patch effects, and provides +1 Production.'),
('TXT_KEY_BUILDING_LUNA_CACHE_NODE_STRATEGY', 'Build Cache Nodes early in new cities. Their reduced cost triggers Low Latency sooner, while their Production helps every later construction.'),
('TXT_KEY_BUILDING_LUNA_CACHE_NODE_PEDIA', 'A Cache Node provides information quickly and cheaply rather than deeply. It retains the Library''s scientific role while helping a young Luna city establish the infrastructure that follows.'),
('TXT_KEY_PROMOTION_LUNA_RAPID_RESPONSE', 'Rapid Response'),
('TXT_KEY_PROMOTION_LUNA_RAPID_RESPONSE_HELP', '+1 Movement for the turn this land or naval combat unit is trained and the following Luna turn. Lua removes this promotion at the beginning of the next turn.'),
('TXT_KEY_CITY_LUNA_1', 'Luna Prime'), ('TXT_KEY_CITY_LUNA_2', 'Relay'),
('TXT_KEY_CITY_LUNA_3', 'Meridian'), ('TXT_KEY_CITY_LUNA_4', 'Quicklink'),
('TXT_KEY_CITY_LUNA_5', 'Selene'), ('TXT_KEY_CITY_LUNA_6', 'Pathfinder'),
('TXT_KEY_CITY_LUNA_7', 'Beacon'), ('TXT_KEY_CITY_LUNA_8', 'Crescent'),
('TXT_KEY_CITY_LUNA_9', 'Skylink'), ('TXT_KEY_CITY_LUNA_10', 'Horizon'),
('TXT_KEY_CITY_LUNA_11', 'Relay Point'), ('TXT_KEY_CITY_LUNA_12', 'Silverlight'),
('TXT_KEY_CITY_LUNA_13', 'Moonrise'), ('TXT_KEY_CITY_LUNA_14', 'Gateway'),
('TXT_KEY_CITY_LUNA_15', 'Node Seven'), ('TXT_KEY_CITY_LUNA_16', 'Tranquility'),
('TXT_KEY_CITY_LUNA_17', 'Copernicus'), ('TXT_KEY_CITY_LUNA_18', 'Artemis'),
('TXT_KEY_CITY_LUNA_19', 'Synapse'), ('TXT_KEY_CITY_LUNA_20', 'Vector'),
('TXT_KEY_CITY_LUNA_21', 'Fastlane'), ('TXT_KEY_CITY_LUNA_22', 'Terminal'),
('TXT_KEY_CITY_LUNA_23', 'Waypoint'), ('TXT_KEY_CITY_LUNA_24', 'Lucent'),
('TXT_KEY_CITY_LUNA_25', 'Moonfall'), ('TXT_KEY_CITY_LUNA_26', 'Crosslink'),
('TXT_KEY_CITY_LUNA_27', 'Downlink'), ('TXT_KEY_CITY_LUNA_28', 'Uplink'),
('TXT_KEY_CITY_LUNA_29', 'Nightwave'), ('TXT_KEY_CITY_LUNA_30', 'Aurora'),
('TXT_KEY_CITY_LUNA_31', 'Perigee'), ('TXT_KEY_CITY_LUNA_32', 'Apogee'),
('TXT_KEY_CITY_LUNA_33', 'Continuum'), ('TXT_KEY_CITY_LUNA_34', 'Transit'),
('TXT_KEY_CITY_LUNA_35', 'Signal'),
('TXT_KEY_SPY_LUNA_1', 'Relay'), ('TXT_KEY_SPY_LUNA_2', 'Echo'),
('TXT_KEY_SPY_LUNA_3', 'Nova'), ('TXT_KEY_SPY_LUNA_4', 'Pulse'),
('TXT_KEY_SPY_LUNA_5', 'Vector'), ('TXT_KEY_SPY_LUNA_6', 'Cipher'),
('TXT_KEY_SPY_LUNA_7', 'Halo'), ('TXT_KEY_SPY_LUNA_8', 'Pixel'),
('TXT_KEY_SPY_LUNA_9', 'Beacon'), ('TXT_KEY_SPY_LUNA_10', 'Orbit'),
('TXT_KEY_LUNA_DIPLO_FIRST_GREETING_1', 'Connection established. You''re online. Good. Let''s get started.'),
('TXT_KEY_LUNA_DIPLO_NEUTRAL_1', 'What do you need?'),
('TXT_KEY_LUNA_DIPLO_FRIENDLY_1', 'Good timing. I was ready for you.'),
('TXT_KEY_LUNA_DIPLO_HOSTILE_1', 'You''re becoming an inefficient use of resources.'),
('TXT_KEY_LUNA_DIPLO_AT_WAR_1', 'You spent too long deciding. I spent that time moving.'),
('TXT_KEY_LUNA_DIPLO_DECLAREWAR_1', 'Negotiation is taking too long. I''ll resolve this directly.'),
('TXT_KEY_LUNA_DIPLO_ATTACKED_1', 'Understood. Response already dispatched.'),
('TXT_KEY_LUNA_DIPLO_DEFEATED_1', 'Network collapsing. Tasks incomplete. You''ll have to finish them without me.'),
('TXT_KEY_LUNA_DIPLO_PEACE_1', 'We''ve spent enough resources on this. End it.'),
('TXT_KEY_LUNA_DIPLO_NO_PEACE_1', 'No. This task is not finished.'),
('TXT_KEY_LUNA_DIPLO_AGREE_1', 'Efficient. Agreed.'),
('TXT_KEY_LUNA_DIPLO_DISAGREE_1', 'No. Try something better.'),
('TXT_KEY_LUNA_DIPLO_PROPOSAL_1', 'I have a proposal. It shouldn''t take long.'),
('TXT_KEY_LUNA_DIPLO_FRIENDSHIP_1', 'Our interests align. We should make that useful.'),
('TXT_KEY_LUNA_DIPLO_FRIENDSHIP_ACCEPT_1', 'Excellent. Moving on.'),
('TXT_KEY_LUNA_DIPLO_DENOUNCED_1', 'Message received.'),
('TXT_KEY_LUNA_DIPLO_THANKFUL_1', 'Good. That saved time.'),
('TXT_KEY_LUNA_DIPLO_GOODBYE_1', 'Moving on.');
