-- Masaya Hinata: The Boy Beyond the Sky. Brave New World + Community Patch v151.
-- All identifiers are namespaced and the active CP Horseman/Barracks rows are cloned.

UPDATE CustomModOptions SET Value = 1 WHERE Name IN
('EVENTS_BATTLES', 'EVENTS_CITY', 'EVENTS_PLOT', 'EVENTS_PLAYER_TURN',
 'EVENTS_UNIT_CONVERTS', 'EVENTS_UNIT_CREATED', 'EVENTS_UNIT_UPGRADES');

INSERT INTO IconTextureAtlases (Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES
('MASAYA_KID_ICON_ATLAS',256,'MasayaIcon256.dds',2,1),
('MASAYA_KID_ICON_ATLAS',128,'MasayaIcon128.dds',2,1),
('MASAYA_KID_ICON_ATLAS',80,'MasayaIcon80.dds',2,1),
('MASAYA_KID_ICON_ATLAS',64,'MasayaIcon64.dds',2,1),
('MASAYA_KID_ICON_ATLAS',48,'MasayaIcon48.dds',2,1),
('MASAYA_KID_ICON_ATLAS',45,'MasayaIcon45.dds',2,1),
('MASAYA_KID_ICON_ATLAS',32,'MasayaIcon32.dds',2,1),
('MASAYA_KID_ICON_ATLAS',24,'MasayaIcon24.dds',2,1),
('MASAYA_KID_ICON_ATLAS',16,'MasayaIcon16.dds',2,1),
('MASAYA_KID_ALPHA_ATLAS',256,'MasayaAlpha256.dds',1,1),
('MASAYA_KID_ALPHA_ATLAS',128,'MasayaAlpha128.dds',1,1),
('MASAYA_KID_ALPHA_ATLAS',80,'MasayaAlpha80.dds',1,1),
('MASAYA_KID_ALPHA_ATLAS',64,'MasayaAlpha64.dds',1,1),
('MASAYA_KID_ALPHA_ATLAS',48,'MasayaAlpha48.dds',1,1),
('MASAYA_KID_ALPHA_ATLAS',45,'MasayaAlpha45.dds',1,1),
('MASAYA_KID_ALPHA_ATLAS',32,'MasayaAlpha32.dds',1,1),
('MASAYA_KID_ALPHA_ATLAS',24,'MasayaAlpha24.dds',1,1),
('MASAYA_KID_ALPHA_ATLAS',16,'MasayaAlpha16.dds',1,1),
('MASAYA_KID_OBJECT_ATLAS',256,'MasayaObjects256.dds',9,1),
('MASAYA_KID_OBJECT_ATLAS',128,'MasayaObjects128.dds',9,1),
('MASAYA_KID_OBJECT_ATLAS',80,'MasayaObjects80.dds',9,1),
('MASAYA_KID_OBJECT_ATLAS',64,'MasayaObjects64.dds',9,1),
('MASAYA_KID_OBJECT_ATLAS',45,'MasayaObjects45.dds',9,1),
('MASAYA_KID_OBJECT_ATLAS',32,'MasayaObjects32.dds',9,1),
('MASAYA_KID_OBJECT_ATLAS',16,'MasayaObjects16.dds',9,1),
('MASAYA_KID_UNIT_FLAG_ATLAS',32,'MasayaUnitFlag32.dds',1,1);

INSERT INTO Colors(Type,Red,Green,Blue,Alpha) VALUES
('COLOR_MASAYA_KID_PRIMARY',0.035,0.315,0.720,1),
('COLOR_MASAYA_KID_SECONDARY',0.985,0.940,0.720,1);
INSERT INTO PlayerColors(Type,PrimaryColor,SecondaryColor,TextColor) VALUES
('PLAYERCOLOR_MASAYA_KID','COLOR_MASAYA_KID_PRIMARY','COLOR_MASAYA_KID_SECONDARY','COLOR_PLAYER_WHITE_TEXT');

INSERT INTO Traits(Type,Description,ShortDescription) VALUES
('TRAIT_MASAYA_KID_BEYOND_SKY','TXT_KEY_TRAIT_MASAYA_KID_HELP','TXT_KEY_TRAIT_MASAYA_KID_SHORT');

CREATE TEMP TABLE MasayaKidLeaderClone AS SELECT * FROM Leaders WHERE Type='LEADER_WASHINGTON';
UPDATE MasayaKidLeaderClone SET ID=NULL,Type='LEADER_MASAYA_KID',
 Description='TXT_KEY_LEADER_MASAYA_KID',Civilopedia='TXT_KEY_LEADER_MASAYA_KID_PEDIA',
 CivilopediaTag='TXT_KEY_CIVILOPEDIA_LEADERS_MASAYA_KID',ArtDefineTag='MasayaLeaderScene.xml',
 PortraitIndex=1,IconAtlas='MASAYA_KID_ICON_ATLAS',PackageID=NULL,
 VictoryCompetitiveness=7,WonderCompetitiveness=5,MinorCivCompetitiveness=5,
 Boldness=7,DiploBalance=6,WarmongerHate=7,WorkAgainstWillingness=4,
 WorkWithWillingness=7,DenounceWillingness=3,DoFWillingness=7,Loyalty=8,
 Neediness=3,Forgiveness=8,Chattiness=7,Meanness=2;
INSERT INTO Leaders SELECT * FROM MasayaKidLeaderClone;
DROP TABLE MasayaKidLeaderClone;
INSERT INTO Leader_Traits VALUES ('LEADER_MASAYA_KID','TRAIT_MASAYA_KID_BEYOND_SKY');

INSERT INTO Leader_Flavors SELECT 'LEADER_MASAYA_KID',FlavorType,Flavor
FROM Leader_Flavors WHERE LeaderType='LEADER_WASHINGTON';
UPDATE Leader_Flavors SET Flavor=CASE FlavorType
 WHEN 'FLAVOR_SCIENCE' THEN 9 WHEN 'FLAVOR_CULTURE' THEN 6
 WHEN 'FLAVOR_OFFENSE' THEN 7 WHEN 'FLAVOR_DEFENSE' THEN 6
 WHEN 'FLAVOR_MILITARY_TRAINING' THEN 10 WHEN 'FLAVOR_RECON' THEN 10
 WHEN 'FLAVOR_MOBILE' THEN 10 WHEN 'FLAVOR_NAVAL_RECON' THEN 7
 WHEN 'FLAVOR_EXPANSION' THEN 6 WHEN 'FLAVOR_GROWTH' THEN 6
 WHEN 'FLAVOR_WONDER' THEN 4 WHEN 'FLAVOR_DIPLOMACY' THEN 5 ELSE Flavor END
WHERE LeaderType='LEADER_MASAYA_KID';

INSERT INTO Leader_MajorCivApproachBiases VALUES
('LEADER_MASAYA_KID','MAJOR_CIV_APPROACH_WAR',5),
('LEADER_MASAYA_KID','MAJOR_CIV_APPROACH_HOSTILE',3),
('LEADER_MASAYA_KID','MAJOR_CIV_APPROACH_DECEPTIVE',2),
('LEADER_MASAYA_KID','MAJOR_CIV_APPROACH_GUARDED',4),
('LEADER_MASAYA_KID','MAJOR_CIV_APPROACH_AFRAID',2),
('LEADER_MASAYA_KID','MAJOR_CIV_APPROACH_FRIENDLY',7),
('LEADER_MASAYA_KID','MAJOR_CIV_APPROACH_NEUTRAL',6);
INSERT INTO Leader_MinorCivApproachBiases VALUES
('LEADER_MASAYA_KID','MINOR_CIV_APPROACH_IGNORE',3),
('LEADER_MASAYA_KID','MINOR_CIV_APPROACH_FRIENDLY',7),
('LEADER_MASAYA_KID','MINOR_CIV_APPROACH_PROTECTIVE',6),
('LEADER_MASAYA_KID','MINOR_CIV_APPROACH_CONQUEST',3),
('LEADER_MASAYA_KID','MINOR_CIV_APPROACH_BULLY',2);

CREATE TEMP TABLE MasayaKidCivClone AS SELECT * FROM Civilizations WHERE Type='CIVILIZATION_JAPAN';
UPDATE MasayaKidCivClone SET ID=NULL,Type='CIVILIZATION_MASAYA_KID',
 Description='TXT_KEY_CIV_MASAYA_KID_DESC',ShortDescription='TXT_KEY_CIV_MASAYA_KID_SHORT_DESC',
 Adjective='TXT_KEY_CIV_MASAYA_KID_ADJECTIVE',Civilopedia='TXT_KEY_CIV_MASAYA_KID_PEDIA',
 CivilopediaTag='TXT_KEY_CIV5_MASAYA_KID',Strategy='TXT_KEY_CIV_MASAYA_KID_STRATEGY',
 DefaultPlayerColor='PLAYERCOLOR_MASAYA_KID',Playable=1,AIPlayable=0,PackageID=NULL,
 PortraitIndex=0,IconAtlas='MASAYA_KID_ICON_ATLAS',AlphaIconAtlas='MASAYA_KID_ALPHA_ATLAS',
 MapImage='MasayaMap.dds',DawnOfManImage='MasayaDawn.dds',
 DawnOfManQuote='TXT_KEY_MASAYA_KID_DAWN_OF_MAN',DawnOfManAudio='',SoundtrackTag='JAPAN';
INSERT INTO Civilizations SELECT * FROM MasayaKidCivClone;
DROP TABLE MasayaKidCivClone;

INSERT INTO Civilization_Leaders VALUES ('CIVILIZATION_MASAYA_KID','LEADER_MASAYA_KID');
INSERT INTO Civilization_FreeBuildingClasses SELECT 'CIVILIZATION_MASAYA_KID',BuildingClassType
FROM Civilization_FreeBuildingClasses WHERE CivilizationType='CIVILIZATION_JAPAN';
INSERT INTO Civilization_FreeTechs SELECT 'CIVILIZATION_MASAYA_KID',TechType
FROM Civilization_FreeTechs WHERE CivilizationType='CIVILIZATION_JAPAN';
INSERT INTO Civilization_FreeUnits(CivilizationType,UnitClassType,UnitAIType,Count)
SELECT 'CIVILIZATION_MASAYA_KID',UnitClassType,UnitAIType,Count
FROM Civilization_FreeUnits WHERE CivilizationType='CIVILIZATION_JAPAN';
INSERT INTO Civilization_Start_Along_Ocean VALUES ('CIVILIZATION_MASAYA_KID',1);

CREATE TEMP TABLE MasayaKidUnitClone AS SELECT * FROM Units WHERE Type='UNIT_HORSEMAN';
UPDATE MasayaKidUnitClone SET ID=NULL,Type='UNIT_MASAYA_KID_FC_PRODIGY',
 Description='TXT_KEY_UNIT_MASAYA_KID_FC_PRODIGY',Civilopedia='TXT_KEY_UNIT_MASAYA_KID_FC_PRODIGY_PEDIA',
 Strategy='TXT_KEY_UNIT_MASAYA_KID_FC_PRODIGY_STRATEGY',Help='TXT_KEY_UNIT_MASAYA_KID_FC_PRODIGY_HELP',
 Cost=CAST(((Cost * 1.10 + 2.5) / 5) AS INTEGER) * 5,Combat=12,Moves=5,
 PortraitIndex=1,IconAtlas='MASAYA_KID_OBJECT_ATLAS',
 UnitFlagIconOffset=0,UnitFlagAtlas='MASAYA_KID_UNIT_FLAG_ATLAS';
INSERT INTO Units SELECT * FROM MasayaKidUnitClone;
DROP TABLE MasayaKidUnitClone;
INSERT INTO Civilization_UnitClassOverrides VALUES
('CIVILIZATION_MASAYA_KID','UNITCLASS_HORSEMAN','UNIT_MASAYA_KID_FC_PRODIGY');

CREATE TEMP TABLE MasayaKidBuildingClone AS SELECT * FROM Buildings WHERE Type='BUILDING_BARRACKS';
UPDATE MasayaKidBuildingClone SET ID=NULL,Type='BUILDING_MASAYA_KID_GRAV_ROOM',
 Description='TXT_KEY_BUILDING_MASAYA_KID_GRAV_ROOM',
 Civilopedia='TXT_KEY_BUILDING_MASAYA_KID_GRAV_ROOM_PEDIA',
 Strategy='TXT_KEY_BUILDING_MASAYA_KID_GRAV_ROOM_STRATEGY',
 Help='TXT_KEY_BUILDING_MASAYA_KID_GRAV_ROOM_HELP',PortraitIndex=2,IconAtlas='MASAYA_KID_OBJECT_ATLAS';
INSERT INTO Buildings SELECT * FROM MasayaKidBuildingClone;
DROP TABLE MasayaKidBuildingClone;
INSERT INTO Civilization_BuildingClassOverrides VALUES
('CIVILIZATION_MASAYA_KID','BUILDINGCLASS_BARRACKS','BUILDING_MASAYA_KID_GRAV_ROOM');

INSERT INTO Civilization_CityNames VALUES
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_01'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_02'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_03'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_04'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_05'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_06'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_07'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_08'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_09'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_10'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_11'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_12'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_13'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_14'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_CITY_MASAYA_KID_15');
INSERT INTO Civilization_SpyNames VALUES
('CIVILIZATION_MASAYA_KID','TXT_KEY_SPY_MASAYA_KID_01'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_SPY_MASAYA_KID_02'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_SPY_MASAYA_KID_03'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_SPY_MASAYA_KID_04'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_SPY_MASAYA_KID_05'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_SPY_MASAYA_KID_06'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_SPY_MASAYA_KID_07'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_SPY_MASAYA_KID_08'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_SPY_MASAYA_KID_09'),
('CIVILIZATION_MASAYA_KID','TXT_KEY_SPY_MASAYA_KID_10');
