-- Static pieces of the design.  Thresholds, stateful rewards, and combat-only
-- Natural Prodigy bonuses are applied event-by-event by MasayaRuntime.lua.

INSERT INTO UnitPromotions
(Type,Description,Help,CannotBeChosen,LostWithUpgrade,PortraitIndex,IconAtlas,PediaType,PediaEntry)
VALUES
('PROMOTION_MASAYA_KID_PRODIGY_INHERENT','TXT_KEY_PROMOTION_MASAYA_KID_PRODIGY_INHERENT',
 'TXT_KEY_PROMOTION_MASAYA_KID_PRODIGY_INHERENT_HELP',1,1,1,'MASAYA_KID_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_MASAYA_KID_PRODIGY_INHERENT'),
('PROMOTION_MASAYA_KID_JUST_ONE_MORE_FLIGHT','TXT_KEY_PROMOTION_MASAYA_KID_JUST_ONE_MORE_FLIGHT',
 'TXT_KEY_PROMOTION_MASAYA_KID_JUST_ONE_MORE_FLIGHT_HELP',1,1,6,'MASAYA_KID_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_MASAYA_KID_JUST_ONE_MORE_FLIGHT'),
('PROMOTION_MASAYA_KID_NATURAL_PRODIGY','TXT_KEY_PROMOTION_MASAYA_KID_NATURAL_PRODIGY',
 'TXT_KEY_PROMOTION_MASAYA_KID_NATURAL_PRODIGY_HELP',1,1,7,'MASAYA_KID_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_MASAYA_KID_NATURAL_PRODIGY'),
('PROMOTION_MASAYA_KID_CANT_PUT_THEM_DOWN','TXT_KEY_PROMOTION_MASAYA_KID_CANT_PUT_THEM_DOWN',
 'TXT_KEY_PROMOTION_MASAYA_KID_CANT_PUT_THEM_DOWN_HELP',1,0,8,'MASAYA_KID_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_MASAYA_KID_CANT_PUT_THEM_DOWN'),
('PROMOTION_MASAYA_KID_CANT_PUT_ACTIVE','TXT_KEY_PROMOTION_MASAYA_KID_CANT_PUT_ACTIVE',
 'TXT_KEY_PROMOTION_MASAYA_KID_CANT_PUT_ACTIVE_HELP',1,0,8,'MASAYA_KID_OBJECT_ATLAS',NULL,NULL),
('PROMOTION_MASAYA_KID_CANT_STOP_XP','TXT_KEY_PROMOTION_MASAYA_KID_CANT_STOP',
 'TXT_KEY_PROMOTION_MASAYA_KID_CANT_STOP_HELP',1,0,4,'MASAYA_KID_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_MASAYA_KID_CANT_STOP'),
('PROMOTION_MASAYA_KID_CANT_STOP_MOVE','TXT_KEY_PROMOTION_MASAYA_KID_CANT_STOP_MOVE',
 'TXT_KEY_PROMOTION_MASAYA_KID_CANT_STOP_MOVE_HELP',1,0,4,'MASAYA_KID_OBJECT_ATLAS',NULL,NULL),
('PROMOTION_MASAYA_KID_BEYOND_SKY','TXT_KEY_PROMOTION_MASAYA_KID_BEYOND_SKY',
 'TXT_KEY_PROMOTION_MASAYA_KID_BEYOND_SKY_HELP',1,0,5,'MASAYA_KID_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_MASAYA_KID_BEYOND_SKY'),
('PROMOTION_MASAYA_KID_PRODIGY_ZOC','TXT_KEY_PROMOTION_MASAYA_KID_PRODIGY_ZOC',
 'TXT_KEY_PROMOTION_MASAYA_KID_PRODIGY_ZOC_HELP',1,1,1,'MASAYA_KID_OBJECT_ATLAS',NULL,NULL),
('PROMOTION_MASAYA_KID_NATURAL_XP_15','TXT_KEY_PROMOTION_MASAYA_KID_NATURAL_XP_15',
 'TXT_KEY_PROMOTION_MASAYA_KID_NATURAL_XP_15_HELP',1,1,7,'MASAYA_KID_OBJECT_ATLAS',NULL,NULL),
('PROMOTION_MASAYA_KID_NATURAL_LEVEL_10','TXT_KEY_PROMOTION_MASAYA_KID_NATURAL_LEVEL_10',
 'TXT_KEY_PROMOTION_MASAYA_KID_NATURAL_LEVEL_10_HELP',1,1,7,'MASAYA_KID_OBJECT_ATLAS',NULL,NULL);

-- The inherited Horseman PROMOTION_CITY_PENALTY already supplies CityAttack=-33.
UPDATE UnitPromotions SET IgnoreTerrainCost=1,CanMoveAfterAttacking=1,River=1
WHERE Type='PROMOTION_MASAYA_KID_PRODIGY_INHERENT';
UPDATE UnitPromotions SET MovesChange=1
WHERE Type='PROMOTION_MASAYA_KID_CANT_PUT_ACTIVE';
UPDATE UnitPromotions SET ExperiencePercent=10
WHERE Type='PROMOTION_MASAYA_KID_CANT_STOP_XP';
UPDATE UnitPromotions SET MovesChange=1
WHERE Type='PROMOTION_MASAYA_KID_CANT_STOP_MOVE';
UPDATE UnitPromotions SET MovesChange=1,IgnoreTerrainCost=1,AttackMod=15,ExperiencePercent=50,River=1
WHERE Type='PROMOTION_MASAYA_KID_BEYOND_SKY';
UPDATE UnitPromotions SET IgnoreZOC=1
WHERE Type='PROMOTION_MASAYA_KID_PRODIGY_ZOC';
UPDATE UnitPromotions SET CombatPercent=15
WHERE Type='PROMOTION_MASAYA_KID_NATURAL_XP_15';
UPDATE UnitPromotions SET CombatPercent=10
WHERE Type='PROMOTION_MASAYA_KID_NATURAL_LEVEL_10';

INSERT INTO Unit_FreePromotions(UnitType,PromotionType) VALUES
('UNIT_MASAYA_KID_FC_PRODIGY','PROMOTION_MASAYA_KID_PRODIGY_INHERENT'),
('UNIT_MASAYA_KID_FC_PRODIGY','PROMOTION_MASAYA_KID_JUST_ONE_MORE_FLIGHT'),
('UNIT_MASAYA_KID_FC_PRODIGY','PROMOTION_MASAYA_KID_NATURAL_PRODIGY');

INSERT INTO UnitPromotions_UnitCombats(PromotionType,UnitCombatType,PediaType)
SELECT promotion.Type,combat.Type,'PEDIA_ATTRIBUTES'
FROM UnitPromotions promotion CROSS JOIN UnitCombatInfos combat
WHERE promotion.Type LIKE 'PROMOTION_MASAYA_KID_%';

INSERT INTO Building_YieldChanges(BuildingType,YieldType,Yield) VALUES
('BUILDING_MASAYA_KID_GRAV_ROOM','YIELD_CULTURE',1),
('BUILDING_MASAYA_KID_GRAV_ROOM','YIELD_SCIENCE',1);
