-- English localization and child Masaya diplomacy.

INSERT INTO Language_en_US(Tag,Text) VALUES
('TXT_KEY_CIV_MASAYA_KID_DESC','The Boy Beyond the Sky'),
('TXT_KEY_CIV_MASAYA_KID_SHORT_DESC','Beyond the Sky'),
('TXT_KEY_CIV_MASAYA_KID_ADJECTIVE','Masayan'),
('TXT_KEY_CIV_MASAYA_KID_PEDIA','This civilization remembers Masaya Hinata in childhood, when Flying Circus was still the simplest and most exciting thing in his world. Every open stretch of sky invited another attempt. Practice followed play, discovery followed practice, and mastery grew from the joy of wanting to fly once more.'),
('TXT_KEY_CIV5_MASAYA_KID_HEADING_1','A Higher Tomorrow'),
('TXT_KEY_CIV5_MASAYA_KID_TEXT_1','Before pressure and expectation could give talent a weight of its own, Masaya flew because the next flight sounded fun. His people inherit that generous momentum: they explore, participate, learn, and rise together.'),
('TXT_KEY_CIV_MASAYA_KID_STRATEGY','Keep units moving and participating. Exploration, combat experience, promotions, strong opponents, veteran units, and garrisoned Grav-Shoe Practice Rooms build Joy of Flight. At 50 Joy, land forces learn faster and Recon/Mounted units move farther. Reaching 100 Joy begins six turns of Beyond the Sky. Junior FC Prodigies are exceptionally mobile and thrive against experienced opponents, but remain poor city attackers.'),

('TXT_KEY_LEADER_MASAYA_KID','Masaya Hinata'),
('TXT_KEY_LEADER_MASAYA_KID_PEDIA','As a boy, Masaya Hinata loved Flying Circus without reservation. He wanted to fly, to test his Grav-Shoes, and then to fly again. Talent appeared not as a burden but as the natural result of curiosity repeated with boundless energy. This portrait preserves that bright beginning: an affectionate memory of the child for whom the sky was invitation enough.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_MASAYA_KID_HEADING_1','The Boy Beyond the Sky'),
('TXT_KEY_CIVILOPEDIA_LEADERS_MASAYA_KID_TEXT_1','Young Masaya approached every course as a new possibility. He watched stronger fliers closely, experimented without embarrassment, and returned to practice for the pleasure of another launch. Friends remembered an enthusiasm so complete that even after training he was reluctant to put his Grav-Shoes down.'),

('TXT_KEY_TRAIT_MASAYA_KID_SHORT','I''ll Be the First to Fly Beyond the Sky'),
('TXT_KEY_TRAIT_MASAYA_KID_HELP','Earn Joy of Flight (0-100) from exploration, combat participation, promotions, strong opponents, veteran units, and Grav-Shoe Practice Rooms. At 50 Joy, land military units gain +10% combat XP, Recon/Mounted units gain +1 Movement, and newly trained military units gain +5 XP. At 100 Joy, Beyond the Sky activates for 6 turns: +1 Movement, ignore terrain costs, +15% attack, +50% combat XP, no river-crossing penalty, and promotions heal 25 HP. Joy resets to 25 when it ends.'),

('TXT_KEY_UNIT_MASAYA_KID_FC_PRODIGY','Junior FC Prodigy'),
('TXT_KEY_UNIT_MASAYA_KID_FC_PRODIGY_PEDIA','A Junior FC Prodigy is still a child athlete, but constant joyful practice has already made movement feel instinctive. The unit''s Grav-Shoes carry it lightly across broken ground, and every bout becomes another lesson. Experienced opponents are not a warning to stay away; they are the most interesting people in the sky.'),
('TXT_KEY_UNIT_MASAYA_KID_FC_PRODIGY_STRATEGY','A faster, slightly more expensive Horseman replacement. It ignores terrain costs, may move after attacking, ignores river-crossing penalties, and can slip through enemy Zones of Control while more than 1 Movement remains. It suffers -33% attack strength against Cities. Surviving combat grants +1 extra XP; its first three combats each grant +2 Joy. Against a unit with more XP it gains +15% strength, plus another +10% if that opponent is at least one level higher.'),
('TXT_KEY_UNIT_MASAYA_KID_FC_PRODIGY_HELP','Replaces the Horseman. 12 [ICON_STRENGTH] Combat Strength, 5 [ICON_MOVES] Movement, and approximately 10% higher Production cost. Highly mobile and strongest against veteran units; -33% attack against Cities.'),

('TXT_KEY_BUILDING_MASAYA_KID_GRAV_ROOM','Grav-Shoe Practice Room'),
('TXT_KEY_BUILDING_MASAYA_KID_GRAV_ROOM_PEDIA','The Practice Room is bright, scuffed, and rarely quiet. Young fliers learn to balance, launch, brake, and laugh at the awkward landings in between. Masaya loved his Grav-Shoes so completely that he would even fall asleep while holding them, as though setting them down might make tomorrow''s flight arrive more slowly.'),
('TXT_KEY_BUILDING_MASAYA_KID_GRAV_ROOM_STRATEGY','A Barracks replacement that retains +15 XP for newly trained military units and adds +1 Culture and +1 Science. Every three owner turns that the City remains garrisoned, it grants +1 Joy of Flight. The per-City counter pauses while ungarrisoned. Military units trained here gain Can''t Put Them Down.'),
('TXT_KEY_BUILDING_MASAYA_KID_GRAV_ROOM_HELP','Replaces the Barracks. +15 XP to newly trained military units, +1 [ICON_CULTURE] Culture, and +1 [ICON_RESEARCH] Science. A garrison generates +1 Joy every 3 turns. Trained military units gain Can''t Put Them Down.'),

('TXT_KEY_PROMOTION_MASAYA_KID_PRODIGY_INHERENT','Born to Fly'),
('TXT_KEY_PROMOTION_MASAYA_KID_PRODIGY_INHERENT_HELP','Ignores terrain movement costs and river-crossing attack penalties; may move after attacking; -33% attack strength against Cities. Ignores enemy Zone of Control while more than 1 Movement remains.'),
('TXT_KEY_PROMOTION_MASAYA_KID_JUST_ONE_MORE_FLIGHT','Just One More Flight'),
('TXT_KEY_PROMOTION_MASAYA_KID_JUST_ONE_MORE_FLIGHT_HELP','After surviving combat, gain +1 additional XP. The first three combats in this unit''s lifetime also grant +2 Joy of Flight each.'),
('TXT_KEY_PROMOTION_MASAYA_KID_NATURAL_PRODIGY','Natural Prodigy'),
('TXT_KEY_PROMOTION_MASAYA_KID_NATURAL_PRODIGY_HELP','During combat against a unit with more XP, +15% Combat Strength. If that opponent is also at least one level higher, gain another +10%.'),
('TXT_KEY_PROMOTION_MASAYA_KID_CANT_PUT_THEM_DOWN','Can''t Put Them Down'),
('TXT_KEY_PROMOTION_MASAYA_KID_CANT_PUT_THEM_DOWN_HELP','For this unit''s first 10 turns, +1 Movement and newly revealed tiles grant +1 XP (maximum 5 XP). The first time this unit earns combat XP, gain +2 Joy of Flight. The tracking promotion remains after the Movement bonus expires.'),
('TXT_KEY_PROMOTION_MASAYA_KID_CANT_PUT_ACTIVE','Can''t Put Them Down: Active'),
('TXT_KEY_PROMOTION_MASAYA_KID_CANT_PUT_ACTIVE_HELP','+1 Movement during the first 10 turns after training in a Grav-Shoe Practice Room.'),
('TXT_KEY_PROMOTION_MASAYA_KID_CANT_STOP','Can''t Stop Flying'),
('TXT_KEY_PROMOTION_MASAYA_KID_CANT_STOP_HELP','Joy of Flight is at least 50: +10% XP earned from combat.'),
('TXT_KEY_PROMOTION_MASAYA_KID_CANT_STOP_MOVE','Can''t Stop Flying: Momentum'),
('TXT_KEY_PROMOTION_MASAYA_KID_CANT_STOP_MOVE_HELP','Joy of Flight is at least 50: +1 Movement for Recon and Mounted units.'),
('TXT_KEY_PROMOTION_MASAYA_KID_BEYOND_SKY','Beyond the Sky'),
('TXT_KEY_PROMOTION_MASAYA_KID_BEYOND_SKY_HELP','+1 Movement, ignore terrain movement costs, +15% attack strength, +50% XP earned from combat, and no river-crossing attack penalty.'),
('TXT_KEY_PROMOTION_MASAYA_KID_PRODIGY_ZOC','Flight Path Open'),
('TXT_KEY_PROMOTION_MASAYA_KID_PRODIGY_ZOC_HELP','Ignores enemy Zone of Control while more than 1 Movement remains.'),
('TXT_KEY_PROMOTION_MASAYA_KID_NATURAL_XP_15','Natural Prodigy: Experienced Opponent'),
('TXT_KEY_PROMOTION_MASAYA_KID_NATURAL_XP_15_HELP','+15% Combat Strength against an opponent with more XP.'),
('TXT_KEY_PROMOTION_MASAYA_KID_NATURAL_LEVEL_10','Natural Prodigy: Higher-Level Opponent'),
('TXT_KEY_PROMOTION_MASAYA_KID_NATURAL_LEVEL_10_HELP','Additional +10% Combat Strength against an opponent at least one level higher.'),

('TXT_KEY_MASAYA_KID_DAWN_OF_MAN','Before expectation, before pressure, before anyone called you a prodigy, there was only the sky.[NEWLINE][NEWLINE]You flew because it was fun. You practiced because every landing made you want one more launch. Even when the day ended, your Grav-Shoes never seemed to leave your hands.[NEWLINE][NEWLINE]Now an entire people look upward with that same wonder. Masaya Hinata, how far can joy alone carry them? Will you be the first to fly beyond the sky?'),

('TXT_KEY_MASAYA_KID_NOTIFICATION_JOY','Joy of Flight: +{1_Num} from {2_Text}. ({3_Num}/100)'),
('TXT_KEY_MASAYA_KID_NOTIFICATION_BEYOND','Beyond the Sky begins! Masaya''s land forces take flight for 6 turns.'),
('TXT_KEY_MASAYA_KID_NOTIFICATION_BEYOND_END','Beyond the Sky ends. Joy of Flight returns to 25.'),
('TXT_KEY_MASAYA_KID_SOURCE_EXPLORATION','exploration'),
('TXT_KEY_MASAYA_KID_SOURCE_COMBAT','combat participation'),
('TXT_KEY_MASAYA_KID_SOURCE_PROMOTION','a promotion'),
('TXT_KEY_MASAYA_KID_SOURCE_STRONG','a strong opponent'),
('TXT_KEY_MASAYA_KID_SOURCE_LEVEL_FOUR','reaching Level 4'),
('TXT_KEY_MASAYA_KID_SOURCE_MORE_FLIGHT','Just One More Flight'),
('TXT_KEY_MASAYA_KID_SOURCE_GRAV_ROOM','a garrisoned Practice Room'),
('TXT_KEY_MASAYA_KID_SOURCE_CANT_PUT','Can''t Put Them Down'),

('TXT_KEY_CITY_MASAYA_KID_01','FC Training Grounds'),
('TXT_KEY_CITY_MASAYA_KID_02','Kunahama'),('TXT_KEY_CITY_MASAYA_KID_03','Blue Horizon'),
('TXT_KEY_CITY_MASAYA_KID_04','Sunrise Platform'),('TXT_KEY_CITY_MASAYA_KID_05','Windward Court'),
('TXT_KEY_CITY_MASAYA_KID_06','Skybridge'),('TXT_KEY_CITY_MASAYA_KID_07','Cloudstep'),
('TXT_KEY_CITY_MASAYA_KID_08','First Launch'),('TXT_KEY_CITY_MASAYA_KID_09','Seabreeze Field'),
('TXT_KEY_CITY_MASAYA_KID_10','Brightwater'),('TXT_KEY_CITY_MASAYA_KID_11','Wingtip Bay'),
('TXT_KEY_CITY_MASAYA_KID_12','Tomorrow''s Course'),('TXT_KEY_CITY_MASAYA_KID_13','Updraft Hill'),
('TXT_KEY_CITY_MASAYA_KID_14','Starline'),('TXT_KEY_CITY_MASAYA_KID_15','Farther Sky'),
('TXT_KEY_SPY_MASAYA_KID_01','Asuka'),('TXT_KEY_SPY_MASAYA_KID_02','Misaki'),
('TXT_KEY_SPY_MASAYA_KID_03','Mashiro'),('TXT_KEY_SPY_MASAYA_KID_04','Rika'),
('TXT_KEY_SPY_MASAYA_KID_05','Madoka'),('TXT_KEY_SPY_MASAYA_KID_06','Aoi'),
('TXT_KEY_SPY_MASAYA_KID_07','Sora'),('TXT_KEY_SPY_MASAYA_KID_08','Tsubasa'),
('TXT_KEY_SPY_MASAYA_KID_09','Hikari'),('TXT_KEY_SPY_MASAYA_KID_10','Haruka');

DELETE FROM Diplomacy_Responses WHERE LeaderType='LEADER_MASAYA_KID' AND ResponseType IN
('RESPONSE_FIRST_GREETING','RESPONSE_GREETING_NEUTRAL_HELLO','RESPONSE_GREETING_HOSTILE_HELLO',
 'RESPONSE_DOW_GENERIC','RESPONSE_ATTACKED_HOSTILE','RESPONSE_DEFEATED','RESPONSE_PEACE_OFFER',
 'RESPONSE_TRADE_ACCEPT_ACCEPTABLE','RESPONSE_TRADE_REJECT_UNACCEPTABLE','RESPONSE_RESPONSE_TO_BEING_DENOUNCED');
INSERT INTO Language_en_US(Tag,Text) VALUES
('TXT_KEY_LEADER_MASAYA_KID_FIRSTGREETING_1','Hi! Have you ever flown from somewhere this high? Come on, I''ll show you the best launch point!'),
('TXT_KEY_LEADER_MASAYA_KID_GREETING_NEUTRAL_1','Perfect timing. I was just about to try one more flight.'),
('TXT_KEY_LEADER_MASAYA_KID_GREETING_HOSTILE_1','You don''t look like you came here to enjoy the view.'),
('TXT_KEY_LEADER_MASAYA_KID_DOW_1','If you''re going to hurt my friends, I''ll meet you in the sky.'),
('TXT_KEY_LEADER_MASAYA_KID_ATTACKED_1','All right. I''ll fly higher than anything you can throw at us!'),
('TXT_KEY_LEADER_MASAYA_KID_DEFEATED_1','I couldn''t reach it this time... but the sky will still be there tomorrow.'),
('TXT_KEY_LEADER_MASAYA_KID_PEACE_1','Let''s stop. Flying is better when everyone gets to come home.'),
('TXT_KEY_LEADER_MASAYA_KID_TRADE_ACCEPT_1','That sounds great!'),
('TXT_KEY_LEADER_MASAYA_KID_TRADE_REJECT_1','Hmm... that doesn''t feel fair.'),
('TXT_KEY_LEADER_MASAYA_KID_DENOUNCED_1','You can say that. I''m still going to fly.' );
INSERT INTO Diplomacy_Responses(LeaderType,ResponseType,Response,Bias) VALUES
('LEADER_MASAYA_KID','RESPONSE_FIRST_GREETING','TXT_KEY_LEADER_MASAYA_KID_FIRSTGREETING%',1),
('LEADER_MASAYA_KID','RESPONSE_GREETING_NEUTRAL_HELLO','TXT_KEY_LEADER_MASAYA_KID_GREETING_NEUTRAL%',1),
('LEADER_MASAYA_KID','RESPONSE_GREETING_HOSTILE_HELLO','TXT_KEY_LEADER_MASAYA_KID_GREETING_HOSTILE%',1),
('LEADER_MASAYA_KID','RESPONSE_DOW_GENERIC','TXT_KEY_LEADER_MASAYA_KID_DOW%',1),
('LEADER_MASAYA_KID','RESPONSE_ATTACKED_HOSTILE','TXT_KEY_LEADER_MASAYA_KID_ATTACKED%',1),
('LEADER_MASAYA_KID','RESPONSE_DEFEATED','TXT_KEY_LEADER_MASAYA_KID_DEFEATED%',1),
('LEADER_MASAYA_KID','RESPONSE_PEACE_OFFER','TXT_KEY_LEADER_MASAYA_KID_PEACE%',1),
('LEADER_MASAYA_KID','RESPONSE_TRADE_ACCEPT_ACCEPTABLE','TXT_KEY_LEADER_MASAYA_KID_TRADE_ACCEPT%',1),
('LEADER_MASAYA_KID','RESPONSE_TRADE_REJECT_UNACCEPTABLE','TXT_KEY_LEADER_MASAYA_KID_TRADE_REJECT%',1),
('LEADER_MASAYA_KID','RESPONSE_RESPONSE_TO_BEING_DENOUNCED','TXT_KEY_LEADER_MASAYA_KID_DENOUNCED%',1);
