-- The Eternal Number Ten. Civilization V: Brave New World + Community Patch.
-- Scalar objects are cloned from BNW rows so CP-added columns retain safe defaults.

UPDATE CustomModOptions SET Value = 1 WHERE Name IN
('EVENTS_BATTLES', 'EVENTS_CITY', 'EVENTS_CITY_CAPITAL', 'EVENTS_CITY_FOUNDING',
 'EVENTS_GOLDEN_AGE', 'EVENTS_PLAYER_TURN', 'EVENTS_UNIT_CREATED',
 'EVENTS_UNIT_PREKILL', 'EVENTS_UNIT_UPGRADES');

INSERT INTO Colors(Type,Red,Green,Blue,Alpha) VALUES
('COLOR_MESSI_PRIMARY',0.36,0.72,0.91,1),
('COLOR_MESSI_SECONDARY',0.97,0.82,0.22,1);
INSERT INTO PlayerColors(Type,PrimaryColor,SecondaryColor,TextColor) VALUES
('PLAYERCOLOR_MESSI','COLOR_MESSI_PRIMARY','COLOR_MESSI_SECONDARY','COLOR_PLAYER_WHITE_TEXT');

INSERT INTO IconTextureAtlases(Atlas,IconSize,Filename,IconsPerRow,IconsPerColumn) VALUES
('MESSI_ICON_ATLAS',256,'MessiIcon256.dds',1,1),
('MESSI_ICON_ATLAS',128,'MessiIcon128.dds',1,1),
('MESSI_ICON_ATLAS',80,'MessiIcon80.dds',1,1),
('MESSI_ICON_ATLAS',64,'MessiIcon64.dds',1,1),
('MESSI_ICON_ATLAS',48,'MessiIcon48.dds',1,1),
('MESSI_ICON_ATLAS',45,'MessiIcon45.dds',1,1),
('MESSI_ICON_ATLAS',32,'MessiIcon32.dds',1,1),
('MESSI_ICON_ATLAS',24,'MessiIcon24.dds',1,1),
('MESSI_ICON_ATLAS',16,'MessiIcon16.dds',1,1),
('MESSI_ALPHA_ATLAS',256,'MessiAlpha256.dds',1,1),
('MESSI_ALPHA_ATLAS',128,'MessiAlpha128.dds',1,1),
('MESSI_ALPHA_ATLAS',80,'MessiAlpha80.dds',1,1),
('MESSI_ALPHA_ATLAS',64,'MessiAlpha64.dds',1,1),
('MESSI_ALPHA_ATLAS',48,'MessiAlpha48.dds',1,1),
('MESSI_ALPHA_ATLAS',45,'MessiAlpha45.dds',1,1),
('MESSI_ALPHA_ATLAS',32,'MessiAlpha32.dds',1,1),
('MESSI_ALPHA_ATLAS',24,'MessiAlpha24.dds',1,1),
('MESSI_ALPHA_ATLAS',16,'MessiAlpha16.dds',1,1),
('MESSI_LEADER_ATLAS',256,'MessiLeader256.dds',1,1),
('MESSI_LEADER_ATLAS',128,'MessiLeader128.dds',1,1),
('MESSI_LEADER_ATLAS',64,'MessiLeader64.dds',1,1),
('MESSI_OBJECT_ATLAS',256,'MessiObjects256.dds',7,1),
('MESSI_OBJECT_ATLAS',128,'MessiObjects128.dds',7,1),
('MESSI_OBJECT_ATLAS',80,'MessiObjects80.dds',7,1),
('MESSI_OBJECT_ATLAS',64,'MessiObjects64.dds',7,1),
('MESSI_OBJECT_ATLAS',45,'MessiObjects45.dds',7,1),
('MESSI_OBJECT_ATLAS',32,'MessiObjects32.dds',7,1),
('MESSI_OBJECT_ATLAS',16,'MessiObjects16.dds',7,1),
('MESSI_UNIT_FLAG_ATLAS',32,'MessiUnitFlag32.dds',1,1);

INSERT INTO Traits(Type,Description,ShortDescription) VALUES
('TRAIT_MESSI_IMMORTALITY','TXT_KEY_TRAIT_MESSI_HELP','TXT_KEY_TRAIT_MESSI_SHORT');

CREATE TEMP TABLE MessiLeaderClone AS SELECT * FROM Leaders WHERE Type='LEADER_WASHINGTON';
UPDATE MessiLeaderClone SET ID=NULL,Type='LEADER_LIONEL_MESSI',
 Description='TXT_KEY_LEADER_LIONEL_MESSI',Civilopedia='TXT_KEY_LEADER_LIONEL_MESSI_PEDIA',
 CivilopediaTag='TXT_KEY_CIVILOPEDIA_LEADERS_LIONEL_MESSI',ArtDefineTag='MessiLeaderScene.xml',
 PortraitIndex=0,IconAtlas='MESSI_LEADER_ATLAS',PackageID=NULL,
 VictoryCompetitiveness=8,WonderCompetitiveness=8,MinorCivCompetitiveness=8,
 Boldness=5,DiploBalance=9,WarmongerHate=8,WorkAgainstWillingness=2,WorkWithWillingness=9,
 DenounceWillingness=3,DoFWillingness=9,Loyalty=9,Neediness=4,Forgiveness=8,Chattiness=5,Meanness=2;
INSERT INTO Leaders SELECT * FROM MessiLeaderClone;
DROP TABLE MessiLeaderClone;
INSERT INTO Leader_Traits VALUES ('LEADER_LIONEL_MESSI','TRAIT_MESSI_IMMORTALITY');

CREATE TEMP TABLE MessiCivClone AS SELECT * FROM Civilizations WHERE Type='CIVILIZATION_AMERICA';
UPDATE MessiCivClone SET ID=NULL,Type='CIVILIZATION_ETERNAL_NUMBER_TEN',
 Description='TXT_KEY_CIV_MESSI_DESC',ShortDescription='TXT_KEY_CIV_MESSI_SHORT_DESC',
 Adjective='TXT_KEY_CIV_MESSI_ADJECTIVE',Civilopedia='TXT_KEY_CIV_MESSI_PEDIA',
 CivilopediaTag='TXT_KEY_CIV5_MESSI',Strategy='TXT_KEY_CIV_MESSI_STRATEGY',
 DefaultPlayerColor='PLAYERCOLOR_MESSI',Playable=1,AIPlayable=1,PackageID=NULL,
 PortraitIndex=0,IconAtlas='MESSI_ICON_ATLAS',AlphaIconAtlas='MESSI_ALPHA_ATLAS',
 MapImage='MessiMap.dds',DawnOfManImage='MessiDawn.dds',
 DawnOfManQuote='TXT_KEY_MESSI_DAWN_OF_MAN',DawnOfManAudio='',SoundtrackTag='BRAZIL',
 ArtDefineTag='ART_DEF_CIVILIZATION_BRAZIL',ArtStyleType='ARTSTYLE_EUROPEAN',
 ArtStyleSuffix='_EURO',ArtStylePrefix='EUROPEAN ';
INSERT INTO Civilizations SELECT * FROM MessiCivClone;
DROP TABLE MessiCivClone;

INSERT INTO Civilization_Leaders VALUES ('CIVILIZATION_ETERNAL_NUMBER_TEN','LEADER_LIONEL_MESSI');
INSERT INTO Civilization_FreeBuildingClasses SELECT 'CIVILIZATION_ETERNAL_NUMBER_TEN',BuildingClassType
 FROM Civilization_FreeBuildingClasses WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_FreeTechs SELECT 'CIVILIZATION_ETERNAL_NUMBER_TEN',TechType
 FROM Civilization_FreeTechs WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_FreeUnits(CivilizationType,UnitClassType,UnitAIType,Count)
 SELECT 'CIVILIZATION_ETERNAL_NUMBER_TEN',UnitClassType,UnitAIType,Count
 FROM Civilization_FreeUnits WHERE CivilizationType='CIVILIZATION_AMERICA';

CREATE TEMP TABLE MessiUnitClone AS SELECT * FROM Units WHERE Type='UNIT_GREAT_GENERAL';
UPDATE MessiUnitClone SET ID=NULL,Type='UNIT_MESSI_NUMBER_TEN',
 Description='TXT_KEY_UNIT_MESSI_NUMBER_TEN',Civilopedia='TXT_KEY_UNIT_MESSI_NUMBER_TEN_PEDIA',
 Strategy='TXT_KEY_UNIT_MESSI_NUMBER_TEN_STRATEGY',Help='TXT_KEY_UNIT_MESSI_NUMBER_TEN_HELP',
 Moves=2,PortraitIndex=0,IconAtlas='MESSI_OBJECT_ATLAS',
 UnitFlagIconOffset=0,UnitFlagAtlas='MESSI_UNIT_FLAG_ATLAS';
INSERT INTO Units SELECT * FROM MessiUnitClone;
DROP TABLE MessiUnitClone;
INSERT INTO Civilization_UnitClassOverrides VALUES
('CIVILIZATION_ETERNAL_NUMBER_TEN','UNITCLASS_GREAT_GENERAL','UNIT_MESSI_NUMBER_TEN');

CREATE TEMP TABLE MessiBuildingClone AS SELECT * FROM Buildings WHERE Type='BUILDING_GARDEN';
UPDATE MessiBuildingClone SET ID=NULL,Type='BUILDING_MESSI_LA_MASIA',
 Description='TXT_KEY_BUILDING_MESSI_LA_MASIA',Civilopedia='TXT_KEY_BUILDING_MESSI_LA_MASIA_PEDIA',
 Strategy='TXT_KEY_BUILDING_MESSI_LA_MASIA_STRATEGY',Help='TXT_KEY_BUILDING_MESSI_LA_MASIA_HELP',
 Cost=135,PrereqTech='TECH_THEOLOGY',FreshWater=0,GreatPeopleRateModifier=15,
 PortraitIndex=1,IconAtlas='MESSI_OBJECT_ATLAS';
INSERT INTO Buildings SELECT * FROM MessiBuildingClone;
DROP TABLE MessiBuildingClone;
INSERT INTO Civilization_BuildingClassOverrides VALUES
('CIVILIZATION_ETERNAL_NUMBER_TEN','BUILDINGCLASS_GARDEN','BUILDING_MESSI_LA_MASIA');

CREATE TEMP TABLE MessiImprovementClone AS SELECT * FROM Improvements WHERE Type='IMPROVEMENT_CITADEL';
UPDATE MessiImprovementClone SET ID=NULL,Type='IMPROVEMENT_MESSI_FOOTBALL_ACADEMY',
 Description='TXT_KEY_IMPROVEMENT_MESSI_FOOTBALL_ACADEMY',
 Civilopedia='TXT_KEY_IMPROVEMENT_MESSI_FOOTBALL_ACADEMY_PEDIA',
 Help='TXT_KEY_IMPROVEMENT_MESSI_FOOTBALL_ACADEMY_HELP',
 NearbyEnemyDamage=0,DefenseModifier=10,PortraitIndex=2,IconAtlas='MESSI_OBJECT_ATLAS';
INSERT INTO Improvements SELECT * FROM MessiImprovementClone;
DROP TABLE MessiImprovementClone;

CREATE TEMP TABLE MessiBuildClone AS SELECT * FROM Builds WHERE Type='BUILD_CITADEL';
UPDATE MessiBuildClone SET ID=NULL,Type='BUILD_MESSI_FOOTBALL_ACADEMY',
 Description='TXT_KEY_BUILD_MESSI_FOOTBALL_ACADEMY',
 Help='TXT_KEY_BUILD_MESSI_FOOTBALL_ACADEMY_HELP',
 ImprovementType='IMPROVEMENT_MESSI_FOOTBALL_ACADEMY',
 IconIndex=2,IconAtlas='MESSI_OBJECT_ATLAS';
INSERT INTO Builds SELECT * FROM MessiBuildClone;
DROP TABLE MessiBuildClone;

INSERT INTO UnitPromotions
(Type,Description,Help,CannotBeChosen,LostWithUpgrade,PortraitIndex,IconAtlas,PediaType,PediaEntry) VALUES
('PROMOTION_MESSI_NUMBER_TEN_MOBILITY','TXT_KEY_PROMOTION_MESSI_NUMBER_TEN_MOBILITY','TXT_KEY_PROMOTION_MESSI_NUMBER_TEN_MOBILITY_HELP',1,0,0,'MESSI_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_MESSI_NUMBER_TEN_MOBILITY'),
('PROMOTION_MESSI_ONE_TWO','TXT_KEY_PROMOTION_MESSI_ONE_TWO','TXT_KEY_PROMOTION_MESSI_ONE_TWO_HELP',1,1,4,'MESSI_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_MESSI_ONE_TWO'),
('PROMOTION_MESSI_ONE_TWO_CHAPTER_3','TXT_KEY_PROMOTION_MESSI_ONE_TWO','TXT_KEY_PROMOTION_MESSI_ONE_TWO_CHAPTER_3_HELP',1,1,4,'MESSI_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_MESSI_ONE_TWO'),
('PROMOTION_MESSI_VISION','TXT_KEY_PROMOTION_MESSI_VISION','TXT_KEY_PROMOTION_MESSI_VISION_HELP',1,1,0,'MESSI_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_MESSI_VISION'),
('PROMOTION_MESSI_CAPITAL_VISION','TXT_KEY_PROMOTION_MESSI_CAPITAL_VISION','TXT_KEY_PROMOTION_MESSI_CAPITAL_VISION_HELP',1,0,3,'MESSI_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_MESSI_CAPITAL_VISION'),
('PROMOTION_MESSI_RESILIENCE','TXT_KEY_PROMOTION_MESSI_RESILIENCE','TXT_KEY_PROMOTION_MESSI_RESILIENCE_HELP',1,1,5,'MESSI_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_MESSI_RESILIENCE');
UPDATE UnitPromotions SET IgnoreTerrainCost=1,IgnoreZOC=1
 WHERE Type='PROMOTION_MESSI_NUMBER_TEN_MOBILITY';
UPDATE UnitPromotions SET MovesChange=1,CombatPercent=5,FlankAttackModifier=10
 WHERE Type='PROMOTION_MESSI_ONE_TWO';
UPDATE UnitPromotions SET CombatPercent=3 WHERE Type='PROMOTION_MESSI_ONE_TWO_CHAPTER_3';
UPDATE UnitPromotions SET MovesChange=1,IgnoreZOC=1,FlankAttackModifier=6
 WHERE Type='PROMOTION_MESSI_VISION';
UPDATE UnitPromotions SET VisibilityChange=1 WHERE Type='PROMOTION_MESSI_CAPITAL_VISION';
UPDATE UnitPromotions SET DefenseMod=6,FriendlyHealChange=15
 WHERE Type='PROMOTION_MESSI_RESILIENCE';

INSERT INTO Unit_FreePromotions(UnitType,PromotionType) VALUES
('UNIT_MESSI_NUMBER_TEN','PROMOTION_MESSI_NUMBER_TEN_MOBILITY');

DELETE FROM Improvement_Yields WHERE ImprovementType='IMPROVEMENT_MESSI_FOOTBALL_ACADEMY';
INSERT INTO Improvement_Yields(ImprovementType,YieldType,Yield) VALUES
('IMPROVEMENT_MESSI_FOOTBALL_ACADEMY','YIELD_CULTURE',1),
('IMPROVEMENT_MESSI_FOOTBALL_ACADEMY','YIELD_SCIENCE',1);
INSERT INTO Improvement_TechYieldChanges(ImprovementType,TechType,YieldType,Yield) VALUES
('IMPROVEMENT_MESSI_FOOTBALL_ACADEMY','TECH_FLIGHT','YIELD_TOURISM',1);
