-- Career Chapters, exact CP policy effects, runtime dummy buildings, AI, and names.

INSERT INTO Policies
(Type,Description,Civilopedia,Help,PolicyBranchType,CultureCost,GridX,GridY,PortraitIndex,IconAtlas,IsDummy) VALUES
('POLICY_MESSI_CHAPTER_1','TXT_KEY_MESSI_CHAPTER_1_TITLE','TXT_KEY_MESSI_CHAPTER_1_STORY','TXT_KEY_MESSI_CHAPTER_1_EFFECTS',NULL,-1,-1,-1,3,'MESSI_OBJECT_ATLAS',1),
('POLICY_MESSI_CHAPTER_2','TXT_KEY_MESSI_CHAPTER_2_TITLE','TXT_KEY_MESSI_CHAPTER_2_STORY','TXT_KEY_MESSI_CHAPTER_2_EFFECTS',NULL,-1,-1,-1,3,'MESSI_OBJECT_ATLAS',1),
('POLICY_MESSI_CHAPTER_3','TXT_KEY_MESSI_CHAPTER_3_TITLE','TXT_KEY_MESSI_CHAPTER_3_STORY','TXT_KEY_MESSI_CHAPTER_3_EFFECTS',NULL,-1,-1,-1,3,'MESSI_OBJECT_ATLAS',1),
('POLICY_MESSI_CHAPTER_4','TXT_KEY_MESSI_CHAPTER_4_TITLE','TXT_KEY_MESSI_CHAPTER_4_STORY','TXT_KEY_MESSI_CHAPTER_4_EFFECTS',NULL,-1,-1,-1,3,'MESSI_OBJECT_ATLAS',1),
('POLICY_MESSI_CHAPTER_5','TXT_KEY_MESSI_CHAPTER_5_TITLE','TXT_KEY_MESSI_CHAPTER_5_STORY','TXT_KEY_MESSI_CHAPTER_5_EFFECTS',NULL,-1,-1,-1,3,'MESSI_OBJECT_ATLAS',1),
('POLICY_MESSI_CHAPTER_6','TXT_KEY_MESSI_CHAPTER_6_TITLE','TXT_KEY_MESSI_CHAPTER_6_STORY','TXT_KEY_MESSI_CHAPTER_6_EFFECTS',NULL,-1,-1,-1,6,'MESSI_OBJECT_ATLAS',1),
('POLICY_MESSI_EPILOGUE_1','TXT_KEY_MESSI_EPILOGUE_TITLE','TXT_KEY_MESSI_EPILOGUE_STORY','TXT_KEY_MESSI_EPILOGUE_EFFECTS',NULL,-1,-1,-1,6,'MESSI_OBJECT_ATLAS',1),
('POLICY_MESSI_EPILOGUE_2','TXT_KEY_MESSI_EPILOGUE_TITLE','TXT_KEY_MESSI_EPILOGUE_STORY','TXT_KEY_MESSI_EPILOGUE_EFFECTS',NULL,-1,-1,-1,6,'MESSI_OBJECT_ATLAS',1),
('POLICY_MESSI_EPILOGUE_3','TXT_KEY_MESSI_EPILOGUE_TITLE','TXT_KEY_MESSI_EPILOGUE_STORY','TXT_KEY_MESSI_EPILOGUE_EFFECTS',NULL,-1,-1,-1,6,'MESSI_OBJECT_ATLAS',1),
('POLICY_MESSI_EPILOGUE_4','TXT_KEY_MESSI_EPILOGUE_TITLE','TXT_KEY_MESSI_EPILOGUE_STORY','TXT_KEY_MESSI_EPILOGUE_EFFECTS',NULL,-1,-1,-1,6,'MESSI_OBJECT_ATLAS',1),
('POLICY_MESSI_EPILOGUE_5','TXT_KEY_MESSI_EPILOGUE_TITLE','TXT_KEY_MESSI_EPILOGUE_STORY','TXT_KEY_MESSI_EPILOGUE_EFFECTS',NULL,-1,-1,-1,6,'MESSI_OBJECT_ATLAS',1),
('POLICY_MESSI_EPILOGUE_6','TXT_KEY_MESSI_EPILOGUE_TITLE','TXT_KEY_MESSI_EPILOGUE_STORY','TXT_KEY_MESSI_EPILOGUE_EFFECTS',NULL,-1,-1,-1,6,'MESSI_OBJECT_ATLAS',1);

UPDATE Policies SET GreatPeopleRateModifier=6 WHERE Type='POLICY_MESSI_CHAPTER_2';
UPDATE Policies SET GoldenAgeDurationMod=10 WHERE Type='POLICY_MESSI_CHAPTER_3';
UPDATE Policies SET MinorQuestFriendshipMod=10,GreatGeneralExtraBonus=2
 WHERE Type='POLICY_MESSI_CHAPTER_5';
INSERT INTO Policy_CapitalYieldChanges(PolicyType,YieldType,Yield) VALUES
('POLICY_MESSI_CHAPTER_1','YIELD_FOOD',1),
('POLICY_MESSI_CHAPTER_1','YIELD_PRODUCTION',1);
INSERT INTO Policy_GoldenAgeYieldMod(PolicyType,YieldType,Yield) VALUES
('POLICY_MESSI_CHAPTER_6','YIELD_TOURISM',6),
('POLICY_MESSI_CHAPTER_6','YIELD_SCIENCE',6);
INSERT INTO Policy_GreatWorkYieldChanges(PolicyType,YieldType,Yield) VALUES
('POLICY_MESSI_CHAPTER_6','YIELD_CULTURE',1);
INSERT INTO Policy_YieldModifiers(PolicyType,YieldType,Yield) VALUES
('POLICY_MESSI_EPILOGUE_1','YIELD_TOURISM',1),
('POLICY_MESSI_EPILOGUE_2','YIELD_TOURISM',1),
('POLICY_MESSI_EPILOGUE_3','YIELD_TOURISM',1),
('POLICY_MESSI_EPILOGUE_4','YIELD_TOURISM',1),
('POLICY_MESSI_EPILOGUE_5','YIELD_TOURISM',1),
('POLICY_MESSI_EPILOGUE_6','YIELD_TOURISM',1);

INSERT INTO BuildingClasses(Type,DefaultBuilding,Description) VALUES
('BUILDINGCLASS_MESSI_CAPITAL_SPECIALIST_SCIENCE','BUILDING_MESSI_CAPITAL_SPECIALIST_SCIENCE','TXT_KEY_BUILDING_MESSI_DUMMY'),
('BUILDINGCLASS_MESSI_LA_MASIA_SPECIALIST_FOOD','BUILDING_MESSI_LA_MASIA_SPECIALIST_FOOD','TXT_KEY_BUILDING_MESSI_DUMMY'),
('BUILDINGCLASS_MESSI_LA_MASIA_PRODUCTION','BUILDING_MESSI_LA_MASIA_PRODUCTION','TXT_KEY_BUILDING_MESSI_DUMMY'),
('BUILDINGCLASS_MESSI_WORLD_WONDER_CULTURE','BUILDING_MESSI_WORLD_WONDER_CULTURE','TXT_KEY_BUILDING_MESSI_DUMMY'),
('BUILDINGCLASS_MESSI_RESILIENCE_PRODUCTION','BUILDING_MESSI_RESILIENCE_PRODUCTION','TXT_KEY_BUILDING_MESSI_DUMMY'),
('BUILDINGCLASS_MESSI_ALLIED_CITY_STATE','BUILDING_MESSI_ALLIED_CITY_STATE','TXT_KEY_BUILDING_MESSI_DUMMY'),
('BUILDINGCLASS_MESSI_ACADEMY_GOLD','BUILDING_MESSI_ACADEMY_GOLD','TXT_KEY_BUILDING_MESSI_DUMMY');

INSERT INTO Buildings
(Type,BuildingClass,Description,Cost,FaithCost,GreatWorkCount,NeverCapture,NukeImmune,ConquestProb,IsDummy,ShowInPedia) VALUES
('BUILDING_MESSI_CAPITAL_SPECIALIST_SCIENCE','BUILDINGCLASS_MESSI_CAPITAL_SPECIALIST_SCIENCE','TXT_KEY_BUILDING_MESSI_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_MESSI_LA_MASIA_SPECIALIST_FOOD','BUILDINGCLASS_MESSI_LA_MASIA_SPECIALIST_FOOD','TXT_KEY_BUILDING_MESSI_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_MESSI_LA_MASIA_PRODUCTION','BUILDINGCLASS_MESSI_LA_MASIA_PRODUCTION','TXT_KEY_BUILDING_MESSI_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_MESSI_WORLD_WONDER_CULTURE','BUILDINGCLASS_MESSI_WORLD_WONDER_CULTURE','TXT_KEY_BUILDING_MESSI_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_MESSI_RESILIENCE_PRODUCTION','BUILDINGCLASS_MESSI_RESILIENCE_PRODUCTION','TXT_KEY_BUILDING_MESSI_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_MESSI_ALLIED_CITY_STATE','BUILDINGCLASS_MESSI_ALLIED_CITY_STATE','TXT_KEY_BUILDING_MESSI_DUMMY',-1,-1,-1,1,1,0,1,0),
('BUILDING_MESSI_ACADEMY_GOLD','BUILDINGCLASS_MESSI_ACADEMY_GOLD','TXT_KEY_BUILDING_MESSI_DUMMY',-1,-1,-1,1,1,0,1,0);

INSERT INTO Building_YieldChanges(BuildingType,YieldType,Yield) VALUES
('BUILDING_MESSI_CAPITAL_SPECIALIST_SCIENCE','YIELD_SCIENCE',1),
('BUILDING_MESSI_LA_MASIA_SPECIALIST_FOOD','YIELD_FOOD',1),
('BUILDING_MESSI_WORLD_WONDER_CULTURE','YIELD_CULTURE',1),
('BUILDING_MESSI_ALLIED_CITY_STATE','YIELD_CULTURE',1),
('BUILDING_MESSI_ACADEMY_GOLD','YIELD_GOLD',1);
INSERT INTO Building_YieldModifiers(BuildingType,YieldType,Yield) VALUES
('BUILDING_MESSI_LA_MASIA_PRODUCTION','YIELD_PRODUCTION',5),
('BUILDING_MESSI_RESILIENCE_PRODUCTION','YIELD_PRODUCTION',6);
UPDATE Buildings SET Happiness=1 WHERE Type='BUILDING_MESSI_ALLIED_CITY_STATE';

INSERT INTO Leader_Flavors(LeaderType,FlavorType,Flavor)
SELECT 'LEADER_LIONEL_MESSI',Type,CASE Type
 WHEN 'FLAVOR_CULTURE' THEN 9 WHEN 'FLAVOR_GREAT_PEOPLE' THEN 10 WHEN 'FLAVOR_WONDER' THEN 8
 WHEN 'FLAVOR_DIPLOMACY' THEN 8 WHEN 'FLAVOR_SCIENCE' THEN 7 WHEN 'FLAVOR_GROWTH' THEN 7
 WHEN 'FLAVOR_OFFENSE' THEN 4 WHEN 'FLAVOR_DEFENSE' THEN 7 ELSE 5 END FROM Flavors;
INSERT INTO Leader_MajorCivApproachBiases(LeaderType,MajorCivApproachType,Bias)
SELECT 'LEADER_LIONEL_MESSI',MajorCivApproachType,CASE MajorCivApproachType
 WHEN 'MAJOR_CIV_APPROACH_WAR' THEN 3 WHEN 'MAJOR_CIV_APPROACH_HOSTILE' THEN 2
 WHEN 'MAJOR_CIV_APPROACH_DECEPTIVE' THEN 1 WHEN 'MAJOR_CIV_APPROACH_GUARDED' THEN 4
 WHEN 'MAJOR_CIV_APPROACH_AFRAID' THEN 3 WHEN 'MAJOR_CIV_APPROACH_FRIENDLY' THEN 9 ELSE 8 END
 FROM Leader_MajorCivApproachBiases WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Leader_MinorCivApproachBiases(LeaderType,MinorCivApproachType,Bias)
SELECT 'LEADER_LIONEL_MESSI',MinorCivApproachType,8
 FROM Leader_MinorCivApproachBiases WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Diplomacy_Responses(LeaderType,ResponseType,Response,Bias)
SELECT 'LEADER_LIONEL_MESSI',ResponseType,Response,Bias
 FROM Diplomacy_Responses WHERE LeaderType='LEADER_WASHINGTON';

INSERT INTO Civilization_CityNames(CivilizationType,CityName) VALUES
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_1'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_2'),
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_3'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_4'),
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_5'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_6'),
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_7'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_8'),
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_9'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_10'),
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_11'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_12'),
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_13'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_14'),
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_15'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_16'),
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_17'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_18'),
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_19'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_CITY_MESSI_20');

INSERT INTO Civilization_SpyNames(CivilizationType,SpyName) VALUES
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_SPY_MESSI_1'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_SPY_MESSI_2'),
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_SPY_MESSI_3'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_SPY_MESSI_4'),
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_SPY_MESSI_5'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_SPY_MESSI_6'),
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_SPY_MESSI_7'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_SPY_MESSI_8'),
('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_SPY_MESSI_9'),('CIVILIZATION_ETERNAL_NUMBER_TEN','TXT_KEY_SPY_MESSI_10');
