-- English localization for The Eternal Number Ten.

INSERT INTO Language_en_US(Tag,Text) VALUES
('TXT_KEY_CIV_MESSI_DESC','The Eternal Number Ten'),
('TXT_KEY_CIV_MESSI_SHORT_DESC','Eternal Number Ten'),
('TXT_KEY_CIV_MESSI_ADJECTIVE','Rosarino'),
('TXT_KEY_CIV_MESSI_PEDIA','The Eternal Number Ten begins modestly and builds a career through Legacy. Great People, Wonders, Golden Ages, City-State alliances, quests, and coordinated Assists unlock six permanent Career Chapters, from A Ball and a Dream to The Third Star.'),
('TXT_KEY_CIV5_MESSI_HEADING_1','From Rosario to Immortality'),
('TXT_KEY_CIV5_MESSI_TEXT_1','A child''s impossible dream becomes a civilization''s long pursuit of excellence. Compact formations, specialist development, loyalty, resilience, and patient diplomacy turn promise into an enduring Legacy.'),
('TXT_KEY_CIV_MESSI_STRATEGY','Build Legacy through Great People, Wonders, first-in-era Golden Ages and City-State alliances, Assists, and later City-State quests. Keep military units in compact Passing Triangles, support them with The Number Ten, and develop La Masia cities. Legacy can accumulate before an era gate, so time each Career Chapter around the civilization''s cultural and diplomatic ascent.'),
('TXT_KEY_LEADER_LIONEL_MESSI','Lionel Messi'),
('TXT_KEY_LEADER_LIONEL_MESSI_PEDIA','Lionel Messi, the Little Boy from Rosario, leads through quiet example rather than spectacle. His career is represented by six permanent chapters earned through Legacy, beginning with fragile promise and culminating in the third star.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_LIONEL_MESSI_HEADING_1','The Little Boy from Rosario'),
('TXT_KEY_CIVILOPEDIA_LEADERS_LIONEL_MESSI_TEXT_1','Small in stature and immense in possibility, the boy from Rosario learned to combine individual brilliance with collective movement. His civilization rewards the same pattern: patient development, close support, and decisive action when space finally appears.'),
('TXT_KEY_MESSI_DAWN_OF_MAN','Before the stadiums, the trophies, and the number ten, there was a small boy chasing a ball through Rosario. Build his Legacy, write each chapter, and lead the Eternal Number Ten from a fragile dream to immortality.'),

('TXT_KEY_TRAIT_MESSI_SHORT','From Rosario to Immortality'),
('TXT_KEY_TRAIT_MESSI_HELP','Earn persistent Legacy from Great People (+2), World Wonders (+4), the first City-State alliance and Golden Age each Era (+3), Assists (+1), and later City-State quests. Legacy unlocks six permanent Career Chapters at 25/55/90/130/180/240, subject to Era gates. Land combat units beginning a turn beside two friendly combat units gain One-Two Football: +1 Movement, +5% Combat Strength, and +10% Flanking Bonus for that turn.'),

('TXT_KEY_UNIT_MESSI_NUMBER_TEN','The Number Ten'),
('TXT_KEY_UNIT_MESSI_NUMBER_TEN_PEDIA','The Number Ten replaces the Great General. It moves two tiles, ignores terrain movement costs and enemy Zones of Control, retains the Citadel action, and may instead expend itself to construct a Football Academy.'),
('TXT_KEY_UNIT_MESSI_NUMBER_TEN_STRATEGY','Keep The Number Ten adjacent to a compact group of combat units. At the start of the turn those units gain Vision Beyond the Defence, which combines with Passing Triangles. Build a Football Academy when a permanent cultural, scientific, and defensive foothold is more valuable than the moving aura.'),
('TXT_KEY_UNIT_MESSI_NUMBER_TEN_HELP','Great General replacement. 2 Movement; ignores terrain cost and enemy Zones of Control. Adjacent friendly combat units gain +1 Movement, ignore enemy Zones of Control, and +6% Flanking Bonus for the turn; assisted killers heal 5 HP. May build either a Citadel or Football Academy.'),
('TXT_KEY_BUILDING_MESSI_LA_MASIA','La Masia'),
('TXT_KEY_BUILDING_MESSI_LA_MASIA_PEDIA','La Masia replaces the Garden at Theology. It needs no Fresh Water, costs 135 Production, supplies +15% Great Person generation and +1 Culture, and feeds specialists through careful development.'),
('TXT_KEY_BUILDING_MESSI_LA_MASIA_STRATEGY','Build La Masia in specialist cities. It produces +1 Food for every two assigned Specialists. Whenever a Great Person is born here the city celebrates for one turn, adds one extra Legacy, and refreshes a six-turn +5% Production bonus.'),
('TXT_KEY_BUILDING_MESSI_LA_MASIA_HELP','Garden replacement available at Theology. No Fresh Water requirement. +15% [ICON_GREAT_PEOPLE] Great Person generation and +1 [ICON_CULTURE] Culture. +1 [ICON_FOOD] Food for every two Specialists. Great Person births grant 1 turn of We Love the King Day, +1 additional Legacy, and +5% [ICON_PRODUCTION] Production for 6 turns.'),
('TXT_KEY_BUILDING_MESSI_DUMMY','Eternal Number Ten effect'),
('TXT_KEY_IMPROVEMENT_MESSI_FOOTBALL_ACADEMY','Football Academy'),
('TXT_KEY_IMPROVEMENT_MESSI_FOOTBALL_ACADEMY_PEDIA','A Football Academy is a Great Person improvement constructed by The Number Ten as an alternative to a Citadel. It claims nearby unowned land without damaging adjacent enemies.'),
('TXT_KEY_IMPROVEMENT_MESSI_FOOTBALL_ACADEMY_HELP','Claims its tile and adjacent unowned tiles. +1 [ICON_CULTURE] Culture and +1 [ICON_RESEARCH] Science; +1 [ICON_TOURISM] Tourism after Flight. +10% Defense for a stationed unit. Nearby worked tiles can add Gold to a specialist-developed city. Does not damage adjacent enemies.'),
('TXT_KEY_BUILD_MESSI_FOOTBALL_ACADEMY','Construct a Football Academy'),
('TXT_KEY_BUILD_MESSI_FOOTBALL_ACADEMY_HELP','Expend The Number Ten to construct a Football Academy. The normal Citadel action remains available.'),

('TXT_KEY_PROMOTION_MESSI_NUMBER_TEN_MOBILITY','The Number Ten'),
('TXT_KEY_PROMOTION_MESSI_NUMBER_TEN_MOBILITY_HELP','Ignores terrain movement costs and enemy Zones of Control.'),
('TXT_KEY_PROMOTION_MESSI_ONE_TWO','One-Two Football'),
('TXT_KEY_PROMOTION_MESSI_ONE_TWO_HELP','+1 Movement, +5% Combat Strength, and +10% Flanking Bonus this turn from beginning beside at least two friendly combat units.'),
('TXT_KEY_PROMOTION_MESSI_ONE_TWO_CHAPTER_3_HELP','The Golden Years adds +3% Combat Strength to One-Two Football.'),
('TXT_KEY_PROMOTION_MESSI_VISION','Vision Beyond the Defence'),
('TXT_KEY_PROMOTION_MESSI_VISION_HELP','+1 Movement, ignores enemy Zones of Control, and +6% Flanking Bonus this turn from beginning beside The Number Ten.'),
('TXT_KEY_PROMOTION_MESSI_CAPITAL_VISION','A Ball and a Dream'),
('TXT_KEY_PROMOTION_MESSI_CAPITAL_VISION_HELP','+1 Sight from training in Rosario after Chapter I.'),
('TXT_KEY_PROMOTION_MESSI_RESILIENCE','Resilience'),
('TXT_KEY_PROMOTION_MESSI_RESILIENCE_HELP','+6% Defensive Combat Strength and +15% healing in friendly territory while Resilience is active.'),

('TXT_KEY_MESSI_CHAPTER_1_TITLE','Chapter I — A Ball and a Dream'),
('TXT_KEY_MESSI_CHAPTER_1_EFFECTS','25 Legacy. Capital: +1 Food and +1 Production. Newly founded cities begin with +10 Food. Scouts and civilian units trained in the Capital gain +1 Sight.'),
('TXT_KEY_MESSI_CHAPTER_1_STORY','Before the stadiums, the trophies and the number ten, there was a small boy chasing a ball through Rosario.[NEWLINE][NEWLINE]Lionel was smaller than many of the children around him, yet with the ball at his feet those differences seemed to disappear. From Grandoli to Newell''s Old Boys, his talent became increasingly difficult to ignore.[NEWLINE][NEWLINE]His greatest obstacle was not a defender, but his own physical development. His family searched for a way forward, believing that somewhere there must be a place willing to invest in the potential hidden within him.[NEWLINE][NEWLINE]For now, he was simply a child with a ball, a loving family, and an impossible dream.[NEWLINE][NEWLINE]“The child may be small, but the dream growing inside him has no limits.”'),
('TXT_KEY_MESSI_CHAPTER_2_TITLE','Chapter II — The Napkin Contract'),
('TXT_KEY_MESSI_CHAPTER_2_EFFECTS','55 Legacy; Classical Era. +6% Great Person generation empire-wide. Theology grants a free La Masia in the Capital. Capital Specialists provide +1 Science each.'),
('TXT_KEY_MESSI_CHAPTER_2_STORY','Talent alone was not enough. Someone had to believe in it.[NEWLINE][NEWLINE]At thirteen years old, Lionel left Argentina and travelled across the ocean for an opportunity in Barcelona. Far from Rosario, his future remained uncertain.[NEWLINE][NEWLINE]Then came a commitment that would become part of football history: a promise hurriedly written on a napkin. Barcelona would give the boy his chance.[NEWLINE][NEWLINE]At La Masia, his natural ability became part of something larger. He learned positional movement, combination play, timing, patience and how individual brilliance could exist inside a collective system.[NEWLINE][NEWLINE]The boy from Rosario had found another home.[NEWLINE][NEWLINE]“A future that appeared too uncertain for a contract was secured by a promise written on a napkin.”'),
('TXT_KEY_MESSI_CHAPTER_3_TITLE','Chapter III — The Golden Years'),
('TXT_KEY_MESSI_CHAPTER_3_EFFECTS','90 Legacy; Renaissance Era. Golden Ages last +10% longer. Assist Culture and Golden Age Point rewards are +15%. One-Two Football gains +3% Combat Strength. World Wonders provide +1 Culture.'),
('TXT_KEY_MESSI_CHAPTER_3_STORY','The fragile child became the centre of one of football''s defining generations.[NEWLINE][NEWLINE]Lionel began on the wing, moved into the centre, created, assisted and scored with a consistency that turned extraordinary performances into expectation.[NEWLINE][NEWLINE]Around him, Barcelona moved in triangles. Players exchanged positions, created space and understood one another almost instinctively.[NEWLINE][NEWLINE]Lionel could finish a move, begin one or destroy a defensive structure by himself when no obvious route existed. Trophies accumulated. Records fell. Individual awards followed.[NEWLINE][NEWLINE]The little boy from Rosario had become the number ten around whom an entire footballing era revolved.[NEWLINE][NEWLINE]“Greatness did not arrive as a single moment. It returned every week until the extraordinary began to feel inevitable.”'),
('TXT_KEY_MESSI_CHAPTER_4_TITLE','Chapter IV — Heavy Is the Shirt'),
('TXT_KEY_MESSI_CHAPTER_4_EFFECTS','130 Legacy; Industrial Era. Unlocks Resilience. When a military unit dies, a Golden Age ends, or an allied City-State is lost: 4 turns of +6% city Production, +6% military defensive strength, and +15% friendly-territory healing. 22-turn cooldown.'),
('TXT_KEY_MESSI_CHAPTER_4_STORY','For his club, Lionel appeared capable of everything. For Argentina, every failure seemed to weigh twice as much.[NEWLINE][NEWLINE]The national shirt carried decades of expectation. Finals were reached and lost. A World Cup slipped away. Copa América heartbreak followed.[NEWLINE][NEWLINE]Every defeat became another question about whether he could ever reproduce his club success for his country. Eventually the burden became so heavy that Lionel briefly stepped away.[NEWLINE][NEWLINE]But the dream remained unfinished. So he returned.[NEWLINE][NEWLINE]Greatness was no longer about avoiding failure. It was about facing the same pain again while knowing that victory was never guaranteed. The shirt remained heavy. Lionel chose to wear it anyway.[NEWLINE][NEWLINE]“The greatest strength is not never falling. It is choosing to return when the world remembers only the fall.”'),
('TXT_KEY_MESSI_CHAPTER_5_TITLE','Chapter V — The Long-Awaited Crown'),
('TXT_KEY_MESSI_CHAPTER_5_EFFECTS','180 Legacy; Modern Era. Each allied City-State grants +1 Culture and +1 Happiness. City-State quest Influence rewards +10%. The Number Ten aura rises from +15% to +17%. Completed City-State quests grant +1 Legacy, capped at two per Era.'),
('TXT_KEY_MESSI_CHAPTER_5_STORY','Lionel had spent years trying to carry Argentina. At last, Argentina became a team willing to carry him too.[NEWLINE][NEWLINE]A new generation formed around its captain. They defended for him, ran for him and fought with the understanding that his dream had become theirs.[NEWLINE][NEWLINE]Lionel remained the creator and inspiration, but he no longer stood alone beneath the weight of expectation.[NEWLINE][NEWLINE]At the Copa América, Argentina finally reached the moment it had been chasing. When the final whistle sounded, Lionel fell to his knees. His teammates surrounded him and lifted him into the air.[NEWLINE][NEWLINE]The burden that had followed him for years had finally become a crown.[NEWLINE][NEWLINE]“He had carried their hopes for years. At last, they carried him toward victory.”'),
('TXT_KEY_MESSI_CHAPTER_6_TITLE','Chapter VI — The Third Star'),
('TXT_KEY_MESSI_CHAPTER_6_EFFECTS','240 Legacy; Atomic Era. Once: 6-turn Golden Age, 3 turns of WLTKD in every city, one free Social Policy, full healing for every Number Ten, and +8 XP for military units. Permanently: +6% Tourism and Science during Golden Ages and +1 Culture from Great Works.'),
('TXT_KEY_MESSI_CHAPTER_6_STORY','There was one dream left.[NEWLINE][NEWLINE]The World Cup had followed Lionel throughout his entire career, always close enough to imagine, yet distant enough to hurt. Now, near the end of his journey, he returned for another attempt.[NEWLINE][NEWLINE]The tournament began with disaster, but Argentina did not collapse. Lionel scored when hope began to fade. He created when opponents surrounded him. Around him stood a team prepared to run, suffer and fight for its captain.[NEWLINE][NEWLINE]Then came a final that seemed unwilling to end. After extra time, the World Cup would be decided from the penalty spot. Then came the final save.[NEWLINE][NEWLINE]Decades of longing exploded into celebration. The little boy from Rosario had reached the summit of the game.[NEWLINE][NEWLINE]“At the end of the longest road, the little boy from Rosario finally found heaven—and held the world in his hands.”'),
('TXT_KEY_MESSI_EPILOGUE_TITLE','Epilogue — The Story Continues'),
('TXT_KEY_MESSI_EPILOGUE_EFFECTS','After Chapter VI, every additional 55 Legacy grants a 2-turn Golden Age and Culture equal to 15 × the current Era number. The first six rewards also grant +1% permanent Tourism.'),
('TXT_KEY_MESSI_EPILOGUE_STORY','Many stories would have ended with the World Cup. Lionel continued.[NEWLINE][NEWLINE]The pace and surroundings changed, but the game remained. There were still matches to play, passes to create, teammates to inspire and moments to leave behind.[NEWLINE][NEWLINE]His legacy no longer depended upon another trophy. Whatever came next would not decide whether he had achieved greatness. It would simply add another page.[NEWLINE][NEWLINE]The story continues.'),

('TXT_KEY_MESSI_UI_LAUNCHER','LEGACY'),
('TXT_KEY_MESSI_UI_HEADER','THE ETERNAL NUMBER TEN'),
('TXT_KEY_MESSI_UI_SUBTITLE','CAREER CHAPTERS'),
('TXT_KEY_MESSI_UI_CURRENT','LEGACY: {1_Num} / {2_Num}'),
('TXT_KEY_MESSI_UI_COMPLETE','LEGACY: {1_Num}  •  THE STORY CONTINUES'),
('TXT_KEY_MESSI_UI_NEXT','Next: {1_Name}'),
('TXT_KEY_MESSI_UI_REQUIRES','Requires: {1_Era}'),
('TXT_KEY_MESSI_UI_UNLOCKED','UNLOCKED'),
('TXT_KEY_MESSI_UI_LOCKED','LOCKED'),
('TXT_KEY_MESSI_UI_GOLDEN_STAR','★ THIRD STAR'),
('TXT_KEY_MESSI_UI_HISTORY','Epilogue rewards: {1_Num}  •  Permanent Tourism: +{2_Num}%'),
('TXT_KEY_MESSI_UI_CLOSE','CLOSE'),
('TXT_KEY_MESSI_ERA_ANY','No Era requirement'),

('TXT_KEY_MESSI_NOTIFICATION_LEGACY','Legacy +{1_Num}: {2_Source}. Total Legacy: {3_Total}.'),
('TXT_KEY_MESSI_NOTIFICATION_LEGACY_SUMMARY','The Legacy grows'),
('TXT_KEY_MESSI_NOTIFICATION_CHAPTER','{1_Title} has been unlocked.[NEWLINE][NEWLINE]{2_Effects}'),
('TXT_KEY_MESSI_NOTIFICATION_CHAPTER_SUMMARY','A new Career Chapter'),
('TXT_KEY_MESSI_NOTIFICATION_RESILIENCE','Resilience is active for 4 turns. Cities gain +6% Production; military units gain +6% defensive strength and +15% friendly-territory healing.'),
('TXT_KEY_MESSI_NOTIFICATION_RESILIENCE_SUMMARY','Resilience'),
('TXT_KEY_MESSI_NOTIFICATION_RESILIENCE_END','Resilience has ended. It can trigger again after its civilization-wide cooldown.'),
('TXT_KEY_MESSI_NOTIFICATION_RESILIENCE_END_SUMMARY','Resilience ends'),
('TXT_KEY_MESSI_NOTIFICATION_EPILOGUE','The Story Continues: a 2-turn Golden Age and {1_Num} Culture. Permanent Tourism is now +{2_Num}%.'),
('TXT_KEY_MESSI_NOTIFICATION_EPILOGUE_SUMMARY','The Story Continues'),
('TXT_KEY_MESSI_SOURCE_GREAT_PERSON','Great Person born'),
('TXT_KEY_MESSI_SOURCE_LA_MASIA','La Masia development'),
('TXT_KEY_MESSI_SOURCE_WONDER','World Wonder completed'),
('TXT_KEY_MESSI_SOURCE_ALLIANCE','first City-State alliance this Era'),
('TXT_KEY_MESSI_SOURCE_GOLDEN_AGE','first Golden Age this Era'),
('TXT_KEY_MESSI_SOURCE_ASSIST','Assist'),
('TXT_KEY_MESSI_SOURCE_QUEST','City-State quest'),

('TXT_KEY_CITY_MESSI_1','Rosario'),('TXT_KEY_CITY_MESSI_2','Barcelona'),
('TXT_KEY_CITY_MESSI_3','Buenos Aires'),('TXT_KEY_CITY_MESSI_4','Miami'),
('TXT_KEY_CITY_MESSI_5','Paris'),('TXT_KEY_CITY_MESSI_6','Santa Fe'),
('TXT_KEY_CITY_MESSI_7','Lusail'),('TXT_KEY_CITY_MESSI_8','Beijing'),
('TXT_KEY_CITY_MESSI_9','Doha'),('TXT_KEY_CITY_MESSI_10','Rio de Janeiro'),
('TXT_KEY_CITY_MESSI_11','La Plata'),('TXT_KEY_CITY_MESSI_12','Cordoba'),
('TXT_KEY_CITY_MESSI_13','Seville'),('TXT_KEY_CITY_MESSI_14','Madrid'),
('TXT_KEY_CITY_MESSI_15','Marseille'),('TXT_KEY_CITY_MESSI_16','New Jersey'),
('TXT_KEY_CITY_MESSI_17','Atlanta'),('TXT_KEY_CITY_MESSI_18','Los Angeles'),
('TXT_KEY_CITY_MESSI_19','New York'),('TXT_KEY_CITY_MESSI_20','Tokyo'),
('TXT_KEY_SPY_MESSI_1','Jorge'),('TXT_KEY_SPY_MESSI_2','Celia'),
('TXT_KEY_SPY_MESSI_3','Rodrigo'),('TXT_KEY_SPY_MESSI_4','Matias'),
('TXT_KEY_SPY_MESSI_5','Antonela'),('TXT_KEY_SPY_MESSI_6','Pablo'),
('TXT_KEY_SPY_MESSI_7','Andres'),('TXT_KEY_SPY_MESSI_8','Angel'),
('TXT_KEY_SPY_MESSI_9','Emiliano'),('TXT_KEY_SPY_MESSI_10','Lionel');
