-- PaulsoaresJr -- The First Night. Brave New World + Community Patch v151.
-- All identifiers are namespaced; no existing civilization is modified.

UPDATE CustomModOptions SET Value = 1 WHERE Name IN
('EVENTS_NW_DISCOVERY', 'EVENTS_GOODY_CHOICE', 'EVENTS_PLOT',
 'EVENTS_UNIT_CONVERTS', 'EVENTS_UNIT_CREATED');
-- CP v151 (5.4.2/5.4.6) already sends the other used hooks through base
-- CallHook paths. NW_DISCOVERY is needed for the discovering unit arguments.
-- Do not disable event families requested by other civilizations.

INSERT INTO IconTextureAtlases (Atlas, IconSize, Filename, IconsPerRow, IconsPerColumn) VALUES
('PSJ_ICON_ATLAS',256,'PSJIcon256.dds',2,1),
('PSJ_ICON_ATLAS',128,'PSJIcon128.dds',2,1),
('PSJ_ICON_ATLAS',80,'PSJIcon80.dds',2,1),
('PSJ_ICON_ATLAS',64,'PSJIcon64.dds',2,1),
('PSJ_ICON_ATLAS',48,'PSJIcon48.dds',2,1),
('PSJ_ICON_ATLAS',45,'PSJIcon45.dds',2,1),
('PSJ_ICON_ATLAS',32,'PSJIcon32.dds',2,1),
('PSJ_ICON_ATLAS',24,'PSJIcon24.dds',2,1),
('PSJ_ICON_ATLAS',16,'PSJIcon16.dds',2,1),
('PSJ_ALPHA_ATLAS',256,'PSJAlpha256.dds',1,1),
('PSJ_ALPHA_ATLAS',128,'PSJAlpha128.dds',1,1),
('PSJ_ALPHA_ATLAS',80,'PSJAlpha80.dds',1,1),
('PSJ_ALPHA_ATLAS',64,'PSJAlpha64.dds',1,1),
('PSJ_ALPHA_ATLAS',48,'PSJAlpha48.dds',1,1),
('PSJ_ALPHA_ATLAS',45,'PSJAlpha45.dds',1,1),
('PSJ_ALPHA_ATLAS',32,'PSJAlpha32.dds',1,1),
('PSJ_ALPHA_ATLAS',24,'PSJAlpha24.dds',1,1),
('PSJ_ALPHA_ATLAS',16,'PSJAlpha16.dds',1,1),
('PSJ_OBJECT_ATLAS',256,'PSJObjects256.dds',4,1),
('PSJ_OBJECT_ATLAS',128,'PSJObjects128.dds',4,1),
('PSJ_OBJECT_ATLAS',80,'PSJObjects80.dds',4,1),
('PSJ_OBJECT_ATLAS',64,'PSJObjects64.dds',4,1),
('PSJ_OBJECT_ATLAS',45,'PSJObjects45.dds',4,1),
('PSJ_OBJECT_ATLAS',32,'PSJObjects32.dds',4,1),
('PSJ_OBJECT_ATLAS',16,'PSJObjects16.dds',4,1),
('PSJ_UNIT_FLAG_ATLAS',32,'PSJUnitFlag32.dds',1,1);

INSERT INTO Colors(Type,Red,Green,Blue,Alpha) VALUES
('COLOR_PSJ_PRIMARY',0.04,0.12,0.18,1),
('COLOR_PSJ_SECONDARY',0.96,0.70,0.25,1);
INSERT INTO PlayerColors(Type,PrimaryColor,SecondaryColor,TextColor) VALUES
('PLAYERCOLOR_PSJ','COLOR_PSJ_PRIMARY','COLOR_PSJ_SECONDARY','COLOR_PLAYER_WHITE_TEXT');

INSERT INTO Traits(Type,Description,ShortDescription) VALUES
('TRAIT_PSJ_SURVIVE_THRIVE','TXT_KEY_TRAIT_PSJ_HELP','TXT_KEY_TRAIT_PSJ_SHORT');

CREATE TEMP TABLE PSJLeaderClone AS SELECT * FROM Leaders WHERE Type='LEADER_WASHINGTON';
UPDATE PSJLeaderClone SET ID=NULL,Type='LEADER_PSJ_PAUL',Description='TXT_KEY_LEADER_PSJ_PAUL',
 Civilopedia='TXT_KEY_LEADER_PSJ_PAUL_PEDIA',CivilopediaTag='TXT_KEY_CIVILOPEDIA_LEADERS_PSJ_PAUL',
 ArtDefineTag='PSJLeaderScene.xml',PortraitIndex=1,IconAtlas='PSJ_ICON_ATLAS',PackageID=NULL,
 VictoryCompetitiveness=7,WonderCompetitiveness=3,MinorCivCompetitiveness=5,
 Boldness=4,DiploBalance=8,WarmongerHate=9,WorkAgainstWillingness=3,WorkWithWillingness=9,
 DenounceWillingness=4,DoFWillingness=9,Loyalty=9,Neediness=3,Forgiveness=8,Chattiness=6,Meanness=2;
INSERT INTO Leaders SELECT * FROM PSJLeaderClone;
DROP TABLE PSJLeaderClone;
INSERT INTO Leader_Traits VALUES ('LEADER_PSJ_PAUL','TRAIT_PSJ_SURVIVE_THRIVE');

INSERT INTO Leader_Flavors SELECT 'LEADER_PSJ_PAUL',FlavorType,Flavor
FROM Leader_Flavors WHERE LeaderType='LEADER_WASHINGTON';
UPDATE Leader_Flavors SET Flavor=CASE FlavorType
 WHEN 'FLAVOR_EXPANSION' THEN 5 WHEN 'FLAVOR_WONDER' THEN 3
 WHEN 'FLAVOR_SCIENCE' THEN 9 WHEN 'FLAVOR_CULTURE' THEN 10
 WHEN 'FLAVOR_MILITARY_TRAINING' THEN 5 WHEN 'FLAVOR_OFFENSE' THEN 3
 WHEN 'FLAVOR_DEFENSE' THEN 8 WHEN 'FLAVOR_RECON' THEN 10
 WHEN 'FLAVOR_TILE_IMPROVEMENT' THEN 10 WHEN 'FLAVOR_GREAT_PEOPLE' THEN 7
 WHEN 'FLAVOR_MOBILE' THEN 8 WHEN 'FLAVOR_PRODUCTION' THEN 6 WHEN 'FLAVOR_GROWTH' THEN 9 WHEN 'FLAVOR_DIPLOMACY' THEN 7 WHEN 'FLAVOR_GOLD' THEN 7 ELSE Flavor END
WHERE LeaderType='LEADER_PSJ_PAUL';

INSERT INTO Leader_MajorCivApproachBiases VALUES
('LEADER_PSJ_PAUL','MAJOR_CIV_APPROACH_WAR',2),
('LEADER_PSJ_PAUL','MAJOR_CIV_APPROACH_HOSTILE',2),
('LEADER_PSJ_PAUL','MAJOR_CIV_APPROACH_DECEPTIVE',1),
('LEADER_PSJ_PAUL','MAJOR_CIV_APPROACH_GUARDED',6),
('LEADER_PSJ_PAUL','MAJOR_CIV_APPROACH_AFRAID',2),
('LEADER_PSJ_PAUL','MAJOR_CIV_APPROACH_FRIENDLY',9),
('LEADER_PSJ_PAUL','MAJOR_CIV_APPROACH_NEUTRAL',5);
INSERT INTO Leader_MinorCivApproachBiases VALUES
('LEADER_PSJ_PAUL','MINOR_CIV_APPROACH_IGNORE',3),
('LEADER_PSJ_PAUL','MINOR_CIV_APPROACH_FRIENDLY',9),
('LEADER_PSJ_PAUL','MINOR_CIV_APPROACH_PROTECTIVE',7),
('LEADER_PSJ_PAUL','MINOR_CIV_APPROACH_CONQUEST',1),
('LEADER_PSJ_PAUL','MINOR_CIV_APPROACH_BULLY',1);

CREATE TEMP TABLE PSJCivClone AS SELECT * FROM Civilizations WHERE Type='CIVILIZATION_AMERICA';
UPDATE PSJCivClone SET ID=NULL,Type='CIVILIZATION_PSJ_FIRST_NIGHT',Description='TXT_KEY_CIV_PSJ_DESC',
 ShortDescription='TXT_KEY_CIV_PSJ_SHORT_DESC',Adjective='TXT_KEY_CIV_PSJ_ADJECTIVE',
 Civilopedia='TXT_KEY_CIV_PSJ_PEDIA',CivilopediaTag='TXT_KEY_CIV5_PSJ',Strategy='TXT_KEY_CIV_PSJ_STRATEGY',
 DefaultPlayerColor='PLAYERCOLOR_PSJ',Playable=1,AIPlayable=1,PackageID=NULL,
 ArtDefineTag='ART_DEF_CIVILIZATION_AMERICA',ArtStyleType='ARTSTYLE_EUROPEAN',ArtStyleSuffix='_EURO',ArtStylePrefix='EUROPEAN ',
 PortraitIndex=0,IconAtlas='PSJ_ICON_ATLAS',AlphaIconAtlas='PSJ_ALPHA_ATLAS',
 MapImage='PSJMap.dds',DawnOfManImage='PSJDawn.dds',DawnOfManQuote='TXT_KEY_PSJ_DAWN_OF_MAN',
 DawnOfManAudio='',SoundtrackTag='AMERICA';
INSERT INTO Civilizations SELECT * FROM PSJCivClone;
DROP TABLE PSJCivClone;

INSERT INTO Civilization_Leaders VALUES ('CIVILIZATION_PSJ_FIRST_NIGHT','LEADER_PSJ_PAUL');
INSERT INTO Civilization_FreeBuildingClasses SELECT 'CIVILIZATION_PSJ_FIRST_NIGHT',BuildingClassType
FROM Civilization_FreeBuildingClasses WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_FreeTechs SELECT 'CIVILIZATION_PSJ_FIRST_NIGHT',TechType
FROM Civilization_FreeTechs WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_FreeUnits(CivilizationType,UnitClassType,UnitAIType,Count)
SELECT 'CIVILIZATION_PSJ_FIRST_NIGHT',UnitClassType,UnitAIType,Count
FROM Civilization_FreeUnits WHERE CivilizationType='CIVILIZATION_AMERICA';


CREATE TEMP TABLE PSJUnitClone AS SELECT * FROM Units WHERE Type='UNIT_SCOUT';
UPDATE PSJUnitClone SET ID=NULL,Type='UNIT_PSJ_SURVIVOR',Description='TXT_KEY_UNIT_PSJ_SURVIVOR',
 Civilopedia='TXT_KEY_UNIT_PSJ_SURVIVOR_PEDIA',Strategy='TXT_KEY_UNIT_PSJ_SURVIVOR_STRATEGY',
 Help='TXT_KEY_UNIT_PSJ_SURVIVOR_HELP',Moves=2,PortraitIndex=0,IconAtlas='PSJ_OBJECT_ATLAS',
 UnitFlagIconOffset=0,UnitFlagAtlas='PSJ_UNIT_FLAG_ATLAS';
INSERT INTO Units SELECT * FROM PSJUnitClone;
DROP TABLE PSJUnitClone;
INSERT INTO Civilization_UnitClassOverrides VALUES
('CIVILIZATION_PSJ_FIRST_NIGHT','UNITCLASS_SCOUT','UNIT_PSJ_SURVIVOR');

CREATE TEMP TABLE PSJBuildingClone AS SELECT * FROM Buildings WHERE Type='BUILDING_MONUMENT';
UPDATE PSJBuildingClone SET ID=NULL,Type='BUILDING_PSJ_STARTER_HOUSE',
 Description='TXT_KEY_BUILDING_PSJ_STARTER_HOUSE',
 Civilopedia='TXT_KEY_BUILDING_PSJ_STARTER_HOUSE_PEDIA',
 Strategy='TXT_KEY_BUILDING_PSJ_STARTER_HOUSE_STRATEGY',
 Help='TXT_KEY_BUILDING_PSJ_STARTER_HOUSE_HELP',PortraitIndex=1,IconAtlas='PSJ_OBJECT_ATLAS';
INSERT INTO Buildings SELECT * FROM PSJBuildingClone;
DROP TABLE PSJBuildingClone;
INSERT INTO Civilization_BuildingClassOverrides VALUES
('CIVILIZATION_PSJ_FIRST_NIGHT','BUILDINGCLASS_MONUMENT','BUILDING_PSJ_STARTER_HOUSE');


INSERT INTO Civilization_CityNames VALUES
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_00'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_01'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_02'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_03'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_04'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_05'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_06'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_07'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_08'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_09'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_10'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_11'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_12'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_13'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_14'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_15'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_16'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_17'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_18'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_CITY_19');
INSERT INTO Civilization_SpyNames VALUES
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_SPY_00'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_SPY_01'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_SPY_02'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_SPY_03'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_SPY_04'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_SPY_05'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_SPY_06'),
('CIVILIZATION_PSJ_FIRST_NIGHT','TXT_KEY_PSJ_SPY_07');
