-- The Capano Circuit. Brave New World + Community Patch v151.
-- All identifiers are namespaced; no existing civilization is modified.

UPDATE CustomModOptions SET Value = 1 WHERE Name IN
('EVENTS_BATTLES', 'EVENTS_CITY', 'EVENTS_DIPLO_MODIFIERS', 'EVENTS_PLOT',
 'EVENTS_PLAYER_TURN', 'EVENTS_TILE_IMPROVEMENTS', 'EVENTS_UNIT_CAPTURE',
 'EVENTS_UNIT_CONVERTS', 'EVENTS_UNIT_CREATED', 'EVENTS_UNIT_PREKILL',
 'EVENTS_UNIT_UPGRADES', 'EVENTS_WAR_AND_PEACE');

INSERT INTO IconTextureAtlases (Atlas, IconSize, Filename, IconsPerRow, IconsPerColumn) VALUES
('CAPANO_ICON_ATLAS',256,'CapanoIcon256.dds',2,1),
('CAPANO_ICON_ATLAS',128,'CapanoIcon128.dds',2,1),
('CAPANO_ICON_ATLAS',80,'CapanoIcon80.dds',2,1),
('CAPANO_ICON_ATLAS',64,'CapanoIcon64.dds',2,1),
('CAPANO_ICON_ATLAS',48,'CapanoIcon48.dds',2,1),
('CAPANO_ICON_ATLAS',45,'CapanoIcon45.dds',2,1),
('CAPANO_ICON_ATLAS',32,'CapanoIcon32.dds',2,1),
('CAPANO_ICON_ATLAS',24,'CapanoIcon24.dds',2,1),
('CAPANO_ICON_ATLAS',16,'CapanoIcon16.dds',2,1),
('CAPANO_ALPHA_ATLAS',256,'CapanoAlpha256.dds',1,1),
('CAPANO_ALPHA_ATLAS',128,'CapanoAlpha128.dds',1,1),
('CAPANO_ALPHA_ATLAS',80,'CapanoAlpha80.dds',1,1),
('CAPANO_ALPHA_ATLAS',64,'CapanoAlpha64.dds',1,1),
('CAPANO_ALPHA_ATLAS',48,'CapanoAlpha48.dds',1,1),
('CAPANO_ALPHA_ATLAS',45,'CapanoAlpha45.dds',1,1),
('CAPANO_ALPHA_ATLAS',32,'CapanoAlpha32.dds',1,1),
('CAPANO_ALPHA_ATLAS',24,'CapanoAlpha24.dds',1,1),
('CAPANO_ALPHA_ATLAS',16,'CapanoAlpha16.dds',1,1),
('CAPANO_OBJECT_ATLAS',256,'CapanoObjects256.dds',14,1),
('CAPANO_OBJECT_ATLAS',128,'CapanoObjects128.dds',14,1),
('CAPANO_OBJECT_ATLAS',80,'CapanoObjects80.dds',14,1),
('CAPANO_OBJECT_ATLAS',64,'CapanoObjects64.dds',14,1),
('CAPANO_OBJECT_ATLAS',45,'CapanoObjects45.dds',14,1),
('CAPANO_OBJECT_ATLAS',32,'CapanoObjects32.dds',14,1),
('CAPANO_OBJECT_ATLAS',16,'CapanoObjects16.dds',14,1),
('CAPANO_UNIT_FLAG_ATLAS',32,'CapanoUnitFlag32.dds',1,1);

INSERT INTO Colors(Type,Red,Green,Blue,Alpha) VALUES
('COLOR_CAPANO_PRIMARY',0.035,0.035,0.045,1),
('COLOR_CAPANO_SECONDARY',0.56,0.25,0.72,1);
INSERT INTO PlayerColors(Type,PrimaryColor,SecondaryColor,TextColor) VALUES
('PLAYERCOLOR_CAPANO','COLOR_CAPANO_PRIMARY','COLOR_CAPANO_SECONDARY','COLOR_PLAYER_WHITE_TEXT');

INSERT INTO Traits(Type,Description,ShortDescription) VALUES
('TRAIT_CAPANO_IMPOSSIBLE_POSSIBLE','TXT_KEY_TRAIT_CAPANO_HELP','TXT_KEY_TRAIT_CAPANO_SHORT');

CREATE TEMP TABLE CapanoLeaderClone AS SELECT * FROM Leaders WHERE Type='LEADER_WASHINGTON';
UPDATE CapanoLeaderClone SET ID=NULL,Type='LEADER_ENRICO_CAPANO',Description='TXT_KEY_LEADER_ENRICO_CAPANO',
 Civilopedia='TXT_KEY_LEADER_ENRICO_CAPANO_PEDIA',CivilopediaTag='TXT_KEY_CIVILOPEDIA_LEADERS_ENRICO_CAPANO',
 ArtDefineTag='CapanoLeaderScene.xml',PortraitIndex=1,IconAtlas='CAPANO_ICON_ATLAS',PackageID=NULL,
 VictoryCompetitiveness=8,WonderCompetitiveness=5,MinorCivCompetitiveness=7,
 Boldness=6,DiploBalance=8,WarmongerHate=7,WorkAgainstWillingness=5,WorkWithWillingness=7,
 DenounceWillingness=4,DoFWillingness=6,Loyalty=7,Neediness=4,Forgiveness=7,Chattiness=5,Meanness=3;
INSERT INTO Leaders SELECT * FROM CapanoLeaderClone;
DROP TABLE CapanoLeaderClone;
INSERT INTO Leader_Traits VALUES ('LEADER_ENRICO_CAPANO','TRAIT_CAPANO_IMPOSSIBLE_POSSIBLE');

INSERT INTO Leader_Flavors SELECT 'LEADER_ENRICO_CAPANO',FlavorType,Flavor
FROM Leader_Flavors WHERE LeaderType='LEADER_WASHINGTON';
UPDATE Leader_Flavors SET Flavor=CASE FlavorType
 WHEN 'FLAVOR_EXPANSION' THEN 5 WHEN 'FLAVOR_WONDER' THEN 5
 WHEN 'FLAVOR_SCIENCE' THEN 8 WHEN 'FLAVOR_CULTURE' THEN 8
 WHEN 'FLAVOR_MILITARY_TRAINING' THEN 9 WHEN 'FLAVOR_OFFENSE' THEN 6
 WHEN 'FLAVOR_DEFENSE' THEN 8 WHEN 'FLAVOR_RECON' THEN 8
 WHEN 'FLAVOR_TILE_IMPROVEMENT' THEN 10 WHEN 'FLAVOR_GREAT_PEOPLE' THEN 7
 WHEN 'FLAVOR_MOBILE' THEN 8 WHEN 'FLAVOR_PRODUCTION' THEN 8 ELSE Flavor END
WHERE LeaderType='LEADER_ENRICO_CAPANO';

INSERT INTO Leader_MajorCivApproachBiases VALUES
('LEADER_ENRICO_CAPANO','MAJOR_CIV_APPROACH_WAR',5),
('LEADER_ENRICO_CAPANO','MAJOR_CIV_APPROACH_HOSTILE',4),
('LEADER_ENRICO_CAPANO','MAJOR_CIV_APPROACH_DECEPTIVE',2),
('LEADER_ENRICO_CAPANO','MAJOR_CIV_APPROACH_GUARDED',6),
('LEADER_ENRICO_CAPANO','MAJOR_CIV_APPROACH_AFRAID',2),
('LEADER_ENRICO_CAPANO','MAJOR_CIV_APPROACH_FRIENDLY',6),
('LEADER_ENRICO_CAPANO','MAJOR_CIV_APPROACH_NEUTRAL',5);
INSERT INTO Leader_MinorCivApproachBiases VALUES
('LEADER_ENRICO_CAPANO','MINOR_CIV_APPROACH_IGNORE',3),
('LEADER_ENRICO_CAPANO','MINOR_CIV_APPROACH_FRIENDLY',6),
('LEADER_ENRICO_CAPANO','MINOR_CIV_APPROACH_PROTECTIVE',7),
('LEADER_ENRICO_CAPANO','MINOR_CIV_APPROACH_CONQUEST',4),
('LEADER_ENRICO_CAPANO','MINOR_CIV_APPROACH_BULLY',3);

CREATE TEMP TABLE CapanoCivClone AS SELECT * FROM Civilizations WHERE Type='CIVILIZATION_AMERICA';
UPDATE CapanoCivClone SET ID=NULL,Type='CIVILIZATION_CAPANO_CIRCUIT',Description='TXT_KEY_CIV_CAPANO_DESC',
 ShortDescription='TXT_KEY_CIV_CAPANO_SHORT_DESC',Adjective='TXT_KEY_CIV_CAPANO_ADJECTIVE',
 Civilopedia='TXT_KEY_CIV_CAPANO_PEDIA',CivilopediaTag='TXT_KEY_CIV5_CAPANO',Strategy='TXT_KEY_CIV_CAPANO_STRATEGY',
 DefaultPlayerColor='PLAYERCOLOR_CAPANO',Playable=1,AIPlayable=1,PackageID=NULL,
 ArtDefineTag='ART_DEF_CIVILIZATION_AMERICA',ArtStyleType='ARTSTYLE_EUROPEAN',ArtStyleSuffix='_EURO',ArtStylePrefix='EUROPEAN ',
 PortraitIndex=0,IconAtlas='CAPANO_ICON_ATLAS',AlphaIconAtlas='CAPANO_ALPHA_ATLAS',
 MapImage='CapanoMap.dds',DawnOfManImage='CapanoLeader.dds',DawnOfManQuote='TXT_KEY_CAPANO_DAWN_OF_MAN',
 DawnOfManAudio='',SoundtrackTag='AMERICA';
INSERT INTO Civilizations SELECT * FROM CapanoCivClone;
DROP TABLE CapanoCivClone;

INSERT INTO Civilization_Leaders VALUES ('CIVILIZATION_CAPANO_CIRCUIT','LEADER_ENRICO_CAPANO');
INSERT INTO Civilization_FreeBuildingClasses SELECT 'CIVILIZATION_CAPANO_CIRCUIT',BuildingClassType
FROM Civilization_FreeBuildingClasses WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_FreeTechs SELECT 'CIVILIZATION_CAPANO_CIRCUIT',TechType
FROM Civilization_FreeTechs WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_FreeUnits(CivilizationType,UnitClassType,UnitAIType,Count)
SELECT 'CIVILIZATION_CAPANO_CIRCUIT',UnitClassType,UnitAIType,Count
FROM Civilization_FreeUnits WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_Start_Region_Priority VALUES ('CIVILIZATION_CAPANO_CIRCUIT','REGION_HILLS');

CREATE TEMP TABLE CapanoUnitClone AS SELECT * FROM Units WHERE Type='UNIT_WORKER';
UPDATE CapanoUnitClone SET ID=NULL,Type='UNIT_CAPANO_ROUTE_SETTER',Description='TXT_KEY_UNIT_CAPANO_ROUTE_SETTER',
 Civilopedia='TXT_KEY_UNIT_CAPANO_ROUTE_SETTER_PEDIA',Strategy='TXT_KEY_UNIT_CAPANO_ROUTE_SETTER_STRATEGY',
 Help='TXT_KEY_UNIT_CAPANO_ROUTE_SETTER_HELP',Moves=3,PortraitIndex=0,IconAtlas='CAPANO_OBJECT_ATLAS',
 UnitFlagIconOffset=0,UnitFlagAtlas='CAPANO_UNIT_FLAG_ATLAS';
INSERT INTO Units SELECT * FROM CapanoUnitClone;
DROP TABLE CapanoUnitClone;
INSERT INTO Civilization_UnitClassOverrides VALUES
('CIVILIZATION_CAPANO_CIRCUIT','UNITCLASS_WORKER','UNIT_CAPANO_ROUTE_SETTER');

CREATE TEMP TABLE CapanoBuildingClone AS SELECT * FROM Buildings WHERE Type='BUILDING_ARMORY';
UPDATE CapanoBuildingClone SET ID=NULL,Type='BUILDING_CAPANO_COMPETITION_CENTRE',
 Description='TXT_KEY_BUILDING_CAPANO_COMPETITION_CENTRE',
 Civilopedia='TXT_KEY_BUILDING_CAPANO_COMPETITION_CENTRE_PEDIA',
 Strategy='TXT_KEY_BUILDING_CAPANO_COMPETITION_CENTRE_STRATEGY',
 Help='TXT_KEY_BUILDING_CAPANO_COMPETITION_CENTRE_HELP',PortraitIndex=1,IconAtlas='CAPANO_OBJECT_ATLAS';
INSERT INTO Buildings SELECT * FROM CapanoBuildingClone;
DROP TABLE CapanoBuildingClone;
INSERT INTO Civilization_BuildingClassOverrides VALUES
('CIVILIZATION_CAPANO_CIRCUIT','BUILDINGCLASS_ARMORY','BUILDING_CAPANO_COMPETITION_CENTRE');

CREATE TEMP TABLE CapanoBuildClone AS SELECT * FROM Builds WHERE Type='BUILD_FORT';
UPDATE CapanoBuildClone SET ID=NULL,Type='BUILD_CAPANO_BOULDER_SECTOR',
 Description='TXT_KEY_BUILD_CAPANO_BOULDER_SECTOR',Help='TXT_KEY_BUILD_CAPANO_BOULDER_SECTOR_HELP',
 Recommendation='TXT_KEY_BUILD_CAPANO_BOULDER_SECTOR_REC',HotKey=NULL,HotKeyAlt=NULL,
 PrereqTech='TECH_CONSTRUCTION',ImprovementType='IMPROVEMENT_CAPANO_BOULDER_SECTOR',
 IconIndex=2,IconAtlas='CAPANO_OBJECT_ATLAS';
INSERT INTO Builds SELECT * FROM CapanoBuildClone;
DROP TABLE CapanoBuildClone;

INSERT INTO Improvements
(Type,Description,Civilopedia,Help,ArtDefineTag,SpecificCivRequired,CivilizationType,
 HillsMakesValid,NoTwoAdjacent,DefenseModifier,PortraitIndex,IconAtlas)
VALUES
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','TXT_KEY_IMPROVEMENT_CAPANO_BOULDER_SECTOR',
 'TXT_KEY_IMPROVEMENT_CAPANO_BOULDER_SECTOR_PEDIA','TXT_KEY_IMPROVEMENT_CAPANO_BOULDER_SECTOR_HELP',
 'ART_DEF_IMPROVEMENT_FORT',1,'CIVILIZATION_CAPANO_CIRCUIT',1,1,0,2,'CAPANO_OBJECT_ATLAS');

INSERT INTO Improvement_ValidTerrains VALUES
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','TERRAIN_GRASS'),
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','TERRAIN_PLAINS'),
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','TERRAIN_DESERT'),
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','TERRAIN_TUNDRA'),
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','TERRAIN_SNOW');

INSERT INTO DiploModifiers(Type,Description,FromCivilizationType,ToCivilizationType) VALUES
('DIPLOMODIFIER_CAPANO_RESPECT_SEND','TXT_KEY_DIPLOMODIFIER_CAPANO_RESPECT_SEND','CIVILIZATION_CAPANO_CIRCUIT',NULL),
('DIPLOMODIFIER_CAPANO_ABANDONED_PROJECT','TXT_KEY_DIPLOMODIFIER_CAPANO_ABANDONED_PROJECT','CIVILIZATION_CAPANO_CIRCUIT',NULL),
('DIPLOMODIFIER_CAPANO_STRONG_CLIMBERS','TXT_KEY_DIPLOMODIFIER_CAPANO_STRONG_CLIMBERS','CIVILIZATION_CAPANO_CIRCUIT',NULL);

INSERT INTO Civilization_CityNames VALUES
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_HAUS'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_GRAMPIANS'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_ARCO'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_MELBOURNE'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_AMMAGAMMA'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_DYNO'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_CRUX'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_ARETE'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_MANTLE'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_SLAB'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_OVERHANG'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_TRAVERSE'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_BASECAMP'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_SUMMIT'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_CITY_NAME_CAPANO_BETA');

INSERT INTO Civilization_SpyNames VALUES
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_SPY_NAME_CAPANO_0'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_SPY_NAME_CAPANO_1'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_SPY_NAME_CAPANO_2'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_SPY_NAME_CAPANO_3'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_SPY_NAME_CAPANO_4'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_SPY_NAME_CAPANO_5'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_SPY_NAME_CAPANO_6'),
('CIVILIZATION_CAPANO_CIRCUIT','TXT_KEY_SPY_NAME_CAPANO_7');
