-- Inherited-object additions and the database half of Capano's runtime effects.

INSERT INTO Unit_Builds(UnitType,BuildType) VALUES
('UNIT_CAPANO_ROUTE_SETTER','BUILD_CAPANO_BOULDER_SECTOR');
INSERT INTO Unit_FreePromotions(UnitType,PromotionType) VALUES
('UNIT_CAPANO_ROUTE_SETTER','PROMOTION_CAPANO_ROUTE_SETTER');

CREATE TEMP TABLE CapanoBuildFeatureClone AS
SELECT * FROM BuildFeatures WHERE BuildType='BUILD_FORT';
UPDATE CapanoBuildFeatureClone SET BuildType='BUILD_CAPANO_BOULDER_SECTOR';
INSERT INTO BuildFeatures SELECT * FROM CapanoBuildFeatureClone;
DROP TABLE CapanoBuildFeatureClone;

INSERT INTO Building_YieldChanges(BuildingType,YieldType,Yield)
SELECT 'BUILDING_CAPANO_COMPETITION_CENTRE','YIELD_SCIENCE',0
WHERE NOT EXISTS (SELECT 1 FROM Building_YieldChanges
 WHERE BuildingType='BUILDING_CAPANO_COMPETITION_CENTRE' AND YieldType='YIELD_SCIENCE');
INSERT INTO Building_YieldChanges(BuildingType,YieldType,Yield)
SELECT 'BUILDING_CAPANO_COMPETITION_CENTRE','YIELD_CULTURE',0
WHERE NOT EXISTS (SELECT 1 FROM Building_YieldChanges
 WHERE BuildingType='BUILDING_CAPANO_COMPETITION_CENTRE' AND YieldType='YIELD_CULTURE');
UPDATE Building_YieldChanges SET Yield=Yield+2
WHERE BuildingType='BUILDING_CAPANO_COMPETITION_CENTRE'
AND YieldType IN ('YIELD_SCIENCE','YIELD_CULTURE');

INSERT INTO Improvement_Yields VALUES
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','YIELD_SCIENCE',1),
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','YIELD_CULTURE',1),
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','YIELD_PRODUCTION',1);
INSERT INTO Improvement_TechYieldChanges VALUES
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','TECH_EDUCATION','YIELD_SCIENCE',1),
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','TECH_GUILDS','YIELD_PRODUCTION',1),
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','TECH_ARCHITECTURE','YIELD_CULTURE',1),
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','TECH_RADIO','YIELD_CULTURE',1),
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','TECH_SCIENTIFIC_THEORY','YIELD_SCIENCE',1);
INSERT INTO Improvement_Flavors VALUES
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','FLAVOR_SCIENCE',10),
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','FLAVOR_CULTURE',10),
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','FLAVOR_PRODUCTION',8),
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','FLAVOR_DEFENSE',8),
('IMPROVEMENT_CAPANO_BOULDER_SECTOR','FLAVOR_TILE_IMPROVEMENT',10);

INSERT INTO UnitPromotions
(Type,Description,Help,CannotBeChosen,LostWithUpgrade,PortraitIndex,IconAtlas,PediaType,PediaEntry,OrderPriority)
VALUES
('PROMOTION_CAPANO_ROUTE_SETTER','TXT_KEY_PROMOTION_CAPANO_ROUTE_SETTER','TXT_KEY_PROMOTION_CAPANO_ROUTE_SETTER_HELP',1,1,0,'CAPANO_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_CAPANO_ROUTE_SETTER',100),
('PROMOTION_CAPANO_SETTER_HILLS_WORK','TXT_KEY_PROMOTION_CAPANO_SETTER_HILLS_WORK','TXT_KEY_PROMOTION_CAPANO_SETTER_HILLS_WORK_HELP',1,1,0,'CAPANO_OBJECT_ATLAS',NULL,NULL,0),
('PROMOTION_CAPANO_BETA_1','TXT_KEY_PROMOTION_CAPANO_BETA_1','TXT_KEY_PROMOTION_CAPANO_BETA_1_HELP',1,1,3,'CAPANO_OBJECT_ATLAS',NULL,NULL,91),
('PROMOTION_CAPANO_BETA_2','TXT_KEY_PROMOTION_CAPANO_BETA_2','TXT_KEY_PROMOTION_CAPANO_BETA_2_HELP',1,1,3,'CAPANO_OBJECT_ATLAS',NULL,NULL,92),
('PROMOTION_CAPANO_BETA_3','TXT_KEY_PROMOTION_CAPANO_BETA_3','TXT_KEY_PROMOTION_CAPANO_BETA_3_HELP',1,1,3,'CAPANO_OBJECT_ATLAS',NULL,NULL,93),
('PROMOTION_CAPANO_BETA_4','TXT_KEY_PROMOTION_CAPANO_BETA_4','TXT_KEY_PROMOTION_CAPANO_BETA_4_HELP',1,1,3,'CAPANO_OBJECT_ATLAS',NULL,NULL,94),
('PROMOTION_CAPANO_BETA_ATTACK_5','TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_5','TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_5_HELP',1,1,3,'CAPANO_OBJECT_ATLAS',NULL,NULL,0),
('PROMOTION_CAPANO_BETA_ATTACK_10','TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_10','TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_10_HELP',1,1,3,'CAPANO_OBJECT_ATLAS',NULL,NULL,0),
('PROMOTION_CAPANO_BETA_ATTACK_15','TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_15','TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_15_HELP',1,1,3,'CAPANO_OBJECT_ATLAS',NULL,NULL,0),
('PROMOTION_CAPANO_BETA_ATTACK_20','TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_20','TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_20_HELP',1,1,3,'CAPANO_OBJECT_ATLAS',NULL,NULL,0),
('PROMOTION_CAPANO_AWKWARD_BLUE','TXT_KEY_PROMOTION_CAPANO_AWKWARD','TXT_KEY_PROMOTION_CAPANO_AWKWARD_BLUE_HELP',1,1,4,'CAPANO_OBJECT_ATLAS',NULL,NULL,80),
('PROMOTION_CAPANO_AWKWARD_PURPLE','TXT_KEY_PROMOTION_CAPANO_AWKWARD','TXT_KEY_PROMOTION_CAPANO_AWKWARD_PURPLE_HELP',1,1,4,'CAPANO_OBJECT_ATLAS',NULL,NULL,81),
('PROMOTION_CAPANO_READ_SEQUENCE','TXT_KEY_PROMOTION_CAPANO_READ_SEQUENCE','TXT_KEY_PROMOTION_CAPANO_READ_SEQUENCE_HELP',1,0,5,'CAPANO_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_CAPANO_READ_SEQUENCE',82),
('PROMOTION_CAPANO_COMPETITION_MOVEMENT','TXT_KEY_PROMOTION_CAPANO_COMPETITION_MOVEMENT','TXT_KEY_PROMOTION_CAPANO_COMPETITION_MOVEMENT_HELP',1,0,6,'CAPANO_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_CAPANO_COMPETITION_MOVEMENT',83),
('PROMOTION_CAPANO_COMPETITION_ACTIVE','TXT_KEY_PROMOTION_CAPANO_COMPETITION_ACTIVE','TXT_KEY_PROMOTION_CAPANO_COMPETITION_ACTIVE_HELP',1,1,6,'CAPANO_OBJECT_ATLAS',NULL,NULL,0),
('PROMOTION_CAPANO_FOOTWORK','TXT_KEY_PROMOTION_CAPANO_FOOTWORK','TXT_KEY_PROMOTION_CAPANO_FOOTWORK_HELP',1,0,7,'CAPANO_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_CAPANO_FOOTWORK',84),
('PROMOTION_CAPANO_BODY_POSITION','TXT_KEY_PROMOTION_CAPANO_BODY_POSITION','TXT_KEY_PROMOTION_CAPANO_BODY_POSITION_HELP',1,0,8,'CAPANO_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_CAPANO_BODY_POSITION',85),
('PROMOTION_CAPANO_BODY_ACTIVE','TXT_KEY_PROMOTION_CAPANO_BODY_ACTIVE','TXT_KEY_PROMOTION_CAPANO_BODY_ACTIVE_HELP',1,1,8,'CAPANO_OBJECT_ATLAS',NULL,NULL,0),
('PROMOTION_CAPANO_COORDINATION','TXT_KEY_PROMOTION_CAPANO_COORDINATION','TXT_KEY_PROMOTION_CAPANO_COORDINATION_HELP',1,0,9,'CAPANO_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_CAPANO_COORDINATION',86),
('PROMOTION_CAPANO_COMMIT','TXT_KEY_PROMOTION_CAPANO_COMMIT','TXT_KEY_PROMOTION_CAPANO_COMMIT_HELP',1,0,10,'CAPANO_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_CAPANO_COMMIT',87),
('PROMOTION_CAPANO_COMMIT_ACTIVE','TXT_KEY_PROMOTION_CAPANO_COMMIT_ACTIVE','TXT_KEY_PROMOTION_CAPANO_COMMIT_ACTIVE_HELP',1,1,10,'CAPANO_OBJECT_ATLAS',NULL,NULL,0),
('PROMOTION_CAPANO_COMPLETE_CLIMBER','TXT_KEY_PROMOTION_CAPANO_COMPLETE_CLIMBER','TXT_KEY_PROMOTION_CAPANO_COMPLETE_CLIMBER_HELP',1,0,11,'CAPANO_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_CAPANO_COMPLETE_CLIMBER',88),
('PROMOTION_CAPANO_COMPLETE_HILLS','TXT_KEY_PROMOTION_CAPANO_COMPLETE_HILLS','TXT_KEY_PROMOTION_CAPANO_COMPLETE_HILLS_HELP',1,1,11,'CAPANO_OBJECT_ATLAS',NULL,NULL,0),
('PROMOTION_CAPANO_YELLOW_CIRCUIT','TXT_KEY_PROMOTION_CAPANO_YELLOW_CIRCUIT','TXT_KEY_PROMOTION_CAPANO_YELLOW_CIRCUIT_HELP',1,0,12,'CAPANO_OBJECT_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_CAPANO_YELLOW_CIRCUIT',89);

UPDATE UnitPromotions SET HillsDoubleMove=1
WHERE Type='PROMOTION_CAPANO_ROUTE_SETTER';
UPDATE UnitPromotions SET WorkRateMod=25
WHERE Type='PROMOTION_CAPANO_SETTER_HILLS_WORK';
UPDATE UnitPromotions SET AttackMod=5 WHERE Type='PROMOTION_CAPANO_BETA_ATTACK_5';
UPDATE UnitPromotions SET AttackMod=10 WHERE Type='PROMOTION_CAPANO_BETA_ATTACK_10';
UPDATE UnitPromotions SET AttackMod=15 WHERE Type='PROMOTION_CAPANO_BETA_ATTACK_15';
UPDATE UnitPromotions SET AttackMod=20 WHERE Type='PROMOTION_CAPANO_BETA_ATTACK_20';
UPDATE UnitPromotions SET CombatPercent=-10 WHERE Type='PROMOTION_CAPANO_AWKWARD_BLUE';
UPDATE UnitPromotions SET CombatPercent=-12 WHERE Type='PROMOTION_CAPANO_AWKWARD_PURPLE';
UPDATE UnitPromotions SET RoughAttack=10,RoughDefense=10
WHERE Type='PROMOTION_CAPANO_READ_SEQUENCE';
UPDATE UnitPromotions SET AttackMod=15
WHERE Type='PROMOTION_CAPANO_COMPETITION_ACTIVE';
UPDATE UnitPromotions SET HillsDefense=10 WHERE Type='PROMOTION_CAPANO_FOOTWORK';
UPDATE UnitPromotions SET CombatPercent=10 WHERE Type='PROMOTION_CAPANO_BODY_ACTIVE';
UPDATE UnitPromotions SET AttackMod=15 WHERE Type='PROMOTION_CAPANO_COMMIT_ACTIVE';
UPDATE UnitPromotions SET MovesChange=1,CombatPercent=10
WHERE Type='PROMOTION_CAPANO_COMPLETE_CLIMBER';
UPDATE UnitPromotions SET IgnoreZOC=1 WHERE Type='PROMOTION_CAPANO_COMPLETE_HILLS';

-- Expose the permanent technique promotions to every standard land combat class.
INSERT INTO UnitPromotions_UnitCombats(PromotionType,UnitCombatType,PediaType)
SELECT promotion.Type,combat.Type,'PEDIA_ATTRIBUTES'
FROM UnitPromotions promotion CROSS JOIN UnitCombatInfos combat
WHERE promotion.Type IN
('PROMOTION_CAPANO_READ_SEQUENCE','PROMOTION_CAPANO_COMPETITION_MOVEMENT',
 'PROMOTION_CAPANO_FOOTWORK','PROMOTION_CAPANO_BODY_POSITION',
 'PROMOTION_CAPANO_COORDINATION','PROMOTION_CAPANO_COMMIT',
 'PROMOTION_CAPANO_COMPLETE_CLIMBER','PROMOTION_CAPANO_YELLOW_CIRCUIT')
AND combat.Type IN
('UNITCOMBAT_RECON','UNITCOMBAT_ARCHER','UNITCOMBAT_MOUNTED','UNITCOMBAT_MELEE',
 'UNITCOMBAT_SIEGE','UNITCOMBAT_GUN','UNITCOMBAT_ARMOR','UNITCOMBAT_HELICOPTER');
