-- English localization and fictionalized diplomacy for The Capano Circuit.

INSERT INTO Language_en_US(Tag,Text) VALUES
('TXT_KEY_CIV_CAPANO_DESC','The Capano Circuit'),
('TXT_KEY_CIV_CAPANO_SHORT_DESC','The Capano Circuit'),
('TXT_KEY_CIV_CAPANO_ADJECTIVE','Capano'),
('TXT_KEY_CIV_CAPANO_PEDIA','The Capano Circuit'),
('TXT_KEY_CIV_CAPANO_STRATEGY','[COLOR_POSITIVE_TEXT]The Capano Circuit[ENDCOLOR] learns through difficult movement. Prepare hilly ground with Boulder Sectors, train units on them once per Era, and keep attacking the same strong target until four failed attempts produce a rewarding SEND. Competition Coaching Centres turn mobile land armies into dangerous attackers.'),
('TXT_KEY_CIV5_CAPANO','The Capano Circuit'),
('TXT_KEY_CIV5_CAPANO_TITLE','The Capano Circuit'),
('TXT_KEY_CIV5_CAPANO_HEADING_1','The Circuit of Impossible Movement'),
('TXT_KEY_CIV5_CAPANO_TEXT_1','The Circuit is a civilization built around projecting: the practice of returning to a difficult problem with better information. Its setters shape terrain into deliberate sequences, its coaches turn mistakes into instruction, and its soldiers learn to value position over brute force.'),
('TXT_KEY_CIV5_CAPANO_HEADING_2','From Italy to Australia'),
('TXT_KEY_CIV5_CAPANO_TEXT_2','Enrico began climbing in Italy, passed through youth competition, and followed climbing across the world to Australia. Competition, outdoor bouldering, routesetting, and coaching became parts of one continuous education in movement.'),
('TXT_KEY_CIV5_CAPANO_HEADING_3','The Haus and the Grampians'),
('TXT_KEY_CIV5_CAPANO_TEXT_3','Modern walls and Australian sandstone provide different kinds of instruction. In the Haus, a sequence can be reset and refined. In the Grampians, the stone sets the terms. The Circuit treats both as libraries whose lessons become stronger with every Era.'),
('TXT_KEY_CIV5_CAPANO_HEADING_4','Impossible Until It Is Possible'),
('TXT_KEY_CIV5_CAPANO_TEXT_4','Failure is useful only when studied. A Capano unit that changes targets throws away its accumulated Beta; a unit that survives four honest attempts against a worthy opponent becomes terrifyingly precise. The final SEND returns knowledge to the entire civilization.'),

('TXT_KEY_LEADER_ENRICO_CAPANO','Enrico Capano'),
('TXT_KEY_LEADER_ENRICO_CAPANO_PEDIA','Enrico Capano is a climber, competitor, routesetter, and coach whose public climbing life connects Italy, international youth competition, Australian sandstone, and Victorian competition coaching. This fictional Civilization V portrayal translates that movement-focused career into a society that learns from difficult terrain and worthy opposition.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ENRICO_CAPANO','Enrico Capano'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ENRICO_CAPANO_NAME','Enrico Capano'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ENRICO_CAPANO_SUBTITLE','Student of Movement'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ENRICO_CAPANO_LIVED','The Contemporary Era'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ENRICO_CAPANO_TITLES_1','Leader of the Capano Circuit'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ENRICO_CAPANO_HEADING_1','Climber, Setter, Coach'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ENRICO_CAPANO_TEXT_1','Enrico''s design follows a progression from competitor and outdoor climber to routesetter and coach. Rather than granting simple strength, his civilization rewards repeated attempts, difficult targets, prepared terrain, and dynamic movement.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ENRICO_CAPANO_HEADING_2','Temperament'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ENRICO_CAPANO_TEXT_2','Enrico is competitive, calm, and movement-obsessed. He prefers Science, Culture, military training, defense, reconnaissance, tile improvement, and experienced units, without being inherently warmongering.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ENRICO_CAPANO_FACTS_1','His hardest publicly listed ascent is Ammagamma, graded V13, in the Grampians.'),

('TXT_KEY_TRAIT_CAPANO_SHORT','Impossible Until It''s Possible'),
('TXT_KEY_TRAIT_CAPANO_HELP','When one of your combat units attacks the same enemy Unit or City without defeating it, it gains target-specific [COLOR_POSITIVE_TEXT]Beta[ENDCOLOR]. Its next attempts against that Project gain +5%, +10%, +15%, then +20% Combat Strength; changing targets abandons all Beta. Defeating a Project after four failed attempts heals 25 HP, grants 10 XP, and awards [ICON_RESEARCH] Science and [ICON_CULTURE] Culture based on the target''s effective strength and Era. The target must have been at least as strong as the attacker when the Project began to qualify. A SEND against a target at least 50% stronger than the attacker''s original base strength earns the once-per-game [COLOR_POSITIVE_TEXT]Ammagamma[ENDCOLOR] reward: 500 Science, 500 Culture, and a Golden Age.'),

('TXT_KEY_UNIT_CAPANO_ROUTE_SETTER','Route Setter'),
('TXT_KEY_UNIT_CAPANO_ROUTE_SETTER_HELP','Replaces the Worker. Has [ICON_MOVES] 3 Movement, moves through Hills at double speed, and constructs Improvements on Hills 25% faster. It can build the exclusive Boulder Sector from Construction.'),
('TXT_KEY_UNIT_CAPANO_ROUTE_SETTER_STRATEGY','Use Route Setters to turn Hills and land adjacent to Mountains into a productive training circuit. Boulder Sectors cannot be adjacent, so plan alternating defensive lanes rather than dense clusters.'),
('TXT_KEY_UNIT_CAPANO_ROUTE_SETTER_PEDIA','[COLOR_POSITIVE_TEXT]Game Info[ENDCOLOR][NEWLINE]Unique Worker with 3 Movement, double movement through Hills, and 25% faster Improvement construction while on Hills. It alone can construct Boulder Sectors.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Background[ENDCOLOR][NEWLINE]A route setter composes movement through deliberate choices of holds, angles, distances, and body positions. Within the Circuit, setters apply that practice to the landscape itself.'),

('TXT_KEY_BUILDING_CAPANO_COMPETITION_CENTRE','Competition Coaching Centre'),
('TXT_KEY_BUILDING_CAPANO_COMPETITION_CENTRE_HELP','Replaces the Armory and retains all of its effects. Provides [ICON_RESEARCH] +2 Science and [ICON_CULTURE] +2 Culture. Land combat units completed through Production in this City gain [COLOR_POSITIVE_TEXT]Competition Movement[ENDCOLOR]: after moving across at least 2 tiles in a turn, they gain +15% Combat Strength when attacking for the rest of that turn.'),
('TXT_KEY_BUILDING_CAPANO_COMPETITION_CENTRE_STRATEGY','Build a Competition Coaching Centre in cities producing mobile land armies. Move trained units two tiles before attacking to activate their dynamic-movement bonus.'),
('TXT_KEY_BUILDING_CAPANO_COMPETITION_CENTRE_PEDIA','[COLOR_POSITIVE_TEXT]Game Info[ENDCOLOR][NEWLINE]Unique Armory with +2 Science and +2 Culture. Production-trained land combat units gain Competition Movement.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Background[ENDCOLOR][NEWLINE]The Centre represents the Circuit''s transition from competition experience into systematic coaching. Position, coordination, and acceleration become repeatable skills rather than isolated feats.'),

('TXT_KEY_BUILD_CAPANO_BOULDER_SECTOR','Construct a Boulder Sector'),
('TXT_KEY_BUILD_CAPANO_BOULDER_SECTOR_HELP','Creates a Boulder Sector on a Hill or land tile adjacent to a Mountain. Boulder Sectors cannot be adjacent.'),
('TXT_KEY_BUILD_CAPANO_BOULDER_SECTOR_REC','Boulder Sectors combine Science, Culture, and Production, train friendly military units, and make enemy movement awkward.'),
('TXT_KEY_IMPROVEMENT_CAPANO_BOULDER_SECTOR','Boulder Sector'),
('TXT_KEY_IMPROVEMENT_CAPANO_BOULDER_SECTOR_HELP','May be built on a Hill or on land adjacent to a Mountain and cannot be adjacent to another Boulder Sector. Base yields: [ICON_RESEARCH] +1 Science, [ICON_CULTURE] +1 Culture, [ICON_PRODUCTION] +1 Production. Guilds adds +1 Production; Education and Scientific Theory each add +1 Science; Architecture and Radio each add +1 Culture.[NEWLINE][NEWLINE]Capano units pay only 1 Movement to enter. Enemy units pay up to 1 additional Movement and suffer Awkward Sequence (-10% Combat Strength, becoming -12% at Architecture) until their next turn. A military unit ending its turn here trains once per Era for +5 XP and 10 turns of +10% Combat Strength in Rough Terrain. Training after Plastics marks the unit for +15% larger SEND yields.'),
('TXT_KEY_IMPROVEMENT_CAPANO_BOULDER_SECTOR_PEDIA','A Boulder Sector is a deliberately constructed collection of movements rather than a generic wall. Its Blue, Red, Purple, Black, and Yellow circuits mature with Construction, Guilds, Architecture, Scientific Theory, and Plastics, turning the landscape into both defensive puzzle and training library.'),

('TXT_KEY_PROMOTION_CAPANO_ROUTE_SETTER','Changing the Terrain'),
('TXT_KEY_PROMOTION_CAPANO_ROUTE_SETTER_HELP','Double movement through Hills. Hill Improvements are constructed 25% faster while the matching work mission is active.'),
('TXT_KEY_PROMOTION_CAPANO_SETTER_HILLS_WORK','Setter''s Pace'),
('TXT_KEY_PROMOTION_CAPANO_SETTER_HILLS_WORK_HELP','+25% Worker construction speed while building an Improvement on a Hill.'),
('TXT_KEY_PROMOTION_CAPANO_BETA_1','Beta I'),
('TXT_KEY_PROMOTION_CAPANO_BETA_1_HELP','Projecting one specific target. The next attempt against it gains +5% Combat Strength. Attacking anything else abandons the Project.'),
('TXT_KEY_PROMOTION_CAPANO_BETA_2','Beta II'),
('TXT_KEY_PROMOTION_CAPANO_BETA_2_HELP','Projecting one specific target. The next attempt against it gains +10% Combat Strength. Attacking anything else abandons the Project.'),
('TXT_KEY_PROMOTION_CAPANO_BETA_3','Beta III'),
('TXT_KEY_PROMOTION_CAPANO_BETA_3_HELP','Projecting one specific target. The next attempt against it gains +15% Combat Strength. Attacking anything else abandons the Project.'),
('TXT_KEY_PROMOTION_CAPANO_BETA_4','Solved Beta'),
('TXT_KEY_PROMOTION_CAPANO_BETA_4_HELP','The next attempt against this Project gains +20% Combat Strength. A qualifying victory becomes a SEND.'),
('TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_5','Beta: +5%'),
('TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_5_HELP','Temporary target-specific attack modifier.'),
('TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_10','Beta: +10%'),
('TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_10_HELP','Temporary target-specific attack modifier.'),
('TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_15','Beta: +15%'),
('TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_15_HELP','Temporary target-specific attack modifier.'),
('TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_20','Beta: +20%'),
('TXT_KEY_PROMOTION_CAPANO_BETA_ATTACK_20_HELP','Temporary target-specific attack modifier.'),
('TXT_KEY_PROMOTION_CAPANO_AWKWARD','Awkward Sequence'),
('TXT_KEY_PROMOTION_CAPANO_AWKWARD_BLUE_HELP','-10% Combat Strength until the beginning of this unit''s next turn.'),
('TXT_KEY_PROMOTION_CAPANO_AWKWARD_PURPLE_HELP','-12% Combat Strength until the beginning of this unit''s next turn. Surely this isn''t Purple.'),
('TXT_KEY_PROMOTION_CAPANO_READ_SEQUENCE','Read the Sequence'),
('TXT_KEY_PROMOTION_CAPANO_READ_SEQUENCE_HELP','+10% Combat Strength when attacking or defending in Rough Terrain. Expires 10 turns after Boulder Sector training.'),
('TXT_KEY_PROMOTION_CAPANO_COMPETITION_MOVEMENT','Competition Movement'),
('TXT_KEY_PROMOTION_CAPANO_COMPETITION_MOVEMENT_HELP','After moving across at least 2 tiles this turn, gain +15% Combat Strength when attacking until your next turn.'),
('TXT_KEY_PROMOTION_CAPANO_COMPETITION_ACTIVE','Competition Movement Active'),
('TXT_KEY_PROMOTION_CAPANO_COMPETITION_ACTIVE_HELP','+15% Combat Strength when attacking this turn.'),
('TXT_KEY_PROMOTION_CAPANO_FOOTWORK','Footwork'),
('TXT_KEY_PROMOTION_CAPANO_FOOTWORK_HELP','+10% Defense on Hills. Earned after 1 qualifying SEND.'),
('TXT_KEY_PROMOTION_CAPANO_BODY_POSITION','Body Position'),
('TXT_KEY_PROMOTION_CAPANO_BODY_POSITION_HELP','+10% Combat Strength while adjacent to at least two different terrain types. Earned after 2 qualifying SENDS.'),
('TXT_KEY_PROMOTION_CAPANO_BODY_ACTIVE','Body Position Active'),
('TXT_KEY_PROMOTION_CAPANO_BODY_ACTIVE_HELP','+10% Combat Strength from reading two or more adjacent terrain types.'),
('TXT_KEY_PROMOTION_CAPANO_COORDINATION','Coordination'),
('TXT_KEY_PROMOTION_CAPANO_COORDINATION_HELP','Regain 1 Movement after defeating an enemy as the attacker. Earned after 3 qualifying SENDS.'),
('TXT_KEY_PROMOTION_CAPANO_COMMIT','Commit'),
('TXT_KEY_PROMOTION_CAPANO_COMMIT_HELP','+15% Combat Strength when attacking below 50 HP. Earned after 4 qualifying SENDS.'),
('TXT_KEY_PROMOTION_CAPANO_COMMIT_ACTIVE','Commit Active'),
('TXT_KEY_PROMOTION_CAPANO_COMMIT_ACTIVE_HELP','+15% Combat Strength when attacking below 50 HP.'),
('TXT_KEY_PROMOTION_CAPANO_COMPLETE_CLIMBER','Complete Climber'),
('TXT_KEY_PROMOTION_CAPANO_COMPLETE_CLIMBER_HELP','+1 Movement and +10% Combat Strength. Ignores enemy Zone of Control while on Hills. Earned after 5 qualifying SENDS.'),
('TXT_KEY_PROMOTION_CAPANO_COMPLETE_HILLS','Complete Climber: Hills'),
('TXT_KEY_PROMOTION_CAPANO_COMPLETE_HILLS_HELP','Ignores enemy Zone of Control while on Hills.'),
('TXT_KEY_PROMOTION_CAPANO_YELLOW_CIRCUIT','Yellow Circuit'),
('TXT_KEY_PROMOTION_CAPANO_YELLOW_CIRCUIT_HELP','This unit trained on a Boulder Sector after Plastics. Its future SEND Science and Culture rewards are 15% larger.'),

('TXT_KEY_CAPANO_DAWN_OF_MAN','Enrico Capano, student of movement, competitor, climber and setter, the wall has followed you across the world. From your beginnings in Italy and the competition circuit to the stone of Australia and the walls of the Haus, every impossible sequence has become another lesson.[NEWLINE][NEWLINE]Your people do not fear failure. They study it. Let your setters create challenges worthy of those who attempt them. Teach your climbers to move rather than merely overpower. Turn every failed attempt into knowledge, every difficult enemy into a project, and every project eventually into a send.[NEWLINE][NEWLINE]Enrico, will you read the sequence that history has set before you?[NEWLINE][NEWLINE]Will you build a civilization that proves once again that the impossible is only impossible until it''s possible?'),
('TXT_KEY_CAPANO_SEND_NOTIFICATION','SEND! {1_UnitName} solved a worthy Project: +25 HP, +10 XP, +{2_Amount} Science and +{2_Amount} Culture.'),
('TXT_KEY_CAPANO_AMMAGAMMA_NOTIFICATION','AMMAGAMMA! {1_UnitName} sent a Project at least 50% stronger than its original base strength: +500 Science, +500 Culture, and a Golden Age.'),
('TXT_KEY_CAPANO_TRAINING_NOTIFICATION','{1_UnitName} completed this Era''s Boulder Sector: +5 XP and Read the Sequence for 10 turns.'),
('TXT_KEY_CAPANO_YELLOW_NOTIFICATION','{1_UnitName} learned the Yellow Circuit. Its SEND yields are permanently increased by 15%.'),

('TXT_KEY_DIPLOMODIFIER_CAPANO_RESPECT_SEND','They consistently overcome strong opponents.'),
('TXT_KEY_DIPLOMODIFIER_CAPANO_ABANDONED_PROJECT','They repeatedly begin wars and abandon them without a victory.'),
('TXT_KEY_DIPLOMODIFIER_CAPANO_STRONG_CLIMBERS','Their ranks contain many highly promoted units.'),

('TXT_KEY_CITY_NAME_CAPANO_HAUS','The Haus'),
('TXT_KEY_CITY_NAME_CAPANO_GRAMPIANS','The Grampians'),
('TXT_KEY_CITY_NAME_CAPANO_ARCO','Arco'),
('TXT_KEY_CITY_NAME_CAPANO_MELBOURNE','Melbourne'),
('TXT_KEY_CITY_NAME_CAPANO_AMMAGAMMA','Ammagamma'),
('TXT_KEY_CITY_NAME_CAPANO_DYNO','Dyno'),
('TXT_KEY_CITY_NAME_CAPANO_CRUX','Crux'),
('TXT_KEY_CITY_NAME_CAPANO_ARETE','Arete'),
('TXT_KEY_CITY_NAME_CAPANO_MANTLE','Mantle'),
('TXT_KEY_CITY_NAME_CAPANO_SLAB','Slab'),
('TXT_KEY_CITY_NAME_CAPANO_OVERHANG','Overhang'),
('TXT_KEY_CITY_NAME_CAPANO_TRAVERSE','Traverse'),
('TXT_KEY_CITY_NAME_CAPANO_BASECAMP','Basecamp'),
('TXT_KEY_CITY_NAME_CAPANO_SUMMIT','Summit'),
('TXT_KEY_CITY_NAME_CAPANO_BETA','Beta'),
('TXT_KEY_SPY_NAME_CAPANO_0','Spotter'),
('TXT_KEY_SPY_NAME_CAPANO_1','Setter'),
('TXT_KEY_SPY_NAME_CAPANO_2','Belayer'),
('TXT_KEY_SPY_NAME_CAPANO_3','Topo'),
('TXT_KEY_SPY_NAME_CAPANO_4','Crimp'),
('TXT_KEY_SPY_NAME_CAPANO_5','Dyno'),
('TXT_KEY_SPY_NAME_CAPANO_6','Send'),
('TXT_KEY_SPY_NAME_CAPANO_7','Chalk'),

('TXT_KEY_LEADER_CAPANO_FIRSTGREETING_1','Enrico. Welcome. If something looks impossible, you''re probably just missing the movement.'),
('TXT_KEY_LEADER_CAPANO_GREETING_POLITE_1','Good problems today?'),
('TXT_KEY_LEADER_CAPANO_GREETING_NEUTRAL_1','Still working it out?'),
('TXT_KEY_LEADER_CAPANO_GREETING_HOSTILE_1','You don''t need more strength. You need better beta.'),
('TXT_KEY_LEADER_CAPANO_GREETING_REPEAT_1','You''ve tried the same approach several times now.'),
('TXT_KEY_LEADER_CAPANO_DOW_1','Alright. Let''s see if you can solve this.'),
('TXT_KEY_LEADER_CAPANO_ATTACKED_1','Interesting. Another attempt.'),
('TXT_KEY_LEADER_CAPANO_DEFEATED_1','Nice. You found the beta.'),
('TXT_KEY_LEADER_CAPANO_PEACE_1','We have learned enough from this attempt. Step down, recover, and choose the next problem.'),
('TXT_KEY_LEADER_CAPANO_NO_PEACE_1','Not yet. The sequence is still unfinished.'),
('TXT_KEY_LEADER_CAPANO_TRADE_ACCEPT_1','Good movement. That works for both of us.'),
('TXT_KEY_LEADER_CAPANO_TRADE_REJECT_1','That beta does not solve the problem.'),
('TXT_KEY_LEADER_CAPANO_DENOUNCED_1','A loud opinion is not the same thing as a useful read.'),
('TXT_KEY_LEADER_CAPANO_WARNING_1','Your units are crowding the wall. Give the Circuit room.'),
('TXT_KEY_LEADER_CAPANO_REQUEST_1','A small adjustment now will make the whole sequence better.'),
('TXT_KEY_LEADER_CAPANO_PLEASED_1','Good send. I respect that.'),
('TXT_KEY_LEADER_CAPANO_DISAPPOINTED_1','You left the Project before learning anything from it.'),
('TXT_KEY_LEADER_CAPANO_OPEN_BORDERS_1','Open the circuit. Movement improves when people can compare routes.'),
('TXT_KEY_LEADER_CAPANO_LETS_HEAR_IT_1','Go on. Show me your beta.'),
('TXT_KEY_LEADER_CAPANO_SO_BE_IT_1','Alright. Another attempt.');

INSERT INTO Diplomacy_Responses(LeaderType,ResponseType,Response,Bias) VALUES
('LEADER_ENRICO_CAPANO','RESPONSE_FIRST_GREETING','TXT_KEY_LEADER_CAPANO_FIRSTGREETING%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_GREETING_POLITE_HELLO','TXT_KEY_LEADER_CAPANO_GREETING_POLITE%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_GREETING_NEUTRAL_HELLO','TXT_KEY_LEADER_CAPANO_GREETING_NEUTRAL%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_GREETING_HOSTILE_HELLO','TXT_KEY_LEADER_CAPANO_GREETING_HOSTILE%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_GREETING_REPEAT','TXT_KEY_LEADER_CAPANO_GREETING_REPEAT%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_DOW_GENERIC','TXT_KEY_LEADER_CAPANO_DOW%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_ATTACKED_HOSTILE','TXT_KEY_LEADER_CAPANO_ATTACKED%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_ATTACKED_EXCITED','TXT_KEY_LEADER_CAPANO_ATTACKED%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_ATTACKED_SAD','TXT_KEY_LEADER_CAPANO_ATTACKED%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_DEFEATED','TXT_KEY_LEADER_CAPANO_DEFEATED%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_PEACE_OFFER','TXT_KEY_LEADER_CAPANO_PEACE%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_NO_PEACE','TXT_KEY_LEADER_CAPANO_NO_PEACE%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_TRADE_ACCEPT_ACCEPTABLE','TXT_KEY_LEADER_CAPANO_TRADE_ACCEPT%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_TRADE_ACCEPT_GENEROUS','TXT_KEY_LEADER_CAPANO_TRADE_ACCEPT%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_TRADE_REJECT_UNACCEPTABLE','TXT_KEY_LEADER_CAPANO_TRADE_REJECT%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_TRADE_REJECT_INSULTING','TXT_KEY_LEADER_CAPANO_TRADE_REJECT%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_RESPONSE_TO_BEING_DENOUNCED','TXT_KEY_LEADER_CAPANO_DENOUNCED%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_AGGRESSIVE_MILITARY_WARNING','TXT_KEY_LEADER_CAPANO_WARNING%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_REQUEST','TXT_KEY_LEADER_CAPANO_REQUEST%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_PLEASED','TXT_KEY_LEADER_CAPANO_PLEASED%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_DISAPPOINTED','TXT_KEY_LEADER_CAPANO_DISAPPOINTED%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_OPEN_BORDERS_EXCHANGE','TXT_KEY_LEADER_CAPANO_OPEN_BORDERS%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_LETS_HEAR_IT','TXT_KEY_LEADER_CAPANO_LETS_HEAR_IT%',1),
('LEADER_ENRICO_CAPANO','RESPONSE_SO_BE_IT','TXT_KEY_LEADER_CAPANO_SO_BE_IT%',1);
