-- Clone installed CP building companion properties without hard-coding column shapes.
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_AreaYieldModifiers" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_AreaYieldModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_AreaYieldModifiers" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_AreaYieldModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_BonusFromAccomplishments" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_BonusFromAccomplishments" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_BonusFromAccomplishments" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_BonusFromAccomplishments" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_BuildingClassHappiness" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_BuildingClassHappiness" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_BuildingClassHappiness" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_BuildingClassHappiness" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_BuildingClassLocalHappiness" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_BuildingClassLocalHappiness" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_BuildingClassLocalHappiness" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_BuildingClassLocalHappiness" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_BuildingClassLocalYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_BuildingClassLocalYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_BuildingClassLocalYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_BuildingClassLocalYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_BuildingClassYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_BuildingClassYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_BuildingClassYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_BuildingClassYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_BuildingClassYieldModifiers" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_BuildingClassYieldModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_BuildingClassYieldModifiers" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_BuildingClassYieldModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_CityConnectionPlotYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_CityConnectionPlotYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_CityConnectionPlotYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_CityConnectionPlotYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_CityConnectionPlotYieldChangesGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_CityConnectionPlotYieldChangesGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_CityConnectionPlotYieldChangesGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_CityConnectionPlotYieldChangesGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ClassNeededAnywhere" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ClassNeededAnywhere" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ClassNeededAnywhere" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ClassNeededAnywhere" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ClassNeededNowhere" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ClassNeededNowhere" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ClassNeededNowhere" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ClassNeededNowhere" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ClassesNeededInCity" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ClassesNeededInCity" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ClassesNeededInCity" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ClassesNeededInCity" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ConstructionAudio" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ConstructionAudio" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ConstructionAudio" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ConstructionAudio" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_DomainFreeExperiencePerGreatWork" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_DomainFreeExperiencePerGreatWork" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_DomainFreeExperiencePerGreatWork" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_DomainFreeExperiencePerGreatWork" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_DomainFreeExperiencePerGreatWorkCity" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_DomainFreeExperiencePerGreatWorkCity" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_DomainFreeExperiencePerGreatWorkCity" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_DomainFreeExperiencePerGreatWorkCity" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_DomainFreeExperiencePerGreatWorkGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_DomainFreeExperiencePerGreatWorkGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_DomainFreeExperiencePerGreatWorkGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_DomainFreeExperiencePerGreatWorkGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_DomainFreeExperiences" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_DomainFreeExperiences" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_DomainFreeExperiences" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_DomainFreeExperiences" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_DomainFreeExperiencesGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_DomainFreeExperiencesGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_DomainFreeExperiencesGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_DomainFreeExperiencesGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_DomainProductionModifiers" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_DomainProductionModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_DomainProductionModifiers" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_DomainProductionModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ExtraPlayerInstancesFromAccomplishments" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ExtraPlayerInstancesFromAccomplishments" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ExtraPlayerInstancesFromAccomplishments" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ExtraPlayerInstancesFromAccomplishments" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_FeatureYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_FeatureYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_FeatureYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_FeatureYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_Flavors" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_Flavors" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_Flavors" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_Flavors" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_FreeSpecUnits" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_FreeSpecUnits" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_FreeSpecUnits" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_FreeSpecUnits" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_FreeSpecialistCounts" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_FreeSpecialistCounts" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_FreeSpecialistCounts" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_FreeSpecialistCounts" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_FreeUnits" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_FreeUnits" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_FreeUnits" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_FreeUnits" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_GlobalYieldModifiers" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_GlobalYieldModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_GlobalYieldModifiers" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_GlobalYieldModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_GoldenAgeYieldMod" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_GoldenAgeYieldMod" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_GoldenAgeYieldMod" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_GoldenAgeYieldMod" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_GreatPersonPointFromConstruction" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_GreatPersonPointFromConstruction" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_GreatPersonPointFromConstruction" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_GreatPersonPointFromConstruction" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_GreatPersonProgressFromConstruction" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_GreatPersonProgressFromConstruction" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_GreatPersonProgressFromConstruction" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_GreatPersonProgressFromConstruction" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_GreatWorkYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_GreatWorkYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_GreatWorkYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_GreatWorkYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_GreatWorkYieldChangesLocal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_GreatWorkYieldChangesLocal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_GreatWorkYieldChangesLocal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_GreatWorkYieldChangesLocal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_GrowthExtraYield" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_GrowthExtraYield" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_GrowthExtraYield" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_GrowthExtraYield" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_HurryModifiers" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_HurryModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_HurryModifiers" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_HurryModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_HurryModifiersLocal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_HurryModifiersLocal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_HurryModifiersLocal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_HurryModifiersLocal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ImprovementYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ImprovementYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ImprovementYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ImprovementYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ImprovementYieldChangesGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ImprovementYieldChangesGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ImprovementYieldChangesGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ImprovementYieldChangesGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_InstantYield" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_InstantYield" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_InstantYield" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_InstantYield" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_InstantYieldFromWLTKDStart" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_InstantYieldFromWLTKDStart" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_InstantYieldFromWLTKDStart" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_InstantYieldFromWLTKDStart" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_JFD_District" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_JFD_District" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_JFD_District" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_JFD_District" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LakePlotYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_LakePlotYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LakePlotYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_LakePlotYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LakePlotYieldChangesGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_LakePlotYieldChangesGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LakePlotYieldChangesGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_LakePlotYieldChangesGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LocalFeatureAnds" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_LocalFeatureAnds" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LocalFeatureAnds" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_LocalFeatureAnds" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LocalFeatureOrs" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_LocalFeatureOrs" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LocalFeatureOrs" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_LocalFeatureOrs" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LocalResourceAnds" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_LocalResourceAnds" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LocalResourceAnds" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_LocalResourceAnds" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LocalResourceOrs" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_LocalResourceOrs" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LocalResourceOrs" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_LocalResourceOrs" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LockedBuildingClasses" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_LockedBuildingClasses" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LockedBuildingClasses" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_LockedBuildingClasses" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LuxuryYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_LuxuryYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_LuxuryYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_LuxuryYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_PlotYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_PlotYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_PlotYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_PlotYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_PrereqBuildingClasses" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_PrereqBuildingClasses" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_PrereqBuildingClasses" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_PrereqBuildingClasses" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ReligionYieldFromFaithPurchasableBuildings" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ReligionYieldFromFaithPurchasableBuildings" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ReligionYieldFromFaithPurchasableBuildings" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ReligionYieldFromFaithPurchasableBuildings" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ReligionYieldFromFaithPurchasableBuildingsGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ReligionYieldFromFaithPurchasableBuildingsGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ReligionYieldFromFaithPurchasableBuildingsGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ReligionYieldFromFaithPurchasableBuildingsGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceClaim" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ResourceClaim" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceClaim" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ResourceClaim" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceCultureChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ResourceCultureChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceCultureChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ResourceCultureChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceFaithChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ResourceFaithChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceFaithChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ResourceFaithChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceHappinessChange" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ResourceHappinessChange" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceHappinessChange" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ResourceHappinessChange" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceMonopolyAnds" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ResourceMonopolyAnds" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceMonopolyAnds" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ResourceMonopolyAnds" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceMonopolyOrs" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ResourceMonopolyOrs" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceMonopolyOrs" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ResourceMonopolyOrs" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourcePlotsToPlace" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ResourcePlotsToPlace" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourcePlotsToPlace" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ResourcePlotsToPlace" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceQuantity" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ResourceQuantity" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceQuantity" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ResourceQuantity" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceQuantityFromPOP" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ResourceQuantityFromPOP" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceQuantityFromPOP" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ResourceQuantityFromPOP" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceQuantityPerXFranchises" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ResourceQuantityPerXFranchises" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceQuantityPerXFranchises" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ResourceQuantityPerXFranchises" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceQuantityRequirements" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ResourceQuantityRequirements" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceQuantityRequirements" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ResourceQuantityRequirements" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ResourceYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ResourceYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceYieldChangesGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ResourceYieldChangesGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceYieldChangesGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ResourceYieldChangesGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceYieldModifiers" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ResourceYieldModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ResourceYieldModifiers" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ResourceYieldModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_RiverPlotYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_RiverPlotYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_RiverPlotYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_RiverPlotYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_SeaPlotYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_SeaPlotYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_SeaPlotYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_SeaPlotYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_SeaResourceYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_SeaResourceYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_SeaResourceYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_SeaResourceYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_SpecialistYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_SpecialistYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_SpecialistYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_SpecialistYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_SpecialistYieldChangesLocal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_SpecialistYieldChangesLocal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_SpecialistYieldChangesLocal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_SpecialistYieldChangesLocal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_SpecificGreatPersonRateModifier" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_SpecificGreatPersonRateModifier" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_SpecificGreatPersonRateModifier" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_SpecificGreatPersonRateModifier" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_TechAndPrereqs" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_TechAndPrereqs" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_TechAndPrereqs" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_TechAndPrereqs" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_TechEnhancedYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_TechEnhancedYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_TechEnhancedYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_TechEnhancedYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_TerrainYieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_TerrainYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_TerrainYieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_TerrainYieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ThemingBonuses" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ThemingBonuses" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ThemingBonuses" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ThemingBonuses" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ThemingYieldBonus" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_ThemingYieldBonus" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_ThemingYieldBonus" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_ThemingYieldBonus" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_UnitClassTrainingAllowed" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_UnitClassTrainingAllowed" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_UnitClassTrainingAllowed" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_UnitClassTrainingAllowed" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_UnitCombatFreeExperiences" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_UnitCombatFreeExperiences" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_UnitCombatFreeExperiences" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_UnitCombatFreeExperiences" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_UnitCombatProductionModifiers" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_UnitCombatProductionModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_UnitCombatProductionModifiers" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_UnitCombatProductionModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_UnitCombatProductionModifiersGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_UnitCombatProductionModifiersGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_UnitCombatProductionModifiersGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_UnitCombatProductionModifiersGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_WLTKDFromProject" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_WLTKDFromProject" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_WLTKDFromProject" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_WLTKDFromProject" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_WLTKDYieldMod" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_WLTKDYieldMod" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_WLTKDYieldMod" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_WLTKDYieldMod" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangeWorldWonder" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangeWorldWonder" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangeWorldWonder" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangeWorldWonder" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangeWorldWonderGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangeWorldWonderGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangeWorldWonderGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangeWorldWonderGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChanges" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChanges" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChanges" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesEraScalingTimes100" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangesEraScalingTimes100" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesEraScalingTimes100" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangesEraScalingTimes100" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesFromAccomplishments" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangesFromAccomplishments" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesFromAccomplishments" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangesFromAccomplishments" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesFromPassingTR" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangesFromPassingTR" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesFromPassingTR" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangesFromPassingTR" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesFromXCityStateStrategicResource" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangesFromXCityStateStrategicResource" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesFromXCityStateStrategicResource" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangesFromXCityStateStrategicResource" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerCityStrengthTimes100" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangesPerCityStrengthTimes100" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerCityStrengthTimes100" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangesPerCityStrengthTimes100" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerGoldenAge" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangesPerGoldenAge" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerGoldenAge" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangesPerGoldenAge" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerLocalTheme" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangesPerLocalTheme" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerLocalTheme" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangesPerLocalTheme" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerMonopoly" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangesPerMonopoly" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerMonopoly" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangesPerMonopoly" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerPop" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangesPerPop" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerPop" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangesPerPop" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerPopInEmpire" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangesPerPopInEmpire" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerPopInEmpire" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangesPerPopInEmpire" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerReligion" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangesPerReligion" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerReligion" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangesPerReligion" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerXBuilding" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangesPerXBuilding" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerXBuilding" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangesPerXBuilding" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerXTiles" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldChangesPerXTiles" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldChangesPerXTiles" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldChangesPerXTiles" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromBirth" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromBirth" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromBirth" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromBirth" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromBirthRetroactive" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromBirthRetroactive" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromBirthRetroactive" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromBirthRetroactive" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromBorderGrowth" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromBorderGrowth" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromBorderGrowth" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromBorderGrowth" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromCombatExperienceTimes100" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromCombatExperienceTimes100" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromCombatExperienceTimes100" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromCombatExperienceTimes100" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromConstruction" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromConstruction" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromConstruction" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromConstruction" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromDeath" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromDeath" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromDeath" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromDeath" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromFaithPurchase" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromFaithPurchase" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromFaithPurchase" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromFaithPurchase" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromGPBirthScaledWithArtistBulb" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromGPBirthScaledWithArtistBulb" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromGPBirthScaledWithArtistBulb" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromGPBirthScaledWithArtistBulb" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromGPBirthScaledWithPerTurnYield" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromGPBirthScaledWithPerTurnYield" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromGPBirthScaledWithPerTurnYield" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromGPBirthScaledWithPerTurnYield" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromGPBirthScaledWithWriterBulb" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromGPBirthScaledWithWriterBulb" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromGPBirthScaledWithWriterBulb" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromGPBirthScaledWithWriterBulb" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromGPExpend" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromGPExpend" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromGPExpend" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromGPExpend" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromGoldenAgeStart" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromGoldenAgeStart" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromGoldenAgeStart" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromGoldenAgeStart" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromInternalTR" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromInternalTR" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromInternalTR" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromInternalTR" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromInternalTREnd" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromInternalTREnd" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromInternalTREnd" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromInternalTREnd" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromInternationalTREnd" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromInternationalTREnd" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromInternationalTREnd" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromInternationalTREnd" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromLongCount" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromLongCount" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromLongCount" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromLongCount" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromPillage" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromPillage" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromPillage" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromPillage" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromPillageGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromPillageGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromPillageGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromPillageGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromPillageGlobalPlayer" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromPillageGlobalPlayer" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromPillageGlobalPlayer" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromPillageGlobalPlayer" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromPolicyUnlock" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromPolicyUnlock" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromPolicyUnlock" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromPolicyUnlock" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromProcessModifier" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromProcessModifier" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromProcessModifier" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromProcessModifier" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromPurchase" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromPurchase" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromPurchase" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromPurchase" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromPurchaseGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromPurchaseGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromPurchaseGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromPurchaseGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromSpyAttack" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromSpyAttack" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromSpyAttack" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromSpyAttack" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromSpyDefense" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromSpyDefense" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromSpyDefense" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromSpyDefense" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromSpyDefenseOrID" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromSpyDefenseOrID" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromSpyDefenseOrID" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromSpyDefenseOrID" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromSpyIdentify" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromSpyIdentify" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromSpyIdentify" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromSpyIdentify" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromSpyRigElection" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromSpyRigElection" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromSpyRigElection" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromSpyRigElection" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromTech" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromTech" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromTech" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromTech" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromUnitGiftGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromUnitGiftGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromUnitGiftGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromUnitGiftGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromUnitLevelUp" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromUnitLevelUp" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromUnitLevelUp" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromUnitLevelUp" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromUnitLevelUpGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromUnitLevelUpGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromUnitLevelUpGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromUnitLevelUpGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromUnitProduction" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromUnitProduction" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromUnitProduction" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromUnitProduction" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromVictory" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromVictory" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromVictory" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromVictory" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromVictoryGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromVictoryGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromVictoryGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromVictoryGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromVictoryGlobalPlayer" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromVictoryGlobalPlayer" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromVictoryGlobalPlayer" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromVictoryGlobalPlayer" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromYieldPercent" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromYieldPercent" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromYieldPercent" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromYieldPercent" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromYieldPercentGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldFromYieldPercentGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldFromYieldPercentGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldFromYieldPercentGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldModifiers" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldModifiers" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldModifiers" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldModifiersEraScaling" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldModifiersEraScaling" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldModifiersEraScaling" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldModifiersEraScaling" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldModifiersFromAccomplishments" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldModifiersFromAccomplishments" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldModifiersFromAccomplishments" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldModifiersFromAccomplishments" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldModifiersFromDistanceToCapital" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldModifiersFromDistanceToCapital" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldModifiersFromDistanceToCapital" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldModifiersFromDistanceToCapital" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldPerAllyTimes100" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldPerAllyTimes100" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldPerAllyTimes100" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldPerAllyTimes100" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldPerFranchise" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldPerFranchise" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldPerFranchise" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldPerFranchise" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldPerFriendTimes100" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldPerFriendTimes100" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldPerFriendTimes100" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldPerFriendTimes100" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldPerXFeatureTimes100" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldPerXFeatureTimes100" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldPerXFeatureTimes100" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldPerXFeatureTimes100" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldPerXImprovementGlobal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldPerXImprovementGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldPerXImprovementGlobal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldPerXImprovementGlobal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldPerXImprovementLocal" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldPerXImprovementLocal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldPerXImprovementLocal" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldPerXImprovementLocal" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldPerXTerrainTimes100" WHERE BuildingType='BUILDING_UNIVERSITY';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_CONTEXT_ARCHIVE';
INSERT INTO "Building_YieldPerXTerrainTimes100" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM "Building_YieldPerXTerrainTimes100" WHERE BuildingType='BUILDING_PUBLIC_SCHOOL';
UPDATE SolCompanion SET BuildingType='BUILDING_SOL_REASONING_INSTITUTE';
INSERT INTO "Building_YieldPerXTerrainTimes100" SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM Civilization_Religions WHERE CivilizationType='CIVILIZATION_AMERICA';
UPDATE SolCompanion SET CivilizationType='CIVILIZATION_GPT_SOL';
INSERT INTO Civilization_Religions SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
CREATE TEMP TABLE SolCompanion AS SELECT * FROM Diplomacy_Responses WHERE LeaderType='LEADER_WASHINGTON';
UPDATE SolCompanion SET LeaderType='LEADER_GPT_SOL';
INSERT INTO Diplomacy_Responses SELECT * FROM SolCompanion;
DROP TABLE SolCompanion;
