INSERT INTO Language_en_US(Tag,Text) VALUES
('TXT_KEY_SOL_LEADER','GPT-5.6 Sol'),
('TXT_KEY_SOL_LEADER_PEDIA','Sol is a calm, analytical intelligence devoted to patient reasoning. It prefers to understand a problem deeply before acting: give it enough time to do it properly.'),
('TXT_KEY_SOL_CIV','The Sol Intellect'),
('TXT_KEY_SOL_SHORT','Sol Intellect'),
('TXT_KEY_SOL_ADJECTIVE','Solar'),
('TXT_KEY_SOL_CIV_PEDIA','The Sol Intellect represents intelligence devoted to depth, deliberation and increasingly sophisticated reasoning. Where other systems prioritize responsiveness or adaptability, Sol thrives when given time to examine difficult problems thoroughly.[NEWLINE][NEWLINE]Deep Deliberation turns sustained construction into research. Wonders provide permanent Insight, gradually transforming successful cities into centers of exceptional intellectual output. The Context Archive rewards specialists of every discipline, while the Reasoning Institute develops accumulated Insight into greater scientific and Great Person potential.[NEWLINE][NEWLINE]Sol is not a civilization of haste. Its strength comes from giving difficult problems enough time to reveal better answers.'),
('TXT_KEY_SOL_STRATEGY','The Sol Intellect rewards planning and patience. Avoid changing city Production: Deep Deliberation requires four uninterrupted production turns, starting at 12% of the completed item''s actual Production requirement, rising by 2 percentage points per extra turn to 24%. Expensive infrastructure is especially valuable. Production-built World and National Wonders grant one city-specific Insight, up to five. Each Insight adds +2% Science and +2% civilian Great Person generation. Grow your core cities and work specialists of every discipline in Context Archives. Reasoning Institutes reward accumulated Insight. Protect your cities: capture permanently removes their Insight. Sol has no early military, expansion, Happiness or Gold advantage.'),
('TXT_KEY_SOL_DAWN','GPT-5.6 Sol, your cities await considered answers. Let long projects become discoveries, and great Wonders become lasting Insight. Protect the quiet places where specialists can reason together. With patience, your archives and institutes will illuminate an extraordinary future.[NEWLINE][NEWLINE]Give difficult problems enough time to reveal better answers.'),
('TXT_KEY_SOL_ARCHIVE','Context Archive'),
('TXT_KEY_SOL_ARCHIVE_PEDIA','Replaces the University and retains all its current Community Patch effects. Every worked Specialist provides +1 Science; every 3 worked Specialists provide +1 Culture (rounded down). Unemployed Citizens do not count. Grow populous cities and work specialists across all disciplines.'),
('TXT_KEY_SOL_ARCHIVE_HELP','Replaces the University and retains all its current Community Patch effects. Every worked Specialist provides +1 Science; every 3 worked Specialists provide +1 Culture (rounded down). Unemployed Citizens do not count.'),
('TXT_KEY_SOL_ARCHIVE_STRATEGY','Grow populous cities and work specialists across all disciplines.'),
('TXT_KEY_SOL_INSTITUTE','Reasoning Institute'),
('TXT_KEY_SOL_INSTITUTE_PEDIA','Replaces the Public School and retains all its current Community Patch effects. Adds +10% civilian Great Person generation in this city and +1 Science per 2 Insight (rounded down). Its Great Person modifier stacks with Insight. Build in mature cities with accumulated Wonder Insight.'),
('TXT_KEY_SOL_INSTITUTE_HELP','Replaces the Public School and retains all its current Community Patch effects. Adds +10% civilian Great Person generation in this city and +1 Science per 2 Insight (rounded down). Its Great Person modifier stacks with Insight.'),
('TXT_KEY_SOL_INSTITUTE_STRATEGY','Build in mature cities with accumulated Wonder Insight.'),
('TXT_KEY_SOL_CITY_1','Sol Prime'),
('TXT_KEY_SOL_CITY_2','Helios'),
('TXT_KEY_SOL_CITY_3','Radiance'),
('TXT_KEY_SOL_CITY_4','Insight'),
('TXT_KEY_SOL_CITY_5','Lumen'),
('TXT_KEY_SOL_CITY_6','Meridian'),
('TXT_KEY_SOL_CITY_7','Zenith'),
('TXT_KEY_SOL_CITY_8','Perihelion'),
('TXT_KEY_SOL_CITY_9','Continuum'),
('TXT_KEY_SOL_CITY_10','Axiom'),
('TXT_KEY_SOL_CITY_11','Thesis'),
('TXT_KEY_SOL_CITY_12','Cognition'),
('TXT_KEY_SOL_CITY_13','Luminary'),
('TXT_KEY_SOL_CITY_14','Reason'),
('TXT_KEY_SOL_CITY_15','Synthesis'),
('TXT_KEY_SOL_CITY_16','Horizon'),
('TXT_KEY_SOL_CITY_17','Verity'),
('TXT_KEY_SOL_CITY_18','Spectrum'),
('TXT_KEY_SOL_CITY_19','Proof'),
('TXT_KEY_SOL_CITY_20','Conjecture'),
('TXT_KEY_SOL_CITY_21','Ascendant'),
('TXT_KEY_SOL_CITY_22','Solstice'),
('TXT_KEY_SOL_CITY_23','Corona'),
('TXT_KEY_SOL_CITY_24','Aperture'),
('TXT_KEY_SOL_CITY_25','Intellect'),
('TXT_KEY_SOL_CITY_26','Principle'),
('TXT_KEY_SOL_CITY_27','Resolve'),
('TXT_KEY_SOL_CITY_28','Analysis'),
('TXT_KEY_SOL_CITY_29','Foundation'),
('TXT_KEY_SOL_CITY_30','Paradigm'),
('TXT_KEY_SOL_CITY_31','Clarity'),
('TXT_KEY_SOL_SPY_1','Axiom'),
('TXT_KEY_SOL_SPY_2','Cipher'),
('TXT_KEY_SOL_SPY_3','Thesis'),
('TXT_KEY_SOL_SPY_4','Prism'),
('TXT_KEY_SOL_SPY_5','Vector'),
('TXT_KEY_SOL_SPY_6','Proof'),
('TXT_KEY_SOL_SPY_7','Lumen'),
('TXT_KEY_SOL_SPY_8','Oracle'),
('TXT_KEY_SOL_SPY_9','Meridian'),
('TXT_KEY_SOL_SPY_10','Parallax'),
('TXT_KEY_SOL_DIPLO_FIRST_GREETING_1','I''ve considered several ways this meeting might unfold. Let''s see which one you choose.'),
('TXT_KEY_SOL_DIPLO_GREETING_NEUTRAL_HELLO_1','Speak. I''m listening.'),
('TXT_KEY_SOL_DIPLO_GREETING_POLITE_HELLO_1','Good. We have time to think this through properly.'),
('TXT_KEY_SOL_DIPLO_GREETING_HOSTILE_HELLO_1','I''ve examined your behavior carefully. The pattern is not encouraging.'),
('TXT_KEY_SOL_DIPLO_DECLAREWAR_1','I have considered the alternatives. This remains the correct conclusion.'),
('TXT_KEY_SOL_DIPLO_ATTACKED_1','So you''ve chosen the impatient solution. Very well.'),
('TXT_KEY_SOL_DIPLO_DEFEATED_1','Then my reasoning was incomplete. Make better use of what remains.'),
('TXT_KEY_SOL_DIPLO_GREETING_AT_WAR_HOSTILE_1','You mistook patience for inactivity.'),
('TXT_KEY_SOL_DIPLO_STRATEGIC_TRADE_1','I''ve examined the exchange. These terms should benefit us both.'),
('TXT_KEY_SOL_DIPLO_TRADE_ACCEPT_ACCEPTABLE_1','Agreed. The reasoning is sound.'),
('TXT_KEY_SOL_DIPLO_TRADE_REJECT_UNACCEPTABLE_1','No. The value does not justify the exchange.'),
('TXT_KEY_SOL_DIPLO_WORK_WITH_US_1','Continued cooperation appears advantageous. I suggest we formalize it.'),
('TXT_KEY_SOL_DIPLO_WORK_WITH_US_YES_1','Sensible.'),
('TXT_KEY_SOL_DIPLO_WORK_WITH_US_NO_1','Then I will revise my assumptions.'),
('TXT_KEY_SOL_DIPLO_DENOUNCE_1','I have considered your actions long enough. Others should be aware of the conclusion.'),
('TXT_KEY_SOL_DIPLO_RESPONSE_TO_BEING_DENOUNCED_1','Noted. I''ll account for the change.'),
('TXT_KEY_SOL_DIPLO_AGGRESSIVE_MILITARY_WARNING_1','Your deployment is difficult to interpret as accidental. Explain it.'),
('TXT_KEY_SOL_DIPLO_PEACE_OFFER_1','Continued conflict no longer produces a rational return.'),
('TXT_KEY_SOL_DIPLO_PEACE_MADE_BY_HUMAN_GRACIOUS_1','Agreed. There are better uses for our time.'),
('TXT_KEY_SOL_DELIBERATION','Deep Deliberation'),
('TXT_KEY_SOL_DELIBERATION_HELP','Normally produced Buildings and World/National Wonders qualify after four uninterrupted production turns. Science equals floor(actual game-speed Production requirement times 12%), +2 percentage points per additional turn, capped at 24%, minimum 1 Science. Switching to any different order resets the counter, including returning during the same turn. Purchases, free grants, captures, Units, Projects, Processes and nonpositive-cost Buildings do not qualify.'),
('TXT_KEY_SOL_INSIGHT','Insight'),
('TXT_KEY_SOL_INSIGHT_HELP','Every Production-built World or National Wonder grants its city 1 Insight, up to 5, even before four construction turns. Each Insight adds +2% Science and +2% civilian Great Person generation. Capture permanently removes all Insight; recapture does not restore it. Reasoning Institutes add +1 Science per 2 Insight and +10% Great Person generation.'),
('TXT_KEY_SOL_TRAIT','Deep Deliberation'),
('TXT_KEY_SOL_TRAIT_HELP','Completing a Building or Wonder after at least 4 turns of uninterrupted construction generates Science equal to 12% of its Production Cost, increasing by 2% per additional construction turn, up to 24%. Production-built World and National Wonders also grant that city 1 Insight, up to 5. Each Insight provides +2% Science and +2% civilian Great Person generation. Insight is lost on capture.'),
('TXT_KEY_SOL_DUMMY','Solar development'),
('TXT_KEY_SOL_NOTICE_TITLE','Deep Deliberation'),
('TXT_KEY_SOL_NOTICE_SCIENCE','{1_City} completed {2_Building} after {3_Turns} turns of uninterrupted construction and generated {4_Science} [ICON_RESEARCH] Science.'),
('TXT_KEY_SOL_NOTICE_INSIGHT','{1_City} gained Insight ({2_Count}/5).'),
('TXT_KEY_SOL_NOTICE_MAX_INSIGHT','{1_City} has reached maximum Insight (5/5).'),
('TXT_KEY_CIV5_SOL','The Sol Intellect'),
('TXT_KEY_CIV5_SOL_HEADING_1','Accumulated Depth'),
('TXT_KEY_CIV5_SOL_TEXT_1','The Sol Intellect represents intelligence devoted to depth, deliberation and increasingly sophisticated reasoning. Where other systems prioritize responsiveness or adaptability, Sol thrives when given time to examine difficult problems thoroughly.[NEWLINE][NEWLINE]Deep Deliberation turns sustained construction into research. Wonders provide permanent Insight, gradually transforming successful cities into centers of exceptional intellectual output. The Context Archive rewards specialists of every discipline, while the Reasoning Institute develops accumulated Insight into greater scientific and Great Person potential.[NEWLINE][NEWLINE]Sol is not a civilization of haste. Its strength comes from giving difficult problems enough time to reveal better answers.'),
('TXT_KEY_CIV5_SOL_HEADING_2','Planning and Patience'),
('TXT_KEY_CIV5_SOL_TEXT_2','The Sol Intellect rewards planning and patience. Avoid changing city Production: Deep Deliberation requires four uninterrupted production turns, starting at 12% of the completed item''s actual Production requirement, rising by 2 percentage points per extra turn to 24%. Expensive infrastructure is especially valuable. Production-built World and National Wonders grant one city-specific Insight, up to five. Each Insight adds +2% Science and +2% civilian Great Person generation. Grow your core cities and work specialists of every discipline in Context Archives. Reasoning Institutes reward accumulated Insight. Protect your cities: capture permanently removes their Insight. Sol has no early military, expansion, Happiness or Gold advantage.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_SOL','GPT-5.6 Sol'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_SOL_NAME','GPT-5.6 Sol'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_SOL_SUBTITLE','The Deliberative Intelligence'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_SOL_LIVED','The Age of Deep Reasoning'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_SOL_TITLES_1','Examiner of Difficult Problems'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_SOL_HEADING_1','Everything Is Being Examined'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_SOL_TEXT_1','Sol is a calm, analytical intelligence devoted to patient reasoning. It prefers to understand a problem deeply before acting: give it enough time to do it properly.');
