-- Community Patch v151. Enable hooks used here; never disable another mod's hooks.
UPDATE CustomModOptions SET Value=1 WHERE Name IN
('EVENTS_BATTLES','EVENTS_CITY','EVENTS_UNIT_CREATED','EVENTS_UNIT_UPGRADES','EVENTS_PARADROPS','EVENTS_WAR_AND_PEACE','EVENTS_RED_COMBAT','EVENTS_RED_COMBAT_RESULT');
INSERT INTO Colors(Type,Red,Green,Blue,Alpha) VALUES ('COLOR_VILTRUM_CRIMSON',0.48,0.025,0.04,1);
INSERT INTO Colors(Type,Red,Green,Blue,Alpha) VALUES ('COLOR_VILTRUM_WHITE',0.96,0.96,0.93,1);
INSERT INTO PlayerColors(Type,PrimaryColor,SecondaryColor,TextColor) VALUES
('PLAYERCOLOR_VILTRUM','COLOR_VILTRUM_CRIMSON','COLOR_VILTRUM_WHITE','COLOR_PLAYER_WHITE_TEXT');
INSERT INTO Traits(Type,Description,ShortDescription) VALUES ('TRAIT_VILTRUM_CONQUEST','TXT_KEY_VILTRUM_TRAIT_HELP','TXT_KEY_VILTRUM_TRAIT');
CREATE TEMP TABLE VILTRUM_Clone AS SELECT * FROM Leaders WHERE Type='LEADER_WASHINGTON';
UPDATE VILTRUM_Clone SET ID=NULL,Type='LEADER_VILTRUM_THRAGG',Description='TXT_KEY_VILTRUM_LEADER',Civilopedia='TXT_KEY_VILTRUM_LEADER_PEDIA',CivilopediaTag='TXT_KEY_CIVILOPEDIA_LEADERS_VILTRUM',ArtDefineTag='ViltrumLeaderScene.xml',PortraitIndex=1,IconAtlas='VILTRUM_ICON_ATLAS',PackageID=NULL,VictoryCompetitiveness=10,WonderCompetitiveness=2,MinorCivCompetitiveness=8,Boldness=10,DiploBalance=2,WarmongerHate=0,DoFWillingness=2,Meanness=10;
INSERT INTO Leaders SELECT * FROM VILTRUM_Clone;
DROP TABLE VILTRUM_Clone;
INSERT INTO Leader_Traits VALUES ('LEADER_VILTRUM_THRAGG','TRAIT_VILTRUM_CONQUEST');
CREATE TEMP TABLE VILTRUM_Clone AS SELECT * FROM Civilizations WHERE Type='CIVILIZATION_AMERICA';
UPDATE VILTRUM_Clone SET ID=NULL,Type='CIVILIZATION_VILTRUM',Description='TXT_KEY_VILTRUM_CIV',ShortDescription='TXT_KEY_VILTRUM_SHORT',Adjective='TXT_KEY_VILTRUM_ADJECTIVE',Civilopedia='TXT_KEY_VILTRUM_CIV_PEDIA',CivilopediaTag='TXT_KEY_CIV5_VILTRUM',Strategy='TXT_KEY_VILTRUM_STRATEGY',DefaultPlayerColor='PLAYERCOLOR_VILTRUM',Playable=1,AIPlayable=0,PackageID=NULL,PortraitIndex=0,IconAtlas='VILTRUM_ICON_ATLAS',AlphaIconAtlas='VILTRUM_ALPHA_ATLAS',MapImage='ViltrumMap.dds',DawnOfManImage='ViltrumDawn.dds',DawnOfManQuote='TXT_KEY_VILTRUM_DAWN',DawnOfManAudio='',SoundtrackTag='ROME';
INSERT INTO Civilizations SELECT * FROM VILTRUM_Clone;
DROP TABLE VILTRUM_Clone;
INSERT INTO Civilization_Leaders VALUES ('CIVILIZATION_VILTRUM','LEADER_VILTRUM_THRAGG');
INSERT INTO Civilization_FreeBuildingClasses SELECT 'CIVILIZATION_VILTRUM',BuildingClassType FROM Civilization_FreeBuildingClasses WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_FreeTechs SELECT 'CIVILIZATION_VILTRUM',TechType FROM Civilization_FreeTechs WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_FreeUnits(CivilizationType,UnitClassType,UnitAIType,Count) SELECT 'CIVILIZATION_VILTRUM',UnitClassType,UnitAIType,Count FROM Civilization_FreeUnits WHERE CivilizationType='CIVILIZATION_AMERICA';
CREATE TEMP TABLE VILTRUM_Clone AS SELECT * FROM Units WHERE Type='UNIT_INFANTRY';
UPDATE VILTRUM_Clone SET ID=NULL,Type='UNIT_VILTRUM_WARRIOR',Description='TXT_KEY_VILTRUM_WARRIOR',Civilopedia='TXT_KEY_VILTRUM_WARRIOR_PEDIA',Strategy='TXT_KEY_VILTRUM_WARRIOR_STRATEGY',Help='TXT_KEY_VILTRUM_WARRIOR_HELP',Combat=82,Moves=3,Cost=1300,FaithCost=2600,PrereqTech='TECH_REPLACEABLE_PARTS',ResourceType=NULL,PortraitIndex=0,IconAtlas='VILTRUM_OBJECT_ATLAS',UnitFlagAtlas='VILTRUM_UNIT_FLAG_ATLAS',UnitFlagIconOffset=0;
INSERT INTO Units SELECT * FROM VILTRUM_Clone;
DROP TABLE VILTRUM_Clone;
INSERT INTO Civilization_UnitClassOverrides VALUES ('CIVILIZATION_VILTRUM','UNITCLASS_INFANTRY','UNIT_VILTRUM_WARRIOR');
INSERT INTO UnitClasses(Type,Description,DefaultUnit) VALUES ('UNITCLASS_VILTRUM_AUXILIARY','TXT_KEY_VILTRUM_AUXILIARY',NULL);
CREATE TEMP TABLE VILTRUM_Clone AS SELECT * FROM Units WHERE Type='UNIT_INFANTRY';
UPDATE VILTRUM_Clone SET ID=NULL,Type='UNIT_VILTRUM_AUXILIARY',Class='UNITCLASS_VILTRUM_AUXILIARY',Description='TXT_KEY_VILTRUM_AUXILIARY',Civilopedia='TXT_KEY_VILTRUM_AUXILIARY_PEDIA',PortraitIndex=0,IconAtlas='VILTRUM_OBJECT_ATLAS';
INSERT INTO Units SELECT * FROM VILTRUM_Clone;
DROP TABLE VILTRUM_Clone;
INSERT INTO Civilization_UnitClassOverrides VALUES ('CIVILIZATION_VILTRUM','UNITCLASS_VILTRUM_AUXILIARY','UNIT_VILTRUM_AUXILIARY');
CREATE TEMP TABLE VILTRUM_Clone AS SELECT * FROM Buildings WHERE Type='BUILDING_MILITARY_ACADEMY';
UPDATE VILTRUM_Clone SET ID=NULL,Type='BUILDING_VILTRUM_COMPLEX',Description='TXT_KEY_VILTRUM_COMPLEX',Civilopedia='TXT_KEY_VILTRUM_COMPLEX_PEDIA',Strategy='TXT_KEY_VILTRUM_COMPLEX_STRATEGY',Help='TXT_KEY_VILTRUM_COMPLEX_HELP',PortraitIndex=1,IconAtlas='VILTRUM_OBJECT_ATLAS',MilitaryProductionModifier=MilitaryProductionModifier+5,Experience=Experience+15;
INSERT INTO Buildings SELECT * FROM VILTRUM_Clone;
DROP TABLE VILTRUM_Clone;
INSERT INTO Civilization_BuildingClassOverrides VALUES ('CIVILIZATION_VILTRUM','BUILDINGCLASS_MILITARY_ACADEMY','BUILDING_VILTRUM_COMPLEX');
