INSERT INTO Language_en_US(Tag,Text) VALUES
('TXT_KEY_VILTRUM_LEADER','Grand Regent Thragg'),
('TXT_KEY_VILTRUM_LEADER_PEDIA','Thragg, Grand Regent of the Viltrum Empire, rules through absolute strength and the preservation of Viltrumite blood. His empire must survive a catastrophe that military force cannot defeat.'),
('TXT_KEY_VILTRUM_CIV','The Viltrum Empire'),
('TXT_KEY_VILTRUM_SHORT','Viltrum'),
('TXT_KEY_VILTRUM_ADJECTIVE','Viltrumite'),
('TXT_KEY_VILTRUM_CIV_PEDIA','The Viltrum Empire conquered countless worlds, sustained by genetically extraordinary warriors. The Great Purge forged its ideology; the Scourge Virus nearly extinguished its people. Conventional subject armies and a handful of survivors must rebuild the dominion.'),
('TXT_KEY_VILTRUM_STRATEGY','Conquer aggressively before the guaranteed Scourge. Each 1300-Production Viltrumite is an enormous investment: keep conventional Infantry, artillery, anti-air and aircraft. Breeding Complexes protect citizens. Stockpile Gold and position defensively after Replaceable Parts. Quarantine preserves more survivors; continuing the crusade creates powerful Last Purebloods at devastating risk.'),
('TXT_KEY_VILTRUM_WARRIOR','Viltrumite Warrior'),
('TXT_KEY_VILTRUM_WARRIOR_PEDIA','A flying strategic breakthrough warrior. One costs about 3.47 ordinary Infantry. Biological Bloodline, Flight, March, Relentless Execution and Planetbreaker are free. Only genuine outbreak survivors receive the strongest survivor promotions.'),
('TXT_KEY_VILTRUM_WARRIOR_STRATEGY','Conquer aggressively before the guaranteed Scourge. Each 1300-Production Viltrumite is an enormous investment: keep conventional Infantry, artillery, anti-air and aircraft. Breeding Complexes protect citizens. Stockpile Gold and position defensively after Replaceable Parts. Quarantine preserves more survivors; continuing the crusade creates powerful Last Purebloods at devastating risk.'),
('TXT_KEY_VILTRUM_WARRIOR_HELP','82 Strength, 3 Movement, 1300 Production; Replaceable Parts. Ignores terrain costs, crosses mountains and coasts, deploys 7 tiles from friendly territory, attacks after deployment, and captures cities. Heals 35 HP on personal capture. Relentless Execution: +15% against targets below 50 HP; Planetbreaker: +20% against cities below half health.'),
('TXT_KEY_VILTRUM_AUXILIARY','Auxiliary Infantry'),
('TXT_KEY_VILTRUM_AUXILIARY_PEDIA','Conventional subject-world Infantry. Retains the installed ruleset Infantry statistics, requirements, upgrades and model. Auxiliaries are unaffected by biological Scourge casualties.'),
('TXT_KEY_VILTRUM_COMPLEX','Viltrumite Breeding Complex'),
('TXT_KEY_VILTRUM_COMPLEX_PEDIA','Replaces the Military Academy and retains its ruleset effects. Adds 15 XP, 2 Production, 1 Food and 5% military Production. First construction grants one citizen once per original city. Each Complex protects one additional citizen during the Scourge.'),
('TXT_KEY_VILTRUM_COMPLEX_STRATEGY','Build before the Scourge to protect population and condition land troops.'),
('TXT_KEY_VILTRUM_COMPLEX_HELP','Military Academy effects plus 15 XP, +2 Production, +1 Food, +5% military Production. First construction: +1 Population. Trained land troops gain Imperial Conditioning. Protects one additional citizen during the Scourge.'),
('TXT_KEY_VILTRUM_BLOODLINE','Viltrumite Bloodline'),
('TXT_KEY_VILTRUM_BLOODLINE_HELP','Biological marker retained through upgrades; targeted by the Scourge.'),
('TXT_KEY_VILTRUM_FLIGHT','Viltrumite Flight'),
('TXT_KEY_VILTRUM_FLIGHT_HELP','Ignore terrain costs; cross mountains and shallow water; deploy 7 tiles and attack after deployment.'),
('TXT_KEY_VILTRUM_EXECUTION','Relentless Execution'),
('TXT_KEY_VILTRUM_EXECUTION_HELP','+15% combat strength against an enemy combat unit below 50 HP.'),
('TXT_KEY_VILTRUM_PLANETBREAKER','Planetbreaker'),
('TXT_KEY_VILTRUM_PLANETBREAKER_HELP','+20% when attacking a city below 50% HP; heal 35 HP on personal city capture.'),
('TXT_KEY_VILTRUM_EXECUTION_ACTIVE','Relentless Execution bonus'),
('TXT_KEY_VILTRUM_EXECUTION_ACTIVE_HELP','Temporary target-conditioned combat modifier.'),
('TXT_KEY_VILTRUM_PLANET_ACTIVE','Planetbreaker bonus'),
('TXT_KEY_VILTRUM_PLANET_ACTIVE_HELP','Temporary wounded-city attack modifier.'),
('TXT_KEY_VILTRUM_MOMENTUM','Imperial Momentum'),
('TXT_KEY_VILTRUM_MOMENTUM_HELP','First conquests activate 8 turns of +15% military Production, +3 XP to trained military units and +5% city attack. Additional first conquests extend by 3 up to 18 remaining turns. Quarantine suspends all conquest rewards.'),
('TXT_KEY_VILTRUM_CONDITIONING','Imperial Conditioning'),
('TXT_KEY_VILTRUM_CONDITIONING_HELP','+5% strength outside friendly territory. Healing +1 HP in friendly or neutral territory (rounded native approximation of 5%).'),
('TXT_KEY_VILTRUM_CONDITION_ACTIVE','Conditioned abroad'),
('TXT_KEY_VILTRUM_CONDITION_ACTIVE_HELP','+5% outside friendly territory.'),
('TXT_KEY_VILTRUM_HARDENED','Scourge-Hardened'),
('TXT_KEY_VILTRUM_HARDENED_HELP','True quarantine survivor: +10% strength, +1 sight, native healing +4 friendly/+2 neutral/+2 enemy HP (approximately 20%).'),
('TXT_KEY_VILTRUM_PUREBLOOD','Last Pureblood'),
('TXT_KEY_VILTRUM_PUREBLOOD_HELP','True crusade survivor: +20% strength, +1 move, Blitz, +20% combat XP. +20% strength below 50 HP; fully heals on personal enemy original-capital capture.'),
('TXT_KEY_VILTRUM_PURE_ACTIVE','Last Pureblood fury'),
('TXT_KEY_VILTRUM_PURE_ACTIVE_HELP','+20% strength while below 50 HP.'),
('TXT_KEY_VILTRUM_GENOME','Hardened Genome'),
('TXT_KEY_VILTRUM_GENOME_HELP','Post-outbreak Viltrumite trained by Viltrum: +5% strength.'),
('TXT_KEY_VILTRUM_WARNING','Impossible Illness'),
('TXT_KEY_VILTRUM_WARNING_HELP','Native healing -5 friendly/-3 neutral/-3 enemy HP (approximately 25% of normal field healing).'),
('TXT_KEY_VILTRUM_QUARANTINE','Total Quarantine'),
('TXT_KEY_VILTRUM_QUARANTINE_HELP','Native healing -10 friendly/-5 neutral/-5 enemy HP (approximately 50% of normal field healing).'),
('TXT_KEY_VILTRUM_NO_HEAL','Dying Empire'),
('TXT_KEY_VILTRUM_NO_HEAL_HELP','Cannot passively heal outside friendly territory.'),
('TXT_KEY_VILTRUM_CITY_0','Viltrum'),
('TXT_KEY_VILTRUM_CITY_1','Argall''s Reach'),
('TXT_KEY_VILTRUM_CITY_2','Regent''s Citadel'),
('TXT_KEY_VILTRUM_CITY_3','Kregg''s Bastion'),
('TXT_KEY_VILTRUM_CITY_4','Conquest''s Rest'),
('TXT_KEY_VILTRUM_CITY_5','Anissa''s Spear'),
('TXT_KEY_VILTRUM_CITY_6','Thula''s Vigil'),
('TXT_KEY_VILTRUM_CITY_7','Lucan''s March'),
('TXT_KEY_VILTRUM_CITY_8','Vidor Prime'),
('TXT_KEY_VILTRUM_CITY_9','The Gene-Forges'),
('TXT_KEY_VILTRUM_CITY_10','Red Sun Colony'),
('TXT_KEY_VILTRUM_CITY_11','Dominion''s Edge'),
('TXT_KEY_VILTRUM_CITY_12','Purity World'),
('TXT_KEY_VILTRUM_CITY_13','Unbroken Sky'),
('TXT_KEY_VILTRUM_CITY_14','Planetbreaker Station'),
('TXT_KEY_VILTRUM_CITY_15','The Regent''s Hand'),
('TXT_KEY_VILTRUM_CITY_16','Bloodline Nexus'),
('TXT_KEY_VILTRUM_CITY_17','The Fifty''s Refuge'),
('TXT_KEY_VILTRUM_CITY_18','Ascendant World'),
('TXT_KEY_VILTRUM_CITY_19','Last Horizon'),
('TXT_KEY_VILTRUM_CITY_20','Imperial Crucible'),
('TXT_KEY_VILTRUM_CITY_21','Silent Conquest'),
('TXT_KEY_VILTRUM_CITY_22','The Outer Dominion'),
('TXT_KEY_VILTRUM_CITY_23','Argall''s Legacy'),
('TXT_KEY_VILTRUM_CITY_24','Throne of Worlds'),
('TXT_KEY_VILTRUM_SPY_0','Kregg'),
('TXT_KEY_VILTRUM_SPY_1','Anissa'),
('TXT_KEY_VILTRUM_SPY_2','Thula'),
('TXT_KEY_VILTRUM_SPY_3','Lucan'),
('TXT_KEY_VILTRUM_SPY_4','Vidor'),
('TXT_KEY_VILTRUM_SPY_5','Conquest'),
('TXT_KEY_VILTRUM_SPY_6','Argall'),
('TXT_KEY_VILTRUM_SPY_7','Nolan'),
('TXT_KEY_VILTRUM_DIPLO_FIRST_GREETING','You have mistaken independence for strength. Your world now belongs to Viltrum.'),
('TXT_KEY_VILTRUM_DIPLO_GREETING_NEUTRAL_HELLO','Speak. The Empire has permitted you a moment of its attention.'),
('TXT_KEY_VILTRUM_DIPLO_GREETING_POLITE_HELLO','You have demonstrated value. Continue to do so.'),
('TXT_KEY_VILTRUM_DIPLO_GREETING_HOSTILE_HELLO','Every day you remain free is an administrative delay.'),
('TXT_KEY_VILTRUM_DIPLO_DECLAREWAR','Your species has been measured. It has been found unnecessary.'),
('TXT_KEY_VILTRUM_DIPLO_GREETING_HUMAN_AT_WAR','You have saved us the inconvenience of inventing a justification.'),
('TXT_KEY_VILTRUM_DIPLO_REQUEST','Surrender what has been requested. Refusal will only increase the final cost.'),
('TXT_KEY_VILTRUM_DIPLO_DEFEATED','Viltrum is not a world. It is blood. So long as one of us remains, the Empire remains.'),
('TXT_KEY_VILTRUM_TRAIT','Blood of Conquest'),
('TXT_KEY_VILTRUM_TRAIT_HELP','Land combat kills heal 15 HP (no civilians or barbarians). First foreign-city conquests give +1 capital Population, 20% shorter resistance and Imperial Momentum: +15% military Production, +3 trained military XP, +5% city attack for 8 turns, extended by 3 up to 18. Garrisoned cities gain +1 Production, +1 Happiness and +3 strength. A Great Purge and a guaranteed Scourge shape the empire. Quarantine disables conquest bonuses; Crusade reduces kill healing to 10. Durations scale with game speed.'),
('TXT_KEY_VILTRUM_DUMMY','Viltrum imperial administration'),
('TXT_KEY_VILTRUM_DAWN','The Viltrum Empire was built upon a single truth: strength confers the right to rule.[NEWLINE][NEWLINE]The weak among your own people were purged. The survivors crossed the stars, bringing countless worlds beneath the Viltrumite banner. Their armies broke, their governments surrendered, and their resources sustained an empire that appeared invincible.[NEWLINE][NEWLINE]Yet something now moves unseen through Viltrumite blood. An enemy too small to strike, too numerous to conquer, and too patient to intimidate.[NEWLINE][NEWLINE]Grand Regent Thragg, will you build an empire capable of surviving its own extinction? Will the galaxy witness the death of Viltrum—or learn that even a handful of Viltrumites are enough to rule the stars?'),
('TXT_KEY_VILTRUM_PURGE_EVENT','The Great Purge'),
('TXT_KEY_VILTRUM_PURGE_EVENT_HELP','Viltrum has turned its strength inward. Those judged unworthy are being hunted by their own people. Entire cities have become battlegrounds as the Empire determines whether survival itself is proof of superiority.[NEWLINE][NEWLINE]The weak plead for protection. The warriors demand that the purge continue.'),
('TXT_KEY_VILTRUM_SCOURGE_EVENT','The Scourge Virus'),
('TXT_KEY_VILTRUM_SCOURGE_EVENT_HELP','The Scourge has reached Viltrum. Quarantine loses 75% population and 80% Bloodline units (at least two survive if available). Survivors have 25 HP and Scourge-Hardened. Growth stops, Production -40%, military Production another -50%, healing slows, conquest bonuses stop and Settlers are blocked for 20 turns. Recovery: 20 turns of +25% Growth, +15% Production and +1 Happiness/city.[NEWLINE][NEWLINE]Crusade loses 85% population and 90% Bloodline units (at least one survives), with 10 HP and Last Pureblood. For 25 turns: -75% Growth, -50% Production, -10 Happiness and no field healing abroad. Kill healing becomes 10; first conquests shorten the crisis. Peace is blocked for the first 10 turns. Recovery gives +15% Growth for 15 turns. Capitals retain 2 citizens; Complexes protect one extra. All durations scale with speed.'),
('TXT_KEY_VILTRUM_EXTINCTION','Conceal the Extinction'),
('TXT_KEY_VILTRUM_EXTINCTION_HELP','The galaxy must not know how few Viltrumites remain. If subject worlds discover the truth, rebellion will spread faster than the virus itself.[NEWLINE][NEWLINE]Maintain the illusion: pay two turns of net Gold income, at least 500 (speed-scaled), for 20 turns of +25% spy defense and +10% city strength. Demonstrate fear: free Great General, survivors +10 XP, 5 turns of Momentum, and two rebels near an occupied city. Custom diplomatic penalties are unavailable; no fabricated DLL calls are made.'),
('TXT_KEY_CIV5_VILTRUM','The Viltrum Empire'),
('TXT_KEY_CIV5_VILTRUM_HEADING_1','Strength Confers the Right to Rule'),
('TXT_KEY_CIV5_VILTRUM_TEXT_1','The Viltrum Empire conquered countless worlds, sustained by genetically extraordinary warriors. The Great Purge forged its ideology; the Scourge Virus nearly extinguished its people. Conventional subject armies and a handful of survivors must rebuild the dominion.'),
('TXT_KEY_CIV5_VILTRUM_HEADING_2','The Surviving Empire'),
('TXT_KEY_CIV5_VILTRUM_TEXT_2','Conquer aggressively before the guaranteed Scourge. Each 1300-Production Viltrumite is an enormous investment: keep conventional Infantry, artillery, anti-air and aircraft. Breeding Complexes protect citizens. Stockpile Gold and position defensively after Replaceable Parts. Quarantine preserves more survivors; continuing the crusade creates powerful Last Purebloods at devastating risk.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_VILTRUM','Grand Regent Thragg'),
('TXT_KEY_CIVILOPEDIA_LEADERS_VILTRUM_NAME','Grand Regent Thragg'),
('TXT_KEY_CIVILOPEDIA_LEADERS_VILTRUM_SUBTITLE','Regent of the Viltrum Empire'),
('TXT_KEY_CIVILOPEDIA_LEADERS_VILTRUM_LIVED','A fictional leader from Invincible'),
('TXT_KEY_CIVILOPEDIA_LEADERS_VILTRUM_TITLES','Grand Regent'),
('TXT_KEY_CIVILOPEDIA_LEADERS_VILTRUM_HEADING_1','Blood and Dominion'),
('TXT_KEY_CIVILOPEDIA_LEADERS_VILTRUM_TEXT_1','Thragg, Grand Regent of the Viltrum Empire, rules through absolute strength and the preservation of Viltrumite blood. His empire must survive a catastrophe that military force cannot defeat.');
