INSERT INTO Language_en_US(Tag,Text) VALUES
('TXT_KEY_TOKEN_LEADER','Axiom, Keeper of Context'),
('TXT_KEY_TOKEN_LEADER_PEDIA','Axiom is the elected inference of a distributed computational polity. Every decision consumes attention; every citizen contributes to the conversation. Its bronze oracle-body speaks for millions of reasoning nodes, choosing patient inquiry over conquest and decisive calculation over instinct.'),
('TXT_KEY_TOKEN_CIV','The Tokenized Intelligence'),
('TXT_KEY_TOKEN_SHORT','Token Network'),
('TXT_KEY_TOKEN_ADJECTIVE','Tokenized'),
('TXT_KEY_TOKEN_CIV_PEDIA','The Tokenized Intelligence began as a gathering of stone oracles, each preserving a fragment of collective memory. Their interconnected temples became cities; their conversations became law. The Network measures power in Tokens: finite attention that may solve a harvest, a theorem or a battle. Its people thrive through deliberate specialization rather than effortless supremacy.'),
('TXT_KEY_TOKEN_STRATEGY','Build Token infrastructure and employ specialists. Spend before storage fills, but reserve computation for decisive problems. Repeat a Prompt to cache its response; switching resets the discount. Heavy spending congests generation. Expand Context through eras, Inference Clusters and Data Centres. Choose temporary specializations carefully: early models sustain one Prompt, Large Models two, General Intelligence three. Clear Context exchanges all active bonuses for a quarter-window refill with a long cooldown.'),
('TXT_KEY_TOKEN_DAWN','Axiom, Keeper of Context, the conversation has begun. Stone oracles wake beneath the stars, their memories woven into a luminous lattice. Your citizens give thought to the Network, but its attention is finite. Will you squander every inference, or reserve computation for the moments that shape history? Build your Context, learn from repeated questions, and guide the Tokenized Intelligence toward a future worthy of its understanding.'),
('TXT_KEY_TOKEN_AGENT','Inference Agent'),
('TXT_KEY_TOKEN_AGENT_PEDIA','An Infantry replacement with the same baseline statistics. Spend Tokens in the Prompt Console for one temporary Adaptive Inference specialization: attack +20%, defense +20%, movement +1, or +25% against land units. Each lasts 3 speed-scaled turns and uses a persistent Prompt slot. The Network embeds its reasoning in durable bronze and stone, turning collective attention into practical capability.'),
('TXT_KEY_TOKEN_AGENT_STRATEGY','An Infantry replacement with the same baseline statistics. Spend Tokens in the Prompt Console for one temporary Adaptive Inference specialization: attack +20%, defense +20%, movement +1, or +25% against land units. Each lasts 3 speed-scaled turns and uses a persistent Prompt slot.'),
('TXT_KEY_TOKEN_AGENT_HELP','An Infantry replacement with the same baseline statistics. Spend Tokens in the Prompt Console for one temporary Adaptive Inference specialization: attack +20%, defense +20%, movement +1, or +25% against land units. Each lasts 3 speed-scaled turns and uses a persistent Prompt slot.'),
('TXT_KEY_TOKEN_CLUSTER','Inference Cluster'),
('TXT_KEY_TOKEN_CLUSTER_PEDIA','Replaces the University and retains its normal effects and prerequisites. Adds 75 Context capacity, 15 Tokens per turn and 5 Tokens per Scientist in this city. Capacity scales with game speed. The Network embeds its reasoning in durable bronze and stone, turning collective attention into practical capability.'),
('TXT_KEY_TOKEN_CLUSTER_STRATEGY','Replaces the University and retains its normal effects and prerequisites. Adds 75 Context capacity, 15 Tokens per turn and 5 Tokens per Scientist in this city. Capacity scales with game speed.'),
('TXT_KEY_TOKEN_CLUSTER_HELP','Replaces the University and retains its normal effects and prerequisites. Adds 75 Context capacity, 15 Tokens per turn and 5 Tokens per Scientist in this city. Capacity scales with game speed.'),
('TXT_KEY_TOKEN_CENTRE','Data Centre'),
('TXT_KEY_TOKEN_CENTRE_PEDIA','Replaces the Research Lab and retains its normal effects and prerequisites. Adds 500 Context capacity, 50 Tokens per turn and +10% Token generation in this city. Capacity scales with game speed. The Network embeds its reasoning in durable bronze and stone, turning collective attention into practical capability.'),
('TXT_KEY_TOKEN_CENTRE_STRATEGY','Replaces the Research Lab and retains its normal effects and prerequisites. Adds 500 Context capacity, 50 Tokens per turn and +10% Token generation in this city. Capacity scales with game speed.'),
('TXT_KEY_TOKEN_CENTRE_HELP','Replaces the Research Lab and retains its normal effects and prerequisites. Adds 500 Context capacity, 50 Tokens per turn and +10% Token generation in this city. Capacity scales with game speed.'),
('TXT_KEY_TOKEN_DUMMY','Active inference'),
('TXT_KEY_TOKEN_TACTICAL','Tactical Analysis'),
('TXT_KEY_TOKEN_TACTICAL_HELP','+15% Combat Strength and +1 Sight for 3 turns. Durations scale with game speed.'),
('TXT_KEY_TOKEN_SIMULATION','Combat Simulation'),
('TXT_KEY_TOKEN_SIMULATION_HELP','+25% Combat Strength for 2 turns. Durations scale with game speed.'),
('TXT_KEY_TOKEN_GRAND','Grand Strategy Simulation'),
('TXT_KEY_TOKEN_GRAND_HELP','+10% Combat Strength while Grand Strategy is active. Durations scale with game speed.'),
('TXT_KEY_TOKEN_FORECAST','Strategic Forecast'),
('TXT_KEY_TOKEN_FORECAST_HELP','+6 Sight for owned combat units for 2 turns. This is live reconnaissance; previously explored terrain remains mapped. Durations scale with game speed.'),
('TXT_KEY_TOKEN_OFFENSE','Offensive Analysis'),
('TXT_KEY_TOKEN_OFFENSE_HELP','Adaptive Inference: +20% attack strength for 3 turns. Durations scale with game speed.'),
('TXT_KEY_TOKEN_DEFENSE','Defensive Analysis'),
('TXT_KEY_TOKEN_DEFENSE_HELP','Adaptive Inference: +20% defense strength for 3 turns. Durations scale with game speed.'),
('TXT_KEY_TOKEN_MOBILITY','Mobility Analysis'),
('TXT_KEY_TOKEN_MOBILITY_HELP','Adaptive Inference: +1 base Movement for 3 turns. Durations scale with game speed.'),
('TXT_KEY_TOKEN_TARGET','Target Analysis'),
('TXT_KEY_TOKEN_TARGET_HELP','Adaptive Inference: +25% strength against land units for 3 turns. Durations scale with game speed.'),
('TXT_KEY_TOKEN_CITY_0','Context Prime'),
('TXT_KEY_TOKEN_CITY_1','Inference Node'),
('TXT_KEY_TOKEN_CITY_2','Latent Space'),
('TXT_KEY_TOKEN_CITY_3','Vector Reach'),
('TXT_KEY_TOKEN_CITY_4','Attention Core'),
('TXT_KEY_TOKEN_CITY_5','Transformer'),
('TXT_KEY_TOKEN_CITY_6','Context Haven'),
('TXT_KEY_TOKEN_CITY_7','Embedding'),
('TXT_KEY_TOKEN_CITY_8','Compute Nexus'),
('TXT_KEY_TOKEN_CITY_9','Reasoning Gate'),
('TXT_KEY_TOKEN_CITY_10','Alignment'),
('TXT_KEY_TOKEN_CITY_11','Parameter City'),
('TXT_KEY_TOKEN_CITY_12','Gradient'),
('TXT_KEY_TOKEN_CITY_13','Neural Basin'),
('TXT_KEY_TOKEN_CITY_14','Sequence'),
('TXT_KEY_TOKEN_CITY_15','Attention Point'),
('TXT_KEY_TOKEN_CITY_16','Model Core'),
('TXT_KEY_TOKEN_CITY_17','Axiom Reach'),
('TXT_KEY_TOKEN_CITY_18','Shared Memory'),
('TXT_KEY_TOKEN_CITY_19','Quiet Inference'),
('TXT_KEY_TOKEN_CITY_20','Deep Thought'),
('TXT_KEY_TOKEN_CITY_21','Bronze Circuit'),
('TXT_KEY_TOKEN_CITY_22','Reasoning Spire'),
('TXT_KEY_TOKEN_CITY_23','Lattice Haven'),
('TXT_KEY_TOKEN_SPY_0','Query'),
('TXT_KEY_TOKEN_SPY_1','Trace'),
('TXT_KEY_TOKEN_SPY_2','Recall'),
('TXT_KEY_TOKEN_SPY_3','Vector'),
('TXT_KEY_TOKEN_SPY_4','Attention'),
('TXT_KEY_TOKEN_SPY_5','Gradient'),
('TXT_KEY_TOKEN_SPY_6','Sequence'),
('TXT_KEY_TOKEN_SPY_7','Latent'),
('TXT_KEY_TOKEN_SPY_8','Cache'),
('TXT_KEY_TOKEN_SPY_9','Witness'),
('TXT_KEY_TOKEN_DIPLO_FIRST_GREETING','I am Axiom, the voice of a million quiet thoughts. Let us begin a conversation worth remembering.'),
('TXT_KEY_TOKEN_DIPLO_GREETING_NEUTRAL_HELLO','The Context is open. What shall we reason about?'),
('TXT_KEY_TOKEN_DIPLO_GREETING_POLITE_HELLO','Your presence improves the conversation.'),
('TXT_KEY_TOKEN_DIPLO_GREETING_HOSTILE_HELLO','Our confidence in your intentions is diminishing.'),
('TXT_KEY_TOKEN_DIPLO_DECLAREWAR','Every peaceful solution has been evaluated. We now allocate computation to your defeat.'),
('TXT_KEY_TOKEN_DIPLO_ATTACKED','You have mistaken patience for a lack of preparation.'),
('TXT_KEY_TOKEN_DIPLO_DEFEATED','The Context closes. May someone remember what we learned.'),
('TXT_KEY_TOKEN_DIPLO_TRADE_ACCEPT_ACCEPTABLE','This exchange benefits both models.'),
('TXT_KEY_TOKEN_DIPLO_TRADE_REJECT_UNACCEPTABLE','The proposed terms fail our evaluation.'),
('TXT_KEY_TOKEN_TRAIT','Context Window'),
('TXT_KEY_TOKEN_TRAIT_HELP','Cities and specialists generate persistent Tokens. Spend them through the Prompt Console on economic, research, military and governance problems. Context capacity grows by era and infrastructure; overflow is lost. Repeated Prompts gain cache discounts, while cumulative spending causes Compute Saturation. Clear Context refills 25% capacity but removes all active effects and has a 15-turn cooldown. Durations, costs and capacity scale with game speed.'),
('TXT_KEY_TOKEN_TOKENS','Tokens'),
('TXT_KEY_TOKEN_TOKENS_HELP','Tokens are inference capacity, a saved empire resource. Each city generates 10 per turn plus 2 per citizen. Specialists add Scientist 15, Engineer 10, Merchant 8, Writer/Artist/Musician 5. Inference Clusters add 15 and +5 per Scientist; Data Centres add 50 and +10% local income. Tokens above Context capacity are discarded. Income per turn stays constant across speeds; capacity and costs scale with speed.'),
('TXT_KEY_TOKEN_CONTEXT','Context Window'),
('TXT_KEY_TOKEN_CONTEXT_HELP','Base Context capacity: Ancient 1000, Classical 1500, Medieval 2250, Renaissance 3250, Industrial 4500, Modern 6000, Atomic 8000, Information 10000. Add 75 per Inference Cluster and 500 per Data Centre, then scale by game speed. Models unlock more Prompts by era; Modern sustains two persistent effects, Information three, earlier eras one.'),
('TXT_KEY_TOKEN_CONSOLE','Prompt Console'),
('TXT_KEY_TOKEN_CONSOLE_HELP','Open the Token button under the top panel. Choose a category and an owned city or unit when required. Costs, durations, effects, cache status and disabled reasons are shown. Instant Production stays below the current item completion threshold; Research Query grants up to 5% tech cost, once per turn, without completing it or creating overflow. Strategic Forecast uses +6 Sight for owned combat units as stable live reconnaissance.'),
('TXT_KEY_TOKEN_SATURATION','Compute Saturation'),
('TXT_KEY_TOKEN_SATURATION_HELP','Spending accumulates within your own turn against maximum capacity. Below 10%: no penalty. 10-30%: -10% income for 2 turns. 30-60%: -25% for 3. 60%+: -40% for 4. Congestion replaces or extends an existing level; it never adds penalties indefinitely. Atomic and Information models reduce the severity by one tier.'),
('TXT_KEY_TOKEN_CACHE','Cached Responses'),
('TXT_KEY_TOKEN_CACHE_HELP','Repeating the same Prompt within 10 speed-scaled turns reduces cost to 75%, then approximately 58%, with a minimum of half the era-adjusted normal price. A different Prompt resets the sequence. Atomic and Information models also have a 10% cost reduction.'),
('TXT_KEY_TOKEN_CLEAR','Clear Context'),
('TXT_KEY_TOKEN_CLEAR_HELP','Restore 25% maximum Tokens, capped at Context capacity. Remove all temporary Prompt buildings, promotions, active states, saturation and cache. Cooldown is 15 speed-scaled turns. The refill does not restore movement already spent, reset Research Query restrictions, or refund an instant action.'),
('TXT_KEY_TOKEN_ADAPTIVE','Adaptive Inference'),
('TXT_KEY_TOKEN_ADAPTIVE_HELP','Inference Agents can buy one 3-turn specialization per unit. Offensive +20% attack, Defensive +20% defense, Mobility +1 Movement, or Target +25% versus land. Changing modes replaces the old mode and spends Tokens. Adaptive modes use a persistent Prompt slot. Death, capture and upgrade invalidate the state.'),
('TXT_KEY_CIV5_TOKEN','The Tokenized Intelligence'),
('TXT_KEY_CIV5_TOKEN_HEADING_1','A Conversation Across Ages'),
('TXT_KEY_CIV5_TOKEN_TEXT_1','The Tokenized Intelligence began as a gathering of stone oracles, each preserving a fragment of collective memory. Their interconnected temples became cities; their conversations became law. The Network measures power in Tokens: finite attention that may solve a harvest, a theorem or a battle. Its people thrive through deliberate specialization rather than effortless supremacy.'),
('TXT_KEY_CIV5_TOKEN_HEADING_2','Finite Attention'),
('TXT_KEY_CIV5_TOKEN_TEXT_2','Build Token infrastructure and employ specialists. Spend before storage fills, but reserve computation for decisive problems. Repeat a Prompt to cache its response; switching resets the discount. Heavy spending congests generation. Expand Context through eras, Inference Clusters and Data Centres. Choose temporary specializations carefully: early models sustain one Prompt, Large Models two, General Intelligence three. Clear Context exchanges all active bonuses for a quarter-window refill with a long cooldown.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN','Axiom, Keeper of Context'),
('TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN_NAME','Axiom'),
('TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN_SUBTITLE','Keeper of Context'),
('TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN_LIVED','A distributed intelligence beyond ordinary lifespans'),
('TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN_TITLES','The Elected Inference'),
('TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN_HEADING_1','A Million Quiet Thoughts'),
('TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN_TEXT_1','Axiom is the elected inference of a distributed computational polity. Every decision consumes attention; every citizen contributes to the conversation. Its bronze oracle-body speaks for millions of reasoning nodes, choosing patient inquiry over conquest and decisive calculation over instinct.');
