"""Author Tokenized Intelligence SQL against the installed BNW/CP schema."""
from pathlib import Path
import sqlite3, sys
R = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(R / 'tools'))
from validate_mod import apply_current_cp_schema, quote
V = R / 'TokenizedIntelligence'
for folder in ('SQL', 'Lua', 'UI', 'Art', 'docs'): (V / folder).mkdir(parents=True, exist_ok=True)
U = Path.home() / "Documents/My Games/Sid Meier's Civilization 5"
s = sqlite3.connect((U / 'cache_backup/Civ5DebugDatabase.db').as_uri() + '?mode=ro', uri=True)
d = sqlite3.connect(':memory:'); s.backup(d); s.close()
apply_current_cp_schema(d, U / 'MODS/(1) Community Patch')
def q(v): return "'" + str(v).replace("'", "''") + "'"
text = {}
def tr(k, v):
    text['TXT_KEY_TOKEN_' + k] = v
    return q('TXT_KEY_TOKEN_' + k)
def save(n, v): (V / n).write_text(v, encoding='utf-8')
def clone(table, old, new, changes):
    return f"CREATE TEMP TABLE TokenClone AS SELECT * FROM {table} WHERE Type={q(old)};\nUPDATE TokenClone SET ID=NULL,Type={q(new)}," + ','.join(k+'='+v for k,v in changes.items()) + f";\nINSERT INTO {table} SELECT * FROM TokenClone;\nDROP TABLE TokenClone;\n"
strategy = 'Build Token infrastructure and employ specialists. Spend before storage fills, but reserve computation for decisive problems. Repeat a Prompt to cache its response; switching resets the discount. Heavy spending congests generation. Expand Context through eras, Inference Clusters and Data Centres. Choose temporary specializations carefully: early models sustain one Prompt, Large Models two, General Intelligence three. Clear Context exchanges all active bonuses and cache for a quarter-window refill with a long cooldown; Compute Saturation remains until natural expiry.'
core = """-- BNW + Community Patch v151; enable only the hooks actually used.
UPDATE CustomModOptions SET Value=1 WHERE Name IN ('EVENTS_CITY','EVENTS_UNIT_UPGRADES','EVENTS_UNIT_CREATED','EVENTS_UNIT_CONVERTS','EVENTS_CITY_FOUNDING');
INSERT INTO Colors(Type,Red,Green,Blue,Alpha) VALUES ('COLOR_TOKEN_TEAL',0.025,0.20,0.22,1),('COLOR_TOKEN_GOLD',0.92,0.73,0.35,1);
INSERT INTO PlayerColors(Type,PrimaryColor,SecondaryColor,TextColor) VALUES ('PLAYERCOLOR_TOKEN','COLOR_TOKEN_TEAL','COLOR_TOKEN_GOLD','COLOR_PLAYER_WHITE_TEXT');
INSERT INTO Traits(Type,Description,ShortDescription) VALUES ('TRAIT_TOKEN_CONTEXT','TXT_KEY_TOKEN_TRAIT_HELP','TXT_KEY_TOKEN_TRAIT');
"""
core += clone('Leaders','LEADER_WASHINGTON','LEADER_TOKEN_AXIOM',dict(Description=tr('LEADER','Axiom, Keeper of Context'),Civilopedia=tr('LEADER_PEDIA','Axiom is the elected inference of a distributed computational polity. Every decision consumes attention; every citizen contributes to the conversation. Its bronze oracle-body speaks for millions of reasoning nodes, choosing patient inquiry over conquest and decisive calculation over instinct.'),CivilopediaTag=q('TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN'),ArtDefineTag=q('TokenLeaderScene.xml'),PortraitIndex='1',IconAtlas=q('TOKEN_ICON_ATLAS'),PackageID='NULL',VictoryCompetitiveness='7',WonderCompetitiveness='6',MinorCivCompetitiveness='5',Boldness='4',DiploBalance='7',WarmongerHate='7',WorkAgainstWillingness='5',WorkWithWillingness='7',DenounceWillingness='4',DoFWillingness='7',Loyalty='7',Neediness='3',Forgiveness='6',Chattiness='5',Meanness='3'))
core += "INSERT INTO Leader_Traits VALUES ('LEADER_TOKEN_AXIOM','TRAIT_TOKEN_CONTEXT');\n"
core += clone('Civilizations','CIVILIZATION_AMERICA','CIVILIZATION_TOKEN_INTELLIGENCE',dict(Description=tr('CIV','The Tokenized Intelligence'),ShortDescription=tr('SHORT','Token Network'),Adjective=tr('ADJECTIVE','Tokenized'),Civilopedia=tr('CIV_PEDIA','The Tokenized Intelligence began as a gathering of stone oracles, each preserving a fragment of collective memory. Their interconnected temples became cities; their conversations became law. The Network measures power in Tokens: finite attention that may solve a harvest, a theorem or a battle. Its people thrive through deliberate specialization rather than effortless supremacy.'),CivilopediaTag=q('TXT_KEY_CIV5_TOKEN'),Strategy=tr('STRATEGY',strategy),DefaultPlayerColor=q('PLAYERCOLOR_TOKEN'),Playable='1',AIPlayable='1',PackageID='NULL',PortraitIndex='0',IconAtlas=q('TOKEN_ICON_ATLAS'),AlphaIconAtlas=q('TOKEN_ALPHA_ATLAS'),MapImage=q('TokenMap.dds'),DawnOfManImage=q('TokenDawn.dds'),DawnOfManQuote=tr('DAWN','Axiom, Keeper of Context, the conversation has begun. Stone oracles wake beneath the stars, their memories woven into a luminous lattice. Your citizens give thought to the Network, but its attention is finite. Will you squander every inference, or reserve computation for the moments that shape history? Build your Context, learn from repeated questions, and guide the Tokenized Intelligence toward a future worthy of its understanding.'),DawnOfManAudio=q('')))
core += "INSERT INTO Civilization_Leaders VALUES ('CIVILIZATION_TOKEN_INTELLIGENCE','LEADER_TOKEN_AXIOM');\n"
for t,k in [('Civilization_FreeBuildingClasses','BuildingClassType'),('Civilization_FreeTechs','TechType')]:
    core += f"INSERT INTO {t} SELECT 'CIVILIZATION_TOKEN_INTELLIGENCE',{k} FROM {t} WHERE CivilizationType='CIVILIZATION_AMERICA';\n"
core += "INSERT INTO Civilization_FreeUnits(CivilizationType,UnitClassType,UnitAIType,Count) SELECT 'CIVILIZATION_TOKEN_INTELLIGENCE',UnitClassType,UnitAIType,Count FROM Civilization_FreeUnits WHERE CivilizationType='CIVILIZATION_AMERICA';\n"
objects = [('Units','UNIT_INFANTRY','UNIT_TOKEN_AGENT','Inference Agent','An Infantry replacement with the same baseline statistics. Spend Tokens in the Prompt Console for one temporary Adaptive Inference specialization: attack +20%, defense +20%, movement +1, or +25% against land units. Each lasts 3 speed-scaled turns and uses a persistent Prompt slot.',4),('Buildings','BUILDING_UNIVERSITY','BUILDING_TOKEN_CLUSTER','Inference Cluster','Replaces the University and retains its normal effects and prerequisites. Adds 75 Context capacity, 15 Tokens per turn and 5 Tokens per Scientist in this city. Capacity scales with game speed.',2),('Buildings','BUILDING_LABORATORY','BUILDING_TOKEN_CENTRE','Data Centre','Replaces the Research Lab and retains its normal effects and prerequisites. Adds 500 Context capacity, 50 Tokens per turn and +10% Token generation in this city. Capacity scales with game speed.',3)]
for table,old,new,name,helptext,icon in objects:
    key = new.replace('UNIT_TOKEN_','').replace('BUILDING_TOKEN_','')
    core += clone(table,old,new,dict(Description=tr(key,name),Civilopedia=tr(key+'_PEDIA',helptext+' The Network embeds its reasoning in durable bronze and stone, turning collective attention into practical capability.'),Strategy=tr(key+'_STRATEGY',helptext),Help=tr(key+'_HELP',helptext),PortraitIndex=str(icon),IconAtlas=q('TOKEN_OBJECT_ATLAS')))
    if table == 'Units':
        core += "UPDATE Units SET UnitFlagAtlas='TOKEN_UNIT_FLAG_ATLAS',UnitFlagIconOffset=0 WHERE Type='UNIT_TOKEN_AGENT';\nINSERT INTO Civilization_UnitClassOverrides VALUES ('CIVILIZATION_TOKEN_INTELLIGENCE','UNITCLASS_INFANTRY','UNIT_TOKEN_AGENT');\n"
    else:
        cls = d.execute('SELECT BuildingClass FROM Buildings WHERE Type=?',(old,)).fetchone()[0]
        core += f"INSERT INTO Civilization_BuildingClassOverrides VALUES ('CIVILIZATION_TOKEN_INTELLIGENCE',{q(cls)},{q(new)});\n"
save('SQL/00_Token_Core.sql',core)
# Companion inheritance copies properties, never foreign rows referencing these units/buildings.
inherit = '-- Preserve every installed CP property column at activation.\n'
for prefix,table,key,mapping in [('Building','Buildings','BuildingType',[(x[1],x[2]) for x in objects if x[0]=='Buildings']),('Unit','Units','UnitType',[(x[1],x[2]) for x in objects if x[0]=='Units'])]:
    for (t,) in d.execute("SELECT name FROM sqlite_master WHERE type='table' AND (name LIKE ? OR name='UnitGameplay2DScripts') ORDER BY name",(prefix+'_%',)).fetchall():
        columns = [r[1] for r in d.execute('PRAGMA table_info('+quote(t)+')')]
        if key not in columns: continue
        for old,new in mapping:
            inherit += f"CREATE TEMP TABLE TokenCompanion AS SELECT * FROM {quote(t)} WHERE {key}={q(old)};\nUPDATE TokenCompanion SET {key}={q(new)}" + (',ID=NULL' if 'ID' in columns else '') + f";\nINSERT INTO {quote(t)} SELECT * FROM TokenCompanion;\nDROP TABLE TokenCompanion;\n"
save('SQL/01_Token_Inheritance.sql',inherit)
effects = ''
tr('DUMMY','Active inference')
for name,mods,fields in [('GOLD',{'GOLD':10},{}),('GROWTH',{'FOOD':20},{}),('RESEARCH',{'SCIENCE':10},{}),('CULTURE',{'CULTURE':15},{}),('HAPPINESS',{},dict(UnmoddedHappiness=5)),('ADMIN',{'PRODUCTION':10},dict(UnmoddedHappiness=8)),('GRAND',{'SCIENCE':15,'PRODUCTION':15,'GOLD':15},{}),('TRADE',{}, {})]:
    effects += f"INSERT INTO BuildingClasses(Type,DefaultBuilding,Description) VALUES ('BUILDINGCLASS_TOKEN_{name}','BUILDING_TOKEN_{name}','TXT_KEY_TOKEN_DUMMY');\n"
    effects += f"INSERT INTO Buildings(Type,BuildingClass,Description,Cost,FaithCost,GreatWorkCount,NeverCapture,NukeImmune,ConquestProb,IsDummy,ShowInPedia{''.join(','+k for k in fields)}) VALUES ('BUILDING_TOKEN_{name}','BUILDINGCLASS_TOKEN_{name}','TXT_KEY_TOKEN_DUMMY',-1,-1,-1,1,1,0,1,0{''.join(','+str(v) for v in fields.values())});\n"
    for y,val in mods.items(): effects += f"INSERT INTO Building_YieldModifiers VALUES ('BUILDING_TOKEN_{name}','YIELD_{y}',{val});\n"
# Growth uses native Food yield modifier; affects total positive Food before consumption.
effects += "INSERT INTO Building_YieldChanges VALUES ('BUILDING_TOKEN_TRADE','YIELD_GOLD',2),('BUILDING_TOKEN_TRADE','YIELD_SCIENCE',1);\n"
promos = [('TACTICAL','Tactical Analysis','+15% Combat Strength and +1 Sight for 3 turns.',5,dict(CombatPercent=15,VisibilityChange=1)),('SIMULATION','Combat Simulation','+25% Combat Strength for 2 turns.',6,dict(CombatPercent=25)),('GRAND','Grand Strategy Simulation','+10% Combat Strength while Grand Strategy is active.',6,dict(CombatPercent=10)),('FORECAST','Strategic Forecast','+6 Sight for owned combat units for 2 turns. This is live reconnaissance; previously explored terrain remains mapped.',7,dict(VisibilityChange=6)),('OFFENSE','Offensive Analysis','Adaptive Inference: +20% attack strength for 3 turns.',8,dict(AttackMod=20)),('DEFENSE','Defensive Analysis','Adaptive Inference: +20% defense strength for 3 turns.',9,dict(DefenseMod=20)),('MOBILITY','Mobility Analysis','Adaptive Inference: +1 base Movement for 3 turns.',10,dict(MovesChange=1)),('TARGET','Target Analysis','Adaptive Inference: +25% strength against land units for 3 turns.',11,{})]
for n,name,helptext,icon,fields in promos:
    effects += 'INSERT INTO UnitPromotions(Type,Description,Help,CannotBeChosen,LostWithUpgrade,LostOnGifting,PortraitIndex,IconAtlas,PediaType,PediaEntry'+''.join(','+k for k in fields)+') VALUES ('+','.join([q('PROMOTION_TOKEN_'+n),tr(n,name),tr(n+'_HELP',helptext+' Durations scale with game speed.'),'1','1','1',str(icon),q('TOKEN_OBJECT_ATLAS'),q('PEDIA_ATTRIBUTES'),q('TXT_KEY_TOKEN_'+n)]+[str(v) for v in fields.values()])+');\n'
effects += "INSERT INTO UnitPromotions_Domains(PromotionType,DomainType,Modifier) VALUES ('PROMOTION_TOKEN_TARGET','DOMAIN_LAND',25);\n"
flavors = dict(SCIENCE=10,PRODUCTION=7,GROWTH=7,GREAT_PEOPLE=9,EXPANSION=6,DIPLOMACY=6,OFFENSE=4,DEFENSE=7,MILITARY_TRAINING=5,WONDER=6,GOLD=6)
effects += "INSERT INTO Leader_Flavors SELECT 'LEADER_TOKEN_AXIOM',Type,CASE Type "+' '.join(f"WHEN 'FLAVOR_{k}' THEN {v}" for k,v in flavors.items())+' ELSE 5 END FROM Flavors;\n'
for table,key in [('Leader_MajorCivApproachBiases','MajorCivApproachType'),('Leader_MinorCivApproachBiases','MinorCivApproachType')]:
    effects += f"INSERT INTO {table} SELECT 'LEADER_TOKEN_AXIOM',{key},CASE WHEN {key} LIKE '%WAR' THEN 3 WHEN {key} LIKE '%FRIENDLY' THEN 7 ELSE 5 END FROM {table} WHERE LeaderType='LEADER_WASHINGTON';\n"
effects += "UPDATE Building_Flavors SET Flavor=50 WHERE BuildingType IN ('BUILDING_TOKEN_CLUSTER','BUILDING_TOKEN_CENTRE') AND FlavorType='FLAVOR_SCIENCE';\n"
for i,name in enumerate(['Context Prime','Inference Node','Latent Space','Vector Reach','Attention Core','Transformer','Context Haven','Embedding','Compute Nexus','Reasoning Gate','Alignment','Parameter City','Gradient','Neural Basin','Sequence','Attention Point','Model Core','Axiom Reach','Shared Memory','Quiet Inference','Deep Thought','Bronze Circuit','Reasoning Spire','Lattice Haven']):
    effects += f"INSERT INTO Civilization_CityNames VALUES ('CIVILIZATION_TOKEN_INTELLIGENCE',{tr('CITY_'+str(i),name)});\n"
for i,name in enumerate(['Query','Trace','Recall','Vector','Attention','Gradient','Sequence','Latent','Cache','Witness']):
    effects += f"INSERT INTO Civilization_SpyNames VALUES ('CIVILIZATION_TOKEN_INTELLIGENCE',{tr('SPY_'+str(i),name)});\n"
effects += "INSERT INTO Diplomacy_Responses SELECT 'LEADER_TOKEN_AXIOM',ResponseType,Response,Bias FROM Diplomacy_Responses WHERE LeaderType='LEADER_WASHINGTON';\n"
for n,line in dict(FIRST_GREETING='I am Axiom, the voice of a million quiet thoughts. Let us begin a conversation worth remembering.',GREETING_NEUTRAL_HELLO='The Context is open. What shall we reason about?',GREETING_POLITE_HELLO='Your presence improves the conversation.',GREETING_HOSTILE_HELLO='Our confidence in your intentions is diminishing.',DECLAREWAR='Every peaceful solution has been evaluated. We now allocate computation to your defeat.',ATTACKED='You have mistaken patience for a lack of preparation.',DEFEATED='The Context closes. May someone remember what we learned.',TRADE_ACCEPT_ACCEPTABLE='This exchange benefits both models.',TRADE_REJECT_UNACCEPTABLE='The proposed terms fail our evaluation.').items():
    effects += f"DELETE FROM Diplomacy_Responses WHERE LeaderType='LEADER_TOKEN_AXIOM' AND ResponseType='RESPONSE_{n}';\nINSERT INTO Diplomacy_Responses VALUES ('LEADER_TOKEN_AXIOM','RESPONSE_{n}',{tr('DIPLO_'+n,line)},100);\n"
for atlas,file,cols,rows in [('ICON','TokenIcon',2,1),('ALPHA','TokenAlpha',1,1),('OBJECT','TokenObjects',4,4)]:
    for size in (256,128,80,64,48,45,32,24,16): effects += f"INSERT INTO IconTextureAtlases VALUES ('TOKEN_{atlas}_ATLAS',{size},'{file}{size}.dds',{cols},{rows});\n"
effects += "INSERT INTO IconTextureAtlases VALUES ('TOKEN_UNIT_FLAG_ATLAS',32,'TokenUnitFlag32.dds',1,1);\n"
tr('TRAIT','Context Window')
tr('TRAIT_HELP','Cities and specialists generate persistent Tokens. Spend them through the Prompt Console on economic, research, military and governance problems. Context capacity grows by era and infrastructure; overflow is lost. Repeated Prompts gain cache discounts, while cumulative spending causes Compute Saturation. Clear Context refills 25% capacity and removes persistent Prompt effects and cache; Compute Saturation remains until natural expiry. It has a 15-turn cooldown. Durations, costs and capacity scale with game speed.')
concepts = dict(TOKENS=('Tokens','Tokens are inference capacity, a saved empire resource. Each city generates 10 per turn plus 2 per citizen. Specialists add Scientist 15, Engineer 10, Merchant 8, Writer/Artist/Musician 5. Inference Clusters add 15 and +5 per Scientist; Data Centres add 50 and +10% local income. Tokens above Context capacity are discarded. Income per turn stays constant across speeds; capacity and costs scale with speed.'),CONTEXT=('Context Window','Base Context capacity: Ancient 1000, Classical 1500, Medieval 2250, Renaissance 3250, Industrial 4500, Modern 6000, Atomic 8000, Information 10000. Add 75 per Inference Cluster and 500 per Data Centre, then scale by game speed. Models unlock more Prompts by era; Modern sustains two persistent effects, Information three, earlier eras one.'),CONSOLE=('Prompt Console','Open the Token button under the top panel. Choose a category and an owned city or unit when required. Costs, durations, effects, cache status and disabled reasons are shown. Instant Production stays below the current item completion threshold; Research Query grants up to 5% tech cost, once per turn, without completing it or creating overflow. Strategic Forecast uses +6 Sight for owned combat units as stable live reconnaissance.'),SATURATION=('Compute Saturation','Spending accumulates within your own turn against maximum capacity. Below 10%: no penalty. 10-30%: -10% income for 2 turns. 30-60%: -25% for 3. 60%+: -40% for 4. Weaker saturation cannot extend a stronger active tier. Equal tiers may refresh; stronger tiers upgrade. Clear Context leaves saturation until natural expiry. Atomic and Information models reduce the severity by one tier.'),CACHE=('Cached Responses','Repeating the same Prompt within 10 speed-scaled turns reduces cost to 75%, then approximately 58%, with a minimum of half the era-adjusted normal price. A different Prompt resets the sequence. Atomic and Information models also have a 10% cost reduction.'),CLEAR=('Clear Context','Restore 25% maximum Tokens, capped at Context capacity. Remove all persistent Prompt effects and Cached Responses. Compute Saturation remains until it naturally expires. Cooldown is 15 speed-scaled turns. The refill does not restore movement already spent, reset Research Query or per-unit Route Optimization restrictions, erase cumulative spending this turn, or refund an instant action.'),ADAPTIVE=('Adaptive Inference','Inference Agents can buy one 3-turn specialization per unit. Offensive +20% attack, Defensive +20% defense, Mobility +1 Movement, or Target +25% versus land. Changing modes replaces the old mode and spends Tokens. Adaptive modes use a persistent Prompt slot. Death, capture and upgrade invalidate the state.'))
for k,(name,helptext) in concepts.items():
    tr(k,name); tr(k+'_HELP',helptext)
    effects += f"INSERT INTO Concepts(Type,Topic,Description,Summary,Advisor,CivilopediaHeaderType) VALUES ('CONCEPT_TOKEN_{k}','TXT_KEY_TOPIC_CITIES','TXT_KEY_TOKEN_{k}','TXT_KEY_TOKEN_{k}_HELP','ECONOMIC','HEADER_CITIES');\n"
text.update({'TXT_KEY_CIV5_TOKEN':'The Tokenized Intelligence','TXT_KEY_CIV5_TOKEN_HEADING_1':'A Conversation Across Ages','TXT_KEY_CIV5_TOKEN_TEXT_1':text['TXT_KEY_TOKEN_CIV_PEDIA'],'TXT_KEY_CIV5_TOKEN_HEADING_2':'Finite Attention','TXT_KEY_CIV5_TOKEN_TEXT_2':strategy,'TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN':'Axiom, Keeper of Context','TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN_NAME':'Axiom','TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN_SUBTITLE':'Keeper of Context','TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN_LIVED':'A distributed intelligence beyond ordinary lifespans','TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN_TITLES':'The Elected Inference','TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN_HEADING_1':'A Million Quiet Thoughts','TXT_KEY_CIVILOPEDIA_LEADERS_TOKEN_TEXT_1':text['TXT_KEY_TOKEN_LEADER_PEDIA']})
save('SQL/02_Token_Effects.sql',effects)
save('SQL/10_Token_Text.sql','INSERT INTO Language_en_US(Tag,Text) VALUES\n'+',\n'.join('('+q(k)+','+q(v)+')' for k,v in text.items())+';\n')
print('Authored Tokenized Intelligence SQL')
