"""Editable English text source for The Shattered Empire."""
TEXT = {
 'CIV':'The Shattered Empire','SHORT':'Shattered Empire','ADJECTIVE':'Imperial','LEADER':'The Last Emperor',
 'TRAIT':'The Weight of an Empire',
 'TRAIT_HELP':'Begin with 82 Imperial Authority, a population-2 capital and two provinces (or Settlers where safe founding is unavailable). Every province has a persistent Governor. Govern Loyalty, military Oaths, reforms and succession to avert civil wars. Survive collapse and restore unity to earn +10% Production and Culture while stable. Open Imperial Administration near the top panel.',
 'CIV_PEDIA':'Conquering the world was never the difficult part. Keeping it was.[NEWLINE][NEWLINE]Aeternum once ruled a world of marble avenues, provincial palaces and legions sworn to the Eternal Throne. Victory brought distant lands into the imperial order, but each Governor acquired estates, clients and soldiers. The Last Emperor inherits the symbols of eternity and the practical burden of persuading powerful people to keep their promises.[NEWLINE][NEWLINE]This fictional civilization tells its history through the Governors appointed, soldiers lost, Emperors chosen, and provinces restored in each campaign. Collapse is avoidable: a loyal, ambitious Governor can remain an invaluable ally.',
 'LEADER_PEDIA':'The Last Emperor is the permanent diplomatic face of the Eternal Throne. Individual rulers succeed one another inside Imperial Administration, where their reigns, relationships and achievements survive saving and loading. The monarch must balance the hereditary court, the armies, and the provincial council.',
 'STRATEGY':'Three early cities and strong Imperial Legions reward expansion, but sustained growth strains administration. Garrison provinces, connect them to Aeternum and construct Governor Palaces. Complete demands before deadlines and manage ambitious Governors before they organize a civil war. Choose reforms and successors that address your weakest institution. Military suppression, autonomy and reconciliation can all end rebellions.',
 'DAWN':'Last Emperor, the Eternal Throne is yours. Aeternum and two provinces await your command. Your Legions can conquer kingdoms; your Governors can keep them prosperous or tear them apart. Rule wisely, listen before resentment hardens, and make the shattered crown whole again.',
 'LEGION':'Imperial Legion','LEGION_HELP':'Replaces the Warrior. Strength 10; costs 15% more (rounded up). Imperial Discipline grants +15% Combat Strength in friendly territory while Authority is at least 60. Discipline survives upgrades. Participates in provincial Oaths and bounded crisis defections.',
 'LEGION_PEDIA':'The Imperial Legion carries the eagle of Aeternum and an oath to the Eternal Throne. Training binds the cohort to its recruiting province; service and victory strengthen its allegiance, while a rebellious home Governor may threaten it. Its inherited discipline endures when its weapons change.',
 'LEGION_STRATEGY':'Use the Legion to defend exposed early provinces. Maintain Authority above 60 for its friendly territory bonus. A veteran with a weak Oath and a rebellious home province may defect; keep provincial loyalty high.',
 'PALACE':"Provincial Governor's Palace",'PALACE_HELP':'Replaces the Monument, retaining all normal costs and effects. +1 Gold. In provinces: +2 Loyalty each political interval and permits autonomy charters. In the capital: +1 Authority every ten Standard-speed turns. Effects scale in timing with game speed.',
 'PALACE_PEDIA':'The Palace combines the public monuments of imperial memory with the offices of provincial rule. Tax accounts, petitions and military rolls pass through its halls. Its strength rests in trusted administration, not merely marble walls.',
 'PALACE_STRATEGY':'Build early in provinces to support Loyalty and unlock autonomy. The capital Palace provides measured Authority recovery. Provincial administration costs 1 Gold per city regardless of the Palace.',
 'DUMMY':'Imperial administration effect','GOLDEN':'Golden Empire','STABLE':'Stable Empire','STRAINED':'Strained Empire','FRACTURED':'Fractured Empire','COLLAPSE':'Imperial Collapse',
 'LOYALIST':'Loyalist','MILITARIST':'Militarist','MERCHANT':'Merchant','POPULIST':'Populist','AMBITIOUS':'Ambitious',
 'NONE':'Unreformed court','MONARCHY':'Absolute Monarchy','FEDERATION':'Imperial Federation','DICTATORSHIP':'Military Dictatorship',
 'PROVINCE_I':'Province I','PROVINCE_II':'Province II',
 'STAGE_0':'Loyal administration','STAGE_1':'Discontent','STAGE_2':'Defiance','STAGE_3':'Armed revolt','STAGE_4':'Secession crisis',
 'HISTORY_FOUNDING':'Aeternum was founded as {1_Name}, seat of the Eternal Throne.',
 'HISTORY_APPOINTED':'{1_Name} was appointed Governor of {2_City}, serving as a {3_Type}.',
 'HISTORY_REPLACED':'The Emperor dismissed {1_Old} and appointed {2_New}.',
 'HISTORY_REBEL':'Governor {1_Name} betrayed the Throne and raised a rebellion in {2_City}.',
 'HISTORY_REBEL_END':'The faction of {1_Name} ended its rebellion: {2_Result}.',
 'HISTORY_WAR':'{1_War} began when {2_Leader} claimed the Throne, supported by {3_Count} provinces.',
 'HISTORY_WAR_END':'{1_War} ended: {2_Result}.',
 'HISTORY_DEFECTION':'A regiment associated with {1_Name} defected ({2_Unit}).',
 'HISTORY_DEMAND_MET':'The court fulfilled the demand of {1_Name}: {2_Demand}.',
 'HISTORY_DEMAND_FAILED':'The court refused or failed the demand of {1_Name}: {2_Demand}.',
 'HISTORY_REFORM':'The Emperor adopted {1_Reform}.','HISTORY_CHARTER':'{1_Name} received a provincial autonomy charter.',
 'HISTORY_PAYMENT':'Received {1_Cost} Gold from the court.','HISTORY_PAID':'The court granted {1_Name} {2_Cost} Gold.',
 'HISTORY_COUNCIL':'The reign of {1_Name} approached its end; the Council presented three successors.',
 'HISTORY_SUCCESSOR':'{1_Name} took the Eternal Throne as {2_Heir}.','HISTORY_SUCCESSION_CRISIS':'A disputed succession cost the Empire legitimacy.',
 'HISTORY_COLLAPSE':'Imperial Authority fell into collapse. The provinces awaited a restoration.',
 'HISTORY_RESTORED':'The Empire Reborn: authority and provincial loyalty endured, restoring imperial unity.',
 'HISTORY_LOST':'The Empire lost {1_City}.','HISTORY_CONQUEST':'The Legions conquered {1_City} during the reign of {2_Emperor}.',
 'DEMAND_TITLE':'Provincial petition','DEMAND_NOTICE':'{1_Name}, Governor of {2_City}, requests: {3_Demand}. Deadline: turn {4_Turn}. Review Imperial Administration.',
 'DEMAND_GARRISON':'Maintain a military garrison','DEMAND_CONNECTION':'Connect the province to the capital','DEMAND_WALLS':'Build Walls','DEMAND_GROWTH':'Increase provincial population','DEMAND_PEACE':'Maintain five Standard-speed turns of peace','DEMAND_FARMS':'Construct two additional Farms','DEMAND_RESOURCE':'Improve the indicated strategic resource','DEMAND_CAMP':'Eliminate the nearby Barbarian camp','DEMAND_FUNDS':'Provide financial assistance','DEMAND_AUTONOMY':'Grant military autonomy',
 'DEMAND_MET':'Demand fulfilled: {1_Demand}.','DEMAND_FAILED':'Demand refused or expired: {1_Demand}.',
 'UNREST_TITLE':'Provincial unrest','UNREST_NOTICE':'{1_Name} in {2_City} has entered {3_Stage}.',
 'REVOLT_TITLE':'Provincial rebellion','REVOLT_NOTICE':'{1_Name} has raised a rebel army near {2_City}. Suppress the tracked forces or negotiate in Imperial Administration.',
 'WAR_NAME':'The War of {1_Count} Crowns','WAR_NOTICE':'{1_Name} claims the Eternal Throne; {2_Count} provinces are involved. The civil war ends when every participating faction is resolved.',
 'REBEL_UNIT':'Rebels of {1_Name}',
 'RESULT_SUPPRESSED':'military suppression','RESULT_AUTONOMY':'negotiated autonomy','RESULT_CONCESSION':'financial concessions','RESULT_RECONCILED':'political reconciliation','RESULT_EXHAUSTED':'exhaustion and autonomy','RESULT_LOST':'territorial loss','RESULT_RESTORED':'imperial unity restored',
 'SUCCESSION_TITLE':'The Imperial Council','SUCCESSION_NOTICE':'Three persistent candidates seek the Eternal Throne. Choose in the Dynasty tab before the deadline; otherwise the Council selects an appropriate heir.',
 'HEIR_BLOOD':'Heir of Blood','HEIR_STEEL':'Heir of Steel','HEIR_COUNCIL':"Council's Choice",'HEIR_COUNCIL_RELATION':'Provincial council',
 'HEIR_HELP_BLOOD':'+15 Authority. Ambitious Governors lose 10 Loyalty. Peaceful succession adds another +5 Authority.',
 'HEIR_HELP_STEEL':'+15 military Oath. Merchant and Populist Governors lose 10 Loyalty. Peaceful succession adds +5 Authority.',
 'HEIR_HELP_COUNCIL':'+10 provincial Loyalty, -15 Authority, and -10% city Production for ten Standard-speed turns. Peaceful succession adds +5 Authority.',
 'HEIR_TRAIT_BLOOD':'Hereditary legitimacy','HEIR_TRAIT_STEEL':'Veteran commander','HEIR_TRAIT_COUNCIL':'Consensus builder','HEIR_TRAIT_FOUNDER':'Keeper of the fractured crown',
 'REFORM_HELP_MONARCHY':'+10% military Production in the capital. Suppression yields +7 Authority instead of +5. Distant provinces lose another 2 Loyalty per interval. Rebel recruitment budgets increase by 1.',
 'REFORM_HELP_FEDERATION':'+3 Loyalty per interval in chartered provinces and fewer demands. Chartered provinces lose 10% Production. Administrative capacity increases by three cities.',
 'REFORM_HELP_DICTATORSHIP':'+15 effective Oath to disciplined Legion lineages while active. +10% Combat Strength against barbarian units, including rebels. Militarist Governor Ambition grows faster.',
 'REFORM_COST':'Costs 10 Authority; changes have a 30 Standard-speed turn cooldown. Unlocks in the Classical Era.',
 'REPLACE_COST':'Costs 8 Authority. Replacement creates one turn of resistance and reduces local military Oaths by 5.',
 'CHARTER_COST':'Peacetime: 50% provincial Gold cost and 5 Authority; +15 Loyalty, +12 Ambition and permanent autonomy. Requires a Palace and loyal or discontented administration.',
 'RECONCILE_COST':'Costs 15 Authority; ends the local revolt and rebuilds loyalty.',
 'REBELLION_REQUIRED':'An active provincial rebellion is required.','AUTHORITY_REQUIRED':'Insufficient Imperial Authority.','GOLD_REQUIRED':'Insufficient Gold.','ERA_REQUIRED':'Reforms unlock in the Classical Era.','COOLDOWN':'This decision is on cooldown.','PALACE_REQUIRED':'A Palace and an unchartered province are required.','INVALID':'This decision is no longer available.','READY':'Decision available.','ACTION_DONE':'The court has enacted the decision.','REPLACED':'Dismissed from office.',
 'ACTION_BRIBE':'Compensate Governor: +12 Loyalty','ACTION_CHARTER':'Grant peacetime autonomy','ACTION_REPLACE':'Replace Governor: 8 Authority','ACTION_FUND':'Fund the petition: fulfill demand','ACTION_REFUSE':'Refuse the petition: -12 Loyalty','ACTION_CONCESSION':'Negotiate financial concessions','ACTION_RECONCILE':'Political reconciliation: 15 Authority',
 'PROMO_DISCIPLINE':'Imperial Discipline','PROMO_HELP_DISCIPLINE':'Persistent Legion lineage. +15% friendly territory strength while Authority is at least 60.',
 'PROMO_DISCIPLINE_ACTIVE':'Imperial Discipline: active','PROMO_HELP_DISCIPLINE_ACTIVE':'+15% Combat Strength in friendly territory.',
 'PROMO_REBEL_COMBAT':'Imperial counterinsurgency','PROMO_HELP_REBEL_COMBAT':'+10% Combat Strength against barbarians, including political rebel armies.',
 'RESTORED_TITLE':'The Empire Reborn','RESTORED_NOTICE':'+10% Production and Culture in all imperial cities while stable. Renewed political crisis makes these effects dormant.',
 'TITLE':'Imperial Administration','LAUNCHER':'Imperial Authority: {1_Authority} - {2_State}',
 'SUMMARY':'Emperor {1_Name} | Authority {2_Authority}: {3_State}[NEWLINE]Government: {4_Reform}',
 'TAB_OVERVIEW':'Overview','TAB_GOVERNORS':'Governors','TAB_DECISIONS':'Decisions','TAB_MILITARY':'Military Oaths','TAB_REFORMS':'Reforms','TAB_DYNASTY':'Dynasty','TAB_CHRONICLE':'Chronicle',
 'GOVERNOR_DETAIL':'{1_City}[NEWLINE]{2_Name}, {3_Archetype}[NEWLINE]Loyalty {4_Loyalty} | Ambition {5_Ambition} | Prestige {6_Prestige}[NEWLINE]{7_Stage}',
 'GOVERNOR_DATES':'Governor #{1_ID}; appointed turn {2_Turn}; relationship {3_Relationship}; autonomy: {4_Charter}',
 'LOYALTY_CHANGE':'Last interval Loyalty change: {1_Amount} (routine movement capped at +/-8)',
 'DEMAND_DETAIL':'Petition: {1_Demand}[NEWLINE]Deadline: turn {2_Turn}; financial compensation: {3_Cost} Gold',
 'DEMAND_TARGET':'Target total: {1_Target}','DEMAND_LOCATION':'Target plot: {1_X}, {2_Y}',
 'DECISION_HELP':'Only currently valid actions are shown. Replacements cost Authority; payments scale with population, income and speed. Decisions have cooldowns. Ambition and Prestige alone never cause rebellion.',
 'OVERVIEW_DETAIL':'Loyal provinces: {1_Loyal} | Discontented: {2_Unrest} | Rebel: {3_Rebels}[NEWLINE]Administrative strain: {4_Strain} | Average Loyalty: {5_Loyalty}[NEWLINE]War duration pressure: {6_Turns} turns',
 'OVERVIEW_HELP':'Loyalty below 45 causes discontent; below 25 causes defiance. Two critical political checks can trigger revolt. Authority below 30 and three nearby severe provinces with an ambitious claimant can produce a War of the Crowns. Administration capacity is 5 + twice your era, with three extra under Federation.',
 'WAR_DETAIL':'{1_War}[NEWLINE]Claimant: {2_Leader}; began turn {3_Turn}[NEWLINE]Provinces: {4_Count}; rebel troops raised: {5_Troops}; defections: {6_Defections}',
 'WAR_RECORD':'{1_War}: claimant {2_Leader}[NEWLINE]Turns {3_Start}-{4_End}: {5_Result}[NEWLINE]Provinces restored {6_Count}; troops raised {7_Troops}; Authority lost {8_Lost}, recovered {9_Recovered}',
 'RESTORATION_DETAIL':'Restoration: {1_State}[NEWLINE]Qualifying stability: {2_Progress}/{3_Required} turns. Requires a resolved collapse, Authority 75, average Loyalty 80, no revolt or pending succession.',
 'SUCCESSION_PENDING':'The Council awaits a successor. Decision deadline: turn {1_Turn}.',
 'MILITARY_OVERVIEW':'Tracked land regiments: {1_Count}; average Oath: {2_Oath}',
 'MILITARY_HELP':'Oaths follow home-province Loyalty and Authority. Defections require a political rebellion and Oath below 40, are limited to two per faction, and exclude foreign mod uniques, civilians, cargo, embarked troops and units in cities. An equivalent rebel is created safely before a defector is removed.',
 'CAPITAL_ARMY':'Central imperial army','UNIT_DETAIL':'{1_Name} (lineage #{2_ID})[NEWLINE]Oath {3_Oath}: {4_Status} | Battles {5_Battles}; kills {6_Kills}',
 'OATH_FANATIC':'Fanatically loyal','OATH_RELIABLE':'Reliable','OATH_QUESTIONABLE':'Questionable','OATH_MUTINY':'Mutiny risk','OATH_DEFECTION':'Defection candidate',
 'DYNASTY_RECORD':'Emperor {1_Name}[NEWLINE]Reign {2_Start}-{3_End} ({4_Length} turns)[NEWLINE]Civil wars {5_Wars}; revolts {6_Revolts}; provinces acquired {7_Acquired}; lost {8_Lost}; reforms {9_Reforms}',
 'REFORM_OVERVIEW':'Active government: {1_Reform}[NEWLINE]Next change available in {2_Turns} turns. Reforms unlock after the Ancient Era and cost 10 Authority.',
 'ADOPT_REFORM':'Adopt {1_Reform}','SELECT_HEIR':'Crown {1_Name}','TURN':'Turn {1_Turn}','UI_HINT':'Decisions are validated by the gameplay manager. Escape closes administration.',
 'YES':'Yes','NO':'No','ACTIVE':'Active','DORMANT':'Dormant','LOCKED':'Not yet restored','UNKNOWN_CITY':'an imperial city',
}
# Settlement hardening and civil-war outcome text.
TEXT.update({
 'SETTLEMENT_COST':'Wartime: 200% provincial Gold cost and 10 Authority. Ends this faction only, guarantees at least 70 Loyalty, adds 20 Ambition and permanent autonomy. Hereditary privileges add 0.5 Ambition each political interval, including after Governor replacement.',
 'AUTHORITY_LABEL':'Authority',
 'ACTION_SETTLEMENT':'Negotiate wartime autonomy',
 'HISTORY_DEMAND_CANCELLED':'The petition of {1_Name} was withdrawn because it was no longer feasible: {2_Demand}. No political penalty applied.',
 'RESULT_MILITARY':'military restoration',
 'RESULT_NEGOTIATED':'negotiated peace and imperial reunification',
 'RESULT_MIXED':'mixed military and negotiated restoration',
 'RESULT_FAILED':'failed restoration or incomplete historical outcome',
 'HISTORY_REBEL_SUPPRESSED':'The Imperial Legions crushed the rebellion of Governor {1_Name}, restoring the Throne through force.',
 'HISTORY_REBEL_AUTONOMY':'Governor {1_Name} accepted an Imperial Charter, ending hostilities in exchange for lasting provincial autonomy.',
 'HISTORY_REBEL_CONCESSION':'Governor {1_Name} accepted financial concessions and ended the rebellion through negotiation.',
 'HISTORY_REBEL_RECONCILED':'Governor {1_Name} reconciled with the Emperor, ending the rebellion through political compromise.',
 'HISTORY_REBEL_EXHAUSTED':'The rebellion of Governor {1_Name} exhausted itself; autonomy replaced a decisive imperial victory.',
 'HISTORY_REBEL_LOST':'The Throne lost the province of Governor {1_Name}; its rebellion ended without imperial victory.',
 'WAR_PROGRESS':'Faction outcomes: military {1_Military}, negotiated {2_Negotiated}, exhausted {3_Exhausted}, lost {4_Lost}, undocumented {5_Unknown}.',
 'WAR_OUTCOMES':'Faction outcomes: military {1_Military}, negotiated {2_Negotiated}, exhausted {3_Exhausted}, lost {4_Lost}, undocumented {5_Unknown}. Completion Authority gained: {6_Bonus}.',
 'WAR_LEGACY':'Historical record from an earlier court: the military and negotiated breakdown was not recorded. Previous rewards remain unchanged.',
})

REASONS = {'GARRISON':'Military garrison','UNGARRISONED':'No military garrison','CONNECTION':'Capital connection','PALACE':"Governor's Palace",'AUTONOMY':'Autonomy charter','FEDERATION':'Federation charter','DISTANCE':'Distance from capital','MONARCHY':'Centralized government','AMBITION':'Ambition above 70','UNHAPPINESS':'Negative imperial Happiness','WAR':'Prolonged warfare','STRAIN':'Administrative overextension','AUTHORITY':'Imperial Authority','LOYALIST':'Loyalist administration','MERCHANT':'Economic restrictions','POPULIST':'Prosperous population','RELATIONSHIP':'Relationship with Emperor','NEARBY_REVOLT':'Nearby rebel support'}
TEXT.update({'REASON_' + k:v for k,v in REASONS.items()})
DIALOGUE = {
 'FIRST_GREETING':'Behold the Eternal Throne. Kingdoms rise and fall, but our Empire shall endure. Do you come as a friend, or as another enemy seeking our ruins?',
 'DEFEATED':'The banners have fallen. The Legions have scattered. Yet remember this, conqueror: even shattered empires leave shadows upon the earth.',
 'DECLAREWAR':'Our Legions will settle what your envoys could not. Let the imperial eagles advance.',
 'ATTACKED':'You strike at the Throne while our provinces watch. You shall learn what still binds this Empire.',
 'PEACE_MADE_BY_HUMAN_GRACIOUS':'Let our peoples rest. Even an Emperor must know when to sheathe the sword.',
 'TRADE_ACCEPT_ACCEPTABLE':'The imperial treasury accepts these terms.',
 'TRADE_REJECT_UNACCEPTABLE':'Such terms would make every Governor laugh at the Throne. Present a fairer offer.',
}
