-- Run after companion-table inheritance.
INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_ROULS_SOMATIC_LATTICE', 'YIELD_SCIENCE', 0
 WHERE NOT EXISTS (SELECT 1 FROM Building_YieldChanges
 WHERE BuildingType = 'BUILDING_ROULS_SOMATIC_LATTICE' AND YieldType = 'YIELD_SCIENCE');
INSERT INTO Building_YieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_ROULS_SOMATIC_LATTICE', 'YIELD_PRODUCTION', 0
 WHERE NOT EXISTS (SELECT 1 FROM Building_YieldChanges
 WHERE BuildingType = 'BUILDING_ROULS_SOMATIC_LATTICE' AND YieldType = 'YIELD_PRODUCTION');
UPDATE Building_YieldChanges SET Yield = Yield + 2
 WHERE BuildingType = 'BUILDING_ROULS_SOMATIC_LATTICE' AND YieldType IN ('YIELD_SCIENCE', 'YIELD_PRODUCTION');

INSERT INTO Unit_FreePromotions (UnitType, PromotionType) VALUES
('UNIT_ROULS_HOLLOWHOUND', 'PROMOTION_ROULS_SECOND_SKIN'),
('UNIT_ROULS_BUDDY', 'PROMOTION_ROULS_EVERLASTING_PASSENGER');
-- Buddy has no ranged-only, anti-submarine, interception, resource or upgrade
-- rows from its visual model. It is a Biology-era naval melee support unit.
INSERT INTO Unit_AITypes (UnitType, UnitAIType) VALUES
('UNIT_ROULS_BUDDY', 'UNITAI_ATTACK_SEA'),
('UNIT_ROULS_BUDDY', 'UNITAI_RESERVE_SEA'),
('UNIT_ROULS_BUDDY', 'UNITAI_ESCORT_SEA');
INSERT INTO Unit_Flavors (UnitType, FlavorType, Flavor) VALUES
('UNIT_ROULS_BUDDY', 'FLAVOR_NAVAL', 22),
('UNIT_ROULS_BUDDY', 'FLAVOR_DEFENSE', 10),
('UNIT_ROULS_BUDDY', 'FLAVOR_NAVAL_RECON', 6);
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
 SELECT 'UNIT_ROULS_BUDDY', SelectionSound, FirstSelectionSound
 FROM UnitGameplay2DScripts WHERE UnitType = 'UNIT_BATTLESHIP';
INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor) VALUES
('BUILDING_ROULS_SOMATIC_LATTICE', 'FLAVOR_SCIENCE', 20),
('BUILDING_ROULS_SOMATIC_LATTICE', 'FLAVOR_PRODUCTION', 15),
('BUILDING_ROULS_SOMATIC_LATTICE', 'FLAVOR_MILITARY_TRAINING', 20);

INSERT INTO Leader_Flavors (LeaderType, FlavorType, Flavor)
 SELECT 'LEADER_TRENT_ROULS', Type,
 CASE Type
 WHEN 'FLAVOR_OFFENSE' THEN 8 WHEN 'FLAVOR_DEFENSE' THEN 8
 WHEN 'FLAVOR_CITY_DEFENSE' THEN 7 WHEN 'FLAVOR_MILITARY_TRAINING' THEN 9
 WHEN 'FLAVOR_SCIENCE' THEN 9 WHEN 'FLAVOR_SPACESHIP' THEN 8
 WHEN 'FLAVOR_NAVAL' THEN 7 WHEN 'FLAVOR_NAVAL_RECON' THEN 7
 WHEN 'FLAVOR_NAVAL_GROWTH' THEN 6 WHEN 'FLAVOR_NAVAL_TILE_IMPROVEMENT' THEN 6
 WHEN 'FLAVOR_RANGED' THEN 7 WHEN 'FLAVOR_MOBILE' THEN 6
 WHEN 'FLAVOR_PRODUCTION' THEN 7 WHEN 'FLAVOR_GROWTH' THEN 6
 WHEN 'FLAVOR_EXPANSION' THEN 5 WHEN 'FLAVOR_DIPLOMACY' THEN 5
 WHEN 'FLAVOR_WONDER' THEN 2 WHEN 'FLAVOR_CULTURE' THEN 3
 WHEN 'FLAVOR_ARCHAEOLOGY' THEN 2 WHEN 'FLAVOR_RELIGION' THEN 1
 ELSE 5 END FROM Flavors;
INSERT INTO Leader_MajorCivApproachBiases (LeaderType, MajorCivApproachType, Bias)
 SELECT 'LEADER_TRENT_ROULS', MajorCivApproachType,
 CASE MajorCivApproachType WHEN 'MAJOR_CIV_APPROACH_WAR' THEN 7
 WHEN 'MAJOR_CIV_APPROACH_AFRAID' THEN 2 WHEN 'MAJOR_CIV_APPROACH_GUARDED' THEN 6
 ELSE 5 END FROM Leader_MajorCivApproachBiases WHERE LeaderType = 'LEADER_WASHINGTON';
INSERT INTO Leader_MinorCivApproachBiases (LeaderType, MinorCivApproachType, Bias)
 SELECT 'LEADER_TRENT_ROULS', MinorCivApproachType, Bias
 FROM Leader_MinorCivApproachBiases WHERE LeaderType = 'LEADER_WASHINGTON';
-- Preserve complete generic diplomatic coverage; specific voice appears below.
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias)
 SELECT 'LEADER_TRENT_ROULS', ResponseType, Response, Bias
 FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_WASHINGTON';

-- Civilization-specific city, spy, Great Person names and diplomacy.
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_1');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_2');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_3');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_4');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_5');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_6');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_7');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_8');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_9');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_10');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_11');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_12');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_13');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_14');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_15');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_16');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_17');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_18');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_19');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_20');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_21');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_22');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_23');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_24');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_25');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_26');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_27');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_28');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_29');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_30');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_31');
INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_CITY_ROULS_32');
INSERT INTO Civilization_SpyNames (CivilizationType, SpyName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_SPY_ROULS_1');
INSERT INTO Civilization_SpyNames (CivilizationType, SpyName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_SPY_ROULS_2');
INSERT INTO Civilization_SpyNames (CivilizationType, SpyName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_SPY_ROULS_3');
INSERT INTO Civilization_SpyNames (CivilizationType, SpyName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_SPY_ROULS_4');
INSERT INTO Civilization_SpyNames (CivilizationType, SpyName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_SPY_ROULS_5');
INSERT INTO Civilization_SpyNames (CivilizationType, SpyName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_SPY_ROULS_6');
INSERT INTO Civilization_SpyNames (CivilizationType, SpyName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_SPY_ROULS_7');
INSERT INTO Civilization_SpyNames (CivilizationType, SpyName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_SPY_ROULS_8');
INSERT INTO Civilization_SpyNames (CivilizationType, SpyName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_SPY_ROULS_9');
INSERT INTO Civilization_SpyNames (CivilizationType, SpyName) VALUES ('CIVILIZATION_ROULS_ASCENDANCY', 'TXT_KEY_SPY_ROULS_10');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_1');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_2');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_3');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_4');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_5');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_6');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_7');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_8');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_9');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_10');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_11');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_12');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_13');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_14');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_15');
INSERT INTO Unit_UniqueNames (UnitType, UniqueName) VALUES ('UNIT_ROULS_MATRIARCH', 'TXT_KEY_MATRIARCH_ROULS_16');
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_FIRST_GREETING';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_FIRST_GREETING', 'TXT_KEY_ROULS_DIPLO_FIRST_GREETING_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_GREETING_NEUTRAL_HELLO';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_GREETING_NEUTRAL_HELLO', 'TXT_KEY_ROULS_DIPLO_GREETING_NEUTRAL_HELLO_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_GREETING_POLITE_HELLO';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_GREETING_POLITE_HELLO', 'TXT_KEY_ROULS_DIPLO_GREETING_POLITE_HELLO_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_GREETING_HOSTILE_HELLO';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_GREETING_HOSTILE_HELLO', 'TXT_KEY_ROULS_DIPLO_GREETING_HOSTILE_HELLO_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_GREETING_AT_WAR_HOSTILE';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_GREETING_AT_WAR_HOSTILE', 'TXT_KEY_ROULS_DIPLO_GREETING_AT_WAR_HOSTILE_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_DECLAREWAR';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_DECLAREWAR', 'TXT_KEY_ROULS_DIPLO_DECLAREWAR_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_DOW_GENERIC';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_DOW_GENERIC', 'TXT_KEY_ROULS_DIPLO_DOW_GENERIC_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_ATTACKED';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_ATTACKED', 'TXT_KEY_ROULS_DIPLO_ATTACKED_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_DEFEATED';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_DEFEATED', 'TXT_KEY_ROULS_DIPLO_DEFEATED_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_PEACE_OFFER';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_PEACE_OFFER', 'TXT_KEY_ROULS_DIPLO_PEACE_OFFER_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_NO_PEACE';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_NO_PEACE', 'TXT_KEY_ROULS_DIPLO_NO_PEACE_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_AGREE_SHORT';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_AGREE_SHORT', 'TXT_KEY_ROULS_DIPLO_AGREE_SHORT_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_DISAGREE_SHORT';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_DISAGREE_SHORT', 'TXT_KEY_ROULS_DIPLO_DISAGREE_SHORT_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_LETS_HEAR_IT';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_LETS_HEAR_IT', 'TXT_KEY_ROULS_DIPLO_LETS_HEAR_IT_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_LETSHEARIT';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_LETSHEARIT', 'TXT_KEY_ROULS_DIPLO_LETSHEARIT_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_GOODBYE';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_GOODBYE', 'TXT_KEY_ROULS_DIPLO_GOODBYE_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_TRADE_ACCEPT_GENEROUS';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_TRADE_ACCEPT_GENEROUS', 'TXT_KEY_ROULS_DIPLO_TRADE_ACCEPT_GENEROUS_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_TRADE_ACCEPT_ACCEPTABLE';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_TRADE_ACCEPT_ACCEPTABLE', 'TXT_KEY_ROULS_DIPLO_TRADE_ACCEPT_ACCEPTABLE_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_TRADE_REJECT_INSULTING';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_TRADE_REJECT_INSULTING', 'TXT_KEY_ROULS_DIPLO_TRADE_REJECT_INSULTING_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_TRADE_REJECT_UNACCEPTABLE';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_TRADE_REJECT_UNACCEPTABLE', 'TXT_KEY_ROULS_DIPLO_TRADE_REJECT_UNACCEPTABLE_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_WORK_WITH_US';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_WORK_WITH_US', 'TXT_KEY_ROULS_DIPLO_WORK_WITH_US_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_WORK_WITH_US_YES';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_WORK_WITH_US_YES', 'TXT_KEY_ROULS_DIPLO_WORK_WITH_US_YES_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_RESPONSE_TO_BEING_DENOUNCED';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 'TXT_KEY_ROULS_DIPLO_RESPONSE_TO_BEING_DENOUNCED_1', 1);
DELETE FROM Diplomacy_Responses WHERE LeaderType = 'LEADER_TRENT_ROULS' AND ResponseType = 'RESPONSE_THANKFUL';
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_TRENT_ROULS', 'RESPONSE_THANKFUL', 'TXT_KEY_ROULS_DIPLO_THANKFUL_1', 1);
