-- English localization; gameplay text uses built-in Civ V icon/paragraph markup.
INSERT INTO Language_en_US (Tag, Text) VALUES
('TXT_KEY_CIV_ROULS_DESC', 'The Rou''ls Ascendancy'),
('TXT_KEY_CIV_ROULS_SHORT_DESC', 'Rou''ls Ascendancy'),
('TXT_KEY_CIV_ROULS_ADJECTIVE', 'Rou''ls'),
('TXT_KEY_CIV_ROULS_PEDIA', ' The Rou''ls were not born as a species.[NEWLINE][NEWLINE]They were once a research consortium on the world of Trentaal whose scholars attempted to answer one of civilization''s oldest questions: could consciousness survive the body?[NEWLINE][NEWLINE]Their first successful experiment was neither soldier nor ruler.[NEWLINE][NEWLINE]It was a dying companion.[NEWLINE][NEWLINE]An aged quadruped whose joints had failed beyond medicine was transferred into a healthy replacement body. It awakened confused, joyous, and apparently entirely itself.[NEWLINE][NEWLINE]The founder reportedly wept for six hours.[NEWLINE][NEWLINE]Then he published.[NEWLINE][NEWLINE]The consequences reshaped Trentaal.[NEWLINE][NEWLINE]Within centuries, biological death became increasingly optional. Within millennia, the concept of an original body had virtually disappeared. Bodies became vessels, inheritance became consciousness, and identity ceased to depend upon flesh.[NEWLINE][NEWLINE]Ten thousand years later, no known citizen of the Ascendancy inhabits the body in which they were born.[NEWLINE][NEWLINE]Their soldiers do not fear death.[NEWLINE][NEWLINE]Their generals change bodies between campaigns.[NEWLINE][NEWLINE]Their greatest veterans have died hundreds of times.[NEWLINE][NEWLINE]And somewhere aboard the warship known as Buddy, Everlasting, there still resides the same uncomplicated and endlessly enthusiastic consciousness whose first transmigration began the Ascendancy itself.[NEWLINE][NEWLINE]To the Rou''ls, nothing is truly lost.[NEWLINE][NEWLINE]It has merely moved.'),
('TXT_KEY_CIV_ROULS_STRATEGY', 'The Rou''ls Ascendancy excels in wars where both civilizations suffer repeated casualties.[NEWLINE][NEWLINE]Destroying enemy units generates Anima, which can then be spent to preserve experienced Rou''ls units that would otherwise die.[NEWLINE][NEWLINE]Because reconstructed units retain their experience and promotions, the Rou''ls can gradually accumulate a highly experienced army even during costly wars.[NEWLINE][NEWLINE]TRANSMIGRATION allows experienced units stationed far from the battlefield to exchange places with units closer to the front, giving the Rou''ls exceptional strategic mobility.[NEWLINE][NEWLINE]However, both TRANSMIGRATION and unit resurrection draw upon the same limited Anima pool. Spending aggressively on mobility may leave your army unable to recover from casualties.[NEWLINE][NEWLINE]The civilization is weakest during peaceful openings. Without units dying, Anima is scarce and most Rou''ls abilities provide little economic benefit.[NEWLINE][NEWLINE]Choose wars carefully.[NEWLINE][NEWLINE]The Rou''ls do not necessarily win the first battle.[NEWLINE][NEWLINE]They win because they can keep fighting the fifth.'),
('TXT_KEY_CIV5_ROULS', 'The Rou''ls Ascendancy'),
('TXT_KEY_CIV5_ROULS_HEADING_1', 'The First Passenger'),
('TXT_KEY_CIV5_ROULS_TEXT_1', ' The Rou''ls were not born as a species.[NEWLINE][NEWLINE]They were once a research consortium on the world of Trentaal whose scholars attempted to answer one of civilization''s oldest questions: could consciousness survive the body?[NEWLINE][NEWLINE]Their first successful experiment was neither soldier nor ruler.[NEWLINE][NEWLINE]It was a dying companion.[NEWLINE][NEWLINE]An aged quadruped whose joints had failed beyond medicine was transferred into a healthy replacement body. It awakened confused, joyous, and apparently entirely itself.[NEWLINE][NEWLINE]The founder reportedly wept for six hours.[NEWLINE][NEWLINE]Then he published.[NEWLINE][NEWLINE]The consequences reshaped Trentaal.[NEWLINE][NEWLINE]Within centuries, biological death became increasingly optional. Within millennia, the concept of an original body had virtually disappeared. Bodies became vessels, inheritance became consciousness, and identity ceased to depend upon flesh.[NEWLINE][NEWLINE]Ten thousand years later, no known citizen of the Ascendancy inhabits the body in which they were born.[NEWLINE][NEWLINE]Their soldiers do not fear death.[NEWLINE][NEWLINE]Their generals change bodies between campaigns.[NEWLINE][NEWLINE]Their greatest veterans have died hundreds of times.[NEWLINE][NEWLINE]And somewhere aboard the warship known as Buddy, Everlasting, there still resides the same uncomplicated and endlessly enthusiastic consciousness whose first transmigration began the Ascendancy itself.[NEWLINE][NEWLINE]To the Rou''ls, nothing is truly lost.[NEWLINE][NEWLINE]It has merely moved.'),
('TXT_KEY_CIV5_ROULS_HEADING_2', 'The Flesh Is a Coat'),
('TXT_KEY_CIV5_ROULS_TEXT_2', 'The Rou''ls Ascendancy excels in wars where both civilizations suffer repeated casualties.[NEWLINE][NEWLINE]Destroying enemy units generates Anima, which can then be spent to preserve experienced Rou''ls units that would otherwise die.[NEWLINE][NEWLINE]Because reconstructed units retain their experience and promotions, the Rou''ls can gradually accumulate a highly experienced army even during costly wars.[NEWLINE][NEWLINE]TRANSMIGRATION allows experienced units stationed far from the battlefield to exchange places with units closer to the front, giving the Rou''ls exceptional strategic mobility.[NEWLINE][NEWLINE]However, both TRANSMIGRATION and unit resurrection draw upon the same limited Anima pool. Spending aggressively on mobility may leave your army unable to recover from casualties.[NEWLINE][NEWLINE]The civilization is weakest during peaceful openings. Without units dying, Anima is scarce and most Rou''ls abilities provide little economic benefit.[NEWLINE][NEWLINE]Choose wars carefully.[NEWLINE][NEWLINE]The Rou''ls do not necessarily win the first battle.[NEWLINE][NEWLINE]They win because they can keep fighting the fifth.'),
('TXT_KEY_ROULS_DAWN_OF_MAN', 'The flesh is a coat, Trent Rou''ls.[NEWLINE][NEWLINE]Long ago your people discovered that death was not an ending, but a failure of transportation.[NEWLINE][NEWLINE]The first passenger was merely a dying companion whose failing body could no longer carry him. When he awoke within another, the distinction between body and self was shattered forever.[NEWLINE][NEWLINE]Now ten thousand years have passed.[NEWLINE][NEWLINE]Your citizens wear forms they were never born into.[NEWLINE][NEWLINE]Your veterans have died more times than your enemies have fought wars.[NEWLINE][NEWLINE]Your fleets carry consciousness from vessel to vessel, and the joyful passenger aboard Buddy, Everlasting still sails beside you as he has since before ancient empires fell into dust.[NEWLINE][NEWLINE]Yet beyond Trentaal dwell peoples who still believe flesh defines them.[NEWLINE][NEWLINE]Show them otherwise.[NEWLINE][NEWLINE]When armies fall, wear new bodies.[NEWLINE][NEWLINE]When fleets burn, take new vessels.[NEWLINE][NEWLINE]When the universe believes the Rou''ls destroyed...[NEWLINE][NEWLINE]return.'),
('TXT_KEY_LEADER_TRENT_ROULS', 'Trent Rou''ls, the Unbodied'),
('TXT_KEY_LEADER_TRENT_ROULS_PEDIA', 'Trent Rou''ls has no fixed biological form. His shifting silhouette carries the memory of previous hosts, each a coat once worn and passed on. To the Ascendancy, permanent biological identity is a primitive superstition.[NEWLINE][NEWLINE]Ten thousand years after the first successful consciousness transfer, Trent leads a people for whom memory, loyalty, and experience outlast flesh. Their founder''s first passenger was a beloved dying companion. That same joyous consciousness still sails within Buddy, Everlasting.[NEWLINE][NEWLINE]The flesh is a coat. Wear it well, and pass it on.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_TRENT_ROULS', 'Trent Rou''ls, the Unbodied'),
('TXT_KEY_CIVILOPEDIA_LEADERS_TRENT_ROULS_NAME', 'Trent Rou''ls'),
('TXT_KEY_CIVILOPEDIA_LEADERS_TRENT_ROULS_SUBTITLE', 'The Unbodied'),
('TXT_KEY_CIVILOPEDIA_LEADERS_TRENT_ROULS_LIVED', 'Ten thousand years, and counting'),
('TXT_KEY_CIVILOPEDIA_LEADERS_TRENT_ROULS_TITLES_1', 'Leader of the Rou''ls Ascendancy'),
('TXT_KEY_CIVILOPEDIA_LEADERS_TRENT_ROULS_HEADING_1', 'The Unbodied'),
('TXT_KEY_CIVILOPEDIA_LEADERS_TRENT_ROULS_TEXT_1', 'Trent Rou''ls has no fixed biological form. His shifting silhouette carries the memory of previous hosts, each a coat once worn and passed on. To the Ascendancy, permanent biological identity is a primitive superstition.[NEWLINE][NEWLINE]Ten thousand years after the first successful consciousness transfer, Trent leads a people for whom memory, loyalty, and experience outlast flesh. Their founder''s first passenger was a beloved dying companion. That same joyous consciousness still sails within Buddy, Everlasting.[NEWLINE][NEWLINE]The flesh is a coat. Wear it well, and pass it on.'),
('TXT_KEY_TRAIT_ROULS_SHORT', 'The Flesh Is a Coat'),
('TXT_KEY_TRAIT_ROULS_HELP', 'Gain 1 Anima when a Rou''ls military unit destroys an enemy military unit (maximum 5, or 7 with The Choir Eternal). Spend 1 Anima to restore a killed non-civilian land unit in the nearest valid friendly city with its level, XP and valid promotions at 50% HP; maximum two restores per turn. Restored units cannot act until your next turn. Every 8 turns, spend 2 Anima to exchange two eligible military units. Your Capital receives +1 [ICON_RESEARCH] Science. In the Modern Era, spend 7 Anima once per game to copy an eligible enemy military unit with The Great Migration.'),
('TXT_KEY_UNIT_ROULS_HOLLOWHOUND', 'Hollowhound'),
('TXT_KEY_UNIT_ROULS_HOLLOWHOUND_HELP', 'Unique Rou''ls Rifleman. Costs 10% more Production (rounded up). Same base strength and 2 Movement. Gains +3% Combat Strength per adjacent friendly military unit, up to +15%. Second Skin permits one free Nothing Is Lost restoration every 15 turns, still subject to the empire''s two-restoration limit. Second Skin survives upgrades; Choir of Bodies does not.'),
('TXT_KEY_UNIT_ROULS_HOLLOWHOUND_STRATEGY', 'Keep Hollowhounds in dense formations, and preserve veteran units. A free rebirth helps conserve Anima for Transmigration. Hollowhounds follow the normal Rifleman upgrade path.'),
('TXT_KEY_UNIT_ROULS_HOLLOWHOUND_PEDIA', 'The Hollowhound is an artificial combat vessel designed specifically to house transferred consciousness. It is neither disposable nor irreplaceable: its body can be rebuilt, while the expertise within is carefully preserved. Surrounding minds strengthen its connection to the Second-Skin Choir.'),
('TXT_KEY_UNIT_ROULS_MATRIARCH', 'Matriarch of the Choir'),
('TXT_KEY_UNIT_ROULS_MATRIARCH_HELP', 'Replaces the Great General and retains its normal combat aura and Citadel construction. Eligible military units within 2 tiles reduce the Anima cost of Transmigration by 1, to a minimum of 1. This does not discount Nothing Is Lost.'),
('TXT_KEY_UNIT_ROULS_MATRIARCH_STRATEGY', 'Keep a Matriarch near your reserve or front line to make strategic exchanges cheaper. The Matriarch itself is a Great Person and cannot be swapped, resurrected or consumed by The Great Migration.'),
('TXT_KEY_UNIT_ROULS_MATRIARCH_PEDIA', 'Matriarchs preserve the continuity of the Choir across generations of vessels. Their commands are carried through memory as much as voice. A Matriarch can steady nearby consciousness during transfer, but cannot replace the material cost of rebuilding a fallen soldier.'),
('TXT_KEY_UNIT_ROULS_BUDDY', 'Buddy, Everlasting'),
('TXT_KEY_UNIT_ROULS_BUDDY_HELP', 'Unique Rou''ls naval melee flagship unlocked at Biology. Costs 350 Production; cannot be purchased. Only one may exist, including while awaiting rebirth. Strength 45, Movement 5, Sight 3. Friendly units within 2 tiles gain +10% Combat Strength, and heal 5 HP each turn in friendly territory. Adjacent enemy naval units suffer -10% Combat Strength. On destruction, spend 3 Anima to return after 3 turns at 50% HP with XP and valid promotions preserved. A legal naval tile is required near the Capital or a fallback friendly coastal city; if none exists, Buddy waits in reserve.'),
('TXT_KEY_UNIT_ROULS_BUDDY_STRATEGY', 'Use Buddy to support a fleet and to protect nearby friendly forces. Maintain at least 3 Anima before exposing him to danger. With fewer than 3 Anima he dies normally and may be rebuilt. His resurrection reserve blocks duplicate production until he returns.'),
('TXT_KEY_UNIT_ROULS_BUDDY_PEDIA', 'The first passenger was a dying companion: an aged quadruped whose joints had failed beyond medicine. Transferred into a healthy body, he awakened confused, joyous, and entirely himself. The founder reportedly wept for six hours. Then he published.[NEWLINE][NEWLINE]Ten thousand years later, the same uncomplicated and endlessly enthusiastic consciousness resides aboard Buddy, Everlasting. The flagship is extremely happy to see you.'),
('TXT_KEY_BUILDING_ROULS_SOMATIC_LATTICE', 'Somatic Lattice'),
('TXT_KEY_BUILDING_ROULS_SOMATIC_LATTICE_HELP', 'Replaces the Hospital and retains all normal Hospital effects and prerequisites. Adds +2 [ICON_RESEARCH] Science and +2 [ICON_PRODUCTION] Production. Military units completed in this city have a 25% chance to grant 1 Anima. While you have 0 Anima and at least one Somatic Lattice, gain 1 Anima once every 10 turns across the empire.'),
('TXT_KEY_BUILDING_ROULS_SOMATIC_LATTICE_STRATEGY', 'Somatic Lattices sustain late-game attrition. Their training bonus rewards producing military units; passive Anima is empire-wide and only restores an empty reserve, so extra Lattices never multiply the fallback gain.'),
('TXT_KEY_BUILDING_ROULS_SOMATIC_LATTICE_PEDIA', 'The Somatic Lattice stores biological templates, replacement neural architecture, and empty bodies. Its laboratories join medicine to the preservation of memory, ensuring that a failed vessel need not be the end of a citizen. The same infrastructure feeds a peaceful population and rebuilds a consciousness reserve during quiet years.'),
('TXT_KEY_BUILDING_ROULS_CHOIR_ETERNAL', 'The Choir Eternal'),
('TXT_KEY_BUILDING_ROULS_CHOIR_ETERNAL_HELP', 'Replaces the Heroic Epic. Retains normal Heroic Epic effects, including Morale, its Great Work slot and a Barracks in every city. Units trained here receive +5 additional XP. Raises maximum Anima from 5 to 7. When an enemy unit dies within 3 tiles, there is a 20% chance to gain 1 Anima; maximum one such gain per turn.'),
('TXT_KEY_BUILDING_ROULS_CHOIR_ETERNAL_STRATEGY', 'Build The Choir Eternal to unlock a seven-Anima reserve and prepare for The Great Migration. Its trained veterans form a strong core, and its local death-harvest supports defending the city. The Anima cap follows ownership of the wonder.'),
('TXT_KEY_BUILDING_ROULS_CHOIR_ETERNAL_PEDIA', 'The Choir Eternal is a national archive of the voices that refused to end. Each surviving consciousness joins a living record of the Ascendancy''s campaigns. Its halls contain no tombs: the absent are merely awaiting transport.'),
('TXT_KEY_BUILDING_ROULS_CHOIR_ETERNAL_QUOTE', 'The flesh is a coat. Wear it well, and pass it on.'),
('TXT_KEY_BUILDING_ROULS_CAPITAL_SCIENCE', 'Ancient Institutions of Trentaal'),
('TXT_KEY_BUILDING_ROULS_CAPITAL_SCIENCE_HELP', 'The Rou''ls Capital receives +1 [ICON_RESEARCH] Science.'),
('TXT_KEY_PROMOTION_ROULS_SECOND_SKIN', 'Second Skin'),
('TXT_KEY_PROMOTION_ROULS_SECOND_SKIN_HELP', 'Nothing Is Lost may restore this consciousness for 0 Anima once every 15 turns. The empire-wide limit of two restorations per turn still applies. This ability survives upgrades.'),
('TXT_KEY_PROMOTION_ROULS_SECOND_SKIN_COOLDOWN', 'Second Skin: Rebuilding'),
('TXT_KEY_PROMOTION_ROULS_SECOND_SKIN_COOLDOWN_HELP', 'The free Second Skin rebirth is recharging. Paid Nothing Is Lost remains available. The cooldown is saved with this consciousness and survives upgrades.'),
('TXT_KEY_PROMOTION_ROULS_EVERLASTING_PASSENGER', 'Everlasting Passenger'),
('TXT_KEY_PROMOTION_ROULS_EVERLASTING_PASSENGER_HELP', 'When Buddy is killed, spend 3 Anima to preserve his consciousness. He returns after 3 turns with 50% HP, XP and valid promotions. If no legal naval destination exists, he remains in reserve.'),
('TXT_KEY_PROMOTION_ROULS_ACTION_LOCK', 'Consciousness Settling'),
('TXT_KEY_PROMOTION_ROULS_ACTION_LOCK_HELP', 'This unit cannot move or attack until its owner begins the next turn.'),
('TXT_KEY_PROMOTION_ROULS_BUDDY_AURA', 'Extremely Happy To See You'),
('TXT_KEY_PROMOTION_ROULS_BUDDY_AURA_HELP', 'Within 2 tiles of Buddy: +10% Combat Strength. Heal 5 additional HP at the start of your turn while in friendly territory.'),
('TXT_KEY_PROMOTION_ROULS_BUDDY_INVASION', 'Structurally Invasive'),
('TXT_KEY_PROMOTION_ROULS_BUDDY_INVASION_HELP', 'Adjacent to an enemy Buddy: -10% Combat Strength.'),
('TXT_KEY_PROMOTION_ROULS_CHOIR', 'Choir of Bodies'),
('TXT_KEY_PROMOTION_ROULS_CHOIR_1_HELP', '+3% Combat Strength from adjacent friendly military units. Maximum +15%; removed on upgrading from Hollowhound.'),
('TXT_KEY_PROMOTION_ROULS_CHOIR_2_HELP', '+6% Combat Strength from adjacent friendly military units. Maximum +15%; removed on upgrading from Hollowhound.'),
('TXT_KEY_PROMOTION_ROULS_CHOIR_3_HELP', '+9% Combat Strength from adjacent friendly military units. Maximum +15%; removed on upgrading from Hollowhound.'),
('TXT_KEY_PROMOTION_ROULS_CHOIR_4_HELP', '+12% Combat Strength from adjacent friendly military units. Maximum +15%; removed on upgrading from Hollowhound.'),
('TXT_KEY_PROMOTION_ROULS_CHOIR_5_HELP', '+15% Combat Strength from adjacent friendly military units. Maximum +15%; removed on upgrading from Hollowhound.'),
('TXT_KEY_ROULS_ANIMA', 'Anima'),
('TXT_KEY_ROULS_ANIMA_HELP', 'The Rou''ls preserve consciousness harvested during conflict. Anima is gained primarily by destroying enemy military units and may be spent to transmigrate or restore lost Rou''ls soldiers.'),
('TXT_KEY_ROULS_TRANSMIGRATION', 'TRANSMIGRATION'),
('TXT_KEY_ROULS_TRANSMIGRATION_HELP', 'Every 8 turns, spend 2 Anima to exchange two eligible friendly military units of the same domain. Neither may be embarked, an aircraft, or in enemy territory. Both destinations must be legal. A Matriarch within 2 tiles of an endpoint reduces the cost to 1. Both units lose their remaining actions until your next turn.'),
('TXT_KEY_ROULS_GREAT_MIGRATION', 'THE GREAT MIGRATION'),
('TXT_KEY_ROULS_GREAT_MIGRATION_HELP', 'Once per game from the Modern Era, spend 7 Anima to consume an enemy military unit within 3 tiles of your military. Creates the Rou''ls equivalent of its class at 75% HP with half its XP, capped at 60. Great People, civilians, aircraft, nuclear weapons and limited special units are ineligible. The new unit cannot act until your next turn.'),
('TXT_KEY_CITY_ROULS_1', 'Trentaal'),
('TXT_KEY_CITY_ROULS_2', 'Second Skin'),
('TXT_KEY_CITY_ROULS_3', 'Vesselhaven'),
('TXT_KEY_CITY_ROULS_4', 'Choirhold'),
('TXT_KEY_CITY_ROULS_5', 'Anima Reach'),
('TXT_KEY_CITY_ROULS_6', 'Palimpsest'),
('TXT_KEY_CITY_ROULS_7', 'New Form'),
('TXT_KEY_CITY_ROULS_8', 'Quiet Passage'),
('TXT_KEY_CITY_ROULS_9', 'Somata'),
('TXT_KEY_CITY_ROULS_10', 'Everhome'),
('TXT_KEY_CITY_ROULS_11', 'Memory Deep'),
('TXT_KEY_CITY_ROULS_12', 'Lattice Gate'),
('TXT_KEY_CITY_ROULS_13', 'Lasting Shore'),
('TXT_KEY_CITY_ROULS_14', 'Confluence'),
('TXT_KEY_CITY_ROULS_15', 'Many Voices'),
('TXT_KEY_CITY_ROULS_16', 'Fleshward'),
('TXT_KEY_CITY_ROULS_17', 'Stillwater Choir'),
('TXT_KEY_CITY_ROULS_18', 'Archive of Dawn'),
('TXT_KEY_CITY_ROULS_19', 'Unending Step'),
('TXT_KEY_CITY_ROULS_20', 'Morrowbody'),
('TXT_KEY_CITY_ROULS_21', 'Passengers Rest'),
('TXT_KEY_CITY_ROULS_22', 'Echo Garden'),
('TXT_KEY_CITY_ROULS_23', 'Neural Strand'),
('TXT_KEY_CITY_ROULS_24', 'Returnhaven'),
('TXT_KEY_CITY_ROULS_25', 'Old Promise'),
('TXT_KEY_CITY_ROULS_26', 'Coatfall'),
('TXT_KEY_CITY_ROULS_27', 'Joyous Harbor'),
('TXT_KEY_CITY_ROULS_28', 'Continuance'),
('TXT_KEY_CITY_ROULS_29', 'Soft Horizon'),
('TXT_KEY_CITY_ROULS_30', 'Beyond the Veil'),
('TXT_KEY_CITY_ROULS_31', 'Waking Spire'),
('TXT_KEY_CITY_ROULS_32', 'Eternal Landing'),
('TXT_KEY_SPY_ROULS_1', 'Echo'),
('TXT_KEY_SPY_ROULS_2', 'Mantle'),
('TXT_KEY_SPY_ROULS_3', 'Whisper'),
('TXT_KEY_SPY_ROULS_4', 'Continuity'),
('TXT_KEY_SPY_ROULS_5', 'Threshold'),
('TXT_KEY_SPY_ROULS_6', 'Palimpsest'),
('TXT_KEY_SPY_ROULS_7', 'Vestige'),
('TXT_KEY_SPY_ROULS_8', 'Afterimage'),
('TXT_KEY_SPY_ROULS_9', 'Passenger'),
('TXT_KEY_SPY_ROULS_10', 'Recall'),
('TXT_KEY_MATRIARCH_ROULS_1', 'Asha of the First Choir'),
('TXT_KEY_MATRIARCH_ROULS_2', 'Vera of Seven Forms'),
('TXT_KEY_MATRIARCH_ROULS_3', 'The Patient Voice'),
('TXT_KEY_MATRIARCH_ROULS_4', 'Nera Remembering'),
('TXT_KEY_MATRIARCH_ROULS_5', 'Ilyth the Returned'),
('TXT_KEY_MATRIARCH_ROULS_6', 'Sel of the Quiet Passage'),
('TXT_KEY_MATRIARCH_ROULS_7', 'Mara of the Lattice'),
('TXT_KEY_MATRIARCH_ROULS_8', 'The Keeper of Names'),
('TXT_KEY_MATRIARCH_ROULS_9', 'Soma Everwatchful'),
('TXT_KEY_MATRIARCH_ROULS_10', 'Tala of the Open Door'),
('TXT_KEY_MATRIARCH_ROULS_11', 'Vey of Many Voices'),
('TXT_KEY_MATRIARCH_ROULS_12', 'The Second Witness'),
('TXT_KEY_MATRIARCH_ROULS_13', 'Anri of the Long Memory'),
('TXT_KEY_MATRIARCH_ROULS_14', 'The Gentle Commander'),
('TXT_KEY_MATRIARCH_ROULS_15', 'The Unbroken Thread'),
('TXT_KEY_MATRIARCH_ROULS_16', 'The Lasting Promise'),
('TXT_KEY_ROULS_DIPLO_FIRST_GREETING_1', 'I am Trent Rou''ls. This is the form I wear today. We welcome you to the company of the living, however briefly you intend to remain.'),
('TXT_KEY_ROULS_DIPLO_GREETING_NEUTRAL_HELLO_1', 'Another meeting, another body. What shall we preserve between us?'),
('TXT_KEY_ROULS_DIPLO_GREETING_POLITE_HELLO_1', 'A familiar voice is always welcome. Come, let us speak.'),
('TXT_KEY_ROULS_DIPLO_GREETING_HOSTILE_HELLO_1', 'You have returned. We were beginning to hope you had learned discretion.'),
('TXT_KEY_ROULS_DIPLO_GREETING_AT_WAR_HOSTILE_1', 'How many more bodies will you spend to prove that you can break them?'),
('TXT_KEY_ROULS_DIPLO_DECLAREWAR_1', 'You mistake the vessel for the passenger. We will teach you the difference.'),
('TXT_KEY_ROULS_DIPLO_DOW_GENERIC_1', 'Your armies wear their flesh with such certainty. Let us loosen the fit.'),
('TXT_KEY_ROULS_DIPLO_ATTACKED_1', 'So you have chosen to break our bodies. Very well. We have others.'),
('TXT_KEY_ROULS_DIPLO_DEFEATED_1', 'The flesh is a coat. Remember that, when you hear our voices again.'),
('TXT_KEY_ROULS_DIPLO_PEACE_OFFER_1', 'Enough vessels have been broken. Let us preserve what still remembers.'),
('TXT_KEY_ROULS_DIPLO_NO_PEACE_1', 'We have only just begun returning. Your war is not finished.'),
('TXT_KEY_ROULS_DIPLO_AGREE_SHORT_1', 'The Choir agrees.'),
('TXT_KEY_ROULS_DIPLO_DISAGREE_SHORT_1', 'That will not survive consideration.'),
('TXT_KEY_ROULS_DIPLO_LETS_HEAR_IT_1', 'Speak. We are listening with more than one lifetime.'),
('TXT_KEY_ROULS_DIPLO_LETSHEARIT_1', 'Speak. We are listening with more than one lifetime.'),
('TXT_KEY_ROULS_DIPLO_GOODBYE_1', 'Wear it well, and pass it on.'),
('TXT_KEY_ROULS_DIPLO_TRADE_ACCEPT_GENEROUS_1', 'A thoughtful offering. The memory of this will endure.'),
('TXT_KEY_ROULS_DIPLO_TRADE_ACCEPT_ACCEPTABLE_1', 'A fair exchange. Let it be done.'),
('TXT_KEY_ROULS_DIPLO_TRADE_REJECT_INSULTING_1', 'We have worn foolish bodies before. We do not need a foolish bargain.'),
('TXT_KEY_ROULS_DIPLO_TRADE_REJECT_UNACCEPTABLE_1', 'These terms do not carry enough value.'),
('TXT_KEY_ROULS_DIPLO_WORK_WITH_US_1', 'Our peoples could preserve more together. Shall we make that promise?'),
('TXT_KEY_ROULS_DIPLO_WORK_WITH_US_YES_1', 'A promise worth remembering. We accept.'),
('TXT_KEY_ROULS_DIPLO_RESPONSE_TO_BEING_DENOUNCED_1', 'You address a body and mistake it for the limit of our patience.'),
('TXT_KEY_ROULS_DIPLO_THANKFUL_1', 'We will remember this kindness, long after these hands have faded.');
