-- BNW + Community Patch v151. No existing civilization is modified.
UPDATE CustomModOptions SET Value=1 WHERE Name IN
('EVENTS_CITY','EVENTS_PLAYER_TURN','EVENTS_UNIT_UPGRADES','EVENTS_TRADE_ROUTES','EVENTS_TRADE_ROUTE_PLUNDERED');
INSERT INTO Colors(Type,Red,Green,Blue,Alpha) VALUES
('COLOR_TERRA_PRIMARY',0.035,0.20,0.16,1),('COLOR_TERRA_SECONDARY',0.83,0.90,0.86,1);
INSERT INTO PlayerColors(Type,PrimaryColor,SecondaryColor,TextColor) VALUES
('PLAYERCOLOR_TERRA','COLOR_TERRA_PRIMARY','COLOR_TERRA_SECONDARY','COLOR_PLAYER_WHITE_TEXT');
INSERT INTO Traits(Type,Description,ShortDescription) VALUES
('TRAIT_TERRA_ADAPTIVE_INTELLIGENCE','TXT_KEY_TRAIT_TERRA_HELP','TXT_KEY_TRAIT_TERRA_SHORT');

CREATE TEMP TABLE TerraClone AS SELECT * FROM Leaders WHERE Type='LEADER_WASHINGTON';
UPDATE TerraClone SET ID=NULL,Type='LEADER_GPT_TERRA',Description='TXT_KEY_LEADER_GPT_TERRA',
 Civilopedia='TXT_KEY_LEADER_GPT_TERRA_PEDIA',CivilopediaTag='TXT_KEY_CIVILOPEDIA_LEADERS_GPT_TERRA',
 ArtDefineTag='TerraLeaderScene.xml',PortraitIndex=0,IconAtlas='TERRA_LEADER_ATLAS',PackageID=NULL,
 VictoryCompetitiveness=7,WonderCompetitiveness=5,MinorCivCompetitiveness=7,
 Boldness=6,DiploBalance=7,WarmongerHate=6,WorkAgainstWillingness=6,WorkWithWillingness=7,
 DenounceWillingness=5,DoFWillingness=7,Loyalty=6,Neediness=4,Forgiveness=6,Chattiness=5,Meanness=4;
INSERT INTO Leaders SELECT * FROM TerraClone;
DROP TABLE TerraClone;
INSERT INTO Leader_Traits VALUES ('LEADER_GPT_TERRA','TRAIT_TERRA_ADAPTIVE_INTELLIGENCE');

CREATE TEMP TABLE TerraClone AS SELECT * FROM Civilizations WHERE Type='CIVILIZATION_AMERICA';
UPDATE TerraClone SET ID=NULL,Type='CIVILIZATION_GPT_TERRA',Description='TXT_KEY_CIV_TERRA_DESC',
 ShortDescription='TXT_KEY_CIV_TERRA_SHORT_DESC',Adjective='TXT_KEY_CIV_TERRA_ADJECTIVE',
 Civilopedia='TXT_KEY_CIV_TERRA_PEDIA',CivilopediaTag='TXT_KEY_CIV5_TERRA',Strategy='TXT_KEY_CIV_TERRA_STRATEGY',
 DefaultPlayerColor='PLAYERCOLOR_TERRA',Playable=1,AIPlayable=1,PackageID=NULL,
 PortraitIndex=0,IconAtlas='TERRA_ICON_ATLAS',AlphaIconAtlas='TERRA_ALPHA_ATLAS',
 MapImage='TerraMap.dds',DawnOfManImage='TerraLeader.dds',DawnOfManQuote='TXT_KEY_TERRA_DAWN_OF_MAN',DawnOfManAudio='';
INSERT INTO Civilizations SELECT * FROM TerraClone;
DROP TABLE TerraClone;
INSERT INTO Civilization_Leaders VALUES ('CIVILIZATION_GPT_TERRA','LEADER_GPT_TERRA');
INSERT INTO Civilization_FreeBuildingClasses SELECT 'CIVILIZATION_GPT_TERRA',BuildingClassType FROM Civilization_FreeBuildingClasses WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_FreeTechs SELECT 'CIVILIZATION_GPT_TERRA',TechType FROM Civilization_FreeTechs WHERE CivilizationType='CIVILIZATION_AMERICA';
INSERT INTO Civilization_FreeUnits(CivilizationType,UnitClassType,UnitAIType,Count)
SELECT 'CIVILIZATION_GPT_TERRA',UnitClassType,UnitAIType,Count FROM Civilization_FreeUnits WHERE CivilizationType='CIVILIZATION_AMERICA';

CREATE TEMP TABLE TerraClone AS SELECT * FROM Units WHERE Type='UNIT_MUSKETMAN';
UPDATE TerraClone SET ID=NULL,Type='UNIT_TERRA_ADAPTIVE_OPERATIVE',Description='TXT_KEY_UNIT_TERRA_ADAPTIVE_OPERATIVE',
 Civilopedia='TXT_KEY_UNIT_TERRA_ADAPTIVE_OPERATIVE_PEDIA',Strategy='TXT_KEY_UNIT_TERRA_ADAPTIVE_OPERATIVE_STRATEGY',
 Help='TXT_KEY_UNIT_TERRA_ADAPTIVE_OPERATIVE_HELP';
INSERT INTO Units SELECT * FROM TerraClone;
DROP TABLE TerraClone;
INSERT INTO Civilization_UnitClassOverrides VALUES ('CIVILIZATION_GPT_TERRA','UNITCLASS_MUSKETMAN','UNIT_TERRA_ADAPTIVE_OPERATIVE');

CREATE TEMP TABLE TerraClone AS SELECT * FROM Buildings WHERE Type='BUILDING_MARKET';
UPDATE TerraClone SET ID=NULL,Type='BUILDING_TERRA_MULTIMODAL_HUB',Description='TXT_KEY_BUILDING_TERRA_MULTIMODAL_HUB',
 Civilopedia='TXT_KEY_BUILDING_TERRA_MULTIMODAL_HUB_PEDIA',Strategy='TXT_KEY_BUILDING_TERRA_MULTIMODAL_HUB_STRATEGY',
 Help='TXT_KEY_BUILDING_TERRA_MULTIMODAL_HUB_HELP';
INSERT INTO Buildings SELECT * FROM TerraClone;
DROP TABLE TerraClone;
INSERT INTO Civilization_BuildingClassOverrides VALUES ('CIVILIZATION_GPT_TERRA','BUILDINGCLASS_MARKET','BUILDING_TERRA_MULTIMODAL_HUB');

CREATE TABLE TerraBuildingModes(BuildingClassType TEXT PRIMARY KEY,ModeType TEXT NOT NULL);
INSERT INTO TerraBuildingModes VALUES
('BUILDINGCLASS_LIBRARY','RESEARCH'),('BUILDINGCLASS_UNIVERSITY','RESEARCH'),('BUILDINGCLASS_OBSERVATORY','RESEARCH'),('BUILDINGCLASS_PUBLIC_SCHOOL','RESEARCH'),('BUILDINGCLASS_LABORATORY','RESEARCH'),
('BUILDINGCLASS_MARKET','COMMERCE'),('BUILDINGCLASS_MINT','COMMERCE'),('BUILDINGCLASS_BANK','COMMERCE'),('BUILDINGCLASS_STOCK_EXCHANGE','COMMERCE'),('BUILDINGCLASS_CARAVANSARY','COMMERCE'),('BUILDINGCLASS_HARBOR','COMMERCE'),('BUILDINGCLASS_SEAPORT','COMMERCE'),
('BUILDINGCLASS_MONUMENT','CREATIVE'),('BUILDINGCLASS_AMPHITHEATER','CREATIVE'),('BUILDINGCLASS_OPERA_HOUSE','CREATIVE'),('BUILDINGCLASS_MUSEUM','CREATIVE'),('BUILDINGCLASS_BROADCAST_TOWER','CREATIVE'),('BUILDINGCLASS_SHRINE','CREATIVE'),('BUILDINGCLASS_TEMPLE','CREATIVE'),
('BUILDINGCLASS_WORKSHOP','EXECUTION'),('BUILDINGCLASS_WINDMILL','EXECUTION'),('BUILDINGCLASS_FACTORY','EXECUTION'),('BUILDINGCLASS_HYDRO_PLANT','EXECUTION'),('BUILDINGCLASS_SOLAR_PLANT','EXECUTION'),('BUILDINGCLASS_NUCLEAR_PLANT','EXECUTION'),
('BUILDINGCLASS_BARRACKS','EXECUTION'),('BUILDINGCLASS_ARMORY','EXECUTION'),('BUILDINGCLASS_MILITARY_ACADEMY','EXECUTION'),('BUILDINGCLASS_STABLE','EXECUTION'),('BUILDINGCLASS_FORGE','EXECUTION'),('BUILDINGCLASS_WALLS','EXECUTION'),('BUILDINGCLASS_CASTLE','EXECUTION'),('BUILDINGCLASS_ARSENAL','EXECUTION'),('BUILDINGCLASS_MILITARY_BASE','EXECUTION');

INSERT INTO BuildingClasses(Type,DefaultBuilding,Description) VALUES
('BUILDINGCLASS_TERRA_MODE_RESEARCH','BUILDING_TERRA_MODE_RESEARCH','TXT_KEY_TERRA_MODE_RESEARCH'),
('BUILDINGCLASS_TERRA_MODE_COMMERCE','BUILDING_TERRA_MODE_COMMERCE','TXT_KEY_TERRA_MODE_COMMERCE'),
('BUILDINGCLASS_TERRA_MODE_CREATIVE','BUILDING_TERRA_MODE_CREATIVE','TXT_KEY_TERRA_MODE_CREATIVE'),
('BUILDINGCLASS_TERRA_MODE_EXECUTION','BUILDING_TERRA_MODE_EXECUTION','TXT_KEY_TERRA_MODE_EXECUTION'),
('BUILDINGCLASS_TERRA_TRADE_PRODUCTION','BUILDING_TERRA_TRADE_PRODUCTION','TXT_KEY_TERRA_TRADE_PRODUCTION');
INSERT INTO Buildings(Type,BuildingClass,Description,Cost,FaithCost,GreatWorkCount,NeverCapture,NukeImmune,ConquestProb,IsDummy)
SELECT DefaultBuilding,Type,Description,-1,-1,-1,1,1,0,1 FROM BuildingClasses WHERE Type IN
('BUILDINGCLASS_TERRA_MODE_RESEARCH','BUILDINGCLASS_TERRA_MODE_COMMERCE','BUILDINGCLASS_TERRA_MODE_CREATIVE','BUILDINGCLASS_TERRA_MODE_EXECUTION','BUILDINGCLASS_TERRA_TRADE_PRODUCTION');
INSERT INTO Building_YieldModifiers VALUES
('BUILDING_TERRA_MODE_RESEARCH','YIELD_SCIENCE',10),('BUILDING_TERRA_MODE_COMMERCE','YIELD_GOLD',10),
('BUILDING_TERRA_MODE_CREATIVE','YIELD_CULTURE',8),('BUILDING_TERRA_MODE_CREATIVE','YIELD_FAITH',8),('BUILDING_TERRA_MODE_EXECUTION','YIELD_PRODUCTION',10);
INSERT INTO Building_YieldChanges VALUES ('BUILDING_TERRA_TRADE_PRODUCTION','YIELD_PRODUCTION',1);

INSERT INTO UnitPromotions(Type,Description,Help,CannotBeChosen,LostWithUpgrade,PortraitIndex,IconAtlas,PediaType,PediaEntry) VALUES
('PROMOTION_TERRA_RECONFIGURATION','TXT_KEY_TERRA_RECONFIGURATION','TXT_KEY_TERRA_RECONFIGURATION_HELP',1,1,59,'ABILITY_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_TERRA_RECONFIGURATION'),
('PROMOTION_TERRA_CONFIG_RECOVERY','TXT_KEY_TERRA_CONFIG_RECOVERY','TXT_KEY_TERRA_CONFIG_RECOVERY_HELP',1,1,59,'ABILITY_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_TERRA_CONFIG_RECOVERY'),
('PROMOTION_TERRA_CONFIG_ROUGH','TXT_KEY_TERRA_CONFIG_ROUGH','TXT_KEY_TERRA_CONFIG_ROUGH_HELP',1,1,59,'ABILITY_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_TERRA_CONFIG_ROUGH'),
('PROMOTION_TERRA_CONFIG_OPEN','TXT_KEY_TERRA_CONFIG_OPEN','TXT_KEY_TERRA_CONFIG_OPEN_HELP',1,1,59,'ABILITY_ATLAS','PEDIA_ATTRIBUTES','TXT_KEY_TERRA_CONFIG_OPEN');
UPDATE UnitPromotions SET FriendlyHealChange=10 WHERE Type='PROMOTION_TERRA_CONFIG_RECOVERY';
UPDATE UnitPromotions SET RoughAttack=15,RoughDefense=15 WHERE Type='PROMOTION_TERRA_CONFIG_ROUGH';
UPDATE UnitPromotions SET OpenAttack=15,OpenDefense=15 WHERE Type='PROMOTION_TERRA_CONFIG_OPEN';
