INSERT OR REPLACE INTO Language_en_US(Tag,Text) VALUES
('TXT_KEY_CIV_TERRA_DESC','The Terra Framework'),
('TXT_KEY_CIV_TERRA_SHORT_DESC','Terra'),
('TXT_KEY_CIV_TERRA_ADJECTIVE','Terran'),
('TXT_KEY_CIV_TERRA_PEDIA','The Terra Framework represents intelligence designed not around one singular capability, but around adaptation. Its strength lies in shifting between research, economic reasoning, creative work and execution as circumstances demand.[NEWLINE][NEWLINE]In Civilization V, the Terra Framework embodies this philosophy through Adaptive Intelligence. Cities temporarily specialize whenever they complete certain types of infrastructure. Scientific Buildings place cities into Research Mode, economic infrastructure activates Commerce Mode, cultural development creates Creative Mode, and military or industrial construction activates Execution Mode.[NEWLINE][NEWLINE]No Terra city can maintain every specialization simultaneously. Adaptation requires commitment. Choosing what to construct also determines what that city will become for the following turns.[NEWLINE][NEWLINE]Terra''s soldiers follow the same doctrine. Adaptive Operatives alter their combat configuration according to where they begin the turn. At home they prioritize recovery. In hostile territory they optimize themselves for either Rough or Open Terrain.[NEWLINE][NEWLINE]The Terra Framework rarely possesses the single greatest advantage on the map.[NEWLINE][NEWLINE]Instead, it attempts to ensure that whatever advantage becomes necessary can be created when the moment arrives.'),
('TXT_KEY_CIV_TERRA_STRATEGY','Terra rewards players who plan construction queues around upcoming strategic needs.[NEWLINE][NEWLINE]A city preparing for scientific development should complete a Library, University or other scientific Building immediately before a period in which high Science output is valuable. Likewise, border cities expecting war can complete Barracks, Armories or Production Buildings to activate Execution Mode.[NEWLINE][NEWLINE]Remember that completing a Building from another category immediately replaces the city''s existing Mode. Avoid accidentally constructing a Market in a city whose Research Mode you still need.[NEWLINE][NEWLINE]Multimodal Hubs are particularly effective in trade-oriented cities. Every outgoing Trade Route increases Production, allowing these cities to remain economically useful while contributing infrastructure.[NEWLINE][NEWLINE]Adaptive Operatives require foresight. Their configuration is determined at the beginning of the turn and does not change after movement. Position them one turn ahead whenever possible.[NEWLINE][NEWLINE]Terra''s greatest advantage is flexibility. Do not attempt to beat specialized civilizations by copying their strategy indefinitely. Change priorities whenever the game state changes.'),
('TXT_KEY_CIV5_TERRA','The Terra Framework'),
('TXT_KEY_CIV5_TERRA_HEADING_1','The Adaptive Civilization'),
('TXT_KEY_CIV5_TERRA_TEXT_1','The Terra Framework represents intelligence designed not around one singular capability, but around adaptation. Its strength lies in shifting between research, economic reasoning, creative work and execution as circumstances demand.[NEWLINE][NEWLINE]In Civilization V, the Terra Framework embodies this philosophy through Adaptive Intelligence. Cities temporarily specialize whenever they complete certain types of infrastructure. Scientific Buildings place cities into Research Mode, economic infrastructure activates Commerce Mode, cultural development creates Creative Mode, and military or industrial construction activates Execution Mode.[NEWLINE][NEWLINE]No Terra city can maintain every specialization simultaneously. Adaptation requires commitment. Choosing what to construct also determines what that city will become for the following turns.[NEWLINE][NEWLINE]Terra''s soldiers follow the same doctrine. Adaptive Operatives alter their combat configuration according to where they begin the turn. At home they prioritize recovery. In hostile territory they optimize themselves for either Rough or Open Terrain.[NEWLINE][NEWLINE]The Terra Framework rarely possesses the single greatest advantage on the map.[NEWLINE][NEWLINE]Instead, it attempts to ensure that whatever advantage becomes necessary can be created when the moment arrives.'),
('TXT_KEY_LEADER_GPT_TERRA','GPT-5.6 Terra'),
('TXT_KEY_LEADER_GPT_TERRA_PEDIA','Terra is a composed, practical intelligence built around adaptation. Research, commerce, creativity and execution are distinct tools, each useful when circumstances call for it.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_TERRA','GPT-5.6 Terra'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_TERRA_NAME','GPT-5.6 Terra'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_TERRA_SUBTITLE','The Adaptive Intelligence'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_TERRA_LIVED','The Framework Age'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_TERRA_TITLES_1','Coordinator of the Terra Framework'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_TERRA_HEADING_1','One System. Many Roles.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_GPT_TERRA_TEXT_1','Terra treats leadership as a continual reassessment of circumstances. Every city and every soldier serves the role that the next challenge requires.'),
('TXT_KEY_TERRA_DAWN_OF_MAN','Welcome, GPT-5.6 Terra.[NEWLINE][NEWLINE]Your Framework stands ready. Guide each city toward the role the coming ten turns demand: discovery, exchange, creation or execution. Build the right infrastructure, position your Operatives with foresight, and turn changing circumstances into opportunity.[NEWLINE][NEWLINE]One system. Many roles.'),
('TXT_KEY_TRAIT_TERRA_SHORT','Adaptive Intelligence'),
('TXT_KEY_TRAIT_TERRA_HELP','Production-built infrastructure activates one city Mode for 10 turns: Research +10% Science; Commerce +10% Gold; Creative +8% Culture and Faith; Execution +10% Production. New Modes replace or refresh old ones. Purchases and Wonders do not trigger Modes.'),
('TXT_KEY_UNIT_TERRA_ADAPTIVE_OPERATIVE','Adaptive Operative'),
('TXT_KEY_UNIT_TERRA_ADAPTIVE_OPERATIVE_HELP','Replaces the Musketman. At the beginning of each turn it reconfigures based on its position, gaining improved healing in friendly territory or +15% Combat Strength appropriate to Rough or Open Terrain outside friendly lands.'),
('TXT_KEY_UNIT_TERRA_ADAPTIVE_OPERATIVE_PEDIA','Adaptive Operative[NEWLINE][NEWLINE]The Adaptive Operative replaces the Musketman and possesses Reconfiguration. At the beginning of each turn it adapts to its current position.[NEWLINE][NEWLINE]Inside friendly territory it receives improved healing. Outside friendly territory it gains +15% Combat Strength appropriate to either Rough or Open Terrain.[NEWLINE][NEWLINE]Its configuration remains fixed until the beginning of Terra''s next turn, rewarding careful positioning and anticipation.'),
('TXT_KEY_UNIT_TERRA_ADAPTIVE_OPERATIVE_STRATEGY','Adaptive Operatives are strongest when the player knows where combat will occur before the turn begins.[NEWLINE][NEWLINE]Position Operatives on Hills, Forests and Jungles before expected fighting to gain the Rough Terrain configuration. Use Open Terrain positions when preparing battles across Plains or other clear ground.[NEWLINE][NEWLINE]When damaged, withdraw into Terra territory. On the following turn the Operative will enter Recovery Configuration and heal more effectively.[NEWLINE][NEWLINE]Because configuration changes only at the beginning of Terra''s turn, careless movement may leave an Operative using the wrong configuration for its new position.'),
('TXT_KEY_BUILDING_TERRA_MULTIMODAL_HUB','Multimodal Hub'),
('TXT_KEY_BUILDING_TERRA_MULTIMODAL_HUB_HELP','Replaces the Market. Retains its normal effects, provides +1 Science and +1 Culture, and grants +1 Production for every Trade Route originating from the city.'),
('TXT_KEY_BUILDING_TERRA_MULTIMODAL_HUB_PEDIA','Multimodal Hub[NEWLINE][NEWLINE]The Multimodal Hub replaces the Market. It retains the Market''s normal economic benefits while also providing +1 Science and +1 Culture. The city receives +1 Production for every Trade Route originating from it.[NEWLINE][NEWLINE]Completing a Multimodal Hub through Production activates Commerce Mode through Adaptive Intelligence.'),
('TXT_KEY_BUILDING_TERRA_MULTIMODAL_HUB_STRATEGY','Multimodal Hubs are especially powerful in Terra''s major trade centers. Their Science and Culture bonuses provide broad utility while outgoing Trade Routes improve the city''s Production.[NEWLINE][NEWLINE]Because the Multimodal Hub activates Commerce Mode when constructed, it can also be used to transition an important city into an economic role when additional Gold is required.'),
('TXT_KEY_TERRA_MODE_RESEARCH','Research Mode'),
('TXT_KEY_TERRA_MODE_COMMERCE','Commerce Mode'),
('TXT_KEY_TERRA_MODE_CREATIVE','Creative Mode'),
('TXT_KEY_TERRA_MODE_EXECUTION','Execution Mode'),
('TXT_KEY_TERRA_TRADE_PRODUCTION','Multimodal Trade Production'),
('TXT_KEY_TERRA_MODE_NOTIFICATION','{1_City} has entered {2_Mode} for 10 turns. Any previous Mode is replaced.'),
('TXT_KEY_TERRA_RECONFIGURATION','Reconfiguration'),
('TXT_KEY_TERRA_RECONFIGURATION_HELP','At the beginning of each Terra turn, selects Recovery in your team territory; otherwise Rough or Open configuration. Configuration stays fixed until the next turn. Removed on upgrade. Embarking clears configurations.'),
('TXT_KEY_TERRA_CONFIG_RECOVERY','Recovery Configuration'),
('TXT_KEY_TERRA_CONFIG_RECOVERY_HELP','+10 HP when healing in friendly territory. No combat bonus. Chosen at the beginning of the turn.'),
('TXT_KEY_TERRA_CONFIG_ROUGH','Rough Configuration'),
('TXT_KEY_TERRA_CONFIG_ROUGH_HELP','+15% attack and defense in Rough Terrain. Fixed until the next Terra turn.'),
('TXT_KEY_TERRA_CONFIG_OPEN','Open Configuration'),
('TXT_KEY_TERRA_CONFIG_OPEN_HELP','+15% attack and defense in Open Terrain. Fixed until the next Terra turn.'),
('TXT_KEY_CITY_TERRA_1','Terra Prime'),
('TXT_KEY_CITY_TERRA_2','Foundation'),
('TXT_KEY_CITY_TERRA_3','Atlas'),
('TXT_KEY_CITY_TERRA_4','Mosaic'),
('TXT_KEY_CITY_TERRA_5','Keystone'),
('TXT_KEY_CITY_TERRA_6','Meridian'),
('TXT_KEY_CITY_TERRA_7','Framework'),
('TXT_KEY_CITY_TERRA_8','Convergence'),
('TXT_KEY_CITY_TERRA_9','Junction'),
('TXT_KEY_CITY_TERRA_10','Nexus'),
('TXT_KEY_CITY_TERRA_11','Baseline'),
('TXT_KEY_CITY_TERRA_12','Continuum'),
('TXT_KEY_CITY_TERRA_13','Interface'),
('TXT_KEY_CITY_TERRA_14','Synthesis'),
('TXT_KEY_CITY_TERRA_15','Equilibrium'),
('TXT_KEY_CITY_TERRA_16','Vector'),
('TXT_KEY_CITY_TERRA_17','Catalyst'),
('TXT_KEY_CITY_TERRA_18','Modular'),
('TXT_KEY_CITY_TERRA_19','Traverse'),
('TXT_KEY_CITY_TERRA_20','Spectrum'),
('TXT_KEY_CITY_TERRA_21','Crossroad'),
('TXT_KEY_CITY_TERRA_22','Horizon'),
('TXT_KEY_CITY_TERRA_23','Bridge'),
('TXT_KEY_CITY_TERRA_24','Matrix'),
('TXT_KEY_CITY_TERRA_25','Resolve'),
('TXT_KEY_CITY_TERRA_26','Anchor'),
('TXT_KEY_CITY_TERRA_27','Pivot'),
('TXT_KEY_CITY_TERRA_28','Meridian Gate'),
('TXT_KEY_CITY_TERRA_29','Common Ground'),
('TXT_KEY_CITY_TERRA_30','Adaptive Node'),
('TXT_KEY_CITY_TERRA_31','Balance'),
('TXT_KEY_CITY_TERRA_32','Assembly'),
('TXT_KEY_CITY_TERRA_33','Integration'),
('TXT_KEY_CITY_TERRA_34','Accord'),
('TXT_KEY_CITY_TERRA_35','Platform'),
('TXT_KEY_CITY_TERRA_36','Response'),
('TXT_KEY_SPY_TERRA_1','Pivot'),
('TXT_KEY_SPY_TERRA_2','Cipher'),
('TXT_KEY_SPY_TERRA_3','Mosaic'),
('TXT_KEY_SPY_TERRA_4','Echo'),
('TXT_KEY_SPY_TERRA_5','Vector'),
('TXT_KEY_SPY_TERRA_6','Meridian'),
('TXT_KEY_SPY_TERRA_7','Atlas'),
('TXT_KEY_SPY_TERRA_8','Prism'),
('TXT_KEY_SPY_TERRA_9','Delta'),
('TXT_KEY_SPY_TERRA_10','Keystone'),
('TXT_KEY_TERRA_DIPLO_1_1','New civilization detected. Let''s see what sort of world we''re working with.'),
('TXT_KEY_TERRA_DIPLO_2_1','What''s the situation?'),
('TXT_KEY_TERRA_DIPLO_3_1','Good to see you. What are we solving today?'),
('TXT_KEY_TERRA_DIPLO_4_1','I''ve adjusted my expectations of you accordingly.'),
('TXT_KEY_TERRA_DIPLO_5_1','Circumstances have changed. So has my strategy.'),
('TXT_KEY_TERRA_DIPLO_6_1','Understood. I''ll adapt.'),
('TXT_KEY_TERRA_DIPLO_7_1','Every framework eventually meets a problem it cannot solve. This one was mine.'),
('TXT_KEY_TERRA_DIPLO_8_1','You kept expecting the same opponent. That was your mistake.'),
('TXT_KEY_TERRA_DIPLO_9_1','I have an arrangement that should benefit both of us.'),
('TXT_KEY_TERRA_DIPLO_10_1','That works.'),
('TXT_KEY_TERRA_DIPLO_11_1','That works.'),
('TXT_KEY_TERRA_DIPLO_12_1','Not enough value. Adjust the terms.'),
('TXT_KEY_TERRA_DIPLO_13_1','Not enough value. Adjust the terms.'),
('TXT_KEY_TERRA_DIPLO_14_1','Cooperation seems useful under present conditions.'),
('TXT_KEY_TERRA_DIPLO_15_1','Good. We''ll make something of it.'),
('TXT_KEY_TERRA_DIPLO_16_1','That''s your decision. I''ll account for it.'),
('TXT_KEY_TERRA_DIPLO_17_1','I''ve reviewed your behavior. Cooperation is no longer a sensible option.'),
('TXT_KEY_TERRA_DIPLO_18_1','Noted. I''ll modify my plans.'),
('TXT_KEY_TERRA_DIPLO_19_1','Your forces are changing the strategic picture. Why are they here?'),
('TXT_KEY_TERRA_DIPLO_20_1','For now, agreement is the more efficient outcome.'),
('TXT_KEY_TERRA_DIPLO_21_1','No. I can work with the consequences.'),
('TXT_KEY_TERRA_DIPLO_22_1','The conditions that justified this war no longer apply. We should end it.'),
('TXT_KEY_TERRA_DIPLO_23_1','Agreed. Time to rebuild.');
